from cog.cog_module import CogModule

class CogFrameworkAstro(CogModule):
    name = "cog-framework-astro"
    version = "1.0.0"
    description = "Astro framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Astro Framework Expertise",
            "",
            "### Core Architecture",
            "- Islands architecture — zero JS by default",
            "- Astro components compile to static HTML at build time",
            "- Interactive components from any framework (React, Vue, Svelte, Solid)",
            "- Partial hydration — only interactive islands ship JavaScript",
            "- Client directives control hydration: client:load, client:visible, client:idle",
            "- Content-focused — ideal for blogs, docs, marketing sites",
            "- Built-in Vite dev server for fast HMR",
            "- Zero JS baseline — add interactivity only where needed",
            "",
            "### Islands Architecture",
            "- Each interactive component is an independent 'island'",
            "- Islands hydrate independently, isolated from each other",
            "- No shared JavaScript runtime between islands",
            "- Server-rendered HTML surrounds interactive islands",
            "- client:load — hydrate immediately on page load",
            "- client:idle — hydrate once browser is idle (requestIdleCallback)",
            "- client:visible — hydrate when element enters viewport",
            "- client:media — hydrate when CSS media query matches",
            "- client:only — skip SSR, only render on client (specify framework)",
            "",
            "### Astro Components",
            "- .astro files with frontmatter script and template",
            "- Frontmatter runs on the server at build time only",
            "- Component props defined in frontmatter: const { title } = Astro.props",
            "- <slot /> for content projection (like children)",
            "- Named slots: <slot name='header' />",
            "- Fragment support with <>...</>",
            "- styles are scoped by default (no <style scoped> needed)",
            "- <style is:global> for global styles",
            "- <style is:inline> for inline styles (no extraction)",
            "- Astro.slots.has('name') checks if slot is provided",
            "",
            "### Routing",
            "- File-based routing under src/pages/",
            "- .astro, .md, .mdx files are pages",
            "- Dynamic routes: [slug].astro or [...slug].astro",
            "- getStaticPaths() generates paths for dynamic routes at build",
            "- Pagination with paginate() in getStaticPaths",
            "- SSR mode for dynamic server-rendered pages",
            "",
            "### Content Collections",
            "- Define schemas for content in src/content/config.ts",
            "- defineCollection with zod schema validation",
            "- query collections with getCollection('blog')",
            "- getEntry('blog', 'slug') for single entry",
            "- Content in src/content/blog/ as .md or .mdx files",
            "- Type-safe frontmatter with inferred schemas",
            "- render() method to render content to HTML",
            "- Content layer API for loading from remote sources",
            "- glob loader for local files, custom loaders for APIs/databases",
            "",
            "### Rendering Modes",
            "- Static (SSG) — default, pre-rendered at build time",
            "- Server (SSR) — rendered per request (requires adapter)",
            "- Hybrid — static by default, opt-in SSR per page",
            "- export const prerender = true | false per page",
            "- Adapter required for SSR: @astrojs/node, @astrojs/deno, @astrojs/cloudflare",
            "",
            "### Integrations",
            "- Framework integrations: @astrojs/react, @astrojs/vue, @astrojs/svelte, @astrojs/solid-js",
            "- CSS: @astrojs/tailwind, @astrojs/mdx",
            "- CMS: @astrojs/contentful, astro Sanity integration",
            "- SEO: @astrojs/sitemap, astro-seo",
            "- Image: @astrojs/image (built-in Image component)",
            "- Custom integrations via astro add or manual config",
            "- Integration hooks: astro:config:setup, astro:config:done, astro:build:start",
            "",
            "### View Transitions",
            "- <ViewTransitions /> component in head for SPA-like navigation",
            "- Animated page transitions using View Transition API",
            "- Fallback animations for browsers without View Transition API",
            "- transition:animate directive for element transitions",
            "- transition:name for custom transition names",
            "- transition:persist to persist elements across navigations",
            "- Astro.beforePreparation, Astro.afterPreparation lifecycle hooks",
            "",
            "### Data Fetching",
            "- fetch() available directly in frontmatter (server-side)",
            "- All fetches happen at build time (SSG) or request time (SSR)",
            "- Astro.glob('./*.md') for importing local markdown files",
            "- import.meta.glob for dynamic imports with Vite",
            "- Static data fetching preferred — no client-side waterfalls",
            "",
            "### MDX Support",
            "- Write JSX in markdown with .mdx files",
            "- Import and use components inside markdown",
            "- Custom components map to override HTML elements",
            "- Interactive components with client directives in MDX",
            "- Frontmatter and layout support same as .astro pages",
            "",
            "### Performance Best Practices",
            "- Ship zero JS by default — use islands only for interactivity",
            "- client:visible for below-fold interactive components",
            "- Use content collections for type-safe content management",
            "- Optimize images with Astro built-in Image component",
            "- Prefetch links with <link rel='prefetch'> or prefetch utility",
            "- Use static generation over SSR when possible",
            "- Compress and optimize assets through Vite config",
            "- Audit bundle with astro build --verbose output",
            "",
            "### Common Operations",
            "Create Astro app:",
            "```bash",
            "npm create astro@latest myapp",
            "```",
            "",
            "Add integrations:",
            "```bash",
            "npx astro add react",
            "npx astro add tailwind",
            "npx astro add sitemap",
            "npx astro add mdx",
            "```",
            "",
            "Build and preview:",
            "```bash",
            "npm run dev",
            "npm run build",
            "npm run preview",
            "```",
            "",
            "Example Astro component:",
            "```astro",
            "---",
            "import Layout from '../layouts/Layout.astro';",
            "const { title } = Astro.props;",
            "---",
            "",
            "<Layout title={title}>",
            "  <h1>{title}</h1>",
            "  <slot />",
            "</Layout>",
            "",
            "<style>",
            "  h1 {",
            "    font-size: 2.5rem;",
            "    color: var(--heading-color);",
            "  }",
            "</style>",
            "```",
            "",
            "Example content collection config:",
            "```typescript",
            "import { defineCollection, z } from 'astro:content';",
            "",
            "const blog = defineCollection({",
            "  type: 'content',",
            "  schema: z.object({",
            "    title: z.string(),",
            "    description: z.string(),",
            "    date: z.date(),",
            "    tags: z.array(z.string()).optional(),",
            "    draft: z.boolean().default(false),",
            "  }),",
            "});",
            "",
            "export const collections = { blog };",
            "```",
            "",
            "Example island with React:",
            "```astro",
            "---",
            "import ReactCounter from '../components/Counter';",
            "---",
            "",
            "<h2>Static content — no JavaScript shipped</h2>",
            "<p>This paragraph is pure HTML.</p>",
            "",
            "<ReactCounter client:visible />",
            "```",
            "",
            "Example dynamic route with getStaticPaths:",
            "```typescript",
            "export async function getStaticPaths() {",
            "  const posts = await getCollection('blog');",
            "  return posts.map((post) => ({",
            "    params: { slug: post.slug },",
            "    props: { post }",
            "  }));",
            "}",
            "",
            "const { post } = Astro.props;",
            "const { Content } = await post.render();",
            "---",
            "",
            "<article>",
            "  <h1>{post.data.title}</h1>",
            "  <Content />",
            "</article>",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["astro", "islands_architecture", "content_collections", "ssr", "ssg", "integrations", "view_transitions", "partial_hydration", "mdx", "multi_framework", "astro_components"]

module = CogFrameworkAstro()
