from cog.cog_module import CogModule

class CogFrameworkSolidjs(CogModule):
    name = "cog-framework-solidjs"
    version = "1.0.0"
    description = "SolidJS framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## SolidJS Framework Expertise",
            "",
            "### Core Architecture",
            "- Fine-grained reactive system — no virtual DOM",
            "- True reactivity: updates only the exact DOM nodes that change",
            "- JSX compiled to real DOM expressions, not virtual DOM diffing",
            "- Components run once (setup function pattern), not on every update",
            "- Reactive primitives handle all state and side effects",
            "- No hook rules or dependency arrays",
            "- Close to vanilla JS performance with framework ergonomics",
            "- SolidStart for full-stack framework (routing, SSR, API)",
            "",
            "### Reactive Primitives",
            "- createSignal(initial) — creates a reactive value with getter and setter",
            "- const [value, setValue] = createSignal(0)",
            "- value() to read, setValue(newValue) or setValue(prev => prev + 1) to write",
            "- createEffect(fn) — runs fn, auto-tracks dependencies, re-runs on changes",
            "- createMemo(fn) — derived reactive value, cached until deps change",
            "- createResource(source, fetcher) — async data fetching with loading/error states",
            "- createStore(initial) — reactive proxy for nested objects/arrays",
            "- const [state, setState] = createStore({ todos: [] })",
            "- Fine-grained updates on nested paths with setState",
            "",
            "### Signals and Reactivity",
            "- Signals are the fundamental reactive unit",
            "- Reading a signal inside a tracking scope creates a subscription",
            "- Tracking scopes: createEffect, createMemo, JSX expressions, onCleanup",
            "- batch(fn) — batches multiple signal updates into one",
            "- untrack(fn) — reads signals without creating subscriptions",
            "- on(source, fn) — explicit dependency instead of auto-tracking",
            "- runWithOwner(owner, fn) — run reactive code with specific ownership",
            "- Signals are NOT tied to components — can live anywhere",
            "- getListener() checks if currently inside a tracking scope",
            "",
            "### Components",
            "- Components are setup functions — run exactly once",
            "- No re-render cycle; reactive primitives handle updates",
            "- Props accessed via props.name or splitProps for destructuring",
            "- mergeProps for merging props (like spread)",
            "- children() for accessing children reactively",
            "- No hooks rules, no dependency arrays, no stale closures",
            "- JSX compiles to DOM node creation, not virtual DOM",
            "",
            "### Control Flow Components",
            "- <Show when={condition} fallback={<Fallback />}>",
            "- <For each={items}>{(item, index) => ...}</For>",
            "- <Switch fallback={...}><Match when={...}>",
            "- <Index each={items}>{(item, index) => ...}</Index> — keyed by index",
            "- <Dynamic component={Component} {...props} />",
            "- <Portal mount={document.body}>...</Portal>",
            "- These are NOT components that re-render — they are reactive control flow",
            "- Use For (keyed) over Index when list items have identity",
            "",
            "### Context API",
            "- createContext(defaultValue) creates a context",
            "- const MyCtx = createContext();",
            "- <MyCtx.Provider value={myValue}> wraps children",
            "- useContext(MyCtx) accesses nearest provider value",
            "- Context values can be reactive (signals, stores)",
            "",
            "### Resources (Async Data)",
            "- createResource(sourceSignal, fetcher) — source-driven fetching",
            "- createResource(async fetcher) — fetch once",
            "- Returns [data, { refetch, mutate, loading, error }]",
            "- Suspense boundary catches pending resources",
            "- <Suspense fallback={<Loading />}>{children}</Suspense>",
            "- ErrorBoundary catches resource errors",
            "- createResource with source signal refetches when source changes",
            "- refetch() manually triggers refetch",
            "- mutate() optimistically updates local resource value",
            "",
            "### SolidStart (Full-Stack Framework)",
            "- File-based routing under src/routes/",
            "- API routes with GET, POST handlers",
            "- Server functions with 'use server' directive",
            "- SSR, SSR streaming, and SPA modes",
            "- routeData() for per-route data loading (like loaders)",
            "- <FileRouter /> for nested layouts",
            "- Meta tags with <Title>, <Meta> components",
            "- Session and cookie management utilities",
            "",
            "### Lifecycle",
            "- onMount(fn) — runs after component first renders",
            "- onCleanup(fn) — runs when reactive scope is disposed",
            "- No componentWillUnmount — onCleanup covers disposal",
            "- onError(fn) — catches errors in reactive computations",
            "",
            "### Performance Best Practices",
            "- Use For instead of map() for lists (keyed reconciliation)",
            "- Prefer createMemo for expensive derived computations",
            "- Use batch() for multiple synchronous updates",
            "- Avoid creating signals in event handlers — hoist them",
            "- Use createStore for complex objects instead of signal per field",
            "- Lazy load routes with lazy() for code splitting",
            "- Use <Show> instead of ternary in JSX for conditional rendering",
            "- Solid compiles away the framework — tiny runtime overhead",
            "",
            "### Common Operations",
            "Create SolidStart app:",
            "```bash",
            "npx degit solidjs/templates/ts myapp",
            "cd myapp && npm install",
            "```",
            "",
            "Development server:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build:",
            "```bash",
            "npm run build",
            "npm run start",
            "```",
            "",
            "Example counter with signals:",
            "```typescript",
            "import { createSignal, createMemo } from 'solid-js';",
            "",
            "function Counter() {",
            "  const [count, setCount] = createSignal(0);",
            "  const doubled = createMemo(() => count() * 2);",
            "  return (",
            "    <div>",
            "      <p>Count: {count()}</p>",
            "      <p>Doubled: {doubled()}</p>",
            "      <button onClick={() => setCount(c => c + 1)}>+</button>",
            "      <button onClick={() => setCount(c => c - 1)}>-</button>",
            "    </div>",
            "  );",
            "}",
            "```",
            "",
            "Example data fetching with resource:",
            "```typescript",
            "import { createResource, Suspense } from 'solid-js';",
            "",
            "async function fetchUser(id: string) {",
            "  const res = await fetch(`/api/users/${id}`);",
            "  return res.json();",
            "}",
            "",
            "function UserProfile(props: { userId: string }) {",
            "  const [user] = createResource(() => props.userId, fetchUser);",
            "  return (",
            "    <Suspense fallback={<p>Loading...</p>}>",
            "      <div>",
            "        <h1>{user()?.name}</h1>",
            "        <p>{user()?.email}</p>",
            "      </div>",
            "    </Suspense>",
            "  );",
            "}",
            "```",
            "",
            "Example store with nested updates:",
            "```typescript",
            "import { createStore, produce } from 'solid-js/store';",
            "",
            "function TodoApp() {",
            "  const [state, setState] = createStore({ todos: [], filter: 'all' });",
            "  const addTodo = (text: string) => {",
            "    setState('todos', produce((todos) => {",
            "      todos.push({ id: Date.now(), text, done: false });",
            "    }));",
            "  };",
            "  const toggle = (id: number) => {",
            "    setState('todos', (t) => t.id === id, 'done', (v) => !v);",
            "  };",
            "  return (",
            "    <For each={state.todos}>",
            "      {(todo) => (",
            "        <div style={{ 'text-decoration': todo.done ? 'line-through' : 'none' }}>",
            "          {todo.text}",
            "          <button onClick={() => toggle(todo.id)}>Toggle</button>",
            "        </div>",
            "      )}",
            "    </For>",
            "  );",
            "}",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["solidjs", "reactive_primitives", "fine_grained_reactivity", "signals", "effects", "memos", "resources", "control_flow", "context", "stores", "solidstart"]

module = CogFrameworkSolidjs()
