from cog.cog_module import CogModule

class CogLangCpp(CogModule):
    name = "cog-lang-cpp"
    version = "1.0.0"
    description = "C++ language expertise including memory management, RAII, smart pointers, templates, STL, move semantics, CMake, and modern C++ best practices"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## C++ Language Expertise",
            "",
            "### Memory Management and RAII",
            "- RAII: Resource Acquisition Is Initialization — bind resource lifetime to object scope",
            "- Stack allocation preferred: automatic destruction when scope exits",
            "- Heap allocation with new/delete: avoid raw new/delete, use smart pointers",
            "- Rule of Zero: classes with only properly designed members need no special member functions",
            "- Rule of Five: if you define any of destructor/copy/move, define all five",
            "- Rule of Three: pre-C++11, if you define destructor/copy ctor/copy assign, define all three",
            "- Memory safety: use tools like AddressSanitizer, Valgrind, cppcheck",
            "- Avoid raw owning pointers; use std::unique_ptr or std::shared_ptr",
            "",
            "### Smart Pointers",
            "- std::unique_ptr<T>: exclusive ownership, zero overhead, move-only",
            "- std::unique_ptr<T[]>: for arrays (prefer std::vector or std::array instead)",
            "- std::make_unique<T>(args...): exception-safe construction (C++14)",
            "- std::shared_ptr<T>: shared ownership via reference counting",
            "- std::make_shared<T>(args...): single allocation for control block + object",
            "- std::weak_ptr<T>: non-owning observer of shared_ptr, avoids cycles",
            "- std::enable_shared_from_this<T>: get shared_ptr from within object",
            "- Custom deleters: std::unique_ptr<FILE, decltype(&fclose)>",
            "",
            "### Move Semantics and Value Categories",
            "- lvalue: has identity, persists beyond expression (named objects)",
            "- rvalue: temporary, about to be destroyed, can be moved from",
            "- std::move casts to rvalue reference — does not move by itself",
            "- std::forward for perfect forwarding in templates",
            "- Move constructor: T(T&& other) noexcept",
            "- Move assignment: T& operator=(T&& other) noexcept",
            "- noexcept on move operations enables optimal std::vector reallocation",
            "- Return Value Optimization (RVO) and Named RVO (NRVO) avoid moves entirely",
            "- Copy elision mandatory in certain contexts since C++17",
            "",
            "### Templates",
            "- Function templates: template<typename T> T max(T a, T b) { return a > b ? a : b; }",
            "- Class templates: template<typename T> class Stack { std::vector<T> data; };",
            "- Template specialization: template<> std::string max(std::string a, std::string b)",
            "- Variadic templates: template<typename... Args> void print(Args... args)",
            "- Fold expressions (C++17): (print(args), ...)",
            "- SFINAE and std::enable_if for conditional template instantiation",
            "- Concepts (C++20): template<typename T> requires Sortable<T> void sort(T& container)",
            "- constexpr if (C++17): if constexpr (std::is_integral_v<T>) for compile-time branching",
            "- Template argument deduction for classes (C++17): std::pair(1, 2.0) without <int, double>",
            "",
            "### STL Containers",
            "- Sequence: vector (default choice), deque, list, forward_list, array",
            "- Associative: set, map, multiset, multimap (ordered, O(log n))",
            "- Unordered: unordered_set, unordered_map (hashed, O(1) average)",
            "- Container adaptors: stack, queue, priority_queue",
            "- vector: contiguous memory, push_back amortized O(1), reserve() to preallocate",
            "- string: std::string with std::string_view (C++17) for non-owning views",
            "- span<T> (C++20): non-owning view over contiguous memory",
            "- Use emplace_back/emplace instead of push_back/insert to avoid temporaries",
            "",
            "### STL Algorithms",
            "- <algorithm> header: sort, find, copy, transform, accumulate, remove_if",
            "- Execution policies (C++17): std::execution::par for parallel execution",
            "- std::sort(v.begin(), v.end()) with optional comparator",
            "- std::remove_if + erase (erase-remove idiom): v.erase(std::remove_if(...), v.end())",
            "- std::erase_if(v, pred) directly (C++20)",
            "- std::transform for element-wise operations",
            "- std::reduce and std::transform_reduce for parallel accumulation",
            "- std::any_of, std::all_of, std::none_of for predicate checks",
            "",
            "### C++17 Features",
            "- Structured bindings: auto [key, value] = *map.begin()",
            "- std::optional<T>: may or may not contain a value",
            "- std::variant<T, U>: type-safe union",
            "- std::any: type-safe container for single values of any type",
            "- if/switch with initializer: if (auto it = m.find(key); it != m.end())",
            "- Inline variables: inline static const std::string name = 'test'",
            "- Fold expressions for variadic templates",
            "- constexpr if for compile-time conditional compilation",
            "- std::string_view for lightweight string references",
            "- std::filesystem for portable file system operations",
            "",
            "### C++20 Features",
            "- Concepts: template<typename T> concept Addable = requires(T a, T b) { a + b; }",
            "- Ranges: std::views::filter | std::views::transform for composable pipelines",
            "- Coroutines: co_await, co_yield, co_return for async programming",
            "- Modules: module; import std; as replacement for header files",
            "- std::format for type-safe string formatting (like Python f-strings)",
            "- std::span<T> for non-owning views over contiguous sequences",
            "- Three-way comparison operator <=> (spaceship operator)",
            "- Designated initializers: Point{.x = 1, .y = 2}",
            "- consteval and constinit for compile-time guarantees",
            "",
            "### C++23 Features",
            "- std::expected<T, E> for error handling without exceptions",
            "- std::print and std::println for formatted output",
            "- std::flat_map, std::flat_set: sorted vector-based containers",
            "- std::generator for coroutine-based lazy sequences",
            "- std::unreachable() for marking unreachable code paths",
            "- Explicit 'this' parameter (deducing this): void foo(this auto&& self)",
            "",
            "### CMake Build System",
            "- CMakeLists.txt: minimum version, project, add_executable, target_link_libraries",
            "- target_include_directories for header search paths",
            "- target_compile_features for C++ standard requirement (cxx_std_20)",
            "- Modern CMake: target-based, not directory-based (avoid include_directories globally)",
            "- FetchContent for downloading dependencies at configure time",
            "- find_package for system-installed libraries",
            "- cmake --build build_dir --parallel for building",
            "- CMake presets (CMakePresets.json) for reproducible configurations",
            "",
            "### Concurrency",
            "- std::thread for OS-level threads",
            "- std::mutex, std::lock_guard, std::unique_lock for mutual exclusion",
            "- std::shared_mutex for read-write locks (C++17)",
            "- std::atomic<T> for lock-free atomic operations",
            "- std::condition_variable for thread notification",
            "- std::future and std::promise for async result passing",
            "- std::async for launching async tasks: auto fut = std::async(std::launch::async, func)",
            "- std::jthread (C++20): auto-joining thread with stop token support",
            "- std::latch and std::barrier (C++20) for thread coordination",
            "",
            "### Code Examples",
            "RAII resource wrapper with smart pointers:",
            "```cpp",
            "#include <memory>",
            "#include <vector>",
            "#include <algorithm>",
            "",
            "class Widget {",
            "public:",
            "    Widget() = default;",
            "    Widget(const Widget&) = delete;",
            "    Widget& operator=(const Widget&) = delete;",
            "    Widget(Widget&&) noexcept = default;",
            "    Widget& operator=(Widget&&) noexcept = default;",
            "    ~Widget() = default;",
            "",
            "    void add_item(std::unique_ptr<Item> item) {",
            "        items_.push_back(std::move(item));",
            "    }",
            "",
            "    const Item* find(int id) const {",
            "        auto it = std::find_if(items_.begin(), items_.end(),",
            "            [id](const auto& ptr) { return ptr->id() == id; });",
            "        return it != items_.end() ? it->get() : nullptr;",
            "    }",
            "",
            "private:",
            "    std::vector<std::unique_ptr<Item>> items_;",
            "};",
            "```",
            "",
            "C++20 ranges and concepts:",
            "```cpp",
            "#include <ranges>",
            "#include <vector>",
            "#include <concepts>",
            "",
            "template<typename T>",
            "concept Numeric = std::integral<T> || std::floating_point<T>;",
            "",
            "auto squares(std::ranges::range auto&& rng) {",
            "    return rng | std::views::transform([](auto x) { return x * x; });",
            "}",
            "```",
            "",
            "Build commands:",
            "```bash",
            "cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20",
            "cmake --build build --parallel $(nproc)",
            "ctest --test-dir build --output-on-failure",
            "cmake --install build --prefix=/usr/local",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["cpp", "memory_management", "raii", "smart_pointers", "templates", "stl", "move_semantics", "constexpr", "cpp17", "cpp20", "cpp23", "cmake", "concurrency", "modern_cpp"]

module = CogLangCpp()
