from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class AzureCLITool(Tool):
    name = "azure.cli"
    description = "Execute Azure CLI commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"az {command}", timeout=120)
        return result

class AzureStorageTool(Tool):
    name = "azure.storage"
    description = "Manage Azure Storage resources"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"az storage {action}")
        return result

class AzureVMTool(Tool):
    name = "azure.vm"
    description = "Manage Azure Virtual Machines"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, vm_name: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"az vm {action} {vm_name}")
        return result

class CogCloudAzure(CogModule):
    name = "cog-cloud-azure"
    version = "1.0.0"
    description = "Microsoft Azure cloud platform expertise"

    def register_tools(self) -> list[Tool]:
        return [AzureCLITool(), AzureStorageTool(), AzureVMTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Microsoft Azure Expertise",
            "",
            "### Core Azure Services",
            "",
            "Compute:",
            "- Virtual Machines (VM)",
            "- Azure App Service",
            "- Azure Functions (serverless)",
            "- Azure Kubernetes Service (AKS)",
            "- Container Instances (ACI)",
            "- Azure Batch",
            "- Service Fabric",
            "- Cloud Services",
            "",
            "Storage:",
            "- Blob Storage",
            "- Disk Storage",
            "- Azure Files",
            "- Queue Storage",
            "- Table Storage",
            "- Azure Data Lake",
            "- Archive Storage",
            "- Premium SSD",
            "",
            "Databases:",
            "- Azure SQL Database",
            "- Azure Cosmos DB",
            "- Azure Database for MySQL",
            "- Azure Database for PostgreSQL",
            "- Azure Database for MariaDB",
            "- Azure Synapse Analytics",
            "- SQL Managed Instance",
            "",
            "Networking:",
            "- Virtual Network (VNet)",
            "- Load Balancer",
            "- Application Gateway",
            "- Azure Front Door",
            "- Traffic Manager",
            "- CDN",
            "- DNS",
            "- VPN Gateway",
            "- ExpressRoute",
            "",
            "### Azure CLI Commands",
            "",
            "Authentication:",
            "- az login",
            "- az logout",
            "- az account list",
            "- az account set --subscription",
            "",
            "Resource groups:",
            "- az group create",
            "- az group list",
            "- az group show",
            "- az group delete",
            "- az group export",
            "",
            "Virtual machines:",
            "- az vm create",
            "- az vm list",
            "- az vm show",
            "- az vm start",
            "- az vm stop",
            "- az vm restart",
            "- az vm deallocate",
            "- az vm delete",
            "- az vm open-port",
            "- az vm list-sizes",
            "",
            "App Service:",
            "- az webapp create",
            "- az webapp list",
            "- az webapp show",
            "- az webapp up",
            "- az webapp deployment",
            "- az webapp config",
            "",
            "Azure Functions:",
            "- az functionapp create",
            "- az functionapp list",
            "- az functionapp show",
            "",
            "Storage:",
            "- az storage account create",
            "- az storage account list",
            "- az storage container create",
            "- az storage blob upload",
            "- az storage blob list",
            "- az storage blob download",
            "- az storage share create",
            "- az storage file upload",
            "",
            "Azure SQL:",
            "- az sql server create",
            "- az sql db create",
            "- az sql db list",
            "- az sql db show",
            "",
            "Cosmos DB:",
            "- az cosmosdb create",
            "- az cosmosdb list",
            "- az cosmosdb show",
            "- az cosmosdb database create",
            "- az cosmosdb collection create",
            "",
            "Virtual Network:",
            "- az network vnet create",
            "- az network vnet list",
            "- az network vnet show",
            "- az network nsg create",
            "- az network nic create",
            "- az network public-ip create",
            "",
            "Azure Kubernetes Service:",
            "- aks create",
            "- aks list",
            "- aks get-credentials",
            "- aks scale",
            "- aks upgrade",
            "",
            "### Azure vs AWS",
            "",
            "Azure advantages:",
            "- Windows integration",
            "- Active Directory",
            ".NET support",
            "- Enterprise agreements",
            "- Hybrid cloud",
            "- Azure Stack",
            "- GitHub integration",
            "- Visual Studio integration",
            "- Power Platform",
            "- Office 365 integration",
            "",
            "AWS advantages:",
            "- Larger market share",
            "- More service options",
            "- More mature",
            "- Larger ecosystem",
            "- Better Linux support",
            "",
            "When to use Azure:",
            "- Microsoft stack",
            "- Windows workloads",
            "- Enterprise directory",
            "- Office 365 integration",
            "- Hybrid cloud",
            "- .NET applications",
            "- SQL Server",
            "",
            "### Key Azure Concepts",
            "",
            "Resource hierarchy:",
            "- Management groups",
            "- Subscriptions",
            "- Resource groups",
            "- Resources",
            "",
            "Resource tags:",
            "- Environment (dev, test, prod)",
            "- Owner/team",
            "- Cost center",
            "- Application",
            "- Compliance",
            "",
            "Regions:",
            "- Region pairs",
            "- Availability zones",
            "- Geography",
            "- Sovereign clouds",
            "",
            "Pricing:",
            "- Pay-as-you-go",
            "- Reserved instances",
            "- Spot instances",
            "- Azure Hybrid Benefit",
            "- Free tier",
            "",
            "### Azure App Service",
            "",
            "App Service plans:",
            "- Free tier",
            "- Shared (D1, F1)",
            "- Basic (B1, B2, B3)",
            "- Standard (S1, S2, S3)",
            "- Premium (P1V2, P2V2, P3V2)",
            "- Premium v3 (P1V3, P2V3, P3V3)",
            "- Isolated (I1, I2, I3)",
            "",
            "Deployment:",
            "- Git integration",
            "- ZIP deploy",
            "- FTP/S",
            "- WebDeploy",
            "- Local Git",
            "- GitHub Actions",
            "- Azure DevOps",
            "- CI/CD pipelines",
            "",
            "Scaling:",
            "- Scale up (plan size)",
            "- Scale out (instance count)",
            "- Auto-scale rules",
            "- Manual scale",
            "- Scale based on metrics",
            "- Scale based on schedule",
            "",
            "### Azure Functions",
            "",
            "Function apps:",
            "- Consumption plan (serverless)",
            "- Premium plan (Elastic Premium)",
            "- Dedicated plan (App Service)",
            "",
            "Triggers:",
            "- HTTP trigger",
            "- Timer trigger",
            "- Blob trigger",
            "- Queue trigger",
            "- Service Bus trigger",
            "- Event Hub trigger",
            "- Cosmos DB trigger",
            "- Event Grid trigger",
            "",
            "Bindings:",
            "- Input bindings",
            "- Output bindings",
            "- HTTP (I/O)",
            "- Blob (I/O)",
            "- Queue (I/O)",
            "- Cosmos DB (I/O)",
            "- Service Bus (I/O)",
            "- Event Hub (I/O)",
            "- Table (I/O)",
            "",
            "### Azure Storage",
            "",
            "Blob storage tiers:",
            "- Hot (frequent access)",
            "- Cool (infrequent access)",
            "- Archive (rarely accessed)",
            "",
            "Storage account types:",
            "- General-purpose v2 (recommended)",
            "- General-purpose v1",
            "- BlobStorage (blob only)",
            "- BlockBlobStorage (premium)",
            "- FileStorage (file shares)",
            "",
            "Blob types:",
            "- Block blobs (text, binary)",
            "- Append blobs (logs)",
            "- Page blobs (VHD)",
            "",
            "Azure Files:",
            "- SMB protocol",
            "- NFS protocol",
            "- File shares",
            "- Mount on VM",
            "- Mount on-premises",
            "",
            "Queue storage:",
            "- Message queue",
            "- Decoupling",
            "- Async processing",
            "- REST API",
            "",
            "### Azure Databases",
            "",
            "Azure SQL Database:",
            "- Managed instance",
            "- Single database",
            "- Elastic pool",
            "- DTU model",
            "- vCore model",
            "- Serverless",
            "- Hyperscale",
            "",
            "Azure Cosmos DB:",
            "- Multi-model (Document, Graph, Table, Column)",
            "- Global distribution",
            "- Automatic indexing",
            "- Turnkey consistency",
            "- Low latency",
            "- High availability",
            "- 5 consistency levels",
            "- Request units (RU/s)",
            "",
            "Azure Database for MySQL:",
            "- Single server",
            "- Flexible server",
            "- MySQL versions",
            "- High availability",
            "- Backup and restore",
            "",
            "Azure Database for PostgreSQL:",
            "- Single server",
            "- Flexible server",
            "- Hyperscale (Citus)",
            "- PostgreSQL versions",
            "",
            "### Azure Networking",
            "",
            "Virtual Network (VNet):",
            "- Address space (CIDR)",
            "- Subnets",
            "- Network interfaces",
            "- IP addresses (public/private)",
            "- DNS integration",
            "- Route tables",
            "",
            "Load Balancer:",
            "- SKU (Basic, Standard)",
            "- Frontend IP configuration",
            "- Backend pools",
            "- Health probes",
            "- Load balancing rules",
            "- Inbound NAT rules",
            "",
            "Application Gateway:",
            "- Web traffic load balancer",
            "- Layer 7 routing",
            "- SSL termination",
            "- Web Application Firewall (WAF)",
            "- URL path-based routing",
            "- Multi-site routing",
            "- Cookie-based session affinity",
            "",
            "Azure Front Door:",
            "- Global HTTP(S) load balancer",
            "- CDN",
            "- WAF",
            "- URL routing",
            "- Caching",
            "- SSL/TLS termination",
            "- Session affinity",
            "",
            "Traffic Manager:",
            "- DNS-based traffic routing",
            "- Performance routing",
            "- Priority routing",
            "- Weighted routing",
            "- Geographic routing",
            "- Multi-region",
            "",
            "VPN Gateway:",
            "- Site-to-site (S2S)",
            "- Point-to-site (P2S)",
            "- VNet-to-VNet",
            "- ExpressRoute",
            "- Route-based VPN",
            "- Policy-based VPN",
            "",
            "### Azure DevOps",
            "",
            "Azure Repos:",
            "- Git repos",
            "- Pull requests",
            "- Branch policies",
            "- Code review",
            "",
            "Azure Pipelines:",
            "- CI/CD",
            "- Multi-stage pipelines",
            "- YAML pipelines",
            "- Classic pipelines",
            "- Build agents (hosted/self-hosted)",
            "",
            "Azure Test Plans:",
            "- Manual testing",
            "- Exploratory testing",
            "- User acceptance testing",
            "",
            "Azure Artifacts:",
            "- Package management",
            "- NuGet, npm, Maven, pip",
            "- Upstream sources",
            "- Package feeds",
            "",
            "### Azure Security",
            "",
            "Identity:",
            "- Azure AD (Entra ID)",
            "- Managed identities",
            "- Service principals",
            "- Role-based access control (RBAC)",
            "- Conditional access",
            "- MFA",
            "",
            "Security Center:",
            "- Security posture",
            "- Threat protection",
            "- Security policies",
            "- Compliance",
            "",
            "Key Vault:",
            "- Secrets",
            "- Keys",
            "- Certificates",
            "- Managed HSM",
            "- Access policies",
            "",
            "### Quick Reference",
            "",
            "Create resource group:",
            "- az group create --name MyResourceGroup --location eastus",
            "",
            "Create VM:",
            "- az vm create --resource-group MyResourceGroup --name MyVM --image UbuntuLTS --admin-username azureuser --generate-ssh-keys",
            "",
            "Open port on VM:",
            "- az vm open-port --port 80 --resource-group MyResourceGroup --name MyVM",
            "",
            "Create App Service:",
            "- az webapp create --resource-group MyResourceGroup --plan MyPlan --name MyWebApp",
            "",
            "Create storage account:",
            "- az storage account create --name mystorageaccount --location eastus --resource-group MyResourceGroup --sku Standard_LRS",
            "",
            "Create Cosmos DB:",
            "- az cosmosdb create --name MyCosmosDB --resource-group MyResourceGroup --default-consistency-level Session",
            "",
            "Create AKS:",
            "- az aks create --resource-group MyResourceGroup --name MyAKSCluster --node-count 3 --enable-addons monitoring --generate-ssh-keys",
            "",
            "Get AKS credentials:",
            "- az aks get-credentials --resource-group MyResourceGroup --name MyAKSCluster",
            "",
            "Scale AKS:",
            "- az aks scale --resource-group MyResourceGroup --name MyAKSCluster --node-count 5",
            "",
            "Create VNet:",
            "- az network vnet create --resource-group MyResourceGroup --name MyVNet --address-prefixes 10.0.0.0/16",
            "",
            "Create subnet:",
            "- az network vnet subnet create --resource-group MyResourceGroup --vnet-name MyVNet --name MySubnet --address-prefixes 10.0.1.0/24",
            "",
            "Create NSG:",
            "- az network nsg create --resource-group MyResourceGroup --name MyNSG",
            "",
            "Create Function App:",
            "- az functionapp create --resource-group MyResourceGroup --consumption-plan-location eastus --runtime node --functions-version 4 --name MyFunctionApp --storage-account mystorageaccount",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "azure",
            "microsoft_azure",
            "cloud_platform",
            "virtual_machines",
            "app_service",
            "azure_functions",
            "storage",
            "blob_storage",
            "azure_sql",
            "cosmos_db",
            "virtual_network",
            "load_balancer",
            "application_gateway",
            "kubernetes_service",
            "devops",
            "pipelines",
            "security",
            "key_vault",
            "monitoring",
            "serverless"
        ]

module = CogCloudAzure()
