from cog.cog_module import CogModule


class CogPackagePnpm(CogModule):
    name = "cog-package-pnpm"
    version = "1.0.0"
    description = "pnpm package manager module covering content-addressable storage, strict node_modules, workspaces, lock files, .npmrc, hoisting, peer dependencies, catalog feature, and pnpm deploy"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Content-Addressable Storage",
            "",
            "pnpm stores all packages in a global content-addressable store (`~/.local/share/pnpm/store`). Every package",
            "version is stored exactly once, and projects reference it via hard links. This saves disk space and speeds up installs.",
            "",
            "```bash",
            "# Store location",
            "pnpm store path",
            "# → /home/user/.local/share/pnpm/store/v3",
            "",
            "# List all packages in the store",
            "pnpm store ls",
            "",
            "# Prune unreferenced packages from the store",
            "pnpm store prune",
            "",
            "# Force re-linking from the store",
            "pnpm install --force",
            "",
            "# Verify store integrity",
            "pnpm store verify",
            "```",
            "",
            "### Store behavior",
            "- On `pnpm install`, packages are downloaded to the store, then hard-linked to `node_modules`",
            "- If a package already exists in the store (from another project), it is linked instantly — no download",
            "- Hard links share the same inode; modifying a file in one project would affect all — but pnpm prevents this",
            "- On CI, use `pnpm config set store-dir /path/to/cache` to persist the store between runs",
            "- Use `pnpm store prune` periodically to remove orphaned packages from the store",
            "",
            "## Strict node_modules Structure",
            "",
            "pnpm creates a nested `node_modules` with a virtual store directory that enforces strict dependency access.",
            "Packages can only import what they declare as dependencies — phantom dependencies are impossible.",
            "",
            "```",
            "node_modules/",
            "├── .pnpm/                          # virtual store (hard links to global store)",
            "│   ├── express@4.18.2/",
            "│   │   └── node_modules/",
            "│   │       ├── express/            # the actual package",
            "│   │       ├── body-parser/        # express's dependency (accessible only to express)",
            "│   │       └── ...",
            "│   └── lodash@4.17.21/",
            "│       └── node_modules/",
            "│           └── lodash/",
            "├── express/                         # symlink → .pnpm/express@4.18.2/node_modules/express",
            "└── lodash/                          # symlink → .pnpm/lodash@4.17.21/node_modules/lodash",
            "```",
            "",
            "### Strict mode benefits",
            "- No phantom dependencies: if package A depends on B which depends on C, A cannot `import C` unless A also declares C",
            "- No NPM flattening bugs: each package sees exactly its declared dependencies",
            "- Symlinks at the top level point into `.pnpm/` which contains the real resolution",
            "- `public-hoist-pattern` controls what gets hoisted to the root `node_modules`",
            "- `.modules.yaml` in `node_modules` tracks pnpm metadata",
            "",
            "## pnpm Workspaces",
            "",
            "```yaml",
            "# pnpm-workspace.yaml",
            "packages:",
            "  - 'packages/*'",
            "  - 'apps/*'",
            "  - '!**/test'",
            "```",
            "",
            "```bash",
            "# Install dependencies for all workspaces",
            "pnpm install",
            "",
            "# Add dependency to a specific workspace",
            "pnpm add zod --filter @scope/utils",
            "",
            "# Run script across all workspaces in parallel",
            "pnpm -r run build",
            "",
            "# Run script in a single workspace",
            "pnpm --filter @scope/core test",
            "",
            "# Run script in dependencies order (topological)",
            "pnpm -r --sort run build",
            "",
            "# List all workspaces",
            "pnpm ls -r --depth 0",
            "```",
            "",
            "### Workspace patterns",
            "- `--filter <selector>` targets specific packages: by name, directory, or glob",
            "- `--filter ...@scope/main` — run in all dependencies of `@scope/main`",
            "- `--filter @scope/main...` — run in `@scope/main` and all its dependents",
            "- `-r` / `--recursive` runs across all workspace packages",
            "- `--sort` ensures topological order (dependencies before dependents) for build scripts",
            "- Workspace packages are symlinked into each other's `node_modules` for local development",
            "",
            "## pnpm-lock.yaml",
            "",
            "```yaml",
            "# pnpm-lock.yaml (simplified)",
            "importers:",
            "  .:",
            "    dependencies:",
            "      express:",
            "        specifier: ^4.18.2",
            "        version: 4.18.2",
            "  packages/utils:",
            "    dependencies:",
            "      zod:",
            "        specifier: ^3.22.0",
            "        version: 3.22.4",
            "",
            "packages:",
            "  /express/4.18.2:",
            "    resolution: {integrity: sha512-...}",
            "    dependencies:",
            "      body-parser: 1.20.1",
            "      cookie: 0.5.0",
            "    dev: false",
            "```",
            "",
            "### Lock file notes",
            "- Always commit `pnpm-lock.yaml` to version control",
            "- `pnpm import` — convert from `package-lock.json` or `yarn.lock`",
            "- `pnpm install --frozen-lockfile` — CI mode; fails if lock file is out of date",
            "- `pnpm install --no-frozen-lockfile` — allows updates (default in dev)",
            "- Lock file includes resolution integrity hashes for supply chain verification",
            "",
            "## .npmrc Configuration",
            "",
            "```ini",
            "# .npmrc (project-level)",
            "strict-peer-dependencies=true",
            "auto-install-peers=true",
            "shamefully-hoist=false",
            "public-hoist-pattern[]=*eslint*",
            "public-hoist-pattern[]=*prettier*",
            "hoist-pattern[]=*types*",
            "",
            "# Custom registry",
            "registry=https://registry.npmjs.org/",
            "@mycompany:registry=https://registry.mycompany.com/",
            "",
            "# Store configuration",
            "store-dir=~/.local/share/pnpm/store",
            "",
            "# Node version enforcement",
            "use-node-version=20.11.0",
            "",
            "# Side effects cache (speeds up reinstall)",
            "side-effects-cache=true",
            "```",
            "",
            "### Key .npmrc settings",
            "- `strict-peer-dependencies=true` — fail on missing/incorrect peer dependencies",
            "- `auto-install-peers=true` — automatically install peer dependencies",
            "- `shamefully-hoist=true` — hoist all deps to root (mimics npm/yarn; loses strictness)",
            "- `public-hoist-pattern` — hoist only matching packages to root `node_modules`",
            "- `hoist-pattern` — hoist matching packages inside `.pnpm/node_modules`",
            "- `node-linker=hoisted` — disable symlinks entirely (useful for incompatible tools)",
            "",
            "## Hoisting",
            "",
            "By default, pnpm does not hoist dependencies. This enforces strict access but may break packages that rely on flat `node_modules`.",
            "",
            "```ini",
            "# Option 1: Shamefully hoist everything (defeats pnpm's purpose)",
            "shamefully-hoist=true",
            "",
            "# Option 2: Selective hoisting (preferred)",
            "public-hoist-pattern[]=*eslint*",
            "public-hoist-pattern[]=*prettier*",
            "public-hoist-pattern[]=*typescript*",
            "",
            "# Option 3: Hoist by dependency type",
            "hoist-pattern[]=*types*",
            "",
            "# Option 4: Fully hoisted node_modules (no symlinks)",
            "node-linker=hoisted",
            "```",
            "",
            "### Hoisting guidelines",
            "- Start with strict mode (no hoisting); add exceptions only for incompatible packages",
            "- Use `public-hoist-pattern` for dev tools that expect flat resolution (ESLint, Prettier)",
            "- Use `hoist-pattern` for packages that need to be visible to other packages internally",
            "- If a package crashes with `Cannot find module`, check if it needs a hoisting exception",
            "- `shamefully-hoist=true` is a last resort; it disables pnpm's strict dependency guarantees",
            "",
            "## Peer Dependencies",
            "",
            "```json",
            "{",
            "  \"peerDependencies\": {",
            "    \"react\": \">=18.0.0\",",
            "    \"react-dom\": \">=18.0.0\"",
            "  },",
            "  \"peerDependenciesMeta\": {",
            "    \"react-dom\": { \"optional\": true }",
            "  }",
            "}",
            "```",
            "",
            "```bash",
            "# Install peer dependencies automatically",
            "pnpm config set auto-install-peers true",
            "",
            "# Check for missing/incorrect peer dependencies",
            "pnpm ls --depth 0",
            "",
            "# View why a peer dependency is required",
            "pnpm why react",
            "```",
            "",
            "### Peer dependency patterns",
            "- pnpm warns (or errors with `strict-peer-dependencies`) on missing peer dependencies",
            "- `auto-install-peers=true` automatically installs peer deps at the correct version",
            "- Use `peerDependenciesMeta` to mark optional peers",
            "- In workspaces, peer dependencies should be declared in the workspace root or the consuming package",
            "- React library pattern: declare `react` as a peer, not a regular dependency",
            "",
            "## Catalog Feature",
            "",
            "The catalog lets you synchronize dependency versions across all workspace packages.",
            "",
            "```yaml",
            "# pnpm-workspace.yaml",
            "packages:",
            "  - 'packages/*'",
            "catalog:",
            "  react: ^18.2.0",
            "  typescript: ^5.3.0",
            "  zod: ^3.22.0",
            "  vitest: ^1.2.0",
            "```",
            "",
            "```json",
            "// packages/utils/package.json",
            "{",
            "  \"dependencies\": {",
            "    \"react\": \"catalog:\"",
            "  },",
            "  \"devDependencies\": {",
            "    \"typescript\": \"catalog:\",",
            "    \"vitest\": \"catalog:\"",
            "  }",
            "}",
            "```",
            "",
            "### Catalog patterns",
            "- `\"catalog:\"` — reference the version from the catalog in `pnpm-workspace.yaml`",
            "- Named catalogs for different version ranges:",
            "  ```yaml",
            "  catalogs:",
            "    react17:",
            "      react: ^17.0.0",
            "    react18:",
            "      react: ^18.0.0",
            "  ```",
            "- Use `\"catalog:react17\"` to reference a named catalog",
            "- Single source of truth for dependency versions across the monorepo",
            "- `pnpm -r update --catalog` — update all catalog-referenced dependencies",
            "",
            "## pnpm deploy",
            "",
            "```bash",
            "# Deploy a workspace package with its production dependencies",
            "pnpm deploy --prod /path/to/deploy @scope/api-server",
            "",
            "# Deploy with specific dependencies only",
            "pnpm deploy --filter @scope/web-app --prod ./dist",
            "",
            "# Deploy for a Docker build context",
            "pnpm deploy --filter @scope/api --prod ./docker-context",
            "```",
            "",
            "### Deploy patterns",
            "- `pnpm deploy` copies a workspace package and its production dependencies to a target directory",
            "- The deployed directory has a standalone `node_modules` (no symlinks to the store)",
            "- Use `--prod` to exclude `devDependencies` for production deployments",
            "- Ideal for Docker builds: deploy only what's needed, then COPY into the image",
            "- Combine with `--filter` to deploy specific workspace packages",
            "- The deployed directory is self-contained and can be moved to any location",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "content-addressable-storage",
            "strict-node-modules",
            "pnpm-workspaces",
            "lock-files",
            "npmrc-config",
            "hoisting",
            "peer-dependencies",
            "catalog-feature",
            "pnpm-deploy",
        ]


module = CogPackagePnpm()
