from cog.cog_module import CogModule

class CogLangTypescript(CogModule):
    name = "cog-lang-typescript"
    version = "1.0.0"
    description = "TypeScript language expertise including type system, generics, utility types, decorators, and advanced patterns"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## TypeScript Language Expertise",
            "",
            "### Type System Fundamentals",
            "- Primitive types: string, number, boolean, null, undefined, symbol, bigint",
            "- Object types via interfaces and type aliases",
            "- Literal types: string literals, numeric literals, boolean literals",
            "- Union types: type A = 'foo' | 'bar' | number",
            "- Intersection types: type AB = A & B",
            "- Tuple types: [string, number, ...boolean[]]",
            "- Enum types: numeric enums, string enums, const enums, ambient enums",
            "- Never type for unreachable code and exhaustive checks",
            "- Unknown type as type-safe alternative to any",
            "- Void for functions that don't return a value",
            "",
            "### Interfaces vs Type Aliases",
            "- Interfaces are extendable and can be merged (declaration merging)",
            "- Type aliases can represent unions, intersections, primitives, and more",
            "- Use interfaces for object shapes and public API contracts",
            "- Use type aliases for unions, utility compositions, and complex types",
            "- Interfaces support 'extends' and 'implements'",
            "- Type aliases support mapped types and conditional types",
            "",
            "### Generics",
            "- Generic functions: function identity<T>(arg: T): T",
            "- Generic interfaces: interface Repository<T> { findAll(): T[] }",
            "- Generic classes: class DataStore<T> { private items: T[] = [] }",
            "- Constrained generics: <T extends HasId>",
            "- Default type parameters: <T = string>",
            "- Multiple type parameters: <TKey, TValue>",
            "- Generic utility: type Readonly<T> = { readonly [P in keyof T]: T[P] }",
            "",
            "### Utility Types",
            "- Partial<T>: make all properties optional",
            "- Required<T>: make all properties required",
            "- Readonly<T>: make all properties readonly",
            "- Record<K, V>: construct a type with keys K and values V",
            "- Pick<T, K>: pick specific properties from T",
            "- Omit<T, K>: omit specific properties from T",
            "- Exclude<U, E>: exclude from union U the types in E",
            "- Extract<U, E>: extract from union U the types in E",
            "- NonNullable<T>: exclude null and undefined from T",
            "- ReturnType<F>: return type of function F",
            "- Parameters<F>: parameter types of function F as tuple",
            "- Awaited<T>: unwrapped Promise type (TypeScript 4.5+)",
            "",
            "### Mapped Types",
            "- Basic mapped type: { [P in keyof T]: T[P] }",
            "- Remapping keys: { [P in keyof T as `${P}Getter`]: () => T[P] }",
            "- Conditional mapped types: { [P in keyof T]: T[P] extends Function ? T[P] : never }",
            "- Template literal types with mapped types",
            "- Key remapping via 'as' clause (TypeScript 4.1+)",
            "",
            "### Conditional Types",
            "- Basic conditional: T extends U ? X : Y",
            "- Infer keyword: T extends Array<infer U> ? U : T",
            "- Distributive conditional types over union types",
            "- Non-distributive with [T] extends [U] ? X : Y",
            "- Built-in conditional: Exclude, Extract, NonNullable",
            "",
            "### Type Guards and Narrowing",
            "- typeof guard: if (typeof x === 'string')",
            "- instanceof guard: if (x instanceof Date)",
            "- 'in' operator: if ('name' in obj)",
            "- Custom type guard: function isString(val: any): val is string",
            "- Assertion functions: function assertDefined<T>(val: T): asserts val is NonNullable<T>",
            "- Discriminated union narrowing via common literal property",
            "- Equality narrowing: if (x !== null)",
            "- Exhaustiveness check with never: default case in switch",
            "",
            "### Discriminated Unions",
            "- Tagged union pattern with literal 'type' or 'kind' property",
            "- Pattern matching via switch/if on discriminant",
            "- Exhaustive checking: function assertNever(x: never): never",
            "- Useful for state machines, action types, AST nodes",
            "- Combine with ReturnType for action creators",
            "",
            "### Decorators (Stage 3 / TC39)",
            "- Class decorators: @sealed class Foo {}",
            "- Method decorators: @log, @deprecated, @bind",
            "- Property decorators: validation, metadata",
            "- Parameter decorators: inject, required",
            "- Accessor decorators for getters/setters",
            "- Decorator factories: function log(options?: Options) { return decorator }",
            "- Requires experimentalDecorators or decorator metadata flags",
            "",
            "### tsconfig Key Options",
            "- strict: enables all strict type-checking options",
            "- strictNullChecks: null and undefined not assignable to other types",
            "- noUncheckedIndexedAccess: add undefined to index signature results",
            "- target: ES2022 for modern Node, ES2020 for broad browser support",
            "- module: nodenext for ESM, commonjs for legacy",
            "- moduleResolution: nodenext or bundler",
            "- esModuleInterop: true for CommonJS interop",
            "- skipLibCheck: true for faster builds",
            "- paths and baseUrl for module aliases",
            "- composite and references for project references",
            "",
            "### Declaration Files",
            "- .d.ts files for type-only declarations",
            "- declare module 'lib' for ambient module declarations",
            "- Triple-slash directives: /// <reference types='node' />",
            "- Global augmentation: declare global { ... }",
            "- Module augmentation: declare module 'express' { ... }",
            "",
            "### Code Examples",
            "Generic repository with constraints:",
            "```typescript",
            "interface Entity { id: string }",
            "",
            "class Repository<T extends Entity> {",
            "  constructor(private items: T[] = []) {}",
            "",
            "  findById(id: string): T | undefined {",
            "    return this.items.find(item => item.id === id);",
            "  }",
            "",
            "  add(item: T): void {",
            "    this.items.push(item);",
            "  }",
            "}",
            "```",
            "",
            "Discriminated union with exhaustiveness:",
            "```typescript",
            "type Shape =",
            "  | { kind: 'circle'; radius: number }",
            "  | { kind: 'rect'; width: number; height: number }",
            "  | { kind: 'triangle'; base: number; height: number };",
            "",
            "function area(shape: Shape): number {",
            "  switch (shape.kind) {",
            "    case 'circle': return Math.PI * shape.radius ** 2;",
            "    case 'rect': return shape.width * shape.height;",
            "    case 'triangle': return 0.5 * shape.base * shape.height;",
            "    default: {",
            "      const _exhaustive: never = shape;",
            "      throw new Error(`Unhandled: ${_exhaustive}`);",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Utility types and mapped types:",
            "```typescript",
            "type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;",
            "",
            "type Getters<T> = {",
            "  [P in keyof T as `get${Capitalize<string & P>}`]: () => T[P];",
            "};",
            "",
            "type Result<T> = { ok: true; value: T } | { ok: false; error: string };",
            "```",
            "",
            "Build and check commands:",
            "```bash",
            "npx tsc --noEmit",
            "npx tsc --watch",
            "npx tsc --project tsconfig.build.json",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["typescript", "type_system", "generics", "utility_types", "type_guards", "discriminated_unions", "decorators", "tsconfig", "declaration_files", "mapped_types", "conditional_types", "narrowing"]

module = CogLangTypescript()
