from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class JavaCompileTool(Tool):
    name = "java.compile"
    description = "Compile Java source files"
    required_permissions = ["shell.execute"]

    def execute(self, files: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"javac {files}")
        return result

class MavenTool(Tool):
    name = "java.maven"
    description = "Execute Maven build commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"mvn {command}", timeout=300)
        return result

class GradleTool(Tool):
    name = "java.gradle"
    description = "Execute Gradle build commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"./gradlew {command}", timeout=300)
        return result

class CogLangJava(CogModule):
    name = "cog-lang-java"
    version = "1.0.0"
    description = "Java programming language expertise"

    def register_tools(self) -> list[Tool]:
        return [JavaCompileTool(), MavenTool(), GradleTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Java Programming Expertise",
            "",
            "### Core Java",
            "",
            "Basic concepts:",
            "- Classes and objects",
            "- Interfaces",
            "- Abstract classes",
            "- Inheritance",
            "- Polymorphism",
            "- Encapsulation",
            "- Packages",
            "- Access modifiers (public, protected, private, default)",
            "- Static vs instance",
            "- Final keyword",
            "- this keyword",
            "- super keyword",
            "",
            "Data types:",
            "- Primitives (int, double, boolean, char, etc.)",
            "- Objects (String, Integer, etc.)",
            "- Arrays",
            "- Collections (List, Set, Map)",
            "- Generics",
            "- Enums",
            "- Records (Java 14+)",
            "- Sealed classes (Java 17+)",
            "",
            "Control flow:",
            "- if/else",
            "- switch (expressions in Java 14+)",
            "- for loops",
            "- enhanced for loops",
            "- while loops",
            "- do/while",
            "- break and continue",
            "- return",
            "",
            "OOP principles:",
            "- SOLID principles",
            "- Design patterns",
            "- Dependency injection",
            "- Composition over inheritance",
            "- Interface segregation",
            "",
            "### Java Features",
            "",
            "Java 8 features:",
            "- Lambda expressions",
            "- Streams API",
            "- Optional",
            "- Functional interfaces",
            "- Method references",
            "- Default methods",
            "- CompletableFuture",
            "- Date/Time API",
            "",
            "Java 9 features:",
            "- Modules (JPMS)",
            "- Private interface methods",
            "- Factory methods for collections",
            "- JShell (REPL)",
            "",
            "Java 10-17 features:",
            "- Local variable type inference (var)",
            "- HTTP Client (Java 11)",
            "- Text blocks (Java 15)",
            "- Records (Java 14)",
            "- Pattern matching (Java 16)",
            "- Sealed classes (Java 17)",
            "",
            "Java 21+ features:",
            "- Virtual threads",
            "- Pattern matching for switch",
            "- Record patterns",
            "- String templates (preview)",
            "",
            "### Exception Handling",
            "",
            "Exception types:",
            "- Checked exceptions (compile-time)",
            "- Unchecked exceptions (runtime)",
            "- Errors (system level)",
            "",
            "Exception keywords:",
            "- try",
            "- catch",
            "- finally",
            "- throw",
            "- throws",
            "",
            "Exception practices:",
            "- Try-with-resources",
            "- Multi-catch (Java 7+)",
            "- Custom exceptions",
            "- Exception chaining",
            "- Don't catch Throwable",
            "- Don't ignore exceptions",
            "",
            "### Collections Framework",
            "",
            "Collection types:",
            "- List (ArrayList, LinkedList)",
            "- Set (HashSet, LinkedHashSet, TreeSet)",
            "- Map (HashMap, LinkedHashMap, TreeMap, ConcurrentHashMap)",
            "- Queue (LinkedList, PriorityQueue)",
            "- Deque (ArrayDeque, LinkedList)",
            "",
            "Collection methods:",
            "- add/addAll",
            "- remove/removeAll",
            "- retainAll/retainAll",
            "- contains/containsAll",
            "- size/isEmpty",
            "- clear",
            "- iterator/spliterator",
            "- stream/parallelStream",
            "",
            "Collection best practices:",
            "- Choose right collection type",
            "- Initialize with capacity",
            "- Use immutable collections",
            "- Use forEach (Java 8+)",
            "- Use streams for bulk operations",
            "- Avoid null in collections",
            "",
            "### Streams API",
            "",
            "Stream operations:",
            "- Intermediate (filter, map, sorted, distinct)",
            "- Terminal (collect, forEach, reduce, count)",
            "- Short-circuit (findFirst, findAny, anyMatch, allMatch)",
            "",
            "Common stream patterns:",
            "- filter/map/collect",
            "- flatMap",
            "- groupingBy",
            "- partitioningBy",
            "- reducing",
            "",
            "Stream sources:",
            "- Collection.stream()",
            "- Arrays.stream()",
            "- Stream.of()",
            "- IntStream.range()",
            "- BufferedReader.lines()",
            "",
            "### Maven",
            "",
            "POM structure:",
            "- project coordinates (groupId, artifactId, version)",
            "- dependencies",
            "- build plugins",
            "- properties",
            "- profiles",
            "- repositories",
            "",
            "Maven commands:",
            "- mvn compile",
            "- mvn test",
            "- mvn package",
            "- mvn install",
            "- mvn clean",
            "- mvn dependency:tree",
            "- mvn dependency:analyze",
            "- mvn versions:display-dependency-updates",
            "",
            "Maven lifecycle phases:",
            "- validate",
            "- compile",
            "- test",
            "- package",
            "- verify",
            "- install",
            "- deploy",
            "",
            "### Gradle",
            "",
            "Gradle build script:",
            "- build.gradle (Groovy DSL)",
            "- build.gradle.kts (Kotlin DSL)",
            "- settings.gradle",
            "- gradle.properties",
            "",
            "Gradle commands:",
            "- ./gradlew build",
            "- ./gradlew test",
            "- ./gradlew bootRun",
            "- ./gradlew dependencies",
            "- ./gradlew clean",
            "",
            "Gradle features:",
            "- Incremental builds",
            "- Build cache",
            "- Configuration avoidance",
            "- Task dependencies",
            "- Multi-project builds",
            "- Custom tasks",
            "",
            "### Spring Boot",
            "",
            "Spring Boot starters:",
            "- spring-boot-starter-web",
            "- spring-boot-starter-data-jpa",
            "- spring-boot-starter-security",
            "- spring-boot-starter-data-redis",
            "- spring-boot-starter-validation",
            "- spring-boot-starter-test",
            "",
            "Spring Boot annotations:",
            "- @SpringBootApplication",
            "- @RestController",
            "- @RequestMapping",
            "- @GetMapping/@PostMapping",
            "- @RequestParam/@PathVariable",
            "- @RequestBody/@ResponseBody",
            "- @Autowired",
            "- @Component/@Service/@Repository",
            "- @Value",
            "- @Configuration/@Bean",
            "- @Profile",
            "",
            "Spring Boot configuration:",
            "- application.properties",
            "- application.yml",
            "- Environment variables",
            "- Command line args",
            "- Configuration properties (@ConfigurationProperties)",
            "",
            "Spring Boot features:",
            "- Auto-configuration",
            "- Embedded server (Tomcat, Jetty, Undertow)",
            "- Actuator (metrics, health)",
            "- Profiles (dev, test, prod)",
            "- Logging (Logback)",
            "- Externalized configuration",
            "- Data validation",
            "- Testing (@SpringBootTest)",
            "",
            "### Spring Framework",
            "",
            "Spring Core:",
            "- IoC container",
            "- Dependency injection",
            "- Beans",
            "- Scopes (singleton, prototype)",
            "- Bean lifecycle",
            "",
            "Spring MVC:",
            "- DispatcherServlet",
            "- Controllers",
            "- Views",
            "- Model",
            "- Handler mappings",
            "- View resolvers",
            "",
            "Spring Data:",
            "- Repositories (JpaRepository, CrudRepository)",
            "- Query methods",
            "- @Query (JPQL/SQL)",
            "- Paging and sorting",
            "- Auditing",
            "- Transactions",
            "",
            "Spring Security:",
            "- Authentication",
            "- Authorization",
            "- Users and roles",
            "- JWT",
            "- OAuth2",
            "- LDAP",
            "",
            "### Testing",
            "",
            "JUnit 5:",
            "- @Test",
            "- @BeforeEach/@BeforeAll",
            "- @AfterEach/@AfterAll",
            "- @DisplayName",
            "- Assertions",
            "- Assumptions",
            "- @ParameterizedTest",
            "- @RepeatedTest",
            "",
            "Testing annotations:",
            "- @SpringBootTest (integration tests)",
            "- @WebMvcTest (MVC tests)",
            "- @DataJpaTest (JPA tests)",
            "- @MockBean (mock beans)",
            "- @SpyBean (spy beans)",
            "- @Autowired (inject dependencies)",
            "",
            "Testing best practices:",
            "- Arrange-Act-Assert",
            "- Given-When-Then",
            "- Test one thing",
            "- Descriptive test names",
            "- Test behavior, not implementation",
            "- Use mocks for dependencies",
            "",
            "### Java Concurrency",
            "",
            "Concurrency primitives:",
            "- Threads (Thread class)",
            "- Runnable",
            "- Callable",
            "- Executors (ExecutorService)",
            "- Thread pools",
            "- Futures",
            "- CompletableFuture",
            "- Virtual threads (Java 21+)",
            "",
            "Synchronization:",
            "- synchronized keyword",
            "- Lock interface",
            "- ReentrantLock",
            "- ReadWriteLock",
            "- Volatile",
            "- Atomic classes",
            "",
            "Concurrent collections:",
            "- ConcurrentHashMap",
            "- ConcurrentLinkedQueue",
            "- CopyOnWriteArrayList",
            "- BlockingQueue (ArrayBlockingQueue, LinkedBlockingQueue)",
            "",
            "### Performance Optimization",
            "",
            "JVM tuning:",
            "- Heap size (-Xms, -Xmx)",
            "- Garbage collectors (G1GC, ZGC, Shenandoah)",
            "- GC logging",
            "- JIT compilation",
            "",
            "Code optimization:",
            "- String concatenation (StringBuilder)",
            "- Collection sizing",
            "- Avoid boxing/unboxing",
            "- Stream vs for loop",
            "- Lazy initialization",
            "- Caching",
            "- Connection pooling",
            "",
            "Profiling:",
            "- VisualVM",
            "- JProfiler",
            "- YourKit",
            "- Async profiler",
            "- Flight Recorder",
            "",
            "### Java Best Practices",
            "",
            "Code style:",
            "- Follow Java conventions",
            "- Use meaningful names",
            "- Keep methods small",
            "- Single responsibility",
            "- DRY (Don't Repeat Yourself)",
            "- Avoid code smells",
            "- Use IDE formatting",
            "",
            "Error handling:",
            "- Handle specific exceptions",
            "- Don't ignore exceptions",
            "- Use custom exceptions",
            "- Log exceptions",
            "- Don't use exceptions for control flow",
            "",
            "Memory management:",
            "- Avoid memory leaks",
            "- Close resources (try-with-resources)",
            "- Use weak references for caching",
            "- Don't hold onto objects",
            "- Profile memory usage",
            "",
            "### Java vs Other Languages",
            "",
            "Java advantages:",
            "- Platform independent (JVM)",
            "- Strong typing",
            "- Mature ecosystem",
            "- Enterprise support",
            "- Multithreading",
            "- Backward compatibility",
            "- Garbage collection",
            "- Rich standard library",
            "",
            "When to use Java:",
            "- Enterprise applications",
            "- Backend services",
            "- Microservices",
            "- Android apps (Kotlin alternative)",
            "- Big data (Hadoop)",
            "- High-performance systems",
            "",
            "### Quick Reference",
            "",
            "Compile Java:",
            "- javac MyClass.java",
            "",
            "Run Java:",
            "- java MyClass",
            "",
            "Maven build:",
            "- mvn clean package",
            "",
            "Run tests:",
            "- mvn test",
            "",
            "Gradle build:",
            "- ./gradlew build",
            "",
            "Run Spring Boot:",
            "- mvn spring-boot:run",
            "- ./gradlew bootRun",
            "",
            "Create JAR:",
            "- mvn package",
            "- java -jar target/myapp.jar",
            "",
            "Add dependency (Maven):",
            "<dependency>",
            "  <groupId>org.springframework.boot</groupId>",
            "  <artifactId>spring-boot-starter-web</artifactId>",
            "</dependency>",
            "",
            "Add dependency (Gradle):",
            "implementation 'org.springframework.boot:spring-boot-starter-web'",
            "",
            "Stream example:",
            "List<String> result = list.stream()",
            "  .filter(s -> s.length() > 3)",
            "  .map(String::toUpperCase)",
            "  .sorted()",
            "  .collect(Collectors.toList());",
            "",
            "Optional usage:",
            "Optional<String> opt = Optional.ofNullable(value);",
            "String result = opt.orElse(\"default\");",
            "String result = opt.orElseThrow(() -> new IllegalStateException());",
            "",
            "Record class:",
            "public record Person(String name, int age) {}",
            "",
            "Virtual thread:",
            "Thread vThread = Thread.startVirtualThread(() -> {",
            "  // task",
            "});",
            "",
            "Spring Boot controller:",
            "@RestController",
            "@RequestMapping(\"/api\")",
            "public class MyController {",
            "  @GetMapping(\"/users/{id}\")",
            "  public User getUser(@PathVariable Long id) {",
            "    return userService.findById(id);",
            "  }",
            "}",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "java",
            "jvm",
            "spring_boot",
            "spring_framework",
            "maven",
            "gradle",
            "oop",
            "streams",
            "collections",
            "generics",
            "lambdas",
            "testing",
            "junit",
            "mockito",
            "concurrency",
            "threads",
            "jvm_tuning",
            "garbage_collection",
            "design_patterns",
            "solid_principles",
            "dependency_injection",
            "rest_api",
            "microservices"
        ]

module = CogLangJava()
