from cog.cog_module import CogModule

class CogDbRedis(CogModule):
    name = "cog-db-redis"
    version = "1.0.0"
    description = "Redis expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Redis In-Memory Data Store Expertise",
            "",
            "### Core Concepts",
            "- Key-value store",
            "- In-memory data structure store",
            "- Single-threaded (mostly)",
            "- O(1) operations",
            "- Data persistence to disk (RDB/AOF)",
            "- Pub/Sub messaging",
            "- Transaction support (MULTI/EXEC/DISCARD)",
            "- Keyspace expiration (TTL)",
            "- Lua scripting",
            "- Modules (extensions)",
            "",
            "### Data Structures",
            "- Strings (binary safe)",
            "- Hashes (object fields)",
            "- Lists (ordered collections)",
            "- Sets (unique collections)",
            "- Sorted Sets (ranked sets with scores)",
            "- Bitmaps (binary operations)",
            "- HyperLogLogs (probabilistic data structures)",
            "- Geospatial (location data)",
            "- Streams (log processing)",
            "",
            "### Redis Operations",
            "- SET key value",
            "- GET key",
            "- MGET key1 key2",
            "- SETEX key seconds value",
            "- INCR key (atomic increment)",
            "- DECR key",
            "- EXISTS key",
            "- DELETE key",
            "- EXPIRE key seconds",
            "- TTL key",
            "- KEYS pattern",
            "",
            "### Hash Operations",
            "- HSET key field value",
            "- HGET key field",
            "HGETALL key",
            "HINCRBY key field increment",
            "HEXISTS key field",
            "",
            "### List Operations",
            "- LPUSH key value",
            "- LRANGE key start stop",
            "- LPOP key",
            "- LLEN key",
            "",
            "### Set Operations",
            "- SADD key member",
            "- SMEMBERS key",
            "- SISMEMBER key member",
            "- SUNION, SINTER, SDIFF",
            "",
            "### Sorted Set Operations",
            "- ZADD key score member",
            "ZRANGE key start stop",
            "ZRANK key member",
            "- ZRANGEBYSCORE min max",
            "",
            "### Pub/Sub",
            "- PUBLISH channel message",
            "- SUBSCRIBE channel",
            "- PSUBSCRIBE pattern",
            "- UNSUBSCRIBE channel",
            "",
            "### Persistence",
            "- RDB (snapshot)",
            "- AOF (append-only file)",
            "- RDB+AOF (both)",
            "- Save commands for manual snapshots",
            "",
            "### Clustering",
            "- Redis Cluster (distributed)",
            "- Sentinel (high availability)",
            "- Master-slave replication",
            "- Hash slots across nodes",
            "- Redis Enterprise",
            "",
            "### Common Use Cases",
            "",
            "Caching:",
            "- Session storage",
            "- Query results",
            "API responses",
            "- Page fragments",
            "- Database query cache",
            "",
            "Rate limiting:",
            "- Request counting",
            "- Sliding window",
            "- Token bucket",
            "",
            "Real-time features:",
            "- Leaderboards",
            "- Session management",
            "- Pub/Sub messaging",
            "- Real-time analytics",
            "",
            "Queues:",
            "- Job queues",
            "- Message queues",
            "- Task queues",
            "",
            "### Redis vs Memcached",
            "- Redis: Persistence, data structures, pub/sub",
            "- Memcached: Simple caching only",
            "- Redis: Slower for simple caching",
            "- Memcached: Faster for simple key-value",
            "",
            "### Quick Reference",
            "Connect:",
            "```bash",
            "redis-cli",
            "redis-cli -h localhost -p 6379",
            "```",
            "",
            "Basic operations:",
            "```redis",
            "SET user:1:name 'John'",
            "GET user:1:name",
            "SETEX user:1:session 3600 'abc123'",
            "INCR counter",
            "ZADD leaderboard 100 'player1'",
            "PUBLISH updates 'User updated'",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["redis", "caching", "pub_sub", "streams", "clustering", "persistence"]

module = CogDbRedis()
