from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class RubyTool(Tool):
    name = "ruby.execute"
    description = "Execute Ruby scripts"
    required_permissions = ["shell.execute"]

    def execute(self, script: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"ruby {script}")
        return result

class BundlerTool(Tool):
    name = "ruby.bundler"
    description = "Execute Bundler commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"bundle {command}", timeout=300)
        return result

class RailsTool(Tool):
    name = "ruby.rails"
    description = "Execute Rails commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"rails {command}")
        return result

class CogLangRuby(CogModule):
    name = "cog-lang-ruby"
    version = "1.0.0"
    description = "Ruby programming language expertise"

    def register_tools(self) -> list[Tool]:
        return [RubyTool(), BundlerTool(), RailsTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Ruby Programming Expertise",
            "",
            "### Core Ruby",
            "",
            "Basic concepts:",
            "- Objects (everything is an object)",
            "- Classes",
            "- Modules",
            "- Methods",
            "- Blocks",
            "- Procs",
            "- Lambdas",
            "- Closures",
            "- Mixins",
            "- Duck typing",
            "",
            "Ruby syntax:",
            "- Variables (local, instance, class, global)",
            "- Constants",
            "- Methods (def/end)",
            "- Conditionals (if/else, unless, case)",
            "- Loops (while, until, for, iterators)",
            "- Exception handling (begin/rescue/ensure)",
            "- Interpolation (#{} )",
            "- String delimiters (', %, %Q)",
            "",
            "Object-oriented features:",
            "- Inheritance (single inheritance)",
            "- Modules (mixins)",
            "- Access control (public, private, protected)",
            "- Method visibility",
            "- Class methods vs instance methods",
            "- Singleton methods",
            "- Class variables (@@)",
            "- Instance variables (@)",
            "",
            "### Modern Ruby Features",
            "",
            "Ruby 2.x-3.x features:",
            "- Keyword arguments (def foo(a:, b:))",
            "- Safe navigation operator (&.)",
            "- Frozen string literals",
            "- Squiggly heredoc (<<~)",
            "- Numbered parameters (_1, _2)",
            "- Pattern matching (case/in)",
            "- Endless methods (def foo() = bar)",
            "- Rightward assignment (=>)",
            "- Find patterns",
            "",
            "### Blocks, Procs, Lambdas",
            "",
            "Blocks:",
            "- Implicit blocks (do/end, {})",
            "- yield keyword",
            "- Block parameters",
            "- Block arity",
            "",
            "Procs:",
            "- Proc objects",
            "- Proc.new",
            "- &proc (to block)",
            "- proc (syntactic sugar)",
            "",
            "Lambdas:",
            "- Lambda literal (->)",
            "- lambda method",
            "- Argument checking",
            "- Return behavior",
            "",
            "### Ruby on Rails",
            "",
            "Rails architecture:",
            "- MVC pattern",
            "- Active Record (ORM)",
            "- Action Controller",
            "- Action View",
            "- Action Mailer",
            "- Active Job",
            "- Action Cable (WebSockets)",
            "- Active Storage (file uploads)",
            "- Action Text (rich text)",
            "- Active Model (validations)",
            "",
            "Rails CLI:",
            "- rails new (create app)",
            "- rails server (start server)",
            "- rails console (REPL)",
            "- rails generate (scaffold, model, controller)",
            "- rails destroy (undo generation)",
            "- rails db:migrate",
            "- rails db:rollback",
            "- rails db:seed",
            "- rails routes",
            "- rails test",
            "",
            "Active Record:",
            "- Models (class ApplicationRecord)",
            "- Migrations (change method)",
            "- Associations (has_many, belongs_to, has_one, has_and_belongs_to_many)",
            "- Validations (validates, validate)",
            "- Callbacks (before_save, after_create)",
            "- Scopes",
            "- Query interface (where, find, order, limit)",
            "- Eager loading (includes, joins, preload)",
            "- Transactions",
            "- Counter cache",
            "- Polymorphic associations",
            "- Single table inheritance",
            "",
            "Rails best practices:",
            "- Fat models, skinny controllers",
            "- Use concerns for shared code",
            "- Use strong parameters",
            "- Use database indexes",
            "- Use background jobs (Active Job)",
            "- Use caching (fragment, Russian doll)",
            "- Use background jobs for slow tasks",
            "- Use background jobs for email",
            "",
            "### Sinatra",
            "",
            "Sinatra basics:",
            "- Lightweight web framework",
            "- Routes (get, post, put, delete, patch)",
            "- Templates (ERB, Haml)",
            "- Before/after filters",
            "- Helpers",
            "- Middleware",
            "- Session support",
            "",
            "Sinatra vs Rails:",
            "- Sinatra: simpler, more control",
            "- Rails: more features, convention over configuration",
            "",
            "### RSpec",
            "",
            "RSpec testing:",
            "- describe/context",
            "- it/example",
            "- expect/should syntax",
            "- Matchers (eq, be_true, include, etc.)",
            "- let/let!",
            "- before/after",
            "- subject",
            "- shared_examples",
            "- mocks/doubles",
            "- stubs",
            "",
            "RSpec Rails:",
            "- Request specs",
            "- Controller specs",
            "- Model specs",
            "- Feature specs (Capybara)",
            "- Routing specs",
            "- View specs",
            "- Helper specs",
            "- Mailer specs",
            "- Job specs",
            "",
            "RSpec best practices:",
            "- Test one thing per example",
            "- Use context for different scenarios",
            "- Use describe for methods",
            "- Use let for lazy evaluation",
            "- Use subject under test",
            "- Avoid mock for everything (unit test)",
            "",
            "### Bundler",
            "",
            "Bundler commands:",
            "- bundle install",
            "- bundle update",
            "- bundle exec (execute in context)",
            "- bundle add (add gem)",
            "- bundle remove (remove gem)",
            "- bundle package (vendor gems)",
            "- bundle show (show gem location)",
            "- bundle outdated (show outdated)",
            "- bundle clean (remove unused)",
            "",
            "Gemfile:",
            "- source (gem source)",
            "- gem (declare dependency)",
            "- group (group dependencies)",
            "- platform (platform-specific)",
            "- git (git repo)",
            "- path (local path)",
            "",
            "### RubyGems",
            "",
            "RubyGems commands:",
            "- gem install",
            "- gem uninstall",
            "- gem update",
            "- gem list",
            "- gem search",
            "- gem build",
            "- gem push",
            "- gem server",
            "",
            "### Ruby Metaprogramming",
            "",
            "Metaprogramming techniques:",
            "- define_method",
            "- method_missing",
            "- class_eval",
            "- instance_eval",
            "- class_variable_set",
            "- instance_variable_set",
            "- const_set",
            "- send (public_send)",
            "",
            "Metaprogramming use cases:",
            "- Dynamic finders",
            "- DSLs (domain-specific languages)",
            "- delegation",
            "- Decorator pattern",
            "",
            "### Ruby Performance",
            "",
            "Performance tips:",
            "- Avoid string concatenation in loops (use array.join)",
            "- Use symbols for hash keys (performance)",
            "- Use frozen string literals",
            "- Use lazy enumeration for large collections",
            "- Use benchmark-ips for benchmarking",
            "- Use ruby-prof for profiling",
            "",
            "Memory optimization:",
            "- Use GC.stat to monitor GC",
            "- Use GC.start to force GC",
            "- Use ObjectSpace to count objects",
            "- Use weak_ref for weak references",
            "",
            "### Ruby Best Practices",
            "",
            "Code style:",
            "- Follow Ruby style guide",
            "- Use meaningful names",
            "- Keep methods small",
            "- Use snake_case for naming",
            "- Use modules for namespacing",
            "- Use freeze on constants",
            "- Use ||= (memoization)",
            "- Use &. (safe navigation)",
            "",
            "Error handling:",
            "- Use begin/rescue for exceptions",
            "- Rescue specific exceptions",
            "- Use ensure for cleanup",
            "- Don't use rescue for control flow",
            "",
            "Ruby idioms:",
            "- Use map over collect",
            "- Use select/find_all over filter",
            "- Use find over detect",
            "- Use each over for",
            "- Use ||= for memoization",
            "- Use || for default values",
            "",
            "### Ruby vs Other Languages",
            "",
            "Ruby advantages:",
            "- Elegant syntax",
            "- Object-oriented (everything is an object)",
            "- Metaprogramming",
            "- Blocks (code as data)",
            "- Dynamic typing",
            "- Rails framework",
            "- Developer happiness",
            "",
            "When to use Ruby:",
            "- Web development (Rails)",
            "- Scripting",
            "- Prototyping",
            "- Startups (fast iteration)",
            "- Developer productivity",
            "",
            "### Quick Reference",
            "",
            "Run Ruby:",
            "- ruby script.rb",
            "- ruby -e 'puts \"hello\"'",
            "",
            "IRB (REPL):",
            "- irb",
            "- pry (better REPL)",
            "",
            "Create Rails app:",
            "- rails new myapp",
            "",
            "Start Rails server:",
            "- rails server",
            "- rails s (short)",
            "",
            "Rails console:",
            "- rails console",
            "- rails c (short)",
            "",
            "Generate scaffold:",
            "- rails generate scaffold User name:string email:string",
            "- rails g scaffold User name:string email:string (short)",
            "",
            "Run migrations:",
            "- rails db:migrate",
            "",
            "Rollback migration:",
            "- rails db:rollback",
            "",
            "Seed database:",
            "- rails db:seed",
            "",
            "Install gems:",
            "- bundle install",
            "",
            "Add gem:",
            "- bundle add rspec-rails",
            "",
            "Run tests:",
            "- rails test",
            "- bundle exec rspec (RSpec)",
            "",
            "Ruby examples:",
            "",
            "Blocks:",
            "[1, 2, 3].each { |n| puts n }",
            "",
            "Procs:",
            "p = Proc.new { |n| n * 2 }",
            "p.call(5) # => 10",
            "",
            "Lambdas:",
            "l = ->(n) { n * 2 }",
            "l.call(5) # => 10",
            "",
            "Safe navigation:",
            "user&.address&.city",
            "",
            "Keyword arguments:",
            "def greet(name:, message: 'Hello')",
            "  \"#{message}, #{name}!\"",
            "end",
            "greet(name: 'John') # => 'Hello, John!'",
            "",
            "Pattern matching (Ruby 2.7+):",
            "case {a: 1, b: 2}",
            "in {a: a, b: b}",
            "  \"a: #{a}, b: #{b}\"",
            "end",
            "",
            "Numbered parameters (Ruby 2.7+):",
            "[1, 2, 3].map { _1 * 2 } # => [2, 4, 6]",
            "",
            "Endless method (Ruby 3.0+):",
            "def square(n) = n * 2",
            "",
            "Rails model:",
            "class User < ApplicationRecord",
            "  has_many :posts",
            "  validates :name, presence: true",
            "  validates :email, uniqueness: true",
            "",
            "  scope :active, -> { where(active: true) }",
            "end",
            "",
            "Rails controller:",
            "class UsersController < ApplicationController",
            "  def show",
            "    @user = User.find(params[:id])",
            "  end",
            "end",
            "",
            "RSpec test:",
            "RSpec.describe User, type: :model do",
            "  subject { build(:user) }",
            "",
            "  it 'is valid with valid attributes' do",
            "    expect(subject).to be_valid",
            "  end",
            "end",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "ruby",
            "rails",
            "sinatra",
            "rspec",
            "bundler",
            "rubygems",
            "metaprogramming",
            "mvc",
            "active_record",
            "activerecord",
            "rest_api",
            "web_development",
            "testing",
            "blocks",
            "procs",
            "lambdas",
            "oop",
            "mixins",
            "duck_typing",
            "dsl"
        ]

module = CogLangRuby()
