from cog.cog_module import CogModule

class CogInfraGitlab(CogModule):
    name = "cog-infra-gitlab"
    version = "1.0.0"
    description = "GitLab CI/CD expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## GitLab CI/CD Expertise",
            "",
            "### Core Concepts",
            "- .gitlab-ci.yml (pipeline definition in project root)",
            "- Pipelines (collection of jobs executed in stages)",
            "- Stages (ordered groups: build, test, deploy)",
            "- Jobs (individual tasks with scripts and configuration)",
            "- Runners (machines that execute jobs: shared, group, specific)",
            "- Artifacts (files produced by jobs, passed between stages)",
            "- Cache (dependencies shared across pipelines)",
            "- Environments (deployment targets: staging, production)",
            "- Variables (CI/CD variables: project, group, instance level)",
            "- Merge requests (code review with pipeline integration)",
            "",
            "### Pipeline Configuration",
            "- stages keyword defines execution order",
            "- Default stage order: .pre, build, test, deploy, .post",
            "- Jobs without a stage default to the test stage",
            "- Workflow rules for controlling pipeline creation",
            "- Pipeline variables and variable precedence",
            "- Multi-project pipelines (trigger across projects)",
            "- Parent-child pipelines (downstream pipeline generation)",
            "- DAG (directed acyclic graph) with needs keyword",
            "- Parallel jobs with parallel: N or parallel matrix",
            "- Interruptible jobs for auto-cancel on new pushes",
            "",
            "### Job Configuration",
            "- script (shell commands to execute)",
            "- image (Docker image for the job)",
            "- services (linked Docker containers: databases, etc.)",
            "- before_script / after_script (pre/post commands)",
            "- only / except (legacy job control)",
            "- rules (modern conditional job execution)",
            "- tags (runner selection)",
            "- variables (job-level variables)",
            "- artifacts (output files and paths)",
            "- cache (dependency caching)",
            "- coverage (regex for coverage extraction)",
            "- retry (auto-retry on failure)",
            "- timeout (job-level timeout)",
            "- resource_group (job mutex for deployments)",
            "- inherit (control variable/defaults inheritance)",
            "",
            "### Runners",
            "- Shared runners (available to all projects)",
            "- Group runners (available to projects in a group)",
            "- Specific runners (bound to individual projects)",
            "- Runner tags for job matching",
            "- Runner executors: docker, shell, kubernetes, virtualbox, etc.",
            "- GitLab Runner configuration: config.toml",
            "- Runner autoscaling with Docker Machine or Kubernetes",
            "- Register runners: gitlab-runner register",
            "- Runner management: pause, unpause, delete",
            "",
            "### Environments and Deployments",
            "- Define environments in jobs with environment keyword",
            "- Static environments (staging, production)",
            "- Dynamic environments (review/$CI_COMMIT_REF_NAME)",
            "- Environment-specific variables",
            "- Protection rules (restricted to protected branches)",
            "- Deployment approvals (protected environments)",
            "- Rollback to previous deployments",
            "- Environment stop actions (cleanup on branch delete)",
            "",
            "### Variables and Secrets",
            "- Project-level CI/CD variables",
            "- Group-level CI/CD variables (inherited)",
            "- Instance-level CI/CD variables (admin)",
            "- Protected variables (only on protected branches/tags)",
            "- Masked variables (hidden in job logs)",
            "- Environment variables (scope to specific environments)",
            "- File-type variables (injected as files)",
            "- Predefined variables: CI_COMMIT_SHA, CI_COMMIT_BRANCH, CI_PIPELINE_ID, etc.",
            "- Variable expression evaluation in rules",
            "- Vault integration for external secrets",
            "",
            "### Artifact and Cache Management",
            "- Artifacts: job outputs saved and downloadable",
            "- Artifact expiration (expire_in)",
            "- Artifact reports (junit, cobertura, codequality, etc.)",
            "- Dependencies keyword to control artifact passing",
            "- Needs keyword for DAG artifact passing",
            "- Cache: shared across pipelines and branches",
            "- Cache keys: per-branch, per-job, or custom",
            "- Cache fallback keys",
            "- Distributed cache with S3 or GCS backend",
            "",
            "### Merge Request Pipelines",
            "- Rules with $CI_PIPELINE_SOURCE == 'merge_request_event'",
            "- only: merge_requests (legacy)",
            "- Pipeline results shown directly in merge request UI",
            "- Code quality reports inline in MR diffs",
            "- Merge train for sequential merges",
            "- Merge when pipeline succeeds",
            "- Required pipelines for merge approval",
            "",
            "### Best Practices",
            "- Use rules instead of only/except",
            "- Use needs for DAG to parallelize jobs",
            "- Cache dependencies to reduce build times",
            "- Use artifacts:reports for test and coverage visualization",
            "- Set expire_in on artifacts to limit storage",
            "- Use protected/masked variables for secrets",
            "- Use environments with protection rules for deployments",
            "- Use resource_group for serial deployments",
            "- Use extends and !reference for DRY config",
            "- Use include for shared pipeline configs",
            "- Tag jobs for runner selection",
            "- Set interruptible: true for non-critical jobs",
            "",
            "### Common Operations",
            "Pipeline management:",
            "```bash",
            "gitlab-runner exec docker build",
            "gitlab-runner list",
            "gitlab-runner verify",
            "gitlab-runner register --url https://gitlab.com --token <token>",
            "```",
            "",
            "GitLab CLI:",
            "```bash",
            "glab mr create --title 'feat: add auth' --description 'details'",
            "glab mr list",
            "glab mr merge 42",
            "glab pipeline list",
            "glab pipeline status",
            "glab ci trace",
            "glab release create v1.0.0",
            "glab issue create --title 'Bug report'",
            "```",
            "",
            "### Example .gitlab-ci.yml",
            "```yaml",
            "stages:",
            "  - lint",
            "  - test",
            "  - build",
            "  - deploy",
            "",
            "variables:",
            "  APP_NAME: myapp",
            "  DOCKER_REGISTRY: registry.example.com",
            "",
            "default:",
            "  image: node:20-alpine",
            "  cache:",
            "    key:",
            "      files:",
            "        - package-lock.json",
            "    paths:",
            "      - node_modules/",
            "  before_script:",
            "    - npm ci --cache .npm --prefer-offline",
            "",
            "workflow:",
            "  rules:",
            "    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'",
            "    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH",
            "    - if: $CI_COMMIT_TAG",
            "",
            "lint:",
            "  stage: lint",
            "  script:",
            "    - npm run lint",
            "    - npm run typecheck",
            "  rules:",
            "    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'",
            "",
            "test:",
            "  stage: test",
            "  parallel: 3",
            "  script:",
            "    - npm test -- --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL",
            "  artifacts:",
            "    reports:",
            "      junit: reports/junit.xml",
            "      coverage_report:",
            "        coverage_format: cobertura",
            "        path: reports/cobertura.xml",
            "  coverage: '/Statements:\\s+(\\d+\\.\\d+)%/'",
            "  rules:",
            "    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'",
            "    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH",
            "",
            "build:",
            "  stage: build",
            "  script:",
            "    - npm run build",
            "    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHORT_SHA .",
            "    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHORT_SHA",
            "  artifacts:",
            "    paths:",
            "      - dist/",
            "    expire_in: 1 week",
            "  rules:",
            "    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH",
            "    - if: $CI_COMMIT_TAG",
            "",
            "deploy:staging:",
            "  stage: deploy",
            "  image: alpine:latest",
            "  script:",
            "    - echo \"Deploying $CI_COMMIT_SHORT_SHA to staging\"",
            "  environment:",
            "    name: staging",
            "    url: https://staging.example.com",
            "  rules:",
            "    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH",
            "",
            "deploy:production:",
            "  stage: deploy",
            "  image: alpine:latest",
            "  script:",
            "    - echo \"Deploying $CI_COMMIT_TAG to production\"",
            "  environment:",
            "    name: production",
            "    url: https://example.com",
            "  resource_group: production",
            "  rules:",
            "    - if: $CI_COMMIT_TAG",
            "  when: manual",
            "```",
            "",
            "### Example with Include",
            "```yaml",
            "include:",
            "  - project: 'devops/shared-ci'",
            "    ref: main",
            "    file: '/templates/docker-build.yml'",
            "  - component: 'devops/shared-ci/build@1.0'",
            "    inputs:",
            "      stage: build",
            "      image: node:20",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["gitlab_ci", "gitlab", "cicd", "pipelines", "runners", "environments", "merge_requests", "gitlab_api"]

module = CogInfraGitlab()
