from cog.cog_module import CogModule

class CogLangRuby(CogModule):
    name = "cog-lang-ruby"
    version = "1.0.0"
    description = "Ruby language expertise including Rails, RSpec, metaprogramming, blocks/procs/lambdas, ActiveRecord, Sidekiq, and modern tooling"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Ruby Language Expertise",
            "",
            "### Language Fundamentals",
            "- Everything is an object, including numbers and nil",
            "- Duck typing: if it walks like a duck and quacks like a duck",
            "- Implicit return: last expression in a method is the return value",
            "- Symbols vs strings: :name is immutable and reused, 'name' creates new object",
            "- Truthy values: everything except nil and false is truthy (including 0 and '')",
            "- Safe navigation operator: user&.name returns nil instead of NoMethodError",
            "- Frozen string literal: # frozen_string_literal: true at top of file",
            "- ENDLESS METHODS (Ruby 3.0+): def square(x) = x * x",
            "- Pattern matching (Ruby 3.0+): case user in { name:, age: } then name end",
            "",
            "### Blocks, Procs, and Lambdas",
            "- Blocks: anonymous chunks of code passed to methods with yield or &param",
            "- Proc: Proc.new { |x| x * 2 } — objectified block, lenient arity",
            "- Lambda: ->(x) { x * 2 } or lambda { |x| x * 2 } — strict arity, local return",
            "- & operator converts block to Proc and vice versa",
            "- yield for calling blocks: def wrap; print '{'; yield; print '}'; end",
            "- Block given? check: block_given? to conditionally yield",
            "- Enumerable methods rely on blocks: map, select, reduce, each_with_index",
            "",
            "### Modules and Mixins",
            "- include: adds instance methods, inserts above the class in lookup chain",
            "- extend: adds class-level methods to the target",
            "- prepend: inserts below the class in lookup chain, use for method wrapping",
            "- Module#ancestors to inspect method resolution order",
            "- ActiveSupport::Concern for easy module patterns: included do; end; ClassMethods",
            "- Module#method_added hook for tracking method definitions",
            "- Refinements: using Module to scope monkey-patching lexically",
            "",
            "### Metaprogramming",
            "- send(:method_name, *args) for dynamic method dispatch",
            "- define_method(:name) { |args| body } for dynamic method creation",
            "- method_missing for catching undefined method calls",
            "- respond_to_missing? must accompany method_missing",
            "- class_eval to define methods in context of a class",
            "- instance_eval to run code in context of an instance",
            "- const_get, const_set for dynamic constant access",
            "- Struct for quick value objects: User = Struct.new(:name, :email)",
            "- OpenStruct for flexible objects (avoid in hot paths, use Struct instead)",
            "- attr_reader, attr_writer, attr_accessor for automatic getters/setters",
            "",
            "### Ruby on Rails",
            "- Convention over configuration: naming conventions drive behavior",
            "- RESTful routing: resources :users creates all CRUD routes",
            "- Controllers inherit ApplicationController, actions map to HTTP verbs",
            "- Strong parameters: params.require(:user).permit(:name, :email)",
            "- before_action for auth and setup, after_action for logging",
            "- Concerns for shared controller/model logic",
            "- Partial rendering: render partial: 'shared/navbar', locals: { user: current_user }",
            "- Helpers: module ApplicationHelper; def formatted_date(date); end; end",
            "- Background jobs: ActiveJob adapter with Sidekiq, Resque, or Solid Queue",
            "- ActionCable for WebSockets, ActionMailbox for inbound email",
            "",
            "### ActiveRecord and Migrations",
            "- Models inherit ApplicationRecord (which inherits ActiveRecord::Base)",
            "- Associations: has_many, belongs_to, has_one, has_and_belongs_to_many, has_many :through",
            "- Scopes: scope :active, -> { where(active: true) }",
            "- Validations: presence, uniqueness, format, length, custom validate methods",
            "- Callbacks: before_save, after_create, around_destroy",
            "- Migrations: add_column, remove_column, change_column, add_index",
            "- Reversible migrations: def up; def down; or use change with reversible",
            "- Enum: enum status: { active: 0, archived: 1 }",
            "- Single Table Inheritance (STI) for class hierarchies in one table",
            "- Optimistic locking with lock_version column",
            "- batch processing: find_each(batch_size: 500) for memory-efficient iteration",
            "",
            "### Bundler and Gemfile",
            "- Gemfile declares dependencies: gem 'rails', '~> 7.1.0'",
            "- bundle install resolves and installs dependencies",
            "- bundle exec ensures commands run in Gemfile context",
            "- Gemfile.lock for reproducible deployments",
            "- Groups: group :development, :test do; gem 'rspec-rails'; end",
            "- Source, git, path, and platform-specific gems",
            "- bundle config set --local without 'production' to exclude groups",
            "",
            "### RSpec Testing",
            "- describe/context/it structure for test organization",
            "- expect(actual).to eq(expected) for expectations",
            "- let and let! for memoized test data (lazy vs eager)",
            "- before(:each), before(:all), after(:each) for setup/teardown",
            "- Shared examples: shared_examples 'validatable' do; it { should validate... }; end",
            "- Doubles and mocks: allow(obj).to receive(:method).and_return(value)",
            "- Factory Bot: create(:user), build(:user), attributes_for(:user)",
            "- System specs with Capybara: visit '/users', click_button 'Save'",
            "- shoulda-matchers for one-liner Rails validations/associations tests",
            "",
            "### Rack Middleware",
            "- Rack is the HTTP interface layer underlying Rails and Sinatra",
            "- Middleware stack processes request/response pipeline",
            "- Each middleware is a callable: def call(env); status, headers, body = @app.call(env); end",
            "- config.middleware.use, config.middleware.insert_before",
            "- Common middleware: Rack::Attack for rate limiting, Rack::Cors for CORS",
            "- Rack::Request and Rack::Response for request/response objects",
            "",
            "### Sidekiq",
            "- Background job processing with Redis as queue backend",
            "- Jobs are plain Ruby classes: class ProcessImage; include Sidekiq::Job; def perform(id); end; end",
            "- ProcessImage.perform_async(image_id) or perform_in(5.minutes, id)",
            "- Sidekiq::Worker set retry: 3, queue: 'critical'",
            "- Sidekiq Web UI for monitoring at /sidekiq",
            "- Batch processing with Sidekiq::Batch for multi-job workflows",
            "- Schedule with sidekiq-cron for recurring jobs",
            "- ActiveJob integration: sidekiq adapter in application.rb",
            "",
            "### Zeitwerk Autoloading",
            "- Rails 7+ uses Zeitwerk for autoloading and code reloading",
            "- Conventional file-to-constant mapping: app/models/user.rb -> User",
            "- inflections.rb for acronym customization: 'API' instead of 'Api'",
            "- config.autoload_paths and config.eager_load_paths",
            "- Namespaces: app/controllers/admin/users_controller.rb -> Admin::UsersController",
            "- Zeitwerk is strict: file name must match constant name",
            "",
            "### Code Examples",
            "Rails model with associations and scopes:",
            "```ruby",
            "class User < ApplicationRecord",
            "  has_many :posts, dependent: :destroy",
            "  has_many :comments, through: :posts",
            "  has_one :profile, dependent: :nullify",
            "",
            "  scope :active, -> { where(deactivated_at: nil) }",
            "  scope :recent, -> { order(created_at: :desc).limit(10) }",
            "",
            "  validates :email, presence: true, uniqueness: true, format: URI::MailTo::EMAIL_REGEXP",
            "  validates :name, presence: true, length: { maximum: 100 }",
            "",
            "  def display_name",
            "    nickname.presence || name.split.first",
            "  end",
            "end",
            "```",
            "",
            "RSpec model spec:",
            "```ruby",
            "RSpec.describe User, type: :model do",
            "  subject { build(:user) }",
            "",
            "  it { is_expected.to validate_presence_of(:email) }",
            "  it { is_expected.to have_many(:posts).dependent(:destroy) }",
            "",
            "  describe '#display_name' do",
            "    context 'with nickname' do",
            "      let(:user) { build(:user, nickname: 'coderrb', name: 'Jane Doe') }",
            "      it 'returns the nickname' do",
            "        expect(user.display_name).to eq('coderrb')",
            "      end",
            "    end",
            "  end",
            "end",
            "```",
            "",
            "Build and run commands:",
            "```bash",
            "bundle install",
            "bundle exec rails db:migrate",
            "bundle exec rspec",
            "bundle exec rubocop",
            "bundle exec rails server -p 3000",
            "bundle exec sidekiq",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["ruby", "rails", "rspec", "metaprogramming", "blocks_procs_lambdas", "active_record", "migrations", "bundler", "sidekiq", "zeitwerk", "rack_middleware", "mixins"]

module = CogLangRuby()
