from cog.cog_module import CogModule


class CogDbMysql(CogModule):
    name = "cog-db-mysql"
    version = "1.0.0"
    description = "MySQL relational database expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## MySQL Relational Database Expertise",
            "",
            "### Core Concepts",
            "- Relational database management system",
            "- ACID compliance (Atomicity, Consistency, Isolation, Durability)",
            "- Client/server architecture",
            "- Storage engines: InnoDB (default), MyISAM, Memory, Archive",
            "- SQL standard compliance with extensions",
            "- Multi-version concurrency control (MVCC) in InnoDB",
            "- Foreign key constraints (InnoDB only)",
            "- Transaction support with SAVEPOINT",
            "",
            "### Data Types",
            "- Numeric: INT, BIGINT, DECIMAL, FLOAT, DOUBLE, TINYINT, SMALLINT",
            "- String: VARCHAR, CHAR, TEXT, MEDIUMTEXT, LONGTEXT, BLOB",
            "- Date/Time: DATE, TIME, DATETIME, TIMESTAMP, YEAR",
            "- JSON: native JSON type with validation and functions",
            "- Spatial: GEOMETRY, POINT, LINESTRING, POLYGON",
            "- Boolean: BOOL/BOOLEAN (alias for TINYINT(1))",
            "- ENUM and SET types",
            "",
            "### Schema Design",
            "- Normalization (1NF, 2NF, 3NF, BCNF)",
            "- Denormalization for read performance",
            "- Primary key selection (auto-increment vs UUID vs composite)",
            "- Foreign key relationships (1:1, 1:N, N:M)",
            "- Junction tables for many-to-many",
            "- Soft delete patterns (deleted_at column)",
            "- Temporal tables for history tracking",
            "- Partitioning (RANGE, LIST, HASH, KEY)",
            "",
            "### Indexing Strategies",
            "- B-Tree indexes (default)",
            "- Primary key (clustered index in InnoDB)",
            "- Secondary indexes (non-clustered)",
            "- Composite indexes and column order",
            "- Covering indexes (index-only scans)",
            "- Unique indexes for constraints",
            "- Full-text indexes (FULLTEXT)",
            "- Prefix indexes for long strings",
            "- Functional indexes (generated columns + index)",
            "- Index condition pushdown (ICP)",
            "- Avoid over-indexing (write penalty)",
            "",
            "### Query Optimization",
            "- EXPLAIN and EXPLAIN ANALYZE",
            "- Query execution plans",
            "- Index usage verification",
            "- JOIN optimization (nested loop, hash join in 8.x)",
            "- Subquery optimization",
            "- Derived table optimization",
            "- ORDER BY optimization",
            "- GROUP BY optimization",
            "- LIMIT optimization",
            "- Query cache (removed in 8.0)",
            "- Optimizer hints",
            "- Performance Schema for monitoring",
            "- Slow query log analysis",
            "",
            "### Transactions and Locking",
            "- BEGIN, COMMIT, ROLLBACK, SAVEPOINT",
            "- Isolation levels: READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE",
            "- InnoDB row-level locking",
            "- Shared (S) and exclusive (X) locks",
            "- Intention locks (table-level)",
            "- Gap locks and next-key locks",
            "- Deadlock detection and resolution",
            "- SELECT ... FOR UPDATE / FOR SHARE",
            "- NOWAIT and SKIP LOCKED",
            "",
            "### Replication",
            "- Asynchronous replication (default)",
            "- Semi-synchronous replication",
            "- Group replication (MySQL InnoDB Cluster)",
            "- Source/replica topology (formerly master/slave)",
            "- Binary log (binlog) formats: ROW, STATEMENT, MIXED",
            "- GTID-based replication",
            "- Replication filters",
            "- Delayed replicas for disaster recovery",
            "- Multi-source replication",
            "",
            "### Backup and Recovery",
            "- mysqldump (logical backup)",
            "- mysqlpump (parallel logical backup)",
            "- Percona XtraBackup (hot physical backup)",
            "- MySQL Enterprise Backup",
            "- Binary log point-in-time recovery",
            "- mysqlbinlog for replay",
            "- Clone plugin (MySQL 8.0+)",
            "- mysqldump --single-transaction for consistent snapshots",
            "",
            "### User Management and Security",
            "- CREATE USER, GRANT, REVOKE",
            "- Role-based access control (MySQL 8.0+)",
            "- Password policies and validation",
            "- SSL/TLS connections",
            "- Audit plugin",
            "- Data masking and de-identification",
            "- Encryption at rest (keyring)",
            "",
            "### JSON Support",
            "- JSON data type with automatic validation",
            "- JSON functions: JSON_EXTRACT, JSON_CONTAINS, JSON_ARRAY, JSON_OBJECT",
            "- JSON_TABLE for relational access",
            "- -> and ->> operators",
            "- JSON_SET, JSON_INSERT, JSON_REPLACE, JSON_REMOVE",
            "- Virtual generated columns on JSON paths",
            "",
            "### Window Functions (8.0+)",
            "- ROW_NUMBER(), RANK(), DENSE_RANK()",
            "- LEAD(), LAG()",
            "- FIRST_VALUE(), LAST_VALUE()",
            "- SUM(), AVG(), COUNT() OVER()",
            "- PARTITION BY and ORDER BY in window frames",
            "",
            "### Common Operations",
            "Connect:",
            "```bash",
            "mysql -u root -p",
            "mysql -h db.example.com -P 3306 -u appuser -p mydb",
            "```",
            "",
            "Create database and table:",
            "```sql",
            "CREATE DATABASE myapp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "",
            "CREATE TABLE users (",
            "  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,",
            "  email VARCHAR(255) NOT NULL UNIQUE,",
            "  name VARCHAR(100) NOT NULL,",
            "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
            "  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,",
            "  INDEX idx_email (email)",
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
            "```",
            "",
            "Insert and query:",
            "```sql",
            "INSERT INTO users (email, name) VALUES ('user@example.com', 'John');",
            "",
            "SELECT u.name, COUNT(o.id) as order_count",
            "FROM users u",
            "LEFT JOIN orders o ON u.id = o.user_id",
            "WHERE u.created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)",
            "GROUP BY u.id",
            "ORDER BY order_count DESC",
            "LIMIT 10;",
            "```",
            "",
            "Explain query:",
            "```sql",
            "EXPLAIN ANALYZE SELECT * FROM users WHERE email = 'test@example.com';",
            "```",
            "",
            "Backup:",
            "```bash",
            "mysqldump -u root -p --single-transaction --routines mydb > backup.sql",
            "mysql -u root -p mydb < backup.sql",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["mysql", "relational_db", "query_optimization", "indexing", "replication", "backup", "json", "window_functions"]

module = CogDbMysql()
