from cog.cog_module import CogModule

class CogInfraKubernetes(CogModule):
    name = "cog-infra-kubernetes"
    version = "1.0.0"
    description = "Kubernetes orchestration expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Kubernetes Orchestration Expertise",
            "",
            "### Core Concepts",
            "- Control plane (API server, etcd, scheduler, controller manager)",
            "- Nodes (kubelet, kube-proxy, container runtime)",
            "- Pods (smallest deployable units, one or more containers)",
            "- Namespaces (logical cluster partitioning)",
            "- Labels and selectors (object grouping and filtering)",
            "- Annotations (non-identifying metadata)",
            "- Resource requests and limits (CPU, memory)",
            "- Taints and tolerations (node scheduling constraints)",
            "- Node affinity and anti-affinity",
            "- Pod disruption budgets (PDB)",
            "",
            "### Workloads",
            "- Deployments (declarative updates for Pods, ReplicaSets)",
            "- ReplicaSets (maintain stable replica count)",
            "- StatefulSets (ordered, stable network identity, persistent storage)",
            "- DaemonSets (run a Pod on every node)",
            "- Jobs (run-to-completion tasks)",
            "- CronJobs (scheduled Jobs)",
            "- Horizontal Pod Autoscaler (HPA)",
            "- Vertical Pod Autoscaler (VPA)",
            "- Pod templates and restart policies",
            "",
            "### Services and Networking",
            "- ClusterIP (internal cluster service, default)",
            "- NodePort (expose on static port per node)",
            "- LoadBalancer (provision external load balancer)",
            "- ExternalName (DNS CNAME alias)",
            "- Headless services (direct Pod DNS)",
            "- Endpoints and EndpointSlices",
            "- Ingress (HTTP/HTTPS routing to services)",
            "- IngressClass (Ingress controller selection)",
            "- NetworkPolicies (Pod-level firewall rules)",
            "- Service Mesh (Istio, Linkerd) concepts",
            "- DNS resolution (CoreDNS, service.namespace.svc.cluster.local)",
            "",
            "### Configuration and Storage",
            "- ConfigMaps (non-sensitive configuration data)",
            "- Secrets (sensitive data, base64-encoded)",
            "- Volume types (emptyDir, hostPath, nfs, persistentVolumeClaim)",
            "- PersistentVolumes (PV) cluster storage resources",
            "- PersistentVolumeClaims (PVC) user storage requests",
            "- StorageClasses (dynamic provisioning)",
            "- Volume snapshot and restore",
            "- Environment variable injection from ConfigMaps and Secrets",
            "- Mounted volumes for config files",
            "",
            "### Helm Package Manager",
            "- Charts (bundled Kubernetes manifests)",
            "- Values files (chart configuration)",
            "- Templates with Go templating",
            "- Release management (install, upgrade, rollback)",
            "- Chart dependencies (requirements.yaml / Chart.yaml)",
            "- Chart repositories and OCI registries",
            "- Helm hooks (pre-install, post-upgrade, etc.)",
            "- helmfile for declarative Helm releases",
            "",
            "### RBAC (Role-Based Access Control)",
            "- Roles (namespace-scoped permissions)",
            "- ClusterRoles (cluster-wide permissions)",
            "- RoleBindings (bind Role to subjects)",
            "- ClusterRoleBindings (bind ClusterRole to subjects)",
            "- Subjects (Users, Groups, ServiceAccounts)",
            "- API groups and resources verbs (get, list, create, delete, etc.)",
            "- ServiceAccount tokens and Pod service accounts",
            "",
            "### Scaling and Reliability",
            "- Horizontal Pod Autoscaler with custom metrics",
            "- PodDisruptionBudget for voluntary evictions",
            "- Topology spread constraints (zone/node distribution)",
            "- Liveness probes (restart unhealthy containers)",
            "- Readiness probes (control traffic routing)",
            "- Startup probes (slow-starting containers)",
            "- Pod priority and preemption",
            "- Resource quotas per namespace",
            "- LimitRanges for default resource allocation",
            "",
            "### Common Operations",
            "Cluster info:",
            "```bash",
            "kubectl cluster-info",
            "kubectl get nodes -o wide",
            "kubectl top nodes",
            "kubectl get namespaces",
            "```",
            "",
            "Workload management:",
            "```bash",
            "kubectl get pods -A",
            "kubectl get deployments -n myns",
            "kubectl describe pod <pod-name> -n myns",
            "kubectl logs -f <pod-name> -c <container> -n myns",
            "kubectl exec -it <pod-name> -- bash -n myns",
            "kubectl scale deployment/app --replicas=5 -n myns",
            "kubectl rollout status deployment/app -n myns",
            "kubectl rollout undo deployment/app -n myns",
            "kubectl set image deployment/app container=image:tag -n myns",
            "```",
            "",
            "Configuration:",
            "```bash",
            "kubectl create configmap myconfig --from-literal=key=value -n myns",
            "kubectl create secret generic mysecret --from-literal=password=s3cret -n myns",
            "kubectl get configmap myconfig -o yaml -n myns",
            "```",
            "",
            "Helm operations:",
            "```bash",
            "helm repo add bitnami https://charts.bitnami.com/bitnami",
            "helm repo update",
            "helm install my-release bitnami/nginx -n myns -f values.yaml",
            "helm upgrade my-release bitnami/nginx -n myns -f values.yaml",
            "helm rollback my-release 1 -n myns",
            "helm list -n myns",
            "helm uninstall my-release -n myns",
            "```",
            "",
            "Troubleshooting:",
            "```bash",
            "kubectl get events --sort-by=.metadata.creationTimestamp -n myns",
            "kubectl describe pod <pod-name> -n myns",
            "kubectl logs <pod-name> --previous -n myns",
            "kubectl get pods -o wide -n myns",
            "kubectl api-resources",
            "kubectl explain pod.spec.containers",
            "```",
            "",
            "### Example Deployment",
            "```yaml",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            "  name: app-deployment",
            "  namespace: production",
            "  labels:",
            "    app: myapp",
            "spec:",
            "  replicas: 3",
            "  selector:",
            "    matchLabels:",
            "      app: myapp",
            "  strategy:",
            "    type: RollingUpdate",
            "    rollingUpdate:",
            "      maxSurge: 1",
            "      maxUnavailable: 0",
            "  template:",
            "    metadata:",
            "      labels:",
            "        app: myapp",
            "    spec:",
            "      serviceAccountName: myapp-sa",
            "      containers:",
            "        - name: myapp",
            "          image: registry.example.com/myapp:1.0.0",
            "          ports:",
            "            - containerPort: 8080",
            "          env:",
            "            - name: DATABASE_URL",
            "              valueFrom:",
            "                secretKeyRef:",
            "                  name: db-secret",
            "                  key: url",
            "            - name: LOG_LEVEL",
            "              valueFrom:",
            "                configMapKeyRef:",
            "                  name: app-config",
            "                  key: log_level",
            "          resources:",
            "            requests:",
            "              cpu: 100m",
            "              memory: 128Mi",
            "            limits:",
            "              cpu: 500m",
            "              memory: 512Mi",
            "          livenessProbe:",
            "            httpGet:",
            "              path: /healthz",
            "              port: 8080",
            "            initialDelaySeconds: 15",
            "            periodSeconds: 10",
            "          readinessProbe:",
            "            httpGet:",
            "              path: /ready",
            "              port: 8080",
            "            initialDelaySeconds: 5",
            "            periodSeconds: 5",
            "```",
            "",
            "### Example Ingress",
            "```yaml",
            "apiVersion: networking.k8s.io/v1",
            "kind: Ingress",
            "metadata:",
            "  name: app-ingress",
            "  annotations:",
            "    nginx.ingress.kubernetes.io/rewrite-target: /",
            "    cert-manager.io/cluster-issuer: letsencrypt-prod",
            "spec:",
            "  ingressClassName: nginx",
            "  tls:",
            "    - hosts:",
            "        - myapp.example.com",
            "      secretName: myapp-tls",
            "  rules:",
            "    - host: myapp.example.com",
            "      http:",
            "        paths:",
            "          - path: /",
            "            pathType: Prefix",
            "            backend:",
            "              service:",
            "                name: app-service",
            "                port:",
            "                  number: 80",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["kubernetes", "k8s", "helm", "deployments", "services", "ingress", "rbac", "configmaps", "secrets", "statefulsets", "hpa"]

module = CogInfraKubernetes()
