from cog.cog_module import CogModule


class CogWebHtml(CogModule):
    name = "cog-web-html"
    version = "1.0.0"
    description = "HTML5 development module covering semantic elements, forms, accessibility/ARIA, SEO, responsive design, Web Components, canvas, Web APIs, performance optimization, and structured data"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## HTML5 Semantic Elements",
            "",
            "Use semantic elements to convey document structure. Never use `<div>` when a semantic alternative exists.",
            "",
            "```html",
            "<header>",
            "  <nav aria-label=\"Primary\">",
            "    <ul>",
            "      <li><a href=\"/\">Home</a></li>",
            "      <li><a href=\"/about\">About</a></li>",
            "    </ul>",
            "  </nav>",
            "</header>",
            "<main>",
            "  <article>",
            "    <h1>Article Title</h1>",
            "    <section>",
            "      <h2>Section Heading</h2>",
            "      <p>Content paragraph.</p>",
            "    </section>",
            "    <aside>",
            "      <p>Related content.</p>",
            "    </aside>",
            "  </article>",
            "</main>",
            "<footer>",
            "  <p>&copy; 2025 Company</p>",
            "</footer>",
            "```",
            "",
            "### Semantic element reference",
            "- `<header>` — introductory content or navigational aids for the nearest sectioning ancestor",
            "- `<nav>` — navigation links; add `aria-label` when multiple `<nav>` elements exist",
            "- `<main>` — the dominant content of the `<body>`; only one per document",
            "- `<article>` — self-contained composition that could be independently distributed",
            "- `<section>` — thematic grouping with a heading",
            "- `<aside>` — tangentially related content (sidebars, pull quotes)",
            "- `<footer>` — footer for the nearest sectioning ancestor",
            "- `<figure>` / `<figcaption>` — illustrative content with optional caption",
            "- `<time datetime=\"2025-01-15\">` — machine-readable date/time",
            "- `<mark>` — highlighted/relevant text",
            "- `<details>` / `<summary>` — disclosure widget",
            "",
            "## Forms and Validation",
            "",
            "Use the Constraint Validation API with built-in attributes. Provide accessible error messages via `aria-describedby`.",
            "",
            "```html",
            "<form novalidate>",
            "  <label for=\"email\">Email</label>",
            "  <input id=\"email\" type=\"email\" required autocomplete=\"email\"",
            "         pattern=\"[^@]+@[^@]+\\.[^@]+\"",
            "         aria-describedby=\"email-error\" />",
            "  <span id=\"email-error\" role=\"alert\"></span>",
            "",
            "  <label for=\"password\">Password</label>",
            "  <input id=\"password\" type=\"password\" required minlength=\"8\"",
            "         aria-describedby=\"password-rules\" />",
            "  <small id=\"password-rules\">Minimum 8 characters.</small>",
            "",
            "  <fieldset>",
            "    <legend>Notification preference</legend>",
            "    <label><input type=\"radio\" name=\"notify\" value=\"email\" checked /> Email</label>",
            "    <label><input type=\"radio\" name=\"notify\" value=\"sms\" /> SMS</label>",
            "  </fieldset>",
            "",
            "  <button type=\"submit\">Sign Up</button>",
            "</form>",
            "```",
            "",
            "### Validation attributes",
            "- `required` — field must have a value",
            "- `type=\"email|url|tel|number|date\"` — built-in format validation",
            "- `pattern=\"regex\"` — custom regex validation",
            "- `minlength` / `maxlength` — text length bounds",
            "- `min` / `max` / `step` — numeric/date bounds",
            "- Use `novalidate` on `<form>` to handle validation in JS with `checkValidity()` / `reportValidity()`",
            "- Set custom errors: `input.setCustomValidity('Message')` and clear with `input.setCustomValidity('')`",
            "",
            "## Accessibility (ARIA)",
            "",
            "ARIA supplements native HTML semantics. Prefer native elements over ARIA roles.",
            "First rule of ARIA: don't use ARIA if a native HTML element provides the semantics.",
            "",
            "```html",
            "<!-- Custom toggle -->",
            "<button role=\"switch\" aria-checked=\"false\" aria-label=\"Dark mode\">",
            "  <span class=\"toggle-track\"></span>",
            "</button>",
            "",
            "<!-- Live region for dynamic content -->",
            "<div aria-live=\"polite\" aria-atomic=\"true\" id=\"status\"></div>",
            "",
            "<!-- Tablist pattern -->",
            "<div role=\"tablist\" aria-label=\"Settings\">",
            "  <button role=\"tab\" id=\"tab-profile\" aria-selected=\"true\" aria-controls=\"panel-profile\">Profile</button>",
            "  <button role=\"tab\" id=\"tab-security\" aria-selected=\"false\" aria-controls=\"panel-security\" tabindex=\"-1\">Security</button>",
            "</div>",
            "<div role=\"tabpanel\" id=\"panel-profile\" aria-labelledby=\"tab-profile\">...</div>",
            "<div role=\"tabpanel\" id=\"panel-security\" aria-labelledby=\"tab-security\" hidden>...</div>",
            "```",
            "",
            "### Key ARIA patterns",
            "- Landmarks: `role=\"banner|navigation|main|complementary|contentinfo|search\"`",
            "- Live regions: `aria-live=\"polite|assertive\"` with `aria-atomic` and `aria-relevant`",
            "- Focus management: `element.focus()` after DOM changes; use `tabindex=\"-1\"` for programmatic focus",
            "- Skip links: `<a href=\"#main\" class=\"skip-link\">Skip to content</a>` as first focusable element",
            "- `aria-expanded` / `aria-controls` for disclosure widgets",
            "- `aria-hidden=\"true\"` to hide decorative elements from assistive technology",
            "- `aria-describedby` to associate help text or error messages",
            "",
            "## SEO Meta Tags",
            "",
            "```html",
            "<head>",
            "  <meta charset=\"utf-8\" />",
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
            "  <title>Page Title — Site Name</title>",
            "  <meta name=\"description\" content=\"Concise page summary under 160 chars.\" />",
            "  <link rel=\"canonical\" href=\"https://example.com/page\" />",
            "",
            "  <!-- Open Graph -->",
            "  <meta property=\"og:type\" content=\"website\" />",
            "  <meta property=\"og:title\" content=\"Page Title\" />",
            "  <meta property=\"og:description\" content=\"Page description\" />",
            "  <meta property=\"og:image\" content=\"https://example.com/og.jpg\" />",
            "  <meta property=\"og:url\" content=\"https://example.com/page\" />",
            "",
            "  <!-- Twitter Card -->",
            "  <meta name=\"twitter:card\" content=\"summary_large_image\" />",
            "",
            "  <!-- Structured Data -->",
            "  <script type=\"application/ld+json\">",
            "  {",
            "    \"@context\": \"https://schema.org\",",
            "    \"@type\": \"Article\",",
            "    \"headline\": \"Article Title\",",
            "    \"datePublished\": \"2025-01-15\",",
            "    \"author\": { \"@type\": \"Person\", \"name\": \"Author\" }",
            "  }",
            "  </script>",
            "</head>",
            "```",
            "",
            "## Responsive Images and Media",
            "",
            "```html",
            "<picture>",
            "  <source srcset=\"hero.webp\" type=\"image/webp\" />",
            "  <source srcset=\"hero.avif\" type=\"image/avif\" />",
            "  <img src=\"hero.jpg\" alt=\"Descriptive alt text\" loading=\"lazy\"",
            "       width=\"1200\" height=\"630\" decoding=\"async\" />",
            "</picture>",
            "",
            "<img srcset=\"small.jpg 480w, medium.jpg 800w, large.jpg 1200w\"",
            "     sizes=\"(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw\"",
            "     src=\"medium.jpg\" alt=\"Responsive image\" />",
            "```",
            "",
            "### Image best practices",
            "- Always include `width` and `height` to prevent layout shift (CLS)",
            "- Use `loading=\"lazy\"` for below-fold images; keep hero images eager",
            "- `decoding=\"async\"` for off-screen images",
            "- Provide `alt` text that describes the image's purpose, not its appearance",
            "- Use `<picture>` for format negotiation (WebP/AVIF fallback to JPEG)",
            "- Use `srcset` + `sizes` for resolution/density switching",
            "",
            "## Web Components",
            "",
            "```html",
            "<template id=\"my-card\">",
            "  <style>",
            "    :host { display: block; border: 1px solid #ddd; border-radius: 8px; padding: 1rem; }",
            "    ::slotted(h2) { margin: 0 0 0.5rem; }",
            "  </style>",
            "  <slot name=\"header\"></slot>",
            "  <slot></slot>",
            "</template>",
            "```",
            "",
            "```javascript",
            "class MyCard extends HTMLElement {",
            "  constructor() {",
            "    super();",
            "    this.attachShadow({ mode: 'open' }).appendChild(",
            "      document.getElementById('my-card').content.cloneNode(true)",
            "    );",
            "  }",
            "}",
            "customElements.define('my-card', MyCard);",
            "```",
            "",
            "### Web Components patterns",
            "- Use `ShadowRoot` for style encapsulation; `:host` for the host element, `::slotted()` for projected content",
            "- Use `<slot>` for content projection; `slotchange` event for dynamic slot content",
            "- Lifecycle callbacks: `connectedCallback`, `disconnectedCallback`, `attributeChangedCallback`, `adoptedCallback`",
            "- Use `observedAttributes` static getter to react to attribute changes",
            "- Prefer `formAssociated` static getter + `ElementInternals` for form-integrated custom elements",
            "",
            "## Canvas and Web APIs",
            "",
            "```html",
            "<canvas id=\"chart\" width=\"600\" height=\"400\">",
            "  <p>Fallback content for non-canvas browsers.</p>",
            "</canvas>",
            "```",
            "",
            "```javascript",
            "const ctx = document.getElementById('chart').getContext('2d');",
            "ctx.fillStyle = '#4f46e5';",
            "ctx.fillRect(10, 10, 150, 100);",
            "",
            "ctx.beginPath();",
            "ctx.arc(300, 200, 50, 0, Math.PI * 2);",
            "ctx.fill();",
            "```",
            "",
            "### Key Web APIs",
            "- **Intersection Observer**: lazy-load images and trigger scroll-based animations without scroll listeners",
            "- **Resize Observer**: respond to element size changes for responsive components",
            "- **Mutation Observer**: watch DOM changes for dynamic content",
            "- **Clipboard API**: `navigator.clipboard.writeText()` / `navigator.clipboard.readText()`",
            "- **Web Animations API**: `element.animate(keyframes, options)` for performant animations",
            "- **Dialog element**: `<dialog>` with `showModal()` for modal interactions",
            "",
            "## HTML Performance",
            "",
            "- Inline critical CSS; defer non-critical stylesheets with `media=\"print\" onload=\"this.media='all'\"`",
            "- Use `<script type=\"module\">` for automatic defer; use `async` for independent scripts",
            "- Preload critical resources: `<link rel=\"preload\" href=\"font.woff2\" as=\"font\" crossorigin />`",
            "- Preconnect to origins: `<link rel=\"preconnect\" href=\"https://cdn.example.com\" />`",
            "- Minimize DOM depth; avoid deep nesting (>15 levels)",
            "- Use `fetchpriority=\"high\"` on LCP images and `fetchpriority=\"low\"` on below-fold resources",
            "- Reduce CLS: always set `width`/`height` on images and videos; reserve space for dynamic content",
            "",
            "## Structured Data (Schema.org)",
            "",
            "```html",
            "<script type=\"application/ld+json\">",
            "{",
            "  \"@context\": \"https://schema.org\",",
            "  \"@type\": \"FAQPage\",",
            "  \"mainEntity\": [",
            "    {",
            "      \"@type\": \"Question\",",
            "      \"name\": \"What is structured data?\",",
            "      \"acceptedAnswer\": {",
            "        \"@type\": \"Answer\",",
            "        \"text\": \"Structured data is a standardized format for providing information about a page.\"",
            "      }",
            "    }",
            "  ]",
            "}",
            "</script>",
            "```",
            "",
            "### Common Schema.org types",
            "- `Article`, `BlogPosting`, `NewsArticle` — content pages",
            "- `Product` with `offers`, `aggregateRating`, `review`",
            "- `Organization` with `sameAs` for social profiles",
            "- `BreadcrumbList` for navigation trails",
            "- `HowTo` for step-by-step instructions",
            "- `Event` with `startDate`, `location`, `offers`",
            "- Validate with Google Rich Results Test before deploying",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "semantic-html5",
            "forms-validation",
            "accessibility-aria",
            "seo-meta-tags",
            "responsive-design",
            "web-components",
            "canvas-api",
            "web-apis",
            "html-performance",
            "structured-data",
        ]


module = CogWebHtml()
