from cog.cog_module import CogModule


class CogPackageNpm(CogModule):
    name = "cog-package-npm"
    version = "1.0.0"
    description = "npm package manager module covering package.json, scripts, dependency management, semantic versioning, lock files, publishing, scoped packages, .npmrc, workspaces, npm audit, and npx"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## package.json Configuration",
            "",
            "```json",
            "{",
            "  \"name\": \"@scope/package-name\",",
            "  \"version\": \"1.0.0\",",
            "  \"description\": \"Package description\",",
            "  \"main\": \"dist/index.js\",",
            "  \"module\": \"dist/index.mjs\",",
            "  \"types\": \"dist/index.d.ts\",",
            "  \"exports\": {",
            "    \".\": {",
            "      \"import\": \"./dist/index.mjs\",",
            "      \"require\": \"./dist/index.js\",",
            "      \"types\": \"./dist/index.d.ts\"",
            "    },",
            "    \"./utils\": {",
            "      \"import\": \"./dist/utils.mjs\",",
            "      \"require\": \"./dist/utils.js\"",
            "    }",
            "  },",
            "  \"files\": [\"dist\"],",
            "  \"scripts\": {",
            "    \"build\": \"tsup src/index.ts --format esm,cjs --dts\",",
            "    \"test\": \"vitest run\",",
            "    \"lint\": \"eslint src --ext .ts\",",
            "    \"prepublishOnly\": \"npm run build\"",
            "  },",
            "  \"keywords\": [\"keyword1\", \"keyword2\"],",
            "  \"license\": \"MIT\",",
            "  \"repository\": { \"type\": \"git\", \"url\": \"https://github.com/user/repo\" },",
            "  \"engines\": { \"node\": \">=18.0.0\" }",
            "}",
            "```",
            "",
            "### package.json fields",
            "- `name` — must be lowercase, hyphen-separated; scoped with `@scope/` prefix",
            "- `version` — semver string; `npm version patch|minor|major` bumps and tags",
            "- `exports` — modern entry point resolution; replaces `main`/`module` with conditional exports",
            "- `files` — whitelist of files included in the published tarball; `.npmignore` is the blacklist alternative",
            "- `engines` — declare required Node.js and npm versions; enforce with `engine-strict` in `.npmrc`",
            "- `type: \"module\"` — treat `.js` files as ES modules; use `.cjs` for CommonJS",
            "",
            "## npm Scripts",
            "",
            "```json",
            "{",
            "  \"scripts\": {",
            "    \"dev\": \"tsx watch src/index.ts\",",
            "    \"build\": \"npm run build:clean && npm run build:js\",",
            "    \"build:clean\": \"rm -rf dist\",",
            "    \"build:js\": \"tsup src/index.ts --format esm,cjs --dts\",",
            "    \"test\": \"vitest run\",",
            "    \"test:watch\": \"vitest\",",
            "    \"test:coverage\": \"vitest run --coverage\",",
            "    \"lint\": \"eslint src --ext .ts && prettier --check .\",",
            "    \"lint:fix\": \"eslint src --ext .ts --fix && prettier --write .\",",
            "    \"release\": \"npm run test && npm run build && npm version patch && npm publish\",",
            "    \"preinstall\": \"npx only-allow pnpm\"",
            "  }",
            "}",
            "```",
            "",
            "### Script patterns",
            "- Pre/post hooks: `prebuild` runs before `build`, `postinstall` runs after `npm install`",
            "- `npm run env` lists all environment variables available in scripts",
            "- `npm run script -- --flag` passes flags after `--` to the underlying command",
            "- `&&` chains commands sequentially (fail-fast); `&` runs in parallel",
            "- Cross-platform: use `cross-env` for env vars, `rimraf` instead of `rm -rf`, `cpy` instead of `cp`",
            "- `npm pkg set scripts.build=\"tsup src/index.ts\"` — programmatically add scripts",
            "",
            "## Dependencies vs devDependencies",
            "",
            "```json",
            "{",
            "  \"dependencies\": {",
            "    \"express\": \"^4.18.2\",",
            "    \"zod\": \"^3.22.0\"",
            "  },",
            "  \"devDependencies\": {",
            "    \"typescript\": \"^5.3.0\",",
            "    \"vitest\": \"^1.2.0\",",
            "    \"eslint\": \"^8.56.0\",",
            "    \"@types/node\": \"^20.11.0\"",
            "  },",
            "  \"peerDependencies\": {",
            "    \"react\": \">=18.0.0\"",
            "  },",
            "  \"peerDependenciesMeta\": {",
            "    \"react\": { \"optional\": true }",
            "  },",
            "  \"optionalDependencies\": {",
            "    \"fsevents\": \"^2.3.0\"",
            "  }",
            "}",
            "```",
            "",
            "### Dependency categories",
            "- `dependencies` — required at runtime; installed when consumers `npm install` your package",
            "- `devDependencies` — build/test tooling only; skipped with `npm install --production`",
            "- `peerDependencies` — expected to be provided by the consuming package; not auto-installed in npm v7+",
            "- `optionalDependencies` — installed if available but the package works without them; handle missing imports gracefully",
            "- `overrides` — force specific versions for transitive dependencies: `\"overrides\": { \"lodash\": \"^4.17.21\" }`",
            "",
            "## Semantic Versioning",
            "",
            "```\nMAJOR.MINOR.PATCH  (e.g., 2.14.3)",
            "",
            "MAJOR — incompatible API changes",
            "MINOR — backward-compatible new features",
            "PATCH — backward-compatible bug fixes",
            "",
            "Range operators:",
            "^1.2.3  → >=1.2.3 <2.0.0   (compatible with major)",
            "~1.2.3  → >=1.2.3 <1.3.0   (compatible with minor)",
            "1.2.x   → >=1.2.0 <1.3.0",
            "*       → any version",
            ">=1.2.3 <2.0.0-0  → explicit range",
            "```",
            "",
            "### Semver best practices",
            "- `npm version patch` — 1.0.0 → 1.0.1 (creates git commit + tag)",
            "- `npm version minor` — 1.0.0 → 1.1.0",
            "- `npm version major` — 1.0.0 → 2.0.0",
            "- `npm version prerelease` — 1.0.0 → 1.0.1-0",
            "- Pre-release: `2.0.0-beta.1` — `npm publish --tag beta`",
            "- Lock exact versions for applications (`\"1.2.3\"`); use ranges for libraries (`\"^1.2.3\"`)",
            "",
            "## Lock Files (package-lock.json)",
            "",
            "- `package-lock.json` pins exact versions of the entire dependency tree",
            "- Always commit `package-lock.json` to version control for reproducible builds",
            "- `npm ci` — clean install from lock file; deletes `node_modules` first, faster than `npm install`",
            "- `npm ci` fails if `package-lock.json` doesn't match `package.json`",
            "- Use `npm ci` in CI/CD pipelines; use `npm install` in development",
            "- `npm install --package-lock-only` — updates lock file without installing",
            "",
            "## Publishing",
            "",
            "```bash",
            "# Login to npm registry",
            "npm login",
            "",
            "# Verify package contents before publishing",
            "npm pack --dry-run",
            "",
            "# Publish a scoped package publicly",
            "npm publish --access public",
            "",
            "# Publish a beta release",
            "npm publish --tag beta",
            "",
            "# Deprecate a version",
            "npm deprecate @scope/package@1.0.0 \"Use 1.0.1 instead\"",
            "",
            "# Unpublish within 72 hours (scoped packages only)",
            "npm unpublish @scope/package@1.0.0",
            "```",
            "",
            "### Publishing checklist",
            "- Verify `files` field includes only what should be published",
            "- Run `npm pack --dry-run` to inspect tarball contents",
            "- Ensure `prepublishOnly` script builds and tests",
            "- Use `--access public` for scoped packages (default is restricted)",
            "- Use `--tag` for pre-release channels: `npm publish --tag next`",
            "- `npm dist-tag ls @scope/package` — list all dist-tags",
            "- `npm dist-tag add @scope/package@1.1.0 latest` — promote a version",
            "",
            "## .npmrc Configuration",
            "",
            "```ini",
            "# Project-level .npmrc",
            "save-exact=true",
            "engine-strict=true",
            "audit=true",
            "",
            "# Use private registry for scoped packages",
            "@mycompany:registry=https://registry.mycompany.com/",
            "",
            "# Global .npmrc (~/.npmrc)",
            "//registry.npmjs.org/:_authToken=${NPM_TOKEN}",
            "init-author-name=Your Name",
            "init-license=MIT",
            "",
            "# Strict peer dependencies",
            "strict-peer-dependencies=true",
            "```",
            "",
            "### .npmrc locations (precedence low → high)",
            "1. Built-in defaults (`/usr/local/etc/npmrc`)",
            "2. Global (`~/.npmrc`)",
            "3. User (`~/.npmrc`)",
            "4. Project (`.npmrc` in project root)",
            "",
            "## npm Workspaces",
            "",
            "```json",
            "{",
            "  \"workspaces\": [\"packages/*\"]",
            "}",
            "```",
            "",
            "```bash",
            "# Install dependency in a specific workspace",
            "npm install lodash -w packages/utils",
            "",
            "# Run script in all workspaces",
            "npm run build -ws",
            "",
            "# Run script in a specific workspace",
            "npm run test -w packages/core",
            "",
            "# List workspaces",
            "npm ls -a --depth=0",
            "```",
            "",
            "### Workspace patterns",
            "- Root `package.json` is the workspace host; each child `packages/*` is a workspace",
            "- Hoisted dependencies go to root `node_modules`; workspace-specific deps stay local",
            "- `npm install -w <pkg>` adds a dependency to that workspace's `package.json`",
            "- Symlinks workspace packages into root `node_modules` for local cross-references",
            "- Use `--workspaces` (`-ws`) for all workspaces; `--workspace` (`-w`) for one",
            "",
            "## npm audit and Security",
            "",
            "```bash",
            "# Check for vulnerabilities",
            "npm audit",
            "",
            "# Auto-fix vulnerabilities",
            "npm audit fix",
            "",
            "# Force fix (may break compatibility)",
            "npm audit fix --force",
            "",
            "# View detailed advisory",
            "npm audit --json",
            "",
            "# Check for outdated packages",
            "npm outdated",
            "",
            "# Update to latest within semver range",
            "npm update",
            "```",
            "",
            "### Security practices",
            "- Run `npm audit` in CI pipelines; fail on high/critical severity",
            "- Use `npm audit --audit-level=high` to fail only on high+ vulnerabilities",
            "- `overrides` in `package.json` to patch transitive vulnerabilities: `\"overrides\": { \"lodash\": \"4.17.21\" }`",
            "- Review `npm ls <package>` to understand dependency trees before updating",
            "- Use `npx npm-check-updates -u` to update all versions in `package.json`",
            "",
            "## npx",
            "",
            "```bash",
            "# Run a one-off command without installing globally",
            "npx create-react-app my-app",
            "npx tsx script.ts",
            "npx prisma studio",
            "",
            "# Use a specific version",
            "npx typescript@5.3.0 --version",
            "",
            "# Run from a GitHub repo",
            "npx github:user/repo",
            "",
            "# Interactive package picker",
            "npx npm-check --update",
            "```",
            "",
            "### npx behavior",
            "- Checks local `node_modules/.bin` first, then downloads to cache if not found",
            "- `--yes` / `-y` skips confirmation prompt for package installation",
            "- `--package` allows multiple packages: `npx -p pkg1 -p pkg2 command`",
            "- Use `--no-install` to only run from local `node_modules`",
            "- `npm exec` is the equivalent command (npm v7+); `npx` is an alias",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "package-json",
            "npm-scripts",
            "dependency-management",
            "semantic-versioning",
            "lock-files",
            "npm-publishing",
            "scoped-packages",
            "npmrc-config",
            "npm-workspaces",
            "npm-audit",
            "npx",
        ]


module = CogPackageNpm()
