from cog.cog_module import CogModule

class CogInfraTerraform(CogModule):
    name = "cog-infra-terraform"
    version = "1.0.0"
    description = "Terraform infrastructure-as-code expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Terraform Infrastructure-as-Code Expertise",
            "",
            "### Core Concepts",
            "- HCL (HashiCorp Configuration Language)",
            "- Providers (AWS, Azure, GCP, Kubernetes, etc.)",
            "- Resources (infrastructure objects being managed)",
            "- Data sources (read-only references to existing infrastructure)",
            "- State (mapping of config to real-world resources)",
            "- Modules (reusable, self-contained Terraform packages)",
            "- Workspaces (named state environments within same config)",
            "- Backend (where state is stored: local, S3, GCS, etc.)",
            "- Variables (input parameters for parameterized configs)",
            "- Outputs (exported values from root module)",
            "- Locals (computed intermediate values)",
            "- Resource lifecycle (create, update, delete)",
            "",
            "### HCL Syntax and Patterns",
            "- Blocks: resource, data, module, variable, output, locals, terraform, provider",
            "- Attributes: key = value assignments",
            "- Expressions: conditionals, for expressions, splat expressions",
            "- Dynamic blocks (generate nested blocks programmatically)",
            "- Terraform functions: length, join, merge, lookup, coalesce, file, templatefile",
            "- String interpolation: ${var.name}",
            "- Conditional expressions: condition ? true_val : false_val",
            "- For expressions: [for s in var.list : upper(s)]",
            "- Type constraints: string, number, bool, list, map, set, object, tuple, any",
            "",
            "### State Management",
            "- State file stores resource mappings and metadata",
            "- State locking prevents concurrent operations (DynamoDB, GCS, etc.)",
            "- Remote state sharing via data sources (data terraform_remote_state)",
            "- State manipulation: terraform state mv, rm, import",
            "- State backends: local, S3+DynamoDB, GCS, Azure Blob, Consul",
            "- State isolation: workspaces vs directory separation",
            "- Sensitive values in state (sensitive = true)",
            "- State drift detection with terraform plan",
            "- Importing existing resources with terraform import",
            "",
            "### Modules",
            "- Root module (current working directory)",
            "- Child modules (called via module blocks)",
            "- Module sources: local path, Git repo, Terraform Registry, S3 bucket",
            "- Module version constraints",
            "- Module inputs and outputs",
            "- Module composition and dependency passing",
            "- Publishing modules to Terraform Registry",
            "- Module best practices: tags, descriptions, examples",
            "",
            "### Workspaces",
            "- Named environments sharing same config",
            "- terraform.workspace interpolation in configs",
            "- Workspace-specific variable files (*.tfvars)",
            "- terraform workspace new/select/list/delete",
            "- Alternative: directory-based separation for isolation",
            "",
            "### Remote Backends",
            "- S3 backend with DynamoDB locking",
            "- GCS backend with native locking",
            "- Azure Blob Storage backend",
            "- Terraform Cloud / Enterprise as backend",
            "- Consul backend for KV-based state",
            "- HTTP backend for custom state storage",
            "- Backend configuration: partial vs full configuration",
            "",
            "### Provisioners and Lifecycle",
            "- Provisioners: local-exec, remote-exec, file",
            "- Use provisioners as last resort (prefer cloud-init, user data)",
            "- Lifecycle meta-arguments: create_before_destroy, prevent_destroy, ignore_changes",
            "- depends_on for explicit dependencies",
            "- count and for_each for resource iteration",
            "- Targeted operations: -target=resource.address",
            "",
            "### Best Practices",
            "- Pin provider versions with version constraints",
            "- Use remote state with locking for team collaboration",
            "- Store .tfstate files in remote backends, never in Git",
            "- Use variables for environment-specific values",
            "- Use output values to expose important information",
            "- Break large configurations into modules",
            "- Use terraform fmt for consistent formatting",
            "- Use terraform validate to catch errors early",
            "- Use pre-commit hooks with terraform validate and tflint",
            "- Use sentinel or OPA policies for governance",
            "- Implement CI/CD for terraform plan/apply",
            "- Use workspaces or directory structure for environment isolation",
            "- Tag all resources consistently",
            "",
            "### Common Operations",
            "Initialize and validate:",
            "```bash",
            "terraform init",
            "terraform init -backend-config=backend.hcl",
            "terraform validate",
            "terraform fmt -recursive",
            "```",
            "",
            "Plan and apply:",
            "```bash",
            "terraform plan -out=tfplan",
            "terraform plan -var-file=prod.tfvars",
            "terraform apply tfplan",
            "terraform apply -auto-approve -var-file=prod.tfvars",
            "terraform apply -target=aws_instance.web",
            "```",
            "",
            "State management:",
            "```bash",
            "terraform state list",
            "terraform state show aws_instance.web",
            "terraform state mv aws_instance.old aws_instance.new",
            "terraform state rm aws_instance.deprecated",
            "terraform import aws_instance.web i-1234567890abcdef0",
            "```",
            "",
            "Workspace operations:",
            "```bash",
            "terraform workspace new staging",
            "terraform workspace select production",
            "terraform workspace list",
            "terraform workspace delete staging",
            "```",
            "",
            "### Example S3 Backend Configuration",
            "```hcl",
            "terraform {",
            "  required_version = \">= 1.6.0\"",
            "  required_providers {",
            "    aws = {",
            "      source  = \"hashicorp/aws\"",
            "      version = \"~> 5.0\"",
            "    }",
            "  }",
            "  backend \"s3\" {",
            "    bucket         = \"my-tf-state\"",
            "    key            = \"infra/terraform.tfstate\"",
            "    region         = \"us-east-1\"",
            "    dynamodb_table = \"tf-lock\"",
            "    encrypt        = true",
            "  }",
            "}",
            "```",
            "",
            "### Example Module Usage",
            "```hcl",
            "module \"vpc\" {",
            "  source  = \"terraform-aws-modules/vpc/aws\"",
            "  version = \"~> 5.0\"",
            "",
            "  name = \"my-vpc\"",
            "  cidr = \"10.0.0.0/16\"",
            "",
            "  azs             = [\"us-east-1a\", \"us-east-1b\", \"us-east-1c\"]",
            "  private_subnets = [\"10.0.1.0/24\", \"10.0.2.0/24\", \"10.0.3.0/24\"]",
            "  public_subnets  = [\"10.0.101.0/24\", \"10.0.102.0/24\", \"10.0.103.0/24\"]",
            "",
            "  enable_nat_gateway   = true",
            "  single_nat_gateway   = true",
            "  enable_vpn_gateway   = false",
            "",
            "  tags = {",
            "    Environment = terraform.workspace",
            "    ManagedBy   = \"terraform\"",
            "  }",
            "}",
            "",
            "resource \"aws_instance\" \"web\" {",
            "  ami           = data.aws_ami.ubuntu.id",
            "  instance_type = var.instance_type",
            "  subnet_id     = module.vpc.private_subnets[0]",
            "",
            "  tags = merge(local.common_tags, {",
            "    Name = \"web-server\"",
            "  })",
            "",
            "  lifecycle {",
            "    create_before_destroy = true",
            "    ignore_changes        = [ami]",
            "  }",
            "}",
            "```",
            "",
            "### Troubleshooting",
            "- Use terraform plan to preview changes before applying",
            "- Check state drift: terraform plan -detailed-exitcode",
            "- Debug logs: TF_LOG=DEBUG terraform apply",
            "- Remove stuck locks: terraform force-unlock <lock-id>",
            "- Refresh state: terraform refresh (deprecated, use plan instead)",
            "- Plugin cache: TF_PLUGIN_CACHE_DIR=~/.terraform.d/plugin-cache",
        ]

    def get_capabilities(self) -> list[str]:
        return ["terraform", "hcl", "infrastructure_as_code", "state_management", "terraform_modules", "providers", "workspaces", "remote_backends"]

module = CogInfraTerraform()
