from cog.cog_module import CogModule

class CogFrameworkAngular(CogModule):
    name = "cog-framework-angular"
    version = "1.0.0"
    description = "Angular framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Angular Framework Expertise",
            "",
            "### Core Architecture",
            "- Component-based architecture with TypeScript",
            "- Hierarchical dependency injection system",
            "- Zone.js change detection (default) or zoneless mode",
            "- Standalone components (Angular 14+) preferred over NgModules",
            "- Template system with HTML + Angular syntax extensions",
            "- Reactive programming with RxJS observables",
            "- Signals for fine-grained reactivity (Angular 16+)",
            "- Strict typing with TypeScript throughout",
            "",
            "### Components",
            "- @Component decorator defines metadata",
            "- Template: inline or external HTML file",
            "- Styles: inline, external, or style URLs",
            "- Standalone components by default (standalone: true)",
            "- imports array for standalone component dependencies",
            "- Lifecycle hooks: ngOnInit, ngOnChanges, ngAfterViewInit, ngOnDestroy",
            "- Input properties with input() signal function or @Input decorator",
            "- Output events with output() signal function or @Output + EventEmitter",
            "- Content projection with <ng-content> (slots)",
            "- View encapsulation: Emulated, ShadowDom, None",
            "",
            "### Signals",
            "- signal() creates a writable reactive value",
            "- computed() creates derived reactive values",
            "- effect() runs side effects when signals change",
            "- input() creates signal-based component inputs",
            "- output() creates typed output emitter",
            "- Fine-grained change detection without Zone.js",
            "- toSignal() converts Observable to Signal",
            "- toObservable() converts Signal to Observable",
            "- linkedSignal() for interdependent signal state",
            "",
            "### Dependency Injection",
            "- Services registered via providedIn: 'root' (singleton)",
            "- inject() function preferred over constructor injection",
            "- Hierarchical injectors follow component tree",
            "- Provider tokens: class, InjectionToken, string",
            "- Factory providers with useFactory",
            "- Value providers with useValue",
            "- providedIn: 'root' vs providedIn: SomeModule vs component-level",
            "- ENVIRONMENT_INITIALIZER for app-wide initialization",
            "",
            "### RxJS Integration",
            "- HttpClient returns Observables by default",
            "- AsyncPipe for subscribing in templates",
            "- takeUntilDestroyed() for automatic unsubscription",
            "- Common operators: map, filter, switchMap, mergeMap, forkJoin, combineLatest",
            "- switchMap for canceling previous requests",
            "- concatMap for ordered sequential requests",
            "- shareReplay for multicasting HTTP responses",
            "- Subject and BehaviorSubject for service communication",
            "",
            "### Routing",
            "- RouterModule with Routes array configuration",
            "- Router outlet for rendering matched components",
            "- Route parameters with ActivatedRoute",
            "- Route guards: canActivate, canMatch, canDeactivate (functional guards)",
            "- Lazy loading: loadComponent and loadChildren",
            "- Nested routes with children array",
            "- Router events for navigation tracking",
            "- Query parameters and fragments",
            "- resolve() for pre-fetching route data",
            "- RouterLink directive for declarative navigation",
            "- router.navigate() for imperative navigation",
            "",
            "### Forms",
            "- Template-driven: ngModel, ngForm (two-way binding)",
            "- Reactive: FormControl, FormGroup, FormArray",
            "- FormBuilder service for concise form creation",
            "- Built-in validators: required, minLength, maxLength, pattern, email",
            "- Custom validators as functions or async validators",
            "- Form state: pristine/dirty, valid/invalid, touched/untouched",
            "- ControlValueAccessor for custom form controls",
            "- Typed forms with NonNullableFormBuilder (Angular 14+)",
            "",
            "### Pipes",
            "- Built-in: async, date, uppercase, lowercase, titlecase, slice, json, percent, currency",
            "- Pure pipes (default): re-evaluated only on input change",
            "- Impure pipes: re-evaluated on every change detection cycle",
            "- Custom pipes with @Pipe decorator and transform() method",
            "- standalone pipes for tree-shakable imports",
            "",
            "### Directives",
            "- Attribute directives: change appearance/behavior of elements",
            "- Structural directives: change DOM layout (*ngIf, *ngFor, *ngSwitch)",
            "- @Directive decorator with selector",
            "- ElementRef, Renderer2 for DOM manipulation",
            "- HostListener for event binding on host element",
            "- HostBinding for property binding on host element",
            "- Input and Output on directives for configuration",
            "",
            "### HTTP Client",
            "- HttpClientModule (or provideHttpClient in standalone)",
            "- Interceptors for request/response pipeline",
            "- HttpRequest and HttpResponse objects",
            "- Retry, error handling with catchError operator",
            "- Upload progress with reportProgress option",
            "- Testing with HttpTestingController",
            "",
            "### Testing",
            "- TestBed for configuring test modules",
            "- ComponentFixture and ComponentTester",
            "- ComponentFixtureAutoDetect for automatic change detection",
            "- HttpClientTestingModule for HTTP mocking",
            "- spyOn and jasmine.createSpy for mocking services",
            "- signal() testing: read and set values directly",
            "- ComponentFixture.detectChanges() for triggering CD",
            "",
            "### Performance Best Practices",
            "- OnPush change detection strategy for components",
            "- TrackBy function for *ngFor to minimize DOM updates",
            "- Lazy load routes with loadComponent/loadChildren",
            "- Use pure pipes instead of method calls in templates",
            "- Virtual scrolling with @angular/cdk ScrollingModule",
            "- Web Workers for CPU-intensive tasks",
            "- Preload strategies for route modules",
            "- Zoneless applications with experimentalZonelessMadness",
            "",
            "### Common Operations",
            "Create Angular app:",
            "```bash",
            "npx @angular/cli new myapp --standalone --routing --style=css",
            "```",
            "",
            "Generate artifacts:",
            "```bash",
            "ng generate component my-component --standalone",
            "ng generate service services/my-service",
            "ng generate guard guards/auth --functional",
            "ng generate pipe pipes/truncate --standalone",
            "ng generate directive directives/highlight --standalone",
            "```",
            "",
            "Build and serve:",
            "```bash",
            "ng serve",
            "ng build --configuration production",
            "ng test",
            "```",
            "",
            "Example standalone component with signals:",
            "```typescript",
            "import { Component, signal, computed, inject } from '@angular/core';",
            "import { CommonModule } from '@angular/common';",
            "import { FormsModule } from '@angular/forms';",
            "",
            "@Component({",
            "  selector: 'app-counter',",
            "  standalone: true,",
            "  imports: [CommonModule, FormsModule],",
            "  template: `",
            "    <h1>Count: {{ count() }}</h1>",
            "    <p>Double: {{ double() }}</p>",
            "    <button (click)='increment()'>+</button>",
            "    <button (click)='decrement()'>-</button>",
            "  `",
            "})",
            "export class CounterComponent {",
            "  count = signal(0);",
            "  double = computed(() => this.count() * 2);",
            "  increment() { this.count.update(v => v + 1); }",
            "  decrement() { this.count.update(v => v - 1); }",
            "}",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["angular", "components", "services", "rxjs", "dependency_injection", "signals", "pipes", "directives", "routing", "forms", "http_client", "testing", "standalone_components"]

module = CogFrameworkAngular()
