from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class MySQLQueryTool(Tool):
    name = "mysql.query"
    description = "Execute MySQL query"
    required_permissions = ["shell.execute"]

    def execute(self, database: str, query: str, host: str = "localhost", user: str = "root", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"mysql -h {host} -u {user} -p {database} -e \"{query}\""
        result = shell.execute(command=command, timeout=120)
        return result

class MySQLDumpTool(Tool):
    name = "mysql.dump"
    description = "Dump MySQL database"
    required_permissions = ["shell.execute", "filesystem.write"]

    def execute(self, database: str, output_file: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"mysqldump {database} > {output_file}"
        result = shell.execute(command=command, timeout=600)
        return result

class MySQLRestoreTool(Tool):
    name = "mysql.restore"
    description = "Restore MySQL database"
    required_permissions = ["shell.execute", "filesystem.read"]

    def execute(self, database: str, input_file: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"mysql {database} < {input_file}"
        result = shell.execute(command=command, timeout=600)
        return result

class CogDbMysql(CogModule):
    name = "cog-db-mysql"
    version = "1.0.0"
    description = "MySQL database expertise"

    def register_tools(self) -> list[Tool]:
        return [MySQLQueryTool(), MySQLDumpTool(), MySQLRestoreTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## MySQL Database Expertise",
            "",
            "### MySQL Fundamentals",
            "- Relational database management system",
            "- Client-server architecture",
            "- SQL (Structured Query Language)",
            "- ACID compliance (Atomicity, Consistency, Isolation, Durability)",
            "- Multi-user concurrency",
            "- Table relationships (foreign keys)",
            "- Indexing for performance",
            "- Storage engines (InnoDB, MyISAM, Memory)",
            "",
            "### Data Types",
            "",
            "Numeric types:",
            "- INT, BIGINT, SMALLINT, TINYINT",
            "- DECIMAL, NUMERIC (exact precision)",
            "- FLOAT, DOUBLE (approximate)",
            "- BIT (bit field)",
            "",
            "String types:",
            "- CHAR, VARCHAR (fixed/variable length)",
            "- TEXT (long text)",
            "- BLOB, BINARY (binary data)",
            "- ENUM (enumerated values)",
            "- SET (set of values)",
            "",
            "Date/time types:",
            "- DATE, TIME, DATETIME, TIMESTAMP",
            "- YEAR",
            "",
            "JSON type:",
            "- JSON (storing JSON documents)",
            "- JSON functions for querying",
            "",
            "### Database Design",
            "",
            "Normalization:",
            "- First Normal Form (1NF): Atomic values",
            "- Second Normal Form (2NF): No partial dependencies",
            "- Third Normal Form (3NF): No transitive dependencies",
            "- Denormalization for performance",
            "",
            "Primary keys:",
            "- AUTO_INCREMENT",
            "- UUID as primary key",
            "- Composite primary keys",
            "- Natural vs surrogate keys",
            "",
            "Foreign keys:",
            "- Referential integrity",
            "- CASCADE operations (ON DELETE, ON UPDATE)",
            "- SET NULL, RESTRICT, NO ACTION",
            "- Foreign key constraints",
            "- Join performance considerations",
            "",
            "Indexes:",
            "- B-tree indexes (default)",
            "- UNIQUE indexes",
            "- FULLTEXT indexes (text search)",
            "- Composite indexes (multiple columns)",
            "- Index cardinality considerations",
            "- Index impact on INSERT/UPDATE/DELETE",
            "",
            "### Query Optimization",
            "",
            "EXPLAIN command:",
            "- EXPLAIN SELECT ...",
            "- EXPLAIN ANALYZE SELECT ...",
            "- Understanding query execution plan",
            "- Using indexes properly",
            "- Avoiding table scans",
            "- Optimizing JOIN operations",
            "",
            "Query optimization:",
            "- Select only needed columns",
            "- Use WHERE instead of HAVING",
            "- Avoid SELECT *",
            "- Use LIMIT for large result sets",
            "- Use appropriate data types",
            "- Partitioning large tables",
            "- Archive old data",
            "- Query cache",
            "",
            "### MySQL Features",
            "",
            "Storage engines:",
            "- InnoDB (default, ACID compliant)",
            "- MyISAM (table-level locking)",
            "- Memory (in-memory, fast)",
            "- CSV (CSV file storage)",
            "- Archive (compression)",
            "- Federated (external data)",
            "",
            "InnoDB features:",
            "- Row-level locking",
            "- Foreign key support",
            "- ACID compliance",
            "- Crash recovery",
            "- Transaction support",
            "- MVCC (Multi-Version Concurrency Control)",
            "",
            "### Replication",
            "",
            "Replication types:",
            "- Master-slave replication",
            "- Master-master replication",
            "- Group replication",
            "- GTID-based replication",
            "",
            "Replication concepts:",
            "- Binary log (binlog)",
            "- Relay log",
            "- Replication lag",
            "- Failover and recovery",
            "- Backup from slave",
            "- Read scaling",
            "- Write splitting",
            "",
            "### Backup Strategies",
            "",
            "Backup types:",
            "- Logical backups (mysqldump)",
            "- Physical backups (raw files)",
            "- Incremental backups",
            "- Full backups",
            "",
            "mysqldump options:",
            "- --single-transaction (consistent snapshot)",
            "- --routines (stored procedures)",
            "- --triggers (triggers)",
            "--events (events)",
            "--quick (faster, large tables)",
            "- --lock-tables (consistent)",
            "- --flush-logs (log flush)",
            "- --master-data (replication)",
            "",
            "Backup tools:",
            "- mysqldump (logical backup)",
            "- mysqlhotcopy (physical backup)",
            "- Percona XtraBackup (physical backup)",
            "- MySQL Enterprise Backup",
            "",
            "### Performance Tuning",
            "",
            "Configuration options:",
            "- innodb_buffer_pool_size (70-80% of RAM)",
            "- max_connections (connection limit)",
            "- query_cache_size (query cache)",
            "- tmp_table_size, max_heap_table_size",
            "- innodb_log_file_size",
            "- innodb_flush_log_at_trx_commit",
            "- innodb_flush_method (O_DSYNC)",
            "- sync_binlog (binary log sync)",
            "",
            "Performance schema:",
            "- Performance Schema (P_S) tables",
            "- Setup actors and consumers",
            "- Monitor query performance",
            "- Identify slow queries",
            "- Index usage statistics",
            "- Table and index statistics",
            "",
            "### User Management",
            "",
            "User privileges:",
            "- CREATE USER 'user'@'host' IDENTIFIED BY 'password';",
            "- GRANT ALL PRIVILEGES ON database.* TO 'user'@'host';",
            "- REVOKE privileges",
            "- DROP USER",
            "- SHOW GRANTS FOR 'user'@'host';",
            "",
            "Privilege types:",
            "- ALL PRIVILEGES",
            "- SELECT, INSERT, UPDATE, DELETE",
            "- CREATE, DROP, ALTER",
            "- GRANT OPTION",
            "- FILE, PROCESS, RELOAD",
            "- SUPER",
            "",
            "User security:",
            "- Strong passwords",
            "- Limit user privileges",
            "- Use % wildcard carefully",
            "- Remove anonymous users",
            "- Disable root remote login",
            "",
            "### MySQL Administration",
            "",
            "Database operations:",
            "- CREATE DATABASE database;",
            "- DROP DATABASE database;",
            "- USE database;",
            "- SHOW DATABASES;",
            "- SHOW TABLES;",
            "- DESCRIBE table;",
            "- SHOW CREATE TABLE table;",
            "",
            "Table operations:",
            "- CREATE TABLE, ALTER TABLE, DROP TABLE",
            "- TRUNCATE TABLE (reset AUTO_INCREMENT)",
            "- RENAME TABLE",
            "- ADD COLUMN, DROP COLUMN",
            "- ADD INDEX, DROP INDEX",
            "",
            "Monitoring:",
            "- SHOW PROCESSLIST (running queries)",
            "- SHOW ENGINE INNODB STATUS (InnoDB stats)",
            "- SHOW MASTER STATUS (replication)",
            "- SHOW SLAVE STATUS (replication)",
            "- SHOW VARIABLES LIKE '%query_cache%';",
            "- SHOW STATUS LIKE '%Handler_read%';",
            "",
            "### SQL Best Practices",
            "",
            "Query writing:",
            "- Use explicit column names",
            "- Use prepared statements",
            "- Avoid SELECT *",
            "- Use appropriate indexes",
            "- Use EXPLAIN to analyze queries",
            "- Avoid subqueries in WHERE clause",
            "- Use JOIN instead of subqueries",
            "- Use UNION ALL instead of UNION (no duplicates)",
            "- Use LIMIT for large results",
            "",
            "Transaction management:",
            "- START TRANSACTION;",
            "- COMMIT; or ROLLBACK;",
            "- ACID properties",
            "- Transaction isolation levels",
            "- Deadlock detection and handling",
            "- Savepoints within transactions",
            "",
            "Index usage:",
            "- Create indexes on frequently queried columns",
            "- Use composite indexes for multi-column queries",
            "- Avoid over-indexing (slows INSERT/UPDATE/DELETE)",
            "- Use EXPLAIN to verify index usage",
            "- Analyze slow query log",
            "- Remove unused indexes",
            "",
            "### MySQL vs Other Databases",
            "",
            "vs PostgreSQL:",
            "- MySQL: Faster reads, simpler",
            "- PostgreSQL: More features, more standards-compliant",
            "- MySQL: Different storage engines",
            "- PostgreSQL: Extension system, advanced features",
            "- MySQL: GROUP BY non-aggregate columns allowed",
            "- PostgreSQL: Strict SQL standard compliance",
            "",
            "vs MongoDB:",
            "- MySQL: Structured data, relationships",
            "- MongoDB: Document-based, flexible schema",
            "- MySQL: SQL query language",
            "- MongoDB: JSON-like query language",
            "- MySQL: ACID transactions",
            "- MongoDB: Atomic operations at document level",
            "",
            "### MySQL Tools",
            "",
            "Command-line tools:",
            "- mysql (command-line client)",
            "- mysqldump (backup)",
            "- mysqladmin (administration)",
            "- mysqlcheck (table optimization)",
            "",
            "GUI tools:",
            "- MySQL Workbench",
            "- phpMyAdmin",
            "- DBeaver",
            "- DataGrip",
            "- HeidiSQL",
            "",
            "Monitoring tools:",
            "- Percona Monitoring and Management (PMM)",
            "- MySQL Enterprise Monitor",
            "- Grafana with MySQL plugins",
            "- Custom monitoring scripts",
            "",
            "Backup tools:",
            "- mysqldump",
            "- Percona XtraBackup",
            "- MySQL Enterprise Backup",
            "- AutoMySQL Backup",
            "",
            "### When Working with MySQL",
            "",
            "Creating databases:",
            "- Plan schema carefully",
            "- Normalize appropriately",
            "- Choose correct data types",
            "- Add constraints for integrity",
            "- Create appropriate indexes",
            "- Plan for growth",
            "",
            "Writing queries:",
            "- Use EXPLAIN to analyze",
            "- Test with small datasets first",
            "- Use prepared statements",
            "- Handle errors gracefully",
            "- Optimize based on EXPLAIN",
            "- Consider cache hit rates",
            "",
            "Performance tuning:",
            "- Monitor slow query log",
            "- Use Performance Schema",
            "- Optimize queries based on EXPLAIN",
            "- Add indexes as needed",
            "- Tune server variables",
            "- Consider partitioning",
            "- Archive old data",
            "",
            "Backup strategy:",
            "- Regular backups",
            "- Test restore procedures",
            "- Store backups off-site",
            "- Monitor backup success",
            "- Document backup procedures",
            "- Consider point-in-time recovery",
            "",
            "Security:",
            "- Use strong passwords",
            "- Limit user privileges",
            "- Use SSL/TLS for connections",
            "- Encrypt backups",
            "- Keep software updated",
            "- Monitor for suspicious activity",
            "- Use firewall",
            "- Disable remote root access",
            "",
            "### Common MySQL Tasks",
            "",
            "Create database:",
            "```sql",
            "CREATE DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            "USE mydb;",
            "```",
            "",
            "Create table:",
            "```sql",
            "CREATE TABLE users (",
            "  id INT AUTO_INCREMENT PRIMARY KEY,",
            "  username VARCHAR(255) NOT NULL UNIQUE,",
            "  email VARCHAR(255) NOT NULL,",
            "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,",
            "  INDEX idx_username (username),",
            "  INDEX idx_email (email)",
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
            "```",
            "",
            "Create user:",
            "```sql",
            "CREATE USER 'appuser'@'localhost' IDENTIFIED BY 'secure_password';",
            "GRANT ALL PRIVILEGES ON mydb.* TO 'appuser'@'localhost';",
            "FLUSH PRIVILEGES;",
            "```",
            "",
            "Backup database:",
            "```bash",
            "mysqldump --single-transaction --routines --triggers mydb > backup.sql",
            "```",
            "",
            "Restore database:",
            "```bash",
            "mysql mydb < backup.sql",
            "```",
            "",
            "Show processlist:",
            "```sql",
            "SHOW PROCESSLIST;",
            "```",
            "",
            "Kill query:",
            "```sql",
            "KILL <process_id>;",
            "```",
            "",
            "Show grants:",
            "```sql",
            "SHOW GRANTS FOR 'user'@'host';",
            "```",
            "",
            "### Troubleshooting",
            "",
            "Common issues:",
            "- Connection refused: Check if MySQL is running, check host/port",
            "- Access denied: Check credentials, grants, host restrictions",
            "- Slow queries: Run EXPLAIN, add indexes, optimize queries",
            "- Deadlocks: Check transaction isolation level, optimize queries",
            "- Disk full: Clear binary logs, archive old data",
            "- Out of memory: Increase innodb_buffer_pool_size, optimize queries",
            "- Replication lag: Check network, optimize slave performance",
            "",
            "Debugging:",
            "- Check error log (/var/log/mysql/error.log)",
            "- Check slow query log",
            "- Use EXPLAIN ANALYZE",
            "- SHOW PROCESSLIST for blocking queries",
            "- SHOW ENGINE INNODB STATUS",
            "- Performance Schema",
            "",
            "### MySQL Versions",
            "",
            "MySQL 8.0+ features:",
            "- Window functions (ROW_NUMBER, RANK, DENSE_RANK)",
            "- CTEs (Common Table Expressions)",
            "- JSON functions",
            "- Recursive CTEs",
            "- SKIP LOCKED, NOWAIT",
            "- LATERAL derived tables",
            "- Clone tables",
            "- Invisible indexes",
            "- Descending indexes",
            "- Multi-valued indexes",
            "",
            "MySQL 8.0 vs 5.7:",
            "- Better performance",
            "- Enhanced security",
            "- No more query cache",
            "- Better InnoDB performance",
            "- Improved JSON support",
            "- Data dictionary",
            "- Resource groups",
            "- Window functions",
            "",
            "### Quick Reference",
            "",
            "Connect to MySQL:",
            "```bash",
            "mysql -u root -p",
            "mysql -u user -h host -p database",
            "```",
            "",
            "Show databases:",
            "```sql",
            "SHOW DATABASES;",
            "```",
            "",
            "Use database:",
            "```sql",
            "USE database;",
            "```",
            "",
            "Show tables:",
            "```sql",
            "SHOW TABLES;",
            "```",
            "",
            "Describe table:",
            "```sql",
            "DESCRIBE table;",
            "```",
            "",
            "Run query:",
            "```sql",
            "SELECT * FROM users WHERE id = 1;",
            "```",
            "",
            "Create database:",
            "```sql",
            "CREATE DATABASE mydb;",
            "```",
            "",
            "Create table:",
            "```sql",
            "CREATE TABLE test (id INT);",
            "```",
            "",
            "Insert data:",
            "```sql",
            "INSERT INTO test VALUES (1);",
            "```",
            "",
            "Update data:",
            "```sql",
            "UPDATE test SET id = 2;",
            "```",
            "",
            "Delete data:",
            "```sql",
            "DELETE FROM test WHERE id = 2;",
            "```",
            "",
            "Join tables:",
            "```sql",
            "SELECT * FROM users",
            "JOIN posts ON users.id = posts.user_id;",
            "```",
            "",
            "Left join:",
            "```sql",
            "SELECT * FROM users",
            "LEFT JOIN posts ON users.id = posts.user_id;",
            "```",
            "",
            "Group by:",
            "```sql",
            "SELECT category, COUNT(*) FROM products GROUP BY category;",
            "```",
            "",
            "Order by:",
            "```sql",
            "SELECT * FROM users ORDER BY created_at DESC;",
            "```",
            "",
            "Limit results:",
            "```sql",
            "SELECT * FROM users LIMIT 10;",
            "```",
            "",
            "Aggregate functions:",
            "```sql",
            "SELECT COUNT(*), AVG(price), SUM(quantity) FROM orders;",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "mysql",
            "mysql_design",
            "mysql_optimization",
            "mysql_backup",
            "mysql_restore",
            "mysql_replication",
            "mysql_administration",
            "sql_queries",
            "database_modeling",
            "indexing",
            "performance_tuning",
            "mysql_8_0_features",
            "transactions",
            "foreign_keys",
            "joins",
            "group_by",
            "window_functions",
            "cte",
            "json_support",
            "mysql_security",
            "mysql_monitoring",
            "backup_strategies",
        ]

module = CogDbMysql()
