from cog.cog_module import CogModule


class CogWebCss(CogModule):
    name = "cog-web-css"
    version = "1.0.0"
    description = "CSS3 development module covering Flexbox, Grid, animations, responsive design, media queries, custom properties, Tailwind CSS, CSS modules, PostCSS, BEM, container queries, and cascade layers"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Flexbox",
            "",
            "Use Flexbox for one-dimensional layouts (rows or columns). Prefer `gap` over margins for spacing between items.",
            "",
            "```css",
            ".card-list {",
            "  display: flex;",
            "  flex-wrap: wrap;",
            "  gap: 1.5rem;",
            "}",
            "",
            ".card-list > * {",
            "  flex: 1 1 300px;",
            "}",
            "",
            ".navbar {",
            "  display: flex;",
            "  align-items: center;",
            "  justify-content: space-between;",
            "  padding: 0 1rem;",
            "}",
            "",
            ".navbar__nav {",
            "  display: flex;",
            "  gap: 0.5rem;",
            "}",
            "```",
            "",
            "### Flexbox patterns",
            "- `flex: 1` ≡ `flex: 1 1 0%` — grow and shrink from zero basis",
            "- `flex: auto` ≡ `flex: 1 1 auto` — grow and shrink from content size",
            "- `flex: none` ≡ `flex: 0 0 auto` — fixed at content size, no grow/shrink",
            "- `margin-inline: auto` on a flex child pushes it to the opposite end",
            "- `min-width: 0` on flex children prevents overflow from long content",
            "- Use `order` for visual reordering without DOM changes; avoid for tab order",
            "",
            "## CSS Grid",
            "",
            "Use Grid for two-dimensional layouts. `grid-template-areas` provides readable layout definitions.",
            "",
            "```css",
            ".page {",
            "  display: grid;",
            "  grid-template-columns: 240px 1fr;",
            "  grid-template-rows: auto 1fr auto;",
            "  grid-template-areas:",
            "    'header header'",
            "    'sidebar main'",
            "    'footer footer';",
            "  min-height: 100vh;",
            "  gap: 1rem;",
            "}",
            "",
            ".page__header { grid-area: header; }",
            ".page__sidebar { grid-area: sidebar; }",
            ".page__main { grid-area: main; }",
            ".page__footer { grid-area: footer; }",
            "",
            ".auto-grid {",
            "  display: grid;",
            "  grid-template-columns: repeat(auto-fill, minmax(min(100%, 280px), 1fr));",
            "  gap: 1.5rem;",
            "}",
            "```",
            "",
            "### Grid patterns",
            "- `repeat(auto-fill, minmax(280px, 1fr))` creates responsive grids without media queries",
            "- Use `min(100%, 280px)` to prevent overflow on narrow viewports",
            "- `subgrid` allows children to align to parent grid tracks: `grid-column: span 3; grid-template-columns: subgrid;`",
            "- `fr` units distribute remaining space; use with `minmax()` for flexible yet bounded columns",
            "- Named grid lines: `grid-template-columns: [full-start] 1fr [content-start] 720px [content-end] 1fr [full-end]`",
            "",
            "## Animations and Transitions",
            "",
            "```css",
            ".card {",
            "  transition: transform 200ms ease, box-shadow 200ms ease;",
            "}",
            "",
            ".card:hover {",
            "  transform: translateY(-4px);",
            "  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.12);",
            "}",
            "",
            "@keyframes slide-in {",
            "  from {",
            "    opacity: 0;",
            "    transform: translateX(-20px);",
            "  }",
            "  to {",
            "    opacity: 1;",
            "    transform: translateX(0);",
            "  }",
            "}",
            "",
            ".toast {",
            "  animation: slide-in 300ms ease-out;",
            "}",
            "```",
            "",
            "### Animation guidelines",
            "- Animate only `transform` and `opacity` for GPU-accelerated, compositor-only animations",
            "- Use `will-change` sparingly and remove after animation: `will-change: transform`",
            "- `prefers-reduced-motion: reduce` — disable or minimize animations",
            "- `transition` for state changes (hover, focus); `@keyframes` for multi-step sequences",
            "- Use `animation-fill-mode: both` to persist start/end states",
            "- Stagger animations with `animation-delay` and CSS custom properties: `style=\"--i: 2\"` then `animation-delay: calc(var(--i) * 100ms)`",
            "",
            "## Responsive Design and Media Queries",
            "",
            "```css",
            "/* Mobile-first breakpoints */",
            ":root {",
            "  --space: 1rem;",
            "}",
            "",
            "@media (min-width: 640px) {",
            "  :root { --space: 1.5rem; }",
            "}",
            "",
            "@media (min-width: 1024px) {",
            "  :root { --space: 2rem; }",
            "}",
            "",
            "/* Container queries */",
            ".card-container {",
            "  container-type: inline-size;",
            "  container-name: card;",
            "}",
            "",
            "@container card (min-width: 400px) {",
            "  .card { flex-direction: row; }",
            "}",
            "",
            "@container card (min-width: 600px) {",
            "  .card__image { width: 50%; }",
            "}",
            "```",
            "",
            "### Responsive patterns",
            "- Mobile-first: write base styles for smallest screens, add `min-width` breakpoints",
            "- Use `clamp()` for fluid typography: `font-size: clamp(1rem, 2.5vw, 2rem)`",
            "- Use `min()` / `max()` for bounded sizing: `width: min(100%, 800px)`",
            "- Container queries respond to parent size, not viewport; use for component-level responsive behavior",
            "- `container-type: inline-size` enables `@container` width queries",
            "",
            "## CSS Custom Properties",
            "",
            "```css",
            ":root {",
            "  --color-primary: #4f46e5;",
            "  --color-primary-light: #818cf8;",
            "  --color-surface: #ffffff;",
            "  --color-text: #1e1e1e;",
            "  --radius: 8px;",
            "  --shadow: 0 1px 3px rgba(0, 0, 0, 0.1);",
            "}",
            "",
            "[data-theme=\"dark\"] {",
            "  --color-surface: #1e1e1e;",
            "  --color-text: #f0f0f0;",
            "}",
            "",
            ".btn {",
            "  background: var(--color-primary);",
            "  color: white;",
            "  border-radius: var(--radius);",
            "  padding: 0.5rem 1rem;",
            "}",
            "",
            ".btn--outline {",
            "  background: transparent;",
            "  color: var(--color-primary);",
            "  box-shadow: inset 0 0 0 2px var(--color-primary);",
            "}",
            "```",
            "",
            "### Custom property patterns",
            "- Define tokens in `:root` for global access; scope to components for local overrides",
            "- Use for theming: toggle a `data-theme` attribute on `<html>`",
            "- Properties cascade and inherit, unlike Sass variables",
            "- Use `@property` for typed properties with initial values: `@property --hue { syntax: '<number>'; initial-value: 0; inherits: false; }`",
            "- Typed properties can be animated by the browser",
            "",
            "## Tailwind CSS Utility Classes",
            "",
            "```html",
            "<div class=\"flex items-center justify-between gap-4 rounded-lg bg-white p-4 shadow-md dark:bg-gray-800\">",
            "  <h2 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Card Title</h2>",
            "  <button class=\"rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2\">",
            "    Action",
            "  </button>",
            "</div>",
            "```",
            "",
            "### Tailwind patterns",
            "- Use `@apply` sparingly in CSS; prefer utility classes in HTML",
            "- Configure `tailwind.config.js` with design tokens: colors, spacing, typography scales",
            "- Use `dark:` prefix for dark mode; `hover:`, `focus:`, `group-hover:`, `peer-focus:` for states",
            "- Responsive prefixes: `sm:`, `md:`, `lg:`, `xl:`, `2xl:` (mobile-first)",
            "- Arbitrary values: `w-[calc(100%-2rem)]`, `text-[clamp(1rem,3vw,2rem)]`",
            "- Use `@layer components` for component classes; `@layer utilities` for custom utilities",
            "",
            "## CSS Modules",
            "",
            "```css",
            "/* Button.module.css */",
            ".button {",
            "  composes: base from '../shared/base.module.css';",
            "  padding: 0.5rem 1rem;",
            "  border-radius: var(--radius);",
            "}",
            "",
            ".primary {",
            "  composes: button;",
            "  background: var(--color-primary);",
            "  color: white;",
            "}",
            "```",
            "",
            "### CSS Modules patterns",
            "- Class names are scoped locally by default; no need for BEM prefixes in module files",
            "- `composes` merges class definitions; keeps specificity flat",
            "- Import as object: `import styles from './Button.module.css'; ... <button className={styles.primary}>`",
            "- Use `:global()` to escape scoping when needed: `:global(.external-class)`",
            "",
            "## PostCSS",
            "",
            "```javascript",
            "// postcss.config.js",
            "module.exports = {",
            "  plugins: [",
            "    require('postcss-preset-env')({ stage: 3 }),",
            "    require('cssnano')({ preset: 'default' }),",
            "  ],",
            "};",
            "```",
            "",
            "### PostCSS ecosystem",
            "- `postcss-preset-env` — use future CSS with configurable `stage` levels",
            "- `autoprefixer` — add vendor prefixes based on browserslist (often included in presets)",
            "- `postcss-import` — inline `@import` statements",
            "- `postcss-nesting` — native CSS nesting syntax",
            "- `cssnano` — minification and optimization for production",
            "",
            "## BEM Methodology",
            "",
            "```css",
            "/* Block */",
            ".card { border: 1px solid #ddd; border-radius: 8px; }",
            "",
            "/* Element */",
            ".card__title { font-size: 1.25rem; font-weight: 600; }",
            ".card__body { padding: 1rem; }",
            "",
            "/* Modifier */",
            ".card--featured { border-color: #4f46e5; }",
            ".card--featured .card__title { color: #4f46e5; }",
            "```",
            "",
            "### BEM naming convention",
            "- Block: `.component` — standalone entity",
            "- Element: `.component__element` — part of a block, separated by double underscore",
            "- Modifier: `.component--modifier` — variant of a block/element, separated by double dash",
            "- Avoid element nesting deeper than one level: `.card__body__text` is an anti-pattern",
            "- Use modifier classes alongside base class: `class=\"card card--featured\"`",
            "",
            "## Cascade Layers",
            "",
            "```css",
            "@layer reset, base, components, utilities;",
            "",
            "@layer reset {",
            "  *, *::before, *::after { box-sizing: border-box; margin: 0; }",
            "}",
            "",
            "@layer base {",
            "  body { font-family: system-ui, sans-serif; line-height: 1.6; }",
            "}",
            "",
            "@layer components {",
            "  .btn { padding: 0.5rem 1rem; border-radius: 4px; }",
            "}",
            "",
            "@layer utilities {",
            "  .sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); }",
            "}",
            "```",
            "",
            "### Cascade layer patterns",
            "- Declaration order of `@layer` sets priority: later layers win over earlier layers",
            "- Unlayered styles have the highest priority, beating all layers",
            "- Use layers to integrate third-party CSS without specificity conflicts",
            "- @layer with @import: @import url('reset.css') layer(reset);",
            "- Layers solve specificity wars without `!important`",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "flexbox",
            "css-grid",
            "animations-transitions",
            "responsive-design",
            "media-queries",
            "css-custom-properties",
            "tailwind-css",
            "css-modules",
            "postcss",
            "bem-methodology",
            "container-queries",
            "cascade-layers",
        ]


module = CogWebCss()
