from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class KubectlTool(Tool):
    name = "k8s.kubectl"
    description = "Execute kubectl commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"kubectl {command}", **kwargs)
        return result

class HelmTool(Tool):
    name = "k8s.helm"
    description = "Helm package manager for Kubernetes"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, release: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        command = f"helm {action} {release}"
        result = shell.execute(command=command, timeout=300)
        return result

class KubeconfigTool(Tool):
    name = "k8s.kubeconfig"
    description = "Manage kubeconfig files"
    required_permissions = ["shell.execute", "filesystem.read"]

    def execute(self, action: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"kubectl {action}", **kwargs)
        return result

class CogInfraKubernetes(CogModule):
    name = "cog-infra-kubernetes"
    version = "1.0.0"
    description = "Kubernetes orchestration expertise"

    def register_tools(self) -> list[Tool]:
        return [KubectlTool(), HelmTool(), KubeconfigTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Kubernetes Orchestration Expertise",
            "",
            "### Core K8s Concepts",
            "- Pods (smallest deployable unit)",
            "- Services (network access)",
            "- Deployments (declarative updates)",
            "- ReplicaSets (ensures desired state)",
            "- StatefulSets (stateful apps)",
            "- DaemonSets (system daemons)",
            "- Namespaces (resource isolation)",
            "- ConfigMaps (configuration data)",
            "- Secrets (sensitive data)",
            "- PersistentVolumes (storage)",
            "- StorageClasses (storage types)",
            "",
            "### Kubernetes Architecture",
            "- Control plane (master node)",
            "- Data plane (worker nodes)",
            "- etcd (key-value store)",
            "- API Server (K8s API)",
            "- Scheduler (pod placement)",
            "- Controller Manager (ensures state)",
            "- Cloud Controller Manager (cloud integration)",
            "- kubelet (agent on nodes)",
            "- kube-proxy (network proxy)",
            "",
            "### Kubernetes Objects",
            "",
            "Pod:",
            "- One or more containers",
            "- Shared storage and network",
            "- Each pod has unique IP",
            "- Ephemeral by design",
            "- Restart policies (Always, OnFailure, Never)",
            "- Liveness probes (health checks)",
            "- Readiness probes (startup checks)",
            "- Resource limits (CPU, memory)",
            "",
            "Service:",
            "- Stable network endpoint",
            "- Pod selector (label selector)",
            "- ClusterIP (internal access)",
            "- NodePort (external access)",
            "LoadBalancer (cloud load balancer)",
            "- Headless services (no cluster IP)",
            "",
            "Deployment:",
            "- Declarative state management",
            "- Replica count management",
            "- Rolling updates (zero downtime)",
            "- Rollback capabilities",
            "- Rollback history",
            "- Pod templates",
            "- Update strategies (RollingUpdate, Recreate)",
            "",
            "StatefulSet:",
            "- Stable network identities",
            "- Ordinal pod numbering",
            "- Stable persistent storage",
            "- Ordered deployment",
            "- Ordered scaling",
            "",
            "ConfigMap:",
            "- Key-value configuration data",
            "- Environment variable injection",
            "- Configuration files",
            "- Hot-reload without restart",
            "- Immutable vs mutable",
            "",
            "Secret:",
            "- Sensitive data storage",
            "- Base64 encoded",
            "- Environment variable injection",
            "- TLS certificates",
            "- API keys and tokens",
            "- Rotation strategies",
            "",
            "PersistentVolume:",
            "- Storage provisioning",
            "- StorageClass abstraction",
            "- PersistentVolumeClaims",
            "- Volume types (NFS, iSCSI, HostPath)",
            "- Access modes (RWO, RWX, ReadOnlyMany)",
            "- Reclaim policies (Retain, Delete)",
            "",
            "### Networking",
            "",
            "Service discovery:",
            "- DNS-based service discovery",
            "- Environment variables",
            "- kube-proxy",
            "- ClusterIP internal routing",
            "- NodePort for external access",
            "- LoadBalancer service type",
            "",
            "Ingress:",
            "- Ingress controllers (nginx, Traefik)",
            "- Ingress rules",
            "- TLS termination",
            "- Path-based routing",
            "- Host-based routing",
            "- URL rewriting",
            "- Rate limiting",
            "- Authentication (OAuth, Basic Auth)",
            "- CORS handling",
            "",
            "Network policies:",
            "- NetworkPolicy resources",
            "- Pod-to-pod communication",
            "Network policies enforcement",
            "- Whitelist approach (allow-list)",
            "- Deny all, then allow specific",
            "",
            "### Kubernetes Commands",
            "",
            "Basic operations:",
            "- kubectl get pods (list pods)",
            "- kubectl get services (list services)",
            "- kubectl get deployments (list deployments)",
            "- kubectl get all (all resources)",
            "",
            "Create resources:",
            "- kubectl apply -f manifest.yaml",
            "- kubectl create -f manifest.yaml",
            "- kubectl delete -f manifest.yaml",
            "",
            "Describe resources:",
            "- kubectl describe pod <name>",
            "- kubectl describe deployment <name>",
            "- kubectl describe node <name>",
            "",
            "View logs:",
            "- kubectl logs <pod>",
            "- kubectl logs -f <deployment> (all pods)",
            "- kubectl logs --previous <pod> (previous instance)",
            "",
            "Exec into container:",
            "- kubectl exec -it <pod> -- sh",
            "- kubectl exec -it <pod> -- bash",
            "",
            "Scale deployments:",
            "- kubectl scale deployment/<name> --replicas=3",
            "- kubectl autoscale deployment/<name> --min=2 --max=10",
            "",
            "Edit resources:",
            "- kubectl edit svc <service>",
            "- kubectl edit deploy <deployment>",
            "- kubectl edit configmap <name>",
            "- kubectl edit secret <name>",
            "",
            "Port forwarding:",
            "- kubectl port-forward <pod> 8080:80",
            "- kubectl port-forward svc/<service> 8080:80",
            "",
            "Apply configurations:",
            "- kubectl apply -f directory/",
            "- kubectl apply -f https://example.com/config.yaml",
            "- kubectl apply -f - (stdin)",
            "",
            "### Helm Charts",
            "",
            "Helm components:",
            "- Chart.yaml (metadata)",
            "- values.yaml (configuration)",
            "- Templates directory (yaml templates)",
            "- Charts directory (subcharts)",
            "- .helmignore (files to ignore)",
            "",
            "Helm operations:",
            "- helm install myrelease ./mychart",
            "- helm upgrade myrelease ./mychart",
            "- helm rollback myrelease 1",
            "- helm uninstall myrelease",
            "- helm list",
            "- helm repo add myrepo https://charts.bitnami.com/bitnami",
            "- helm search <keyword>",
            "- helm show <chart>",
            "",
            "### Kubernetes vs Docker Swarm",
            "",
            "Kubernetes advantages:",
            "- More complex orchestration",
            "- Auto-scaling (HPA)",
            "- Self-healing",
            "- Rich ecosystem",
            "- Cloud-agnostic",
            "- Industry standard",
            "- Declarative configuration",
            "- Large scale support",
            "",
            "Docker Swarm advantages:",
            "- Simpler setup",
            "- Easier learning curve",
            "- Faster to deploy",
            "- Good for small-medium scale",
            "- Docker-native",
            "",
            "### Kubernetes Best Practices",
            "",
            "Resource limits:",
            "- Set CPU/memory requests and limits",
            "- Prevent resource exhaustion",
            "- Enable horizontal pod autoscaling",
            "- Right-size your applications",
            "",
            "Health checks:",
            "- Liveness probes (is app alive?)",
            "- Readiness probes (is app ready?)",
            "- Startup probes (is app starting?)",
            "- Proper probe configuration",
            "- Probe periods and thresholds",
            "- Failure thresholds",
            "",
            "Configuration management:",
            "- Use ConfigMaps for config",
            "- Use Secrets for sensitive data",
            "- Use environment variables",
            "- Immutable config vs hot-reload",
            "- External configuration (ExternalSecret, ConfigMap)",
            "",
            "Security:",
            "- Least privilege RBAC",
            "- Network policies for isolation",
            "- Pod Security Policies (PSP)",
            "- Security contexts (runAsUser, readOnlyRootFilesystem)",
            "- Resource quotas",
            "- Network policies",
            "- Image security scanning",
            "",
            "High availability:",
            "- Multiple replicas",
            "- Anti-affinity rules",
            "- Pod disruption budgets",
            "- Rolling updates with health checks",
            "- Multiple availability zones",
            "- Backup and restore strategies",
            "",
            "Monitoring:",
            "- Prometheus metrics",
            "- Grafana dashboards",
            "- Elasticsearch logging",
            "- Jaeger tracing",
            "- Custom metrics and alerts",
            "- AlertManager",
            "",
            "### Common Kubernetes Patterns",
            "",
            "Deployment strategies:",
            "- RollingUpdate (zero downtime)",
            "- Recreate (brief downtime)",
            "- Blue-green deployments",
            "- Canary deployments",
            "",
            "Config management:",
            "- ConfigMaps (non-sensitive config)",
            "- Secrets (sensitive data)",
            "- Environment variables",
            "- Configuration as code",
            "- GitOps workflows",
            "",
            "Service discovery:",
            "- DNS-based service discovery",
            "- Headless services (stateless)",
            "- Client-side load balancing",
            "- Service mesh (Istio, Linkerd)",
            "",
            "Storage:",
            "- PersistentVolumes for databases",
            "- StatefulSets for stateful apps",
            "- EmptyDir for scratch space",
            "- ConfigMaps for configuration",
            "- Secrets for credentials",
            "",
            "### Kubernetes Tools",
            "",
            "kubectl (main CLI):",
            "- Primary command-line tool",
            "- Aliases for common operations",
            "- Kubeconfig file management",
            "- Multiple context support",
            "",
            "kubectl plugins:",
            "- kubectl-tree (visualize resources)",
            "- kubectl-v1.22+/ (latest features)",
            "- kubectl-rollout (rollout status)",
            "- kubectl-trace (trace requests)",
            "",
            "Helm (package manager):",
            "- Package manager for Kubernetes apps",
            "- Chart repositories",
            "- Release management",
            "- Rolling upgrades",
            "",
            "kubectl vs kubectl (different tools):",
            "- kubectl (Kubernetes CLI)",
            "- kubectl (Kubernetes umbrella project)",
            "",
            "### Quick Reference",
            "",
            "Create deployment:",
            "```yaml",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            "  name: myapp",
            "spec:",
            "  replicas: 3",
            "  selector:",
            "    matchLabels:",
            "      app: myapp",
            "  template:",
            "    metadata:",
            "      labels:",
            "        app: myapp",
            "    spec:",
            "      containers:",
            "      - name: myapp",
            "        image: myapp:v1",
            "          ports:",
            "          - containerPort: 8080",
            "          readinessProbe:",
            "            httpGet:",
            "              path: /health",
            "              port: 8080",
            "          livenessProbe:",
            "            httpGet:",
            "              path: /health",
            "          env:",
            "            - name: DATABASE_URL",
            "              valueFrom:",
            "                secretKeyRef:",
            "                  name: db-secret",
            "                  key: url",
            "          resources:",
            "            requests:",
            "              memory: \"128Mi\"",
              "              cpu: \"100m\"",
            "            limits:",
            "              memory: \"256Mi\"",
            "              cpu: \"200m\"",
            "",
            "Create service:",
            "```yaml",
            "apiVersion: v1",
            "kind: Service",
            "metadata:",
            "  name: myapp",
            "spec:",
            "  selector:",
            "    matchLabels:",
            "      app: myapp",
            "  ports:",
            "  - protocol: TCP",
            "    port: 80,
            "    targetPort: 8080",
            "",
            "            "Create ConfigMap:",
            "```yaml",
            "apiVersion: v1",
            "kind: ConfigMap",
            "metadata:",
            "  name: app-config",
            "data:",
            "  DATABASE_URL: "postgresql://localhost:5432/mydb",
            "  REDIS_URL: "redis://localhost:6379",
            "",
            "Create Secret:",
            "```yaml",
            "apiVersion: v1",
            "kind: Secret",
            "metadata:",
            "  name: db-secret",
            "type: Opaque",
            "data:",
            "  url: postgresql://user:pass@localhost:5432/db",
            "",
            "Apply to Kubernetes:",
            "- kubectl apply -f deployment.yaml",
            "- kubectl get pods",
            "- kubectl logs deployment/myapp",
            "",
            "Scale up:",
            "- kubectl scale deployment/myapp --replicas=5",
            "Scale down:",
            "- kubectl scale deployment/myapp --replicas=1",
            "",
            "Update image:",
            "- kubectl set image deployment/myapp myapp:v2",
            "- kubectl rollout restart deployment/myapp",
            "Rollback:",
            "- kubectl rollout undo deployment/myapp",
            "- kubectl rollout history deployment/myapp",
            "",
            "Debug pods:",
            "- kubectl describe pod <pod-name>",
            "- kubectl logs <pod-name>",
            "- kubectl exec -it <pod-name> -- sh",
            "",
            "Delete resources:",
            "- kubectl delete deployment myapp",
            "- kubectl delete service myapp",
            "- kubectl delete pod <pod-name>",
            "- kubectl delete -f manifest.yaml",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "kubernetes",
            "k8s",
            "containers",
            "orchestration",
            "helm",
            "kubectl",
            "deployments",
            "services",
            "configmaps",
            "secrets",
            "ingress",
            "volumes",
            "scaling",
            "cluster_management",
            "monitoring",
            "troubleshooting",
            "yaml_configuration",
            "manifests",
            "helm_charts",
            "pod_security_policies",
            "resource_limits",
            "health_checks",
            "rolling_updates",
            "blue_green_deployments",
            "canary_deployments"
        ]

module = CogInfraKubernetes()
