from cog.cog_module import CogModule

class CogDbMongodb(CogModule):
    name = "cog-db-mongodb"
    version = "1.0.0"
    description = "MongoDB database expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## MongoDB NoSQL Database Expertise",
            "",
            "### Document Database Concepts",
            "- BSON format (Binary JSON)",
            "- Collections (similar to tables)",
            "- Documents (similar to rows)",
            "- _id field (unique identifier)",
            "- Flexible schema",
            "- Embedded documents vs references",
            "- Document size limit (16MB)",
            "- GridFS for large files",
            "",
            "### Data Modeling",
            "- Document structure design",
            "- Embedding vs referencing",
            "- One-to-one, one-to-many, many-to-many",
            "- Schema validation",
            "- Indexing strategies",
            "- Data types (String, Number, Boolean, Date, Array, Object, Null)",
            "- _id vs custom ids",
            "- Atomic operations",
            "",
            "### Query Language",
            "- find() for querying",
            "- Query operators ($eq, $ne, $gt, $lt, $in, $nin, $and, $or, $not)",
            "- Projection (limit returned fields)",
            "- sort() and limit()",
            "- count() and countDocuments()",
            "- distinct()",
            "- aggregation pipeline",
            "",
            "### Aggregation Pipeline",
            "- $match (filter documents)",
            "- $group (group by fields)",
            "- $project (reshape documents)",
            "- $sort (sort results)",
            "- $limit (limit results)",
            "- $lookup (join collections)",
            "- $unwind (array operations)",
            "- $facet (multiple aggregations)",
            "- $count (count documents)",
            "",
            "### Indexing",
            "- Single field indexes",
            "- Compound indexes",
            "Multikey indexes",
            "- Text indexes",
            "- Geospatial indexes",
            "- Hashed indexes",
            "- TTL indexes (time-to-live)",
            "- Index properties (unique, sparse)",
            "- Covered queries",
            "- Index build process",
            "",
            "### Replication",
            "- Replica sets",
            "- Primary and secondary nodes",
            "- Automatic failover",
            "- Write concerns",
            "- Read preferences",
            "- Oplog (operations log)",
            "- Arbiter (for automatic failover)",
            "",
            "### Sharding",
            "- Sharded clusters",
            "- Shard keys",
            "- Chunk splitting",
            "- Balancer",
            "- Config servers",
            "- Query routers",
            "- Shard key selection",
            "",
            "### GridFS",
            "- Large file storage",
            "- Chunks (255KB default)",
            "- Files collection metadata",
            "- Upload and retrieve files",
            "- Streaming",
            "",
            "### MongoDB vs Relational Databases",
            "- Schema flexibility vs strict schema",
            "- Document-oriented vs table-oriented",
            "- Horizontal scaling (sharding) vs vertical scaling",
            "- JSON documents vs rows/columns",
            "- ACID properties at document level vs transaction level",
            "- Better for unstructured/hierarchical data",
            "- Slower for complex joins",
            "- Better for rapid iteration",
            "",
            "### Common Operations",
            "Connect:",
            "```bash",
            "mongosh mongodb://localhost:27017",
            "mongo --host localhost --port 27017",
            "```",
            "",
            "Use database:",
            "```javascript",
            "use mydb",
            "```",
            "",
            "Insert document:",
            "```javascript",
            "db.users.insertOne({",
            "  name: 'John',",
            "  age: 30,",
            "  email: 'john@example.com'",
            "  created: new Date()",
            "  tags: ['developer', 'admin']",
            "})",
            "```",
            "",
            "Query documents:",
            "```javascript",
            "db.users.find({ age: { $gt: 25 } })",
            "db.users.find({ tags: 'mongodb' })",
            "db.users.find({ name: /^J/ })",
            "```",
            "",
            "Update document:",
            "```javascript",
            "db.users.updateOne({ _id: ObjectId('...') }, {",
            "  $set: { age: 31 }",
            "  $push: { tags: 'senior' }",
            "})",
            "```",
            "",
            "Delete document:",
            "```javascript",
            "db.users.deleteOne({ _id: ObjectId('...') })",
            "```",
            "",
            "Aggregation:",
            "```javascript",
            "db.orders.aggregate([",
            "  { $match: { status: 'completed' } },",
            "  { $group: { _id: '$product', total: { $sum: '$amount' } } } },",
            "  { $sort: { total: -1 } },",
            "  { $limit: 10 }",
            "])",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["mongodb", "nosql", "document_modeling", "aggregation", "replication", "sharding", "gridfs", "indexing"]

module = CogDbMongodb()
