from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class GraphQLValidateTool(Tool):
    name = "graphql.validate"
    description = "Validate GraphQL schemas and queries"
    required_permissions = ["shell.execute"]

    def execute(self, schema_path: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        if schema_path:
            result = shell.execute(command=f"graphql-validator {schema_path}")
        else:
            result = ToolResult(success=True, message="GraphQL validation ready")
        return result

class GraphQLCodegenTool(Tool):
    name = "graphql.codegen"
    description = "Generate TypeScript types from GraphQL schema"
    required_permissions = ["shell.execute", "filesystem.write"]

    def execute(self, schema_path: str, output_path: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(
            command=f"graphql-codegen --schema {schema_path} --output {output_path}"
        )
        return result

class GraphQLIntrospectionTool(Tool):
    name = "graphql.introspection"
    description = "Introspect GraphQL API schema"
    required_permissions = ["shell.execute"]

    def execute(self, endpoint: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(
            command=f"curl -X POST {endpoint} -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name}}}\"}'"
        )
        return result

class CogApiGraphql(CogModule):
    name = "cog-api-graphql"
    version = "1.0.0"
    description = "GraphQL API design and implementation expertise"

    def register_tools(self) -> list[Tool]:
        return [GraphQLValidateTool(), GraphQLCodegenTool(), GraphQLIntrospectionTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## GraphQL Expertise",
            "",
            "### Core Concepts",
            "- Schema (type system)",
            "- Types (object, scalar, enum, interface, union)",
            "- Fields (properties on types)",
            "- Queries (read operations)",
            "- Mutations (write operations)",
            "- Subscriptions (real-time updates)",
            "- Resolvers (data fetching logic)",
            "- Arguments (field parameters)",
            "- Variables (query parameters)",
            "- Directives (query modifiers)",
            "",
            "### Schema Design",
            "",
            "Schema types:",
            "- Object types (data entities)",
            "- Scalar types (Int, Float, String, Boolean, ID)",
            "- Enum types (fixed values)",
            "- Interface types (abstract types)",
            "- Union types (multiple types)",
            "- Input types (mutation input)",
            "- Custom scalars (domain-specific)",
            "",
            "Schema structure:",
            "- Query type (read root)",
            "- Mutation type (write root)",
            "- Subscription type (event root)",
            "- Type definitions",
            "- Input definitions",
            "- Interface definitions",
            "- Enum definitions",
            "- Union definitions",
            "- Directives definitions",
            "",
            "Schema best practices:",
            "- Object types (nouns, not verbs)",
            "- Nullable fields by default",
            "- Non-null for required fields",
            "- Pagination (first, after)",
            "- Filter arguments (where clause)",
            "- Sort arguments (order by)",
            "- Relay connections (edges, nodes)",
            "- Namespacing (prefixes)",
            "- Deprecation (deprecated directive)",
            "",
            "### Query Language",
            "",
            "Query structure:",
            "- Operation type (query, mutation, subscription)",
            "- Operation name (optional but recommended)",
            "- Selection set (fields to fetch)",
            "- Arguments (field parameters)",
            "- Variables (parameterized queries)",
            "- Directives (skip, include, deprecated)",
            "",
            "Field selections:",
            "- Scalar fields (leaf nodes)",
            "- Object fields (nested objects)",
            "- List fields (arrays)",
            "- Inline fragments (type conditions)",
            "- Fragments (reusable selections)",
            "- Fragment spreads (use fragments)",
            "- Metasfields (__typename)",
            "",
            "Query variables:",
            "- $syntax",
            "- Type definitions",
            "- Default values",
            "- Variable usage",
            "",
            "Query directives:",
            "- @include(if: Boolean)",
            "- @skip(if: Boolean)",
            "- @deprecated(reason: String)",
            "- Custom directives",
            "",
            "### Mutations",
            "",
            "Mutation design:",
            "- Verb naming (create, update, delete)",
            "- Input objects (structured input)",
            "- Payload types (mutation result)",
            "- Errors in payload (not null on success)",
            "- Client mutation IDs (idempotency)",
            "",
            "Common mutation patterns:",
            "- Create resource",
            "- Update resource",
            "- Delete resource",
            "- Bulk operations",
            "- Nested mutations",
            "",
            "Mutation best practices:",
            "- Return modified object",
            "- Return errors in payload",
            "- Use input types",
            "- Validation in resolver",
            "- Idempotent mutations",
            "",
            "### Subscriptions",
            "",
            "Subscription architecture:",
            "- WebSocket transport",
            "- Event-based (pub/sub)",
            "- Live queries (polling)",
            "",
            "Subscription types:",
            "- Simple subscriptions (single event)",
            "- Filtered subscriptions (where clause)",
            "- Payload subscriptions (event data)",
            "",
            "Subscription implementation:",
            "- WebSocket server",
            "- Pub/sub system",
            "- Resolver is async generator",
            "- Filter client events",
            "- Authentication",
            "",
            "### Resolvers",
            "",
            "Resolver signature:",
            "- Field resolver (obj, args, context, info)",
            "- Root resolver (parent)",
            "- Default resolvers (property access)",
            "",
            "Resolver patterns:",
            "- Simple field resolvers",
            "- Async resolvers (data fetching)",
            "- DataLoader resolvers (batching)",
            "- Authorization resolvers (permissions)",
            "- Computed field resolvers",
            "",
            "Resolver best practices:",
            "- DataLoader for N+1 queries",
            "- Async/await for async operations",
            "- Error handling (try/catch)",
            "- Context for shared resources",
            "- Caching in resolvers",
            "- Schema stitching (delegation)",
            "",
            "### DataLoader Pattern",
            "",
            "What is DataLoader:",
            "- Batches requests",
            "- Caches results",
            "- Prevents N+1 queries",
            "- Automatic deduplication",
            "",
            "DataLoader usage:",
            "- Create instance per request",
            "- Load many items",
            "- Prime cache manually",
            "- Clear cache per mutation",
            "",
            "Batching strategies:",
            "- In batch (group IDs)",
            "- Batch callback (single query)",
            "- Cache key function",
            "",
            "### Authentication & Authorization",
            "",
            "Authentication:",
            "- JWT tokens",
            "- Context authentication",
            "- Token validation",
            "- Refresh tokens",
            "",
            "Authorization:",
            "- Authorization layer (directive)",
            "- Resolver-level checks",
            "- Field-level permissions",
            "- Role-based access",
            "- Permission-based access",
            "",
            "Best practices:",
            "- Authorize in resolvers",
            "- Context for user data",
            "- Roles and permissions",
            "- Field-level auth",
            "- Custom auth directives",
            "",
            "### Error Handling",
            "",
            "GraphQL errors:",
            "- Null propagation (partial errors)",
            "- Errors array (multiple errors)",
            "- Extensions (custom metadata)",
            "- Path (error location)",
            "- Locations (line/column)",
            "",
            "Error strategies:",
            "- Errors in mutation payload",
            "- User-friendly messages",
            "- Error codes (constants)",
            "- Validation errors",
            "- Internal errors (don't leak)",
            "",
            "Error extensions:",
            "- Code (error code)",
            "- Message (user message)",
            "- Details (debug info)",
            "- Stack trace (development)",
            "",
            "### Caching",
            "",
            "Response caching:",
            "- HTTP caching (Cache-Control)",
            "- Persisted queries",
            "- Automatic persisted queries",
            "",
            "Data caching:",
            "- Application-level cache",
            "- DataLoader cache",
            "- Resolver cache",
            "- CDN cache",
            "",
            "Cache invalidation:",
            "- Mutation-based (clear cache)",
            "- Time-based (TTL)",
            "- Tag-based (cache tags)",
            "- Cache headers",
            "",
            "### Performance Optimization",
            "",
            "Query optimization:",
            "- Limit field depth",
            "- Query complexity analysis",
            "- Query timeout",
            "- Rate limiting",
            "",
            "Resolver optimization:",
            "- DataLoader batching",
            "- Parallel resolvers (Promise.all)",
            "- Data loader caching",
            "- Resolver caching",
            "- Async resolvers",
            "",
            "Schema optimization:",
            "- Avoid deep nesting",
            "- Pagination (first, after)",
            "- Filter capabilities",
            "- Minimal fields",
            "- Use fragments",
            "- Persisted queries",
            "",
            "### Testing",
            "",
            "Schema testing:",
            "- Type validation",
            "- Field existence",
            "- Schema coverage",
            "- Snapshot testing",
            "",
            "Resolver testing:",
            "- Unit tests",
            "- Mock data",
            "- Test context",
            "- Mock dependencies",
            "",
            "Integration testing:",
            "- Query testing",
            "- Mutation testing",
            "- Subscription testing",
            "- Auth testing",
            "- Error handling",
            "",
            "### Tools",
            "",
            "Apollo Server (Node.js):",
            "- Schema-first",
            "- Resolvers",
            "- Data sources",
            "- Apollo Federation",
            "",
            "Apollo Federation:",
            "- Subgraphs (microservices)",
            "- Federation gateway",
            "- Entity types (@key)",
            "- Extend types",
            "- Reference directives",
            "",
            "GraphQL Yoga (Node.js):",
            "- Envelop plugins",
            "- Subscriptions",
            "- Built-in caching",
            "- File uploads",
            "",
            "Graphene (Python):",
            "- Code-first",
            "- Schema-first",
            "- Django integration",
            "- FastAPI integration",
            "",
            "Strawberry (Python):",
            "- Type-based (Python type hints)",
            "- Code-first",
            "- FastAPI integration",
            "",
            "Hot Chocolate (C#):",
            "- Code-first",
            "- Schema-first",
            "- Subscriptions",
            "- Data loaders",
            "",
            "graphql-java (Java):",
            "- Schema-first",
            "- Code-first",
            "- Data loader",
            "",
            "graphql-ruby (Ruby):",
            "- Schema-first",
            "- Ruby-style resolvers",
            "",
            "### GraphQL vs REST",
            "",
            "GraphQL advantages:",
            "- Single endpoint",
            "- No overfetching",
            "- No underfetching",
            "- Type system",
            "- Introspection",
            "- Strongly typed",
            "- Self-documenting",
            "- Versionless",
            "- Frontend-driven",
            "",
            "REST advantages:",
            "- Simpler",
            "- HTTP caching",
            "- Standard tools",
            "- Rate limiting (URL-based)",
            "- Better for simple CRUD",
            "",
            "When to use GraphQL:",
            "- Complex data relationships",
            "- Mobile apps (bandwidth)",
            "- Rapid iteration",
            "- Multiple clients",
            "- Real-time (subscriptions)",
            "- Microservices (federation)",
            "",
            "### Quick Reference",
            "",
            "Define schema:",
            "```graphql",
            "type User {",
            "  id: ID!",
            "  name: String!",
            "  email: String!",
            "  posts: [Post!]!",
            "}",
            "",
            "type Post {",
            "  id: ID!",
            "  title: String!",
            "  content: String!",
            "  author: User!",
            "}",
            "",
            "type Query {",
            "  user(id: ID!): User",
            "  users: [User!]!",
            "  post(id: ID!): Post",
            "  posts: [Post!]!",
            "}",
            "",
            "type Mutation {",
            "  createUser(input: CreateUserInput!): CreateUserPayload!",
            "  createPost(input: CreatePostInput!): CreatePostPayload!",
            "}",
            "",
            "input CreateUserInput {",
            "  name: String!",
            "  email: String!",
            "}",
            "",
            "type CreateUserPayload {",
            "  user: User",
            "  errors: [Error!]!",
            "}",
            "",
            "type Error {",
            "  field: String!",
            "  message: String!",
            "}",
            "```",
            "",
            "Query:",
            "```graphql",
            "query GetUser($id: ID!) {",
            "  user(id: $id) {",
            "    id",
            "    name",
            "    email",
            "    posts {",
            "      id",
            "      title",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Variables:",
            "```json",
            "{",
            "  \"id\": \"1\"",
            "}",
            "```",
            "",
            "Mutation:",
            "```graphql",
            "mutation CreateUser($input: CreateUserInput!) {",
            "  createUser(input: $input) {",
            "    user {",
            "      id",
            "      name",
            "      email",
            "    }",
            "    errors {",
            "      field",
            "      message",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Subscription:",
            "```graphql",
            "subscription OnPostCreated {",
            "  postCreated {",
            "    post {",
            "      id",
            "      title",
            "      author {",
            "        name",
            "      }",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Fragment:",
            "```graphql",
            "fragment UserFields on User {",
            "  id",
            "  name",
            "  email",
            "}",
            "",
            "query Users {",
            "  users {",
            "    ...UserFields",
            "  }",
            "}",
            "```",
            "",
            "Directives:",
            "```graphql",
            "query User($id: ID!, $withPosts: Boolean!) {",
            "  user(id: $id) {",
            "    id",
            "    name",
            "    posts @include(if: $withPosts) {",
            "      title",
            "    }",
            "  }",
            "}",
            "```",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "graphql",
            "api_design",
            "schema_design",
            "queries",
            "mutations",
            "subscriptions",
            "resolvers",
            "dataloader",
            "authentication",
            "authorization",
            "error_handling",
            "testing",
            "apollo_server",
            "apollo_federation",
            "graphql_yoga",
            "graphene",
            "strawberry",
            "optimization",
            "caching",
            "introspection",
            "codegen"
        ]

module = CogApiGraphql()
