from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class ElasticsearchTool(Tool):
    name = "es.query"
    description = "Execute Elasticsearch queries"
    required_permissions = ["shell.execute"]

    def execute(self, index: str, query: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        import json
        query_json = json.dumps(query)
        result = shell.execute(
            command=f"curl -XGET 'localhost:9200/{index}/_search' -H 'Content-Type: application/json' -d '{query_json}'"
        )
        return result

class ESIndexTool(Tool):
    name = "es.index"
    description = "Create and manage Elasticsearch indices"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, index: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"curl -X{action.upper()} 'localhost:9200/{index}'")
        return result

class ESClusterTool(Tool):
    name = "es.cluster"
    description = "Manage Elasticsearch cluster"
    required_permissions = ["shell.execute"]

    def execute(self, endpoint: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"curl -XGET 'localhost:9200/_cluster/{endpoint}'")
        return result

class CogDbElasticsearch(CogModule):
    name = "cog-db-elasticsearch"
    version = "1.0.0"
    description = "Elasticsearch search and analytics expertise"

    def register_tools(self) -> list[Tool]:
        return [ElasticsearchTool(), ESIndexTool(), ESClusterTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Elasticsearch Expertise",
            "",
            "### Core Concepts",
            "- Index (like a database)",
            "- Document (JSON record)",
            "- Field (key-value pair)",
            "- Mapping (schema definition)",
            "- Type (deprecated in 7.x+)",
            "- Cluster (node collection)",
            "- Node (single server)",
            "- Shard (data partition)",
            "- Replica (shard copy)",
            "- Segment (immutable index segment)",
            "",
            "### Elasticsearch Architecture",
            "",
            "Cluster components:",
            "- Cluster state (metadata)",
            "- Master node (management)",
            "- Data node (data storage)",
            "- Coordinating node (query routing)",
            "- Ingest node (document processing)",
            "- Machine learning node (ML jobs)",
            "- Tribe node (federated search)",
            "",
            "Data organization:",
            "- Index (primary data container)",
            "- Shards (horizontal scaling)",
            "- Replicas (high availability)",
            "- Segments (lucene segments)",
            "- Translog (write-ahead log)",
            "- Document ID routing",
            "- Consistent hashing",
            "",
            "### Query DSL (Domain Specific Language)",
            "",
            "Query context:",
            "- Match query (full-text search)",
            "- Term query (exact match)",
            "- Range query (numeric/date ranges)",
            "- Bool query (boolean combinations)",
            "- Prefix query (prefix matching)",
            "- Wildcard query (pattern matching)",
            "- Fuzzy query (typo tolerance)",
            "- Regexp query (regex patterns)",
            "",
            "Filter context:",
            "- Term filter (exact filtering)",
            "- Range filter (range filtering)",
            "- Exists filter (field presence)",
            "- Missing filter (field absence)",
            "- Terms filter (multiple values)",
            "- And filter (conjunction)",
            "- Or filter (disjunction)",
            "- Not filter (negation)",
            "",
            "Aggregations:",
            "- Metrics (avg, sum, min, max)",
            "- Bucketing (terms, range, date)",
            "- Nested (nested documents)",
            "- Histogram (numeric histograms)",
            "- Date histogram (time series)",
            "- Geo bounds (geographic)",
            "- Percentiles (statistical)",
            "- Cardinality (unique count)",
            "",
            "### Index Management",
            "",
            "Create index:",
            "- PUT /index_name",
            "- Mappings (field types)",
            "- Settings (shards, replicas)",
            "- Analyzers (text processing)",
            "- Normalizers (keyword normalization)",
            "- Aliases (index aliases)",
            "",
            "Update mapping:",
            "- PUT /index_name/_mapping",
            "- New field mappings",
            "- Existing field restrictions",
            "- Multi-fields (multiple analyzers)",
            "- Copy-to fields",
            "- Runtime fields",
            "",
            "Index settings:",
            "- Number of shards",
            "- Number of replicas",
            "- Refresh interval",
            "- Analysis configuration",
            "- Index lifecycle management",
            "- Shard allocation filtering",
            "",
            "### Document Operations",
            "",
            "Index document:",
            "- PUT /index_name/_doc/id",
            "- POST /index_name/_doc (auto ID)",
            "- Bulk API (bulk operations)",
            "- Update API (partial updates)",
            "- Upsert (update or insert)",
            "- Delete API",
            "",
            "Document versions:",
            "- Version numbers",
            "- Optimistic locking",
            "- External versioning",
            "- Sequence numbers",
            "- Primary terms",
            "",
            "### Search Capabilities",
            "",
            "Search API:",
            "- URI search (?q=query)",
            "- Request body search",
            "- Multi-index search",
            "- Multi-type search (6.x)",
            "- Scroll API (pagination)",
            "- Search after (deep pagination)",
            "- Point in time API",
            "",
            "Full-text search:",
            "- Inverted index",
            "- TF-IDF scoring",
            "- BM25 scoring",
            "- Phrase matching",
            "- Proximity search",
            "- Highlighting",
            "- Suggesters",
            "",
            "Relevance tuning:",
            "- Boosting",
            "- Function score",
            "- Script scoring",
            "- Rescoring",
            "- Explanation API",
            "",
            "### Aggregations Framework",
            "",
            "Bucket aggregations:",
            "- Terms aggregation (group by)",
            "- Range aggregation (numeric ranges)",
            "- Date range (time ranges)",
            "- Histogram (equal-width buckets)",
            "- Date histogram (time series)",
            "- Nested aggregation",
            "- Reverse nested",
            "- Geohash grid",
            "",
            "Metric aggregations:",
            "- Avg (average)",
            "- Sum (sum)",
            "- Min (minimum)",
            "- Max (maximum)",
            "- Stats (all metrics)",
            "- Extended stats",
            "- Percentiles",
            "- Percentile ranks",
            "- Cardinality (approx unique)",
            "- Value count",
            "",
            "Pipeline aggregations:",
            "- Moving average",
            "- Derivative",
            "- Cumulative sum",
            "- Bucket sort",
            "- Max bucket",
            "- Min bucket",
            "- Avg bucket",
            "- Sum bucket",
            "- Stats bucket",
            "",
            "### Elasticsearch vs SQL Databases",
            "",
            "Elasticsearch advantages:",
            "- Full-text search",
            "- Fast aggregations",
            "- Real-time search",
            "- Auto-completion",
            "- Geospatial queries",
            "- Analyzers and tokenizers",
            "- Distributed by default",
            "- Horizontal scaling",
            "",
            "SQL databases advantages:",
            "- ACID transactions",
            "- Complex joins",
            "- Strong consistency",
            "- Mature tooling",
            "- SQL standard",
            "- Referential integrity",
            "- Secondary indexes",
            "",
            "When to use Elasticsearch:",
            "- Search applications",
            "- Log analytics",
            "- Metrics analytics",
            "- Text search",
            "- Autocomplete",
            "- Geospatial search",
            "- Real-time analytics",
            "- APM and monitoring",
            "",
            "### Elasticsearch Commands",
            "",
            "Cluster health:",
            "- GET /_cluster/health",
            "- GET /_cat/health?v",
            "- GET /_cluster/state",
            "- GET /_cluster/stats",
            "",
            "Index management:",
            "- PUT /my_index",
            "- DELETE /my_index",
            "- GET /my_index",
            "- GET /_cat/indices?v",
            "- GET /my_index/_mapping",
            "- PUT /my_index/_mapping",
            "",
            "Document operations:",
            "- PUT /my_index/_doc/1",
            "- GET /my_index/_doc/1",
            "- POST /my_index/_doc",
            "- POST /my_index/_update/1",
            "- DELETE /my_index/_doc/1",
            "",
            "Search:",
            "- GET /my_index/_search?q=field:value",
            "- POST /my_index/_search",
            "- GET /my_index/_doc/_search",
            "",
            "Bulk operations:",
            "- POST /_bulk",
            "- newline-delimited JSON",
            "- index/create/delete/update",
            "- Bulk size optimization",
            "",
            "### Mapping and Analysis",
            "",
            "Field types:",
            "- Text (full-text)",
            "- Keyword (exact match)",
            "- Numeric (integer, long, float)",
            "- Date (datetime)",
            "- Boolean",
            "- Binary (base64)",
            "- Object (nested objects)",
            "- Nested (array of objects)",
            "- Geo point",
            "- Geo shape",
            "- IP address",
            "- Completion",
            "- Percolator",
            "",
            "Analyzers:",
            "- Character filters",
            "- Tokenizers",
            "- Token filters",
            "- Standard analyzer",
            "- Simple analyzer",
            "- Whitespace analyzer",
            "- Stop analyzer",
            "- Keyword analyzer",
            "- Pattern analyzer",
            "- Language analyzers",
            "- Snowball analyzer",
            "- Fingerprint analyzer",
            "",
            "Tokenizers:",
            "- Standard tokenizer",
            "- Letter tokenizer",
            "- Lowercase tokenizer",
            "- Whitespace tokenizer",
            "- UAX URL email",
            "- NGram tokenizer",
            "- Edge NGram",
            "- Keyword tokenizer",
            "- Pattern tokenizer",
            "- Path hierarchy",
            "",
            "### Distributed Architecture",
            "",
            "Sharding:",
            "- Primary shards",
            "- Replica shards",
            "- Shard routing",
            "- Shard allocation",
            "- Shard relocation",
            "- Rebalancing",
            "- Splitting shards",
            "- Shrinking shards",
            "",
            "Replication:",
            "- Primary replica",
            "- Replica sync",
            "- In-sync replicas",
            "- Quorum (write concern)",
            "- Wait for active shards",
            "- Replica recovery",
            "- Snapshot and restore",
            "",
            "Cluster scaling:",
            "- Add data nodes",
            "- Remove data nodes",
            "- Hot-warm architecture",
            "- Tiered storage",
            "- Node roles",
            "- Node attributes",
            "- Shard filtering",
            "- Allocation awareness",
            "",
            "### Performance Optimization",
            "",
            "Index optimization:",
            "- Shard count sizing",
            "- Refresh interval tuning",
            "- Translog durability",
            "- Merge policy",
            "- Force merge",
            "- Index sorting",
            "- Index lifecycle management",
            "- Rollover indices",
            "",
            "Query optimization:",
            "- Filter context",
            "- Query profiling",
            "- Search slow logs",
            "- Index sorting",
            "- Doc values",
            "- Keyword fields",
            "- Fielddata cache",
            "- Query caching",
            "- Request cache",
            "",
            "Hardware sizing:",
            "- Heap size (50% rule, max 30GB)",
            "- Disk I/O (SSD preferred)",
            "- CPU (coordinator heavy)",
            "- Memory (file system cache)",
            "- Network (low latency)",
            "",
            "### Index Lifecycle Management",
            "",
            "ILM phases:",
            "- Hot (write-heavy)",
            "- Warm (read-heavy)",
            "- Cold (read-only)",
            "- Delete (cleanup)",
            "",
            "ILM actions:",
            "- Rollover (new index)",
            "- Shrink (reduce shards)",
            "- Force merge",
            "- Freeze (read-only cache)",
            "- Delete",
            "- Allocate (move tier)",
            "- Read-only",
            "- Set priority",
            "",
            "### Monitoring and Maintenance",
            "",
            "Cluster monitoring:",
            "- Cluster health (green/yellow/red)",
            "- Node stats",
            "- Indices stats",
            "- Shard allocation",
            "- Pending tasks",
            "- Thread pools",
            "",
            "Performance metrics:",
            "- Search latency",
            "- Indexing rate",
            "- Merge time",
            "- Cache hit ratio",
            "- JVM heap usage",
            "- GC frequency",
            "- CPU usage",
            "- Disk I/O",
            "",
            "Maintenance tasks:",
            "- Backup snapshots",
            "- Restore from snapshot",
            "- Cluster reroute",
            "- Shard allocation",
            "- Cache clearing",
            "- Field data clearing",
            "- Query cache clearing",
            "- Old indices cleanup",
            "",
            "### Quick Reference",
            "",
            "Create index with mapping:",
            "```json",
            "PUT /my_index",
            "{",
            "  \"mappings\": {",
            "    \"properties\": {",
            "      \"title\": { \"type\": \"text\" },",
            "      \"description\": { \"type\": \"text\" },",
            "      \"status\": { \"type\": \"keyword\" },",
            "      \"created\": { \"type\": \"date\" },",
            "      \"priority\": { \"type\": \"integer\" }",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Index document:",
            "```json",
            "PUT /my_index/_doc/1",
            "{",
            "  \"title\": \"Elasticsearch Guide\",",
            "  \"description\": \"Learn Elasticsearch\",\n"      \"  \"status\": \"published\",",
            "  \"created\": \"2026-01-01\",",
            "  \"priority\": 1",
            "}",
            "```",
            "",
            "Match query:",
            "```json",
            "POST /my_index/_search",
            "{",
            "  \"query\": {",
            "    \"match\": { \"title\": \"elasticsearch\" }",
            "  }",
            "}",
            "```",
            "",
            "Bool query:",
            "```json",
            "{",
            "  \"query\": {",
            "    \"bool\": {",
            "      \"must\": [",
            "        { \"match\": { \"title\": \"elasticsearch\" } }",
            "      ],",
            "      \"filter\": [",
            "        { \"term\": { \"status\": \"published\" } }",
            "      ]",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Aggregation:",
            "```json",
            "{",
            "  \"aggs\": {",
            "    \"status_count\": {",
            "      \"terms\": { \"field\": \"status\" }",
            "    },",
            "    \"avg_priority\": {",
            "      \"avg\": { \"field\": \"priority\" }",
            "    }",
            "  }",
            "}",
            "```",
            "",
            "Delete index:",
            "- DELETE /my_index",
            "",
            "Cluster health:",
            "- GET /_cluster/health?pretty",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "elasticsearch",
            "search_engine",
            "analytics",
            "indexing",
            "full_text_search",
            "aggregations",
            "mapping",
            "cluster_management",
            "sharding",
            "replication",
            "log_analytics",
            "metrics",
            "monitoring",
            "query_dsl",
            "document_operations",
            "bulk_operations",
            "analyzers",
            "tokenizers",
            "relevance_tuning",
            "performance_optimization",
            "index_lifecycle",
            "distributed_search"
        ]

module = CogDbElasticsearch()
