from cog.cog_module import CogModule

class CogFrameworkSvelte(CogModule):
    name = "cog-framework-svelte"
    version = "1.0.0"
    description = "Svelte/SvelteKit framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Svelte/SvelteKit Framework Expertise",
            "",
            "### Core Architecture",
            "- Compiler-based framework — no virtual DOM",
            "- Svelte compiles components to imperative JavaScript at build time",
            "- SvelteKit provides file-based routing, SSR, and build tooling",
            "- Minimal runtime overhead compared to React/Vue",
            "- Truly reactive with compile-time dependency tracking",
            "- Built-in scoped styles per component",
            "",
            "### Reactive Declarations",
            "- $: reactive statement — re-runs when dependencies change",
            "- $: doubled = count * 2 — reactive assignment",
            "- $: if (count > 10) { ... } — reactive side effect",
            "- let declarations in script are reactive by default",
            "- $state rune (Svelte 5) for explicit reactive state",
            "- $derived rune for computed values (Svelte 5)",
            "- $effect rune for side effects (Svelte 5)",
            "- Reactivity tracked at compile time, no runtime overhead",
            "",
            "### Components",
            "- .svelte files with <script>, <template>, <style> sections",
            "- Props declared with export let or $props() rune (Svelte 5)",
            "- Event dispatching with createEventDispatcher or callback props",
            "- Slot for content projection, named slots for multiple areas",
            "- {#if}, {:else if}, {:else}, {/if} for conditionals",
            "- {#each items as item, i} for list rendering",
            "- {#await promise} for async template blocks",
            "- {@html rawHtml} for unescaped HTML insertion",
            "- Bindings: bind:value, bind:checked, bind:this, bind:clientWidth",
            "",
            "### Stores",
            "- Writable stores: writable(initialValue)",
            "- Readable stores: readable(initialValue, start function)",
            "- Derived stores: derived(store(s), callback)",
            "- $storeName auto-subscription syntax in components",
            "- store.set(value) and store.update(fn) for writable stores",
            "- Custom stores: return subscribe + any methods",
            "- Stores work across components without prop drilling",
            "- Svelte 5: $state in .svelte.ts files replaces stores for simple cases",
            "",
            "### SvelteKit Routing",
            "- File-based routing under src/routes/",
            "- src/routes/+page.svelte — page component",
            "- src/routes/+page.ts — load function (runs on server + client)",
            "- src/routes/+page.server.ts — server-only load function",
            "- src/routes/+layout.svelte — shared layout",
            "- src/routes/+layout.ts — shared data loading",
            "- src/routes/+error.svelte — error page",
            "- Dynamic params: [slug], [...rest], [[optional]]",
            "- Route groups with (group) parentheses",
            "",
            "### Load Functions",
            "- export const load = async ({ params, fetch, url, parent }) => {}",
            "- +page.ts load runs on both server and client",
            "- +page.server.ts load runs only on the server",
            "- Return plain objects as page data",
            "- Access parent layout data with parent()",
            "- Use fetch() for SSR-safe API calls (not global fetch)",
            "- depends() for fine-grained cache invalidation",
            "- Type-safe with PageLoad and PageServerLoad types",
            "",
            "### Form Actions",
            "- Defined in +page.server.ts with actions object",
            "- export const actions = { default: async ({ request }) => {} }",
            "- Named actions: export const actions = { create: async ..., delete: async ... }",
            "- Form validation and error return with fail(status, { errors })",
            "- use:enhance directive for progressive enhancement",
            "- Redirect after success with redirect() utility",
            "- Cookies and locals accessible in action context",
            "",
            "### Transitions and Animations",
            "- transition:fade, transition:fly, transition:slide",
            "- in: and out: for separate enter/leave transitions",
            "- animate:flip for list reorder animations",
            "- Custom transition functions returning { delay, duration, css, tick }",
            "- Crossfade for shared element transitions between lists",
            "",
            "### Context API",
            "- setContext(key, value) in parent component",
            "- getContext(key) in any descendant component",
            "- Type-safe with generic parameters",
            "- onMount, onDestroy, beforeUpdate, afterUpdate lifecycle",
            "- tick() returns a promise that resolves after DOM update",
            "",
            "### Adapters and Deployment",
            "- @sveltejs/adapter-auto — auto-detect platform",
            "- @sveltejs/adapter-node — Node.js server",
            "- @sveltejs/adapter-static — fully static site",
            "- @sveltejs/adapter-vercel — Vercel deployment",
            "- @sveltejs/adapter-cloudflare — Cloudflare Pages",
            "- @sveltejs/adapter-netlify — Netlify deployment",
            "- prerender option for static page generation",
            "- ssr option to disable SSR for specific pages",
            "",
            "### Performance Best Practices",
            "- Compiler optimizes away unused code",
            "- Use {#each with key} for efficient list updates",
            "- Lazy-load components with import() in dynamic components",
            "- Preload pages with preload or data-sveltekit-preload-data",
            "- Use adapter-static for fully static sites when possible",
            "- Optimize images with @sveltejs/enhanced-img",
            "- Leverage SvelteKit streaming for progressive loading",
            "",
            "### Common Operations",
            "Create SvelteKit app:",
            "```bash",
            "npx sv create myapp",
            "```",
            "",
            "Development server:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build and preview:",
            "```bash",
            "npm run build",
            "npm run preview",
            "```",
            "",
            "Example load function and page:",
            "```typescript",
            "import type { PageLoad } from './$types';",
            "",
            "export const load: PageLoad = async ({ params, fetch }) => {",
            "  const res = await fetch(`/api/posts/${params.slug}`);",
            "  const post = await res.json();",
            "  return { post };",
            "};",
            "```",
            "",
            "```svelte",
            "<script lang=\"ts\">",
            "  let { data } = $props();",
            "</script>",
            "",
            "<article>",
            "  <h1>{data.post.title}</h1>",
            "  <div>{@html data.post.content}</div>",
            "</article>",
            "```",
            "",
            "Example form action:",
            "```typescript",
            "import type { Actions } from './$types';",
            "import { fail, redirect } from '@sveltejs/kit';",
            "",
            "export const actions: Actions = {",
            "  default: async ({ request, cookies }) => {",
            "    const data = await request.formData();",
            "    const email = data.get('email') as string;",
            "    if (!email) return fail(400, { error: 'Email required' });",
            "    await db.user.create({ data: { email } });",
            "    throw redirect(303, '/welcome');",
            "  }",
            "};",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["svelte", "sveltekit", "reactive_declarations", "stores", "ssr", "load_functions", "form_actions", "adapters", "transitions", "context_api", "compiler_based"]

module = CogFrameworkSvelte()
