from cog.cog_module import CogModule

class CogInfraAnsible(CogModule):
    name = "cog-infra-ansible"
    version = "1.0.0"
    description = "Ansible automation expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Ansible Automation Expertise",
            "",
            "### Core Concepts",
            "- Agentless architecture (SSH/WinRM connectivity)",
            "- Idempotent operations (safe to run repeatedly)",
            "- Playbooks (YAML-defined automation tasks)",
            "- Inventory (hosts and groups of hosts)",
            "- Modules (units of work: yum, apt, copy, template, service, etc.)",
            "- Roles (reusable, structured collections of tasks)",
            "- Variables (host vars, group vars, play vars, extra vars)",
            "- Facts (gathered system information from target hosts)",
            "- Handlers (triggered tasks, notified on change)",
            "- Ansible Galaxy (community role repository)",
            "- Jinja2 templating for dynamic configuration",
            "",
            "### Inventory Management",
            "- Static inventory (INI or YAML files)",
            "- Dynamic inventory (scripts or plugins for AWS, GCP, Azure)",
            "- Host groups and nested groups (children)",
            "- Group variables (group_vars/ directory)",
            "- Host variables (host_vars/ directory)",
            "- Multiple inventory sources",
            "- Inventory plugins (yaml, ini, constructed, auto)",
            "- Patterns for host selection (all, webservers, db*&staging, etc.)",
            "",
            "### Playbooks",
            "- YAML structure with plays and tasks",
            "- Play-level settings: hosts, become, vars, roles",
            "- Task-level settings: name, module, args, register, when, loop",
            "- Sequential execution with pre_tasks, roles, tasks, post_tasks",
            "- Tags for selective task execution",
            "- Delegate_to for running tasks on specific hosts",
            "- Local actions with delegate_to: localhost",
            "- Serial execution for rolling updates",
            "- max_fail_percentage for fault tolerance",
            "- import_playbook and include_playbook for composition",
            "",
            "### Modules",
            "- Package management: apt, yum, dnf, pip, npm, gem",
            "- Service management: service, systemd",
            "- File operations: copy, template, file, assemble, fetch",
            "- User management: user, group, authorized_key",
            "- Git operations: git",
            "- Cloud modules: ec2, azure_rm, gcp_compute",
            "- Command execution: command, shell, raw, script",
            "- Database: mysql_db, postgresql_db, mongodb_user",
            "- Archive: unarchive, archive, ansible.builtin.sync",
            "- Wait conditions: wait_for, pause",
            "- Debugging: debug, assert, fail",
            "",
            "### Roles",
            "- Standard directory structure: tasks, handlers, templates, files, vars, defaults, meta",
            "- Role dependencies in meta/main.yml",
            "- Role installation from Galaxy: ansible-galaxy install",
            "- Role creation: ansible-galaxy init",
            "- Role path configuration: roles_path in ansible.cfg",
            "- Molecule for role testing",
            "- Parameterized roles with role vars and defaults",
            "",
            "### Jinja2 Templates",
            "- Variable substitution: {{ variable }}",
            "- Filters: default, join, map, selectattr, regex_replace, to_json, b64encode",
            "- Conditionals: {% if condition %} ... {% endif %}",
            "- Loops: {% for item in list %} ... {% endfor %}",
            "- Macros: {% macro name(arg) %} ... {% endmacro %}",
            "- Template inheritance: {% extends 'base.j2' %}",
            "- Whitespace control: {%- and -%}",
            "- lookup() function for external data",
            "- Nested variable access with dot notation or brackets",
            "",
            "### Variables and Facts",
            "- Variable precedence (22 levels, from default to extra_vars)",
            "- group_vars/all.yml, group_vars/<group>.yml",
            "- host_vars/<host>.yml",
            "- Registered variables from task output",
            "- Magic variables: hostvars, groups, inventory_hostname, ansible_facts",
            "- ansible_facts ( gathered system info: OS, IP, architecture, etc.)",
            "- set_fact for runtime variable creation",
            "- Filters for data transformation",
            "",
            "### Ansible Galaxy",
            "- Search roles: ansible-galaxy search <term>",
            "- Install roles: ansible-galaxy install <author.role>",
            "- Install from requirements.yml",
            "- Publish roles: ansible-galaxy import <github_user> <repo>",
            "- Collections (distributed automation packages)",
            "- ansible-galaxy collection install <namespace.collection>",
            "",
            "### Best Practices",
            "- Use roles for reusable automation",
            "- Keep playbooks simple, move complexity to roles",
            "- Use ansible.cfg for project-level configuration",
            "- Use dynamic inventory for cloud environments",
            "- Use vault for secret encryption",
            "- Name all tasks descriptively",
            "- Use check mode (--check) for dry runs",
            "- Use diff mode (--diff) to see file changes",
            "- Set gather_facts: smart or explicitly when needed",
            "- Use async tasks for long-running operations",
            "- Version control all playbooks and roles",
            "- Use pre_tasks for prerequisite checks",
            "- Use block/rescue/always for error handling",
            "",
            "### Common Operations",
            "Run playbook:",
            "```bash",
            "ansible-playbook site.yml -i inventory/production",
            "ansible-playbook site.yml --check --diff",
            "ansible-playbook site.yml --limit webservers",
            "ansible-playbook site.yml --tags \"install,configure\"",
            "ansible-playbook site.yml --extra-vars \"env=staging\"",
            "ansible-playbook site.yml --vault-password-file ~/.vault_pass",
            "```",
            "",
            "Ad-hoc commands:",
            "```bash",
            "ansible all -i inventory -m ping",
            "ansible webservers -m shell -a 'uptime'",
            "ansible dbservers -m apt -a 'name=postgresql state=present' --become",
            "ansible all -m setup | grep ansible_os_family",
            "ansible localhost -m debug -a 'msg={{ hostvars[\"web1\"] }}'",
            "```",
            "",
            "Galaxy operations:",
            "```bash",
            "ansible-galaxy init myrole",
            "ansible-galaxy install geerlingguy.nginx",
            "ansible-galaxy install -r requirements.yml",
            "ansible-galaxy collection install community.general",
            "ansible-galaxy role list",
            "```",
            "",
            "Vault operations:",
            "```bash",
            "ansible-vault create secrets.yml",
            "ansible-vault edit secrets.yml",
            "ansible-vault encrypt plain.yml",
            "ansible-vault decrypt secrets.yml",
            "ansible-vault rekey secrets.yml",
            "ansible-vault view secrets.yml",
            "```",
            "",
            "### Example Playbook",
            "```yaml",
            "---",
            "- name: Deploy web application",
            "  hosts: webservers",
            "  become: true",
            "  serial: 2",
            "  max_fail_percentage: 25",
            "  vars:",
            "    app_version: \"1.2.3\"",
            "    app_port: 8080",
            "",
            "  pre_tasks:",
            "    - name: Verify connectivity",
            "      ansible.builtin.ping:",
            "",
            "  roles:",
            "    - role: geerlingguy.nginx",
            "      tags: [nginx]",
            "    - role: app_deploy",
            "      tags: [deploy]",
            "",
            "  tasks:",
            "    - name: Install dependencies",
            "      ansible.builtin.apt:",
            "        name:",
            "          - python3-pip",
            "          - libpq-dev",
            "        state: present",
            "        update_cache: true",
            "      tags: [install]",
            "",
            "    - name: Deploy application configuration",
            "      ansible.builtin.template:",
            "        src: templates/app.conf.j2",
            "        dest: /etc/myapp/config.yml",
            "        owner: appuser",
            "        group: appgroup",
            "        mode: '0644'",
            "      notify: Restart application",
            "      tags: [configure]",
            "",
            "    - name: Ensure application is running",
            "      ansible.builtin.service:",
            "        name: myapp",
            "        state: started",
            "        enabled: true",
            "",
            "  handlers:",
            "    - name: Restart application",
            "      ansible.builtin.service:",
            "        name: myapp",
            "        state: restarted",
            "```",
            "",
            "### Example Jinja2 Template",
            "```jinja2",
            "# Managed by Ansible - do not edit manually",
            "server {",
            "    listen {{ app_port }};",
            "    server_name {{ inventory_hostname }};",
            "",
            "    {% for upstream in app_upstreams %}",
            "    location {{ upstream.path }} {",
            "        proxy_pass http://{{ upstream.host }}:{{ upstream.port }};",
            "        proxy_set_header Host $host;",
            "        proxy_set_header X-Real-IP $remote_addr;",
            "    }",
            "    {% endfor %}",
            "",
            "    access_log /var/log/nginx/{{ inventory_hostname }}.access.log;",
            "}",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["ansible", "configuration_management", "playbooks", "roles", "inventory", "jinja2_templates", "ansible_galaxy", "automation"]

module = CogInfraAnsible()
