from cog.cog_module import CogModule

class CogFrameworkRemix(CogModule):
    name = "cog-framework-remix"
    version = "1.0.0"
    description = "Remix framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Remix Framework Expertise",
            "",
            "### Core Architecture",
            "- Full-stack web framework built on Web Fetch API",
            "- Emulates browser behavior on the server",
            "- Nested routing with progressive data loading",
            "- Server-first approach with client-side enhancements",
            "- Built on React Router v6+",
            "- Runs on any Node.js server or edge runtime",
            "- Built-in support for Vite as bundler",
            "",
            "### Loaders (Data Loading)",
            "- Export async loader function from route modules",
            "- Runs on the server before rendering",
            "- Receives params, request, context arguments",
            "- Return data via json() utility or plain objects",
            "- Access loader data in component via useLoaderData()",
            "- Loaders run in parallel for nested routes",
            "- Type-safe with LoaderFunctionArgs generic type",
            "- Can throw redirect() to navigate elsewhere",
            "- Can throw responses for error handling",
            "",
            "### Actions (Data Mutations)",
            "- Export async action function from route modules",
            "- Handles POST, PUT, PATCH, DELETE requests",
            "- Receives params, request, context arguments",
            "- Access form data with formData.get() or request.formData()",
            "- After action completes, loaders are revalidated automatically",
            "- Return redirect() after successful mutation",
            "- Return validation errors as data for form display",
            "- useActionData() accesses action response in component",
            "- useNavigation() tracks submission state",
            "",
            "### Nested Routing",
            "- URL segments map to route file hierarchy",
            "- Each route can export its own loader, action, Component",
            "- Parent routes wrap children via <Outlet />",
            "- Routes load data in parallel (not waterfall)",
            "- Active route links styled with <NavLink />",
            "- Dynamic segments with $param syntax (routes/users/$userId.tsx)",
            "- Splat routes with $.tsx catch-all segments",
            "- Layout routes with _layout.tsx (no URL segment)",
            "- Index routes with index in filename",
            "",
            "### Progressive Enhancement",
            "- Forms work without JavaScript (full page reload fallback)",
            "- <Form> component enhances with client-side navigation",
            "- Start with plain HTML, enhance with JavaScript",
            "- Works even if JavaScript fails to load",
            "- Accessibility built into default form handling",
            "- useFetcher() for non-navigating form submissions",
            "- useFetcher() supports optimistic UI patterns",
            "",
            "### Form Handling",
            "- <Form> component for mutations (replaces fetch + state management)",
            "- method='post' triggers action, method='get' triggers loader",
            "- useNavigation() shows pending state during submission",
            "- useActionData() receives validation errors",
            "- intent-based actions with button name/value",
            "- useFetcher() for forms that don't navigate (todos, likes)",
            "- File uploads via enctype='multipart/form-data'",
            "- Built-in request.formData() parsing",
            "",
            "### Error Boundaries",
            "- Export ErrorBoundary component from any route",
            "- Catches errors from loaders, actions, rendering",
            "- Nested error boundaries catch errors at their level",
            "- useRouteError() provides error details",
            "- isRouteErrorResponse() checks for thrown responses",
            "- Root ErrorBoundary catches unhandled errors",
            "- Error boundary replaces only the failing route segment",
            "- Parent routes remain rendered and interactive",
            "",
            "### Defer and Streaming",
            "- defer() from loader returns data with promises",
            "- Await component renders when promise resolves",
            "- Suspense provides fallback while loading",
            "- Critical data loads immediately, slow data defers",
            "- HTML streams to browser as deferred data resolves",
            "- Use for slow API calls, heavy computations",
            "",
            "### Resource Routes",
            "- Routes without a default export component",
            "- Can return JSON, PDFs, images, any response type",
            "- Useful for API endpoints, RSS feeds, sitemaps",
            "- Access via loader (GET) and action (POST/PUT/DELETE)",
            "- Not tied to UI rendering",
            "",
            "### Performance Best Practices",
            "- Prefetch links with <Link prefetch='intent'>",
            "- Cache loader responses with Cache-Control headers",
            "- Use defer() for slow data to stream HTML",
            "- Minimize client JavaScript with server-first approach",
            "- Use nested route parallel loading",
            "- Set proper headers in loader responses",
            "- Use revalidation only when needed",
            "",
            "### Common Operations",
            "Create Remix app:",
            "```bash",
            "npx create-remix@latest myapp",
            "```",
            "",
            "Development server:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build and start:",
            "```bash",
            "npm run build",
            "npm run start",
            "```",
            "",
            "Example loader and component:",
            "```typescript",
            "import { json } from '@remix-run/node';",
            "import { useLoaderData } from '@remix-run/react';",
            "",
            "export async function loader({ params }: LoaderFunctionArgs) {",
            "  const post = await db.post.findUnique({ where: { slug: params.slug } });",
            "  if (!post) throw new Response('Not Found', { status: 404 });",
            "  return json({ post });",
            "}",
            "",
            "export default function Post() {",
            "  const { post } = useLoaderData<typeof loader>();",
            "  return <article><h1>{post.title}</h1><div>{post.content}</div></article>;",
            "}",
            "```",
            "",
            "Example action with form:",
            "```typescript",
            "import { redirect } from '@remix-run/node';",
            "import { Form, useActionData, useNavigation } from '@remix-run/react';",
            "",
            "export async function action({ request }: ActionFunctionArgs) {",
            "  const formData = await request.formData();",
            "  const title = formData.get('title') as string;",
            "  if (!title || title.length < 3) {",
            "    return { error: 'Title must be at least 3 characters' };",
            "  }",
            "  await db.post.create({ data: { title } });",
            "  return redirect('/posts');",
            "}",
            "",
            "export default function NewPost() {",
            "  const actionData = useActionData<typeof action>();",
            "  const navigation = useNavigation();",
            "  const isSubmitting = navigation.state === 'submitting';",
            "  return (",
            "    <Form method='post'>",
            "      <input name='title' />",
            "      {actionData?.error && <p>{actionData.error}</p>}",
            "      <button type='submit' disabled={isSubmitting}>Save</button>",
            "    </Form>",
            "  );",
            "}",
            "```",
            "",
            "Example error boundary:",
            "```typescript",
            "import { useRouteError, isRouteErrorResponse } from '@remix-run/react';",
            "",
            "export function ErrorBoundary() {",
            "  const error = useRouteError();",
            "  if (isRouteErrorResponse(error)) {",
            "    return <div><h1>{error.status} {error.statusText}</h1></div>;",
            "  }",
            "  return <div><h1>Something went wrong</h1></div>;",
            "}",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["remix", "loaders", "actions", "nested_routing", "progressive_enhancement", "form_handling", "error_boundaries", "defer", "resource_routes", "streaming"]

module = CogFrameworkRemix()
