from cog.cog_module import CogModule


class CogCloudAzure(CogModule):
    name = "cog-cloud-azure"
    version = "1.0.0"
    description = "Microsoft Azure cloud platform module covering Azure CLI, App Services, Functions, Storage, Azure SQL, CosmosDB, VMs, AKS, Azure DevOps, Resource Groups, ARM/Bicep templates, Managed Identities, and Key Vault"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Microsoft Azure Cloud Platform",
            "",
            "### Azure CLI Essentials",
            "- Always use `az` CLI commands with `--output table` for readable output or `--output json` for scripting",
            "- Set default subscription: `az account set --subscription <id>` before running resource commands",
            "- Use `az configure --defaults location=eastus group=myRG` to avoid repeating common parameters",
            "- Query with JMESPath: `az vm list --query '[].{Name:name, State:provisioningState}' -o table`",
            "- Use `az group delete --name myRG --yes --no-wait` for cleanup; always include `--no-wait` in scripts",
            "",
            "### App Services (Web Apps)",
            "- Create and deploy: `az webapp up --name myapp --resource-group myRG --runtime PYTHON:3.11`",
            "- Configure app settings: `az webapp config appsettings set --name myapp --resource-group myRG --settings KEY=VAL`",
            "- Enable deployment slots (Standard tier+): `az webapp deployment slot create --name myapp --resource-group myRG --slot staging`",
            "- Swap slots: `az webapp deployment slot swap --name myapp --resource-group myRG --slot staging --target-slot production`",
            "- Stream logs: `az webapp log tail --name myapp --resource-group myRG`",
            "- Configure CORS, auth, and managed identity through App Settings and the Identity blade",
            "",
            "### Azure Functions (Serverless)",
            "- Create function app: `az functionapp create --name myfunc --resource-group myRG --storage-account mystorage --functions-version 4 --runtime python --consumption-plan-location eastus`",
            "- Deploy: `func azure functionapp publish myfunc` from the function project directory",
            "- Trigger types: HttpTrigger, TimerTrigger, QueueTrigger, BlobTrigger, ServiceBusTrigger, EventGridTrigger, CosmosDBTrigger",
            "- Use managed identity for all bindings instead of connection strings when possible",
            "- Local settings: store in `local.settings.json` (never commit); Values section holds app settings",
            "- Durable Functions patterns: Function Chaining, Fan-out/Fan-in, Async HTTP APIs, Monitor, Human Interaction",
            "",
            "### Storage (Blob / Queue / Table)",
            "- Create storage account: `az storage account create --name mystorage --resource-group myRG --location eastus --sku Standard_LRS --kind StorageV2`",
            "- Blob operations: `az storage blob upload/download/list` with `--container-name` and `--name`",
            "- Use SAS tokens for delegated access: `az storage blob generate-sas --permissions racwd --expiry 2025-12-31T23:59:00Z`",
            "- Queue storage for message buffering: `az storage message put --content '{\"task\":\"process\"}' --queue-name myqueue`",
            "- Table storage via CosmosDB Table API is preferred for new projects over legacy Table storage",
            "- Lifecycle management: auto-tier blobs to Cool/Archive after N days using lifecycle policy JSON",
            "",
            "### Azure SQL & CosmosDB",
            "- Azure SQL: `az sql server create --name myserver --resource-group myRG --admin-user admin --admin-password P@ss`",
            "- Create database: `az sql db create --server myserver --name mydb --resource-group myRG --service-objective S0`",
            "- Connection string: use `az sql db show-connection-string --server myserver --name mydb --client ado.net`",
            "- CosmosDB create: `az cosmosdb create --name mycosmos --resource-group myRG --locations regionName=eastus`",
            "- CosmosDB SQL API: `az cosmosdb sql database create --account-name mycosmos --name mydb --resource-group myRG`",
            "- CosmosDB container with partition key: `az cosmosdb sql container create --account-name mycosmos --database-name mydb --name mycontainer --partition-key-path /tenantId`",
            "- Set RU throughput at container or database level; use autoscale for variable workloads",
            "",
            "### Virtual Machines & AKS",
            "- Create VM: `az vm create --name myvm --resource-group myRG --image Ubuntu2204 --size Standard_D2s_v3 --admin-username azureuser --ssh-key-values ~/.ssh/id_rsa.pub`",
            "- Use `--accelerated-networking true` for supported VM sizes to reduce latency",
            "- AKS create: `az aks create --name myaks --resource-group myRG --node-count 3 --node-vm-size Standard_D2s_v3 --enable-managed-identity --generate-ssh-keys`",
            "- Get AKS credentials: `az aks get-credentials --name myaks --resource-group myRG`",
            "- Use `--enable-addons monitoring,azure-policy` for observability and governance",
            "- Scale AKS: `az aks scale --name myaks --resource-group myRG --node-count 5`",
            "",
            "### ARM / Bicep Templates",
            "- Prefer Bicep over ARM JSON: `az bicep install && az bicep build --file main.bicep`",
            "- Deploy: `az deployment group create --resource-group myRG --template-file main.bicep --parameters params.json`",
            "- Use `what-if` before deploying: `az deployment group what-if --resource-group myRG --template-file main.bicep`",
            "- Bicep modules: use `module` keyword for reusable components and pass parameters between them",
            "- Store reusable Bicep modules in a template spec or private registry: `az bicep publish --file storage.bicep --target br:myacr.azurecr.io/bicep/storage:v1`",
            "",
            "### Managed Identities & Key Vault",
            "- Enable system-assigned identity: `az webapp identity assign --name myapp --resource-group myRG`",
            "- Assign user-assigned: `az identity create --name myIdentity --resource-group myRG`",
            "- Grant Key Vault access: `az key vault set-policy --name mykv --object-id <principalId> --secret-permissions get list`",
            "- Create Key Vault: `az keyvault create --name mykv --resource-group myRG --enable-purge-protection true --enable-soft-delete true`",
            "- Store secrets: `az keyvault secret set --vault-name mykv --name DbPassword --value $DB_PASS`",
            "- Reference in App Settings: `@Microsoft.KeyVault(SecretUri=https://mykv.vault.azure.net/secrets/DbPassword/VERSION)`",
            "- Use `az keyvault secret list-deleted` and `az keyvault secret recover` for soft-delete recovery",
            "",
            "### Azure DevOps & Resource Groups",
            "- Resource groups are the fundamental unit of organization; use naming convention: `rg-<project>-<env>-<region>`",
            "- Tag everything: `az resource tag --ids <resourceId> --tags Environment=Production Team=Backend`",
            "- Azure DevOps pipelines use YAML (`azure-pipelines.yml`): stages → jobs → steps → tasks",
            "- Use variable groups linked to Key Vault for secret management in pipelines",
            "- `az pipelines` commands require `azure-devops` extension: `az extension add --name azure-devops`",
            "",
            "### Commands",
            "```bash",
            "az login --use-device-code",
            "az account set --subscription <subscription-id>",
            "az group create --name myRG --location eastus",
            "az deployment group create --resource-group myRG --template-file main.bicep",
            "az webapp up --name myapp --resource-group myRG --runtime PYTHON:3.11",
            "az functionapp create --name myfunc --resource-group myRG --storage-account mystorage --functions-version 4 --runtime python",
            "az aks create --name myaks --resource-group myRG --node-count 3 --enable-managed-identity",
            "az keyvault secret set --vault-name mykv --name SecretName --value $SECRET_VALUE",
            "az monitor metrics list --resource <resourceId> --metric PercentageCPU",
            "az group delete --name myRG --yes --no-wait",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "azure-cli",
            "app-services",
            "azure-functions",
            "blob-storage",
            "queue-storage",
            "table-storage",
            "azure-sql",
            "cosmosdb",
            "virtual-machines",
            "aks",
            "azure-devops",
            "resource-groups",
            "arm-templates",
            "bicep-templates",
            "managed-identities",
            "key-vault",
        ]


module = CogCloudAzure()
