from cog.cog_module import CogModule

class CogLangPhp(CogModule):
    name = "cog-lang-php"
    version = "1.0.0"
    description = "PHP language expertise including Laravel, Symfony, Composer, PSR standards, PHP 8.x features, and modern tooling"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## PHP Language Expertise",
            "",
            "### Modern PHP 8.x Features",
            "- Attributes (annotations): #[Route('/api/users', methods: ['GET'])]",
            "- Named arguments: str_contains(haystack: $str, needle: '@')",
            "- Match expression: match($status) { 200 => 'OK', 404 => 'Not Found', default => 'Unknown' }",
            "- Constructor property promotion: public function __construct(private string $name, private int $age) {}",
            "- Readonly properties: public readonly string $id",
            "- Enums: enum Status: string { case Active = 'active'; case Inactive = 'inactive'; }",
            "- Fibers for cooperative multitasking: new Fiber(function(): void { ... })",
            "- First-class callable syntax: $fn = strlen(...)",
            "- Union types: int|string, array|Collection",
            "- Intersection types: Countable&Iterator (PHP 8.1)",
            "- DNF types: (A&B)|null (PHP 8.2)",
            "- Readonly classes: readonly class DTO { public string $name; }",
            "- Constants in traits (PHP 8.2)",
            "- #[\\\\SensitiveParameter] to hide values in stack traces (PHP 8.2)",
            "",
            "### Type Declarations",
            "- Scalar types: int, float, string, bool",
            "- Compound types: array, object, callable, iterable",
            "- Class/interface types for type-hinting objects",
            "- Nullable: ?string is shorthand for string|null",
            "- Void return type for functions with no return",
            "- Never return type for functions that throw or exit",
            "- Mixed type for accepting any value",
            "- Static return type for late static binding",
            "- Strict types: declare(strict_types=1) at top of file",
            "",
            "### Enums",
            "- Pure enums without backing type",
            "- Backed enums: enum Status: int { case Active = 1; }",
            "- Enum methods: public function label(): string { return match($this) { ... } }",
            "- Enum static methods: from(), tryFrom(), cases()",
            "- Enums can implement interfaces",
            "- Enums cannot extend classes or other enums",
            "- Use enums instead of constant sets for type safety",
            "",
            "### Laravel Framework",
            "- Routing: Route::get('/users', [UserController::class, 'index'])",
            "- Eloquent ORM: User::where('active', true)->with('posts')->get()",
            "- Migrations: php artisan make:migration create_users_table",
            "- Blade templates: @foreach, @if, @auth, @csrf, @yield('content')",
            "- Middleware for auth, rate limiting, CORS",
            "- Validation: $request->validate(['email' => 'required|email|max:255'])",
            "- Form requests: php artisan make:request StoreUserRequest",
            "- Events and listeners for decoupled architecture",
            "- Jobs and queues for async processing (redis/database/sqs driver)",
            "- Laravel Sail for Docker-based local development",
            "- Laravel Nova, Filament, or Backpack for admin panels",
            "- Laravel Horizon for queue monitoring",
            "",
            "### Symfony Framework",
            "- Symfony Flex for skeleton project setup and recipe management",
            "- Controllers as services with dependency injection",
            "- Doctrine ORM integration for database access",
            "- Twig templating engine with template inheritance",
            "- Symfony Messenger for message queues and async processing",
            "- Symfony Security component for authentication/authorization",
            "- Console commands via Symfony Console component",
            "- Form component for building and handling forms",
            "- Serializer for JSON/XML conversion with normalization",
            "- Web Profiler and Debug Toolbar for development",
            "",
            "### Composer and PSR Standards",
            "- composer init, composer require, composer install, composer update",
            "- Autoloading: PSR-4 in composer.json: 'App\\\\': 'src/'",
            "- composer dump-autoload to regenerate autoloader",
            "- PSR-1: Basic coding standard (camelCase methods, StudlyCaps classes)",
            "- PSR-2/PSR-12: Extended coding style guide",
            "- PSR-4: Autoloading standard from file paths",
            "- PSR-7: HTTP message interfaces (Request, Response, ServerRequest)",
            "- PSR-14: Event dispatcher interfaces",
            "- PSR-15: HTTP middleware (RequestHandlerInterface, MiddlewareInterface)",
            "- PSR-18: HTTP client interface",
            "",
            "### PHPUnit Testing",
            "- Test class extends TestCase (PHPUnit\\Framework\\TestCase)",
            "- Assertions: assertEquals, assertTrue, assertInstanceOf, assertCount",
            "- Data providers: #[DataProvider('providerName')] for parameterized tests",
            "- Setup/teardown: setUp(), tearDown(), setUpBeforeClass()",
            "- Mocking: createMock(Repository::class), expects($this->once())",
            "- Test doubles: stubs, mocks, spies via createConfiguredMock",
            "- phpunit.xml for configuration: test suites, coverage, environment",
            "- pestPHP as alternative: test('it does x', function () { expect(true)->toBeTrue(); })",
            "",
            "### Error Handling and Logging",
            "- Exceptions hierarchy: Throwable -> Error and Exception",
            "- Custom exceptions extending Exception or RuntimeException",
            "- try/catch/finally for exception handling",
            "- set_exception_handler for global exception handling",
            "- Monolog for PSR-3 compliant logging (used by Laravel and Symfony)",
            "- Error reporting: error_reporting(E_ALL), display_errors in php.ini",
            "",
            "### PHP-FPM and OPCache",
            "- PHP-FPM process manager for serving PHP applications",
            "- pm = dynamic | static | ondemand for process management",
            "- OPCache: opcache.enable=1, opcache.memory_consumption=256",
            "- opcache.max_accelerated_files for cached scripts",
            "- opcache.validate_timestamps=0 in production for performance",
            "- opcache.preload for loading scripts at startup (PHP 7.4+)",
            "- php-fpm status page for monitoring pool status",
            "",
            "### Code Examples",
            "Laravel controller with Eloquent:",
            "```php",
            "class UserController extends Controller",
            "{",
            "    public function index(Request $request): JsonResponse",
            "    {",
            "        $users = User::query()",
            "            ->when($request->search, fn($q, $search) => $q->where('name', 'like', \"%{$search}%\"))",
            "            ->with('roles')",
            "            ->paginate($request->per_page ?? 15);",
            "",
            "        return response()->json($users);",
            "    }",
            "",
            "    public function store(StoreUserRequest $request): JsonResponse",
            "    {",
            "        $user = User::create($request->validated());",
            "        return response()->json($user, 201);",
            "    }",
            "}",
            "```",
            "",
            "PHP 8.x enum with methods:",
            "```php",
            "enum OrderStatus: string",
            "{",
            "    case Pending = 'pending';",
            "    case Processing = 'processing';",
            "    case Shipped = 'shipped';",
            "    case Delivered = 'delivered';",
            "    case Cancelled = 'cancelled';",
            "",
            "    public function isFinal(): bool",
            "    {",
            "        return match($this) {",
            "            self::Delivered, self::Cancelled => true,",
            "            default => false,",
            "        };",
            "    }",
            "}",
            "```",
            "",
            "Build and run commands:",
            "```bash",
            "composer install --no-dev --optimize-autoloader",
            "php artisan migrate --force",
            "php artisan config:cache && php artisan route:cache",
            "php artisan test --parallel",
            "vendor/bin/phpunit --coverage-html=coverage/",
            "php -S localhost:8000 -t public/",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["php", "laravel", "symfony", "composer", "psr_standards", "php8_features", "enums", "attributes", "phpunit", "php_fpm", "opcache", "eloquent", "blade_templates"]

module = CogLangPhp()
