from cog.cog_module import CogModule


class CogCloudGcp(CogModule):
    name = "cog-cloud-gcp"
    version = "1.0.0"
    description = "Google Cloud Platform module covering gcloud CLI, Cloud Functions, Cloud Run, BigQuery, Cloud Storage, Compute Engine, GKE, Firestore, Pub/Sub, Cloud SQL, IAM, and Terraform integration"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Google Cloud Platform",
            "",
            "### gcloud CLI Essentials",
            "- Authenticate: `gcloud auth login` for interactive, `gcloud auth activate-service-account --key-file key.json` for CI/CD",
            "- Set project: `gcloud config set project my-project` or use `--project` flag on every command",
            "- Default region/zone: `gcloud config set compute/region us-central1 && gcloud config set compute/zone us-central1-a`",
            "- Format output: `gcloud ... --format='table(name,status)'` or `--format=json` for scripting",
            "- Filter results: `gcloud compute instances list --filter='status=RUNNING' --format='table(name,zone)'`",
            "- List everything: `gcloud assets list --project=my-project --asset-types=compute.googleapis.com.Instance`",
            "",
            "### Cloud Functions (Serverless)",
            "- Deploy: `gcloud functions deploy my-func --runtime python311 --trigger-http --entry-point handler --allow-unauthenticated`",
            "- Event-driven triggers: `--trigger-topic=my-topic` (Pub/Sub), `--trigger-bucket=my-bucket` (Storage), `--trigger-event-filters='type=google.cloud.storage.object.v1.finalized'` (Eventarc)",
            "- Set environment variables: `gcloud functions deploy my-func --set-env-vars KEY=VAL,FOO=BAR --runtime python311 --trigger-http`",
            "- 2nd gen functions use Cloud Run infrastructure: `gcloud functions deploy my-func --gen2 --runtime python311 --trigger-http`",
            "- Use Secret Manager for secrets: `gcloud functions deploy my-func --set-secrets='DB_PASS=db-password:latest'`",
            "- View logs: `gcloud functions logs read my-func --limit 50` or use Cloud Logging in console",
            "",
            "### Cloud Run (Containers)",
            "- Deploy from source: `gcloud run deploy my-service --source . --region us-central1 --allow-unauthenticated`",
            "- Deploy from image: `gcloud run deploy my-service --image gcr.io/my-project/my-image:v1 --region us-central1`",
            "- Set concurrency, memory, CPU: `gcloud run deploy my-service --concurrency 100 --memory 1Gi --cpu 2 --min-instances 1 --max-instances 10`",
            "- Enable Cloud SQL connection: `gcloud run deploy my-service --add-cloudsql-instances my-project:us-central1:my-instance`",
            "- Set IAM policy: `gcloud run services add-iam-policy-binding my-service --region us-central1 --member='user:admin@example.com' --role='roles/run.invoker'`",
            "- Revision traffic splitting: `gcloud run services update-traffic my-service --to-revisions my-service-v1=80,my-service-v2=20 --region us-central1`",
            "",
            "### BigQuery",
            "- Query: `bq query --use_legacy_sql=false 'SELECT name, COUNT(*) FROM `project.dataset.table` GROUP BY name'`",
            "- Create dataset: `bq mk --dataset --location=US my-project:my_dataset`",
            "- Load data from GCS: `bq load --source_format=CSV --autodetect my_dataset.my_table gs://my-bucket/data.csv`",
            "- Export to GCS: `bq extract --destination_format=NEWLINE_DELIMITED_JSON my_dataset.my_table gs://my-bucket/export/`",
            "- Schedule queries: `bq query --use_legacy_sql=false --schedule='every 24 hours' 'SELECT ...' --display_name=daily_etl`",
            "- Use partitioning and clustering for cost optimization: partition by date, cluster by frequently filtered columns",
            "- BigQuery ML: `CREATE OR REPLACE MODEL my_dataset.my_model OPTIONS(model_type='linear_reg') AS SELECT ...`",
            "",
            "### Cloud Storage (GCS)",
            "- Create bucket: `gsutil mb -l us-central1 -c STANDARD gs://my-bucket/`",
            "- Upload/download: `gsutil cp localfile.txt gs://my-bucket/path/` and `gsutil cp gs://my-bucket/file.txt ./`",
            "- Sync directories: `gsutil -m rsync -r -d ./local-dir gs://my-bucket/remote-dir/` (use `-m` for parallel)",
            "- Set lifecycle: auto-delete after 90 days with lifecycle JSON config",
            "- Signed URLs: `gsutil signurl -d 1h private.key gs://my-bucket/file.tar.gz`",
            "- Object versioning: `gsutil versioning set on gs://my-bucket`",
            "",
            "### Compute Engine & GKE",
            "- Create VM: `gcloud compute instances create my-vm --machine-type=e2-medium --zone=us-central1-a --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud --boot-disk-size=50GB`",
            "- Startup script: `--metadata=startup-script='#!/bin/bash\napt-get update && apt-get install -y nginx'`",
            "- Create GKE cluster: `gcloud container clusters create my-cluster --num-nodes=3 --machine-type=e2-medium --region=us-central1 --enable-autopilot`",
            "- Get credentials: `gcloud container clusters get-credentials my-cluster --region=us-central1`",
            "- Use Workload Identity for pod-to-GCP-service binding instead of node service accounts",
            "- Enable autoscaling: `gcloud container clusters update my-cluster --enable-autoscaling --min-nodes=1 --max-nodes=10 --region=us-central1`",
            "",
            "### Firestore, Pub/Sub & Cloud SQL",
            "- Firestore in Native mode for real-time sync; Datastore mode for high-write throughput",
            "- Firestore queries require composite indexes for multi-field ordering; check console for auto-suggested indexes",
            "- Pub/Sub topic: `gcloud pubsub topics create my-topic`",
            "- Subscription: `gcloud pubsub subscriptions create my-sub --topic=my-topic --ack-deadline=60 --message-retention-duration=7d`",
            "- Cloud SQL (PostgreSQL): `gcloud sql instances create my-db --database-version=POSTGRES_15 --tier=db-f1-micro --region=us-central1`",
            "- Connect from Cloud Run: use the Cloud SQL Admin proxy built into Cloud Run via `--add-cloudsql-instances`",
            "- Create database: `gcloud sql databases create appdb --instance=my-db`",
            "",
            "### IAM & Terraform Integration",
            "- Service accounts: `gcloud iam service-accounts create my-sa --display-name='My Service Account'`",
            "- Grant roles: `gcloud projects add-iam-policy-binding my-project --member='serviceAccount:my-sa@my-project.iam.gserviceaccount.com' --role='roles/storage.objectViewer'`",
            "- Terraform state in GCS: configure backend block with `bucket`, `prefix`, and use impersonation for CI/CD",
            "- Use `data.google_iam_policy` and `google_project_iam_policy` for authoritative IAM management in Terraform",
            "- Terraform provider: `provider \"google\" { project = \"my-project\" region = \"us-central1\" }`",
            "- Import existing resources: `terraform import google_compute_instance.my_vm projects/my-project/zones/us-central1-a/instances/my-vm`",
            "",
            "### Commands",
            "```bash",
            "gcloud auth login",
            "gcloud config set project my-project",
            "gcloud run deploy my-service --source . --region us-central1 --allow-unauthenticated",
            "gcloud functions deploy my-func --runtime python311 --trigger-http --gen2",
            "gcloud container clusters create my-cluster --num-nodes=3 --region=us-central1",
            "bq query --use_legacy_sql=false 'SELECT * FROM `project.dataset.table` LIMIT 10'",
            "gsutil -m rsync -r ./dist gs://my-bucket/",
            "gcloud sql instances create my-db --database-version=POSTGRES_15 --tier=db-f1-micro --region=us-central1",
            "gcloud pubsub topics create my-topic",
            "terraform plan -out=tfplan && terraform apply tfplan",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "gcloud-cli",
            "cloud-functions",
            "cloud-run",
            "bigquery",
            "cloud-storage",
            "compute-engine",
            "gke",
            "firestore",
            "pubsub",
            "cloud-sql",
            "iam",
            "terraform",
        ]


module = CogCloudGcp()
