from cog.cog_module import CogModule


class CogPackageYarn(CogModule):
    name = "cog-package-yarn"
    version = "1.0.0"
    description = "Yarn package manager module covering Yarn Berry/PnP, workspaces, plugins, constraints, lock files, Zero-Installs, .yarnrc.yml, yarn dlx, and package extensions"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Yarn Berry and Plug'n'Play (PnP)",
            "",
            "Yarn Berry (v2+) replaces the `node_modules` directory with a `.pnp.cjs` file that tells Node.js",
            "where to find packages on disk. Packages are stored in a cache and referenced by the PnP resolver.",
            "",
            "```bash",
            "# Enable Yarn Berry in a project",
            "yarn set version berry",
            "",
            "# Enable PnP (default in Berry)",
            "yarn config set nodeLinker pnp",
            "",
            "# Install dependencies",
            "yarn install",
            "",
            "# Verify PnP resolution",
            "yarn why express",
            "",
            "# Generate node_modules instead (for incompatible tools)",
            "yarn config set nodeLinker node-modules",
            "```",
            "",
            "### PnP architecture",
            "- `.pnp.cjs` maps every package to its location on disk and its dependency list",
            "- Node.js loads `.pnp.cjs` via `--require` (set in `.pnp.cjs` itself or `.yarnrc.yml`)",
            "- No `node_modules` directory means instant installs and no disk waste",
            "- Packages are unplugged (extracted) only when they have postinstall scripts or binaries",
            "- `.yarn/cache/` contains the zipped package archives",
            "- `yarn unplug <pkg>` extracts a package for inspection or patching",
            "",
            "### nodeLinker modes",
            "- `pnp` — Plug'n'Play (default); fastest, strictest",
            "- `node-modules` — traditional `node_modules` directory; compatible with all tools",
            "- `pnpm` — pnpm-style symlink structure; hybrid approach",
            "",
            "## Yarn Workspaces",
            "",
            "```json",
            "{",
            "  \"private\": true,",
            "  \"workspaces\": {",
            "    \"packages\": [\"packages/*\", \"apps/*\"]",
            "  }",
            "}",
            "```",
            "",
            "```bash",
            "# Install all workspace dependencies",
            "yarn install",
            "",
            "# Add dependency to a specific workspace",
            "yarn workspace @scope/utils add zod",
            "",
            "# Run script in a specific workspace",
            "yarn workspace @scope/core build",
            "",
            "# Run script across all workspaces in parallel",
            "yarn workspaces foreach --parallel run build",
            "",
            "# Run in topological order (dependencies first)",
            "yarn workspaces foreach --topological run build",
            "",
            "# Run from the workspace root only",
            "yarn workspaces foreach --no-private run test",
            "```",
            "",
            "### Workspace patterns",
            "- `yarn workspaces foreach` (Berry) replaces `yarn workspaces run` (Classic)",
            "- Use `--from` to filter: `yarn workspaces foreach --from @scope/app --recursive run build`",
            "- Use `--since` to run only on changed workspaces: `yarn workspaces foreach --since run test`",
            "- `--interlace` mixes output from parallel workspaces; default separates by workspace",
            "- Workspace protocol: \"@scope/utils\": \"workspace:*\" for local package references",
            "- Publishing replaces `workspace:*` with the actual version number",
            "",
            "## Yarn Plugins",
            "",
            "Yarn Berry has a minimal core; features are added via plugins.",
            "",
            "```bash",
            "# List installed plugins",
            "yarn plugin list",
            "",
            "# Install a plugin",
            "yarn plugin import workspace-tools",
            "yarn plugin import typescript",
            "yarn plugin import interactive-tools",
            "",
            "# Remove a plugin",
            "yarn plugin remove workspace-tools",
            "```",
            "",
            "### Essential plugins",
            "- `workspace-tools` — adds `yarn workspaces foreach`, `yarn workspaces list`, and `--since` filtering",
            "- `typescript` — auto-generates `.pnp.cjs` type definitions for TypeScript",
            "- `interactive-tools` — `yarn upgrade-interactive` for visual dependency updates",
            "- `stage` — `yarn stage` auto-stages all modified Yarn-related files",
            "- `version` — `yarn version apply` and `yarn version check` for automated versioning",
            "- `exec` — `yarn exec` for running arbitrary commands in the Yarn context",
            "",
            "### Custom plugins",
            "```typescript",
            "// plugins/my-plugin/index.ts",
            "import { Plugin } from '@yarnpkg/core';",
            "",
            "const plugin: Plugin = {",
            "  commands: [{",
            "    name: 'hello',",
            "    async execute() { console.log('Hello from Yarn!'); },",
            "  }],",
            "};",
            "export default plugin;",
            "```",
            "",
            "## Constraints",
            "",
            "Constraints enforce rules across your monorepo using a Prolog-like DSL.",
            "",
            "```yaml",
            "# constraints.pro",
            "",
            "# Enforce that all workspaces use the same React version",
            "gen_enforced_dependencies(ENV, Package, Dependency, Value) :-",
            "  Dependency = \"react\",",
            "  workspace_has_dependency(Package, Dependency, Value, \"dependencies\"),",
            "  workspace_has_dependency(OtherPackage, Dependency, OtherValue, \"dependencies\"),",
            "  Value \\= OtherValue.",
            "",
            "# Require a license field in every workspace",
            "gen_enforced_field(ENV, Package, \"license\") :-",
            "  \\+workspace_field(Package, \"license\", _).",
            "",
            "# Forbid certain packages",
            "gen_invalid_dependency(ENV, _, \"moment\", _) :-",
            "  true.",
            "```",
            "",
            "```bash",
            "# Check constraints",
            "yarn constraints",
            "",
            "# Auto-fix constraint violations",
            "yarn constraints --fix",
            "```",
            "",
            "### Constraint patterns",
            "- `gen_enforced_dependencies` — ensure consistent dependency versions across workspaces",
            "- `gen_enforced_field` — require specific fields in `package.json`",
            "- `gen_invalid_dependency` — forbid specific packages entirely",
            "- `gen_required_dependency` — require specific packages in all workspaces",
            "- Use `--fix` to auto-resolve violations where possible",
            "- Constraints run automatically as part of `yarn install` when configured",
            "",
            "## yarn.lock",
            "",
            "```yaml",
            "# yarn.lock (Berry format)",
            "\"\"",
            "  resolutions:",
            "    \"@scope/utils@workspace:packages/utils\": \"link:packages/utils\"",
            "    \"express@npm:^4.18.2\":",
            "      version: 4.18.2",
            "      resolution: \"express@npm:4.18.2\"",
            "      dependencies:",
            "        body-parser: \"^1.20.1\"",
            "      checksum: sha512-...",
            "      linkType: hard",
            "```",
            "",
            "### Lock file notes",
            "- Berry uses a different lock format than Classic; migration is handled by `yarn import`",
            "- `yarn install --immutable` — CI mode; fails if the lock file would change (equivalent to `--frozen-lockfile`)",
            "- `yarn install --immutable-cache` — fails if packages need to be downloaded",
            "- Always commit `yarn.lock` to version control",
            "- Checksum verification ensures supply chain integrity",
            "",
            "## Zero-Installs",
            "",
            "Zero-Installs commits the `.yarn/cache` directory to git so that `yarn install` is a no-op after checkout.",
            "",
            "```yaml",
            "# .yarnrc.yml",
            "enableGlobalCache: false",
            "```",
            "",
            "```gitignore",
            "# .gitignore for Zero-Installs",
            ".yarn/*",
            "!.yarn/cache",
            "!.yarn/patches",
            "!.yarn/plugins",
            "!.yarn/releases",
            "!.yarn/sdks",
            "!.yarn/versions",
            "```",
            "",
            "### Zero-Install benefits and tradeoffs",
            "- After `git clone`, no install step is needed — dependencies are already in `.yarn/cache`",
            "- Offline by default; CI builds are faster because nothing needs downloading",
            "- `.pnp.cjs` is also committed, so Node.js resolution works immediately",
            "- Trade-off: git repository size increases (zip archives of all packages)",
            "- Best for teams with fast git hosting; avoid for very large dependency trees",
            "- `yarn config set enableGlobalCache false` to use local cache instead of global",
            "",
            "## .yarnrc.yml Configuration",
            "",
            "```yaml",
            "# .yarnrc.yml",
            "yarnPath: .yarn/releases/yarn-4.1.0.cjs",
            "nodeLinker: pnp",
            "enableGlobalCache: true",
            "globalFolder: ~/.yarn/global-cache",
            "",
            "npmRegistries:",
            "  \"https://registry.mycompany.com\":",
            "    npmAuthToken: \"${NPM_TOKEN}\"",
            "",
            "npmScopes:",
            "  mycompany:",
            "    npmRegistryServer: \"https://registry.mycompany.com\"",
            "",
            "packageExtensions:",
            "  \"styled-components@*\":",
            "    peerDependencies:",
            "      react: \"*\"",
            "",
            "pnpEnableEsmLoader: true",
            "pnpStrictMode: true",
            "",
            "supportedArchitectures:",
            "  os: [linux, darwin]",
            "  cpu: [x64, arm64]",
            "```",
            "",
            "### Key .yarnrc.yml settings",
            "- `yarnPath` — pinned Yarn version (from `yarn set version berry`)",
            "- `nodeLinker` — `pnp` | `node-modules` | `pnpm`",
            "- `enableGlobalCache` — `true` = shared cache, `false` = local `.yarn/cache` (Zero-Installs)",
            "- `pnpStrictMode` — throws if a package tries to access undeclared dependencies",
            "- `packageExtensions` — patch missing peer dependencies without forking",
            "- `supportedArchitectures` — install native packages for multiple platforms (Docker)",
            "",
            "## yarn dlx",
            "",
            "```bash",
            "# Run a package without installing it",
            "yarn dlx create-react-app my-app",
            "yarn dlx tsx script.ts",
            "yarn dlx prisma studio",
            "",
            "# Use a specific version",
            "yarn dlx -p typescript@5.3.0 tsc --version",
            "",
            "# Run from a GitHub repo",
            "yarn dlx github:user/repo",
            "```",
            "",
            "### dlx vs npx",
            "- `yarn dlx` is the Berry equivalent of `npx`",
            "- Downloads and runs a package in an isolated environment; does not affect the project",
            "- Use `-p` / `--package` to specify the package: `yarn dlx -p tsx tsx script.ts`",
            "- The package is not added to any `package.json`",
            "- Useful for scaffolding tools, one-off scripts, and generators",
            "",
            "## Package Extensions",
            "",
            "Package extensions patch third-party packages without forking or waiting for upstream fixes.",
            "",
            "```yaml",
            "# .yarnrc.yml",
            "packageExtensions:",
            "  \"some-package@*\":",
            "    peerDependencies:",
            "      react: \"*\"",
            "      react-dom: \"*\"",
            "    dependencies:",
            "      \"missing-dep\": \"^1.0.0\"",
            "  \"broken-lib@^2.0.0\":",
            "    peerDependenciesMeta:",
            "      optional-peer:",
            "        optional: true",
            "```",
            "",
            "### Package extension patterns",
            "- Add missing peer dependencies: pkg@* { peerDependencies: { react: '*' } }",
            "- Add missing regular dependencies: pkg@* { dependencies: { missing: '^1.0.0' } }",
            "- Mark peer dependencies as optional: pkg@* { peerDependenciesMeta: { peer: { optional: true } } }",
            "- Version range targeting: pkg@^2.0.0 applies only to matching versions",
            "- Use `*` to apply to all versions of a package",
            "- Prefer `packageExtensions` over `resolutions` for dependency fixes",
            "",
            "## Resolutions",
            "",
            "```json",
            "{",
            "  \"resolutions\": {",
            "    \"lodash\": \"^4.17.21\",",
            "    \"**/semver\": \"^7.5.0\",",
            "    \"@scope/package/sub-dependency\": \"^2.0.0\"",
            "  }",
            "}",
            "```",
            "",
            "### Resolution patterns",
            "- Override any transitive dependency version regardless of what parent packages request",
            "- lodash: ^4.17.21 — override all instances of lodash",
            "- **/semver — glob pattern for nested occurrences",
            "- @scope/pkg/dep — target a specific package's sub-dependency",
            "- Use sparingly; `packageExtensions` is preferred for peer dependency fixes",
            "- Combine with `yarn dedupe` to ensure a single version is used",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "yarn-berry-pnp",
            "yarn-workspaces",
            "yarn-plugins",
            "yarn-constraints",
            "lock-files",
            "zero-installs",
            "yarnrc-config",
            "yarn-dlx",
            "package-extensions",
        ]


module = CogPackageYarn()
