from cog.cog_module import CogModule


class CogApiRest(CogModule):
    name = "cog-api-rest"
    version = "1.0.0"
    description = "REST API design module covering HTTP methods, status codes, authentication, rate limiting, OpenAPI/Swagger, versioning, HATEOAS, pagination, error handling, CORS, idempotency, and best practices"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## REST API Design",
            "",
            "### HTTP Methods & Semantics",
            "- GET: retrieve resource(s), never modify state, cacheable, safe, idempotent",
            "- POST: create a resource or trigger a process, non-idempotent (multiple calls = multiple resources)",
            "- PUT: full replacement of a resource at a known URI, idempotent — client must send complete representation",
            "- PATCH: partial update of a resource, technically non-idempotent but should be designed to be idempotent",
            "- DELETE: remove a resource, idempotent — deleting same resource twice should return 200/204 then 404",
            "- OPTIONS: describe communication options (used by CORS preflight), return `Allow` header with supported methods",
            "- HEAD: identical to GET but without response body — use for cache validation, existence checks",
            "- Use nouns for resources (`/users`, `/orders`) not verbs (`/getUser`, `/createOrder`)",
            "",
            "### Status Codes",
            "- **200 OK**: successful GET, PUT, PATCH, or DELETE; include updated resource in response body",
            "- **201 Created**: successful POST; include `Location` header pointing to new resource URI",
            "- **204 No Content**: successful DELETE or PUT/PATCH when no response body is returned",
            "- **301 Moved Permanently**: resource relocated; update bookmarks; include new `Location` header",
            "- **304 Not Modified**: cache hit; return empty body with cache headers (ETag, Last-Modified)",
            "- **400 Bad Request**: malformed syntax, invalid JSON, missing required fields — include validation details",
            "- **401 Unauthorized**: missing or invalid authentication token (not 'unauthorized' — that's 403)",
            "- **403 Forbidden**: authenticated but not authorized; user lacks permission for this resource/action",
            "- **404 Not Found**: resource does not exist; distinguish from 403 if hiding existence is a security requirement",
            "- **409 Conflict**: request conflicts with current state (duplicate email, version mismatch, constraint violation)",
            "- **422 Unprocessable Entity**: syntactically correct but semantically invalid (business rule violation)",
            "- **429 Too Many Requests**: rate limit exceeded; include `Retry-After` header with seconds to wait",
            "- **500 Internal Server Error**: unexpected server failure — never expose stack traces in production",
            "- **502/503/504**: gateway/upstream failures; 503 should include `Retry-After` header",
            "",
            "### Authentication & Authorization",
            "- Use OAuth 2.0 + OpenID Connect for user-facing APIs; issue JWT access tokens (short-lived, 15min) + refresh tokens",
            "- API keys for server-to-server: pass in `X-API-Key` header (not query string — avoid logging leakage)",
            "- JWT structure: `Authorization: Bearer <token>` — validate signature, expiry, issuer, audience on every request",
            "- Scope-based authorization: define granular scopes like `orders:read`, `orders:write`, `admin:all`",
            "- Role-based access control (RBAC): map roles to permissions; check both authentication and authorization per endpoint",
            "- Always use HTTPS/TLS; reject plain HTTP requests with 301 redirect or 400 error",
            "- Store password hashes with bcrypt/argon2; never store plaintext passwords or reversible encryption",
            "",
            "### Rate Limiting",
            "- Use sliding window or token bucket algorithm; track per-user, per-IP, or per-API-key",
            "- Return rate limit headers: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (Unix timestamp)",
            "- When rate limited: return 429 with `Retry-After` header and human-readable error message",
            "- Different tiers: free=100req/hr, pro=1000req/hr, enterprise=10000req/hr",
            "- Implement at API gateway level (Kong, AWS API Gateway, Cloudflare) not in application code",
            "- Use Redis for distributed rate limiting: `INCR` + `EXPIRE` or `EVAL` with Lua for atomic operations",
            "- Consider cost-based rate limiting for expensive operations (reports, exports, bulk endpoints)",
            "",
            "### OpenAPI / Swagger Specification",
            "- Define API contract in `openapi.yaml` (v3.1 preferred) with paths, schemas, responses, security schemes",
            "- Use `$ref` to reference shared schemas: `$ref: '#/components/schemas/User'` for DRY spec maintenance",
            "- Document every response code per operation: `200`, `400`, `401`, `404`, `500` with example bodies",
            "- Use `example` and `examples` fields in schemas for documentation and mocking",
            "- Generate server stubs and client SDKs with OpenAPI Generator: `openapi-generator-cli generate -i openapi.yaml -g python-fastapi -o server/`",
            "- Validate requests against spec at runtime using middleware (e.g.,connexion for Python, express-openapi-validate for Node)",
            "- Use `description` on every field, endpoint, and schema for self-documenting APIs",
            "",
            "### API Versioning",
            "- **URL path versioning**: `/v1/users`, `/v2/users` — most common, clearest, easiest to route",
            "- **Header versioning**: `Accept: application/vnd.myapi.v2+json` — cleaner URLs, more complex routing",
            "- **Query parameter**: `?version=2` — simplest but breaks caching, avoid for public APIs",
            "- Maintain backward compatibility within a major version; deprecate fields with `Sunset` header before removal",
            "- Support at most 2 major versions simultaneously; sunset old versions with 6+ months notice",
            "- Version the OpenAPI spec alongside the API; each major version has its own spec file",
            "",
            "### HATEOAS & Pagination",
            "- HATEOAS links in response: `{ \"data\": [...], \"_links\": { \"self\": \"/v1/users?page=2\", \"next\": \"/v1/users?page=3\", \"prev\": \"/v1/users?page=1\" } }`",
            "- Cursor-based pagination for large datasets: `?cursor=abc123&limit=50` — use opaque cursor from last result",
            "- Offset-based pagination for small datasets: `?offset=100&limit=50` — avoid for large offsets (slow with deep paging)",
            "- Include pagination metadata: `{ \"total\": 1053, \"page\": 3, \"per_page\": 50, \"total_pages\": 22 }`",
            "- Use `Link` header for RESTful pagination: `Link: <https://api.example.com/v1/users?page=4>; rel=\"next\"`",
            "",
            "### Error Handling",
            "- Consistent error envelope: `{ \"error\": { \"code\": \"VALIDATION_ERROR\", \"message\": \"Human-readable description\", \"details\": [{ \"field\": \"email\", \"message\": \"Invalid email format\" }] }, \"request_id\": \"req_abc123\" }`",
            "- Use machine-readable error codes (string, not HTTP status number): `USER_NOT_FOUND`, `RATE_LIMITED`, `INVALID_INPUT`",
            "- Include `request_id` (correlation ID) in every error response for distributed tracing",
            "- Log full error details server-side with request_id; return sanitized message to client",
            "- Never expose internal state: stack traces, database queries, file paths, or internal IP addresses",
            "",
            "### CORS & Security Headers",
            "- Configure CORS with explicit origins: `Access-Control-Allow-Origin: https://app.example.com` (not `*` for credentialed requests)",
            "- Required headers for browsers: `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, `Access-Control-Max-Age`",
            "- Security headers: `Strict-Transport-Security`, `X-Content-Type-Options: nosniff`, `X-Frame-Options: DENY`, `Content-Security-Policy`",
            "- Preflight requests: handle OPTIONS method at API gateway; cache with `Access-Control-Max-Age: 86400`",
            "- Use `Vary: Origin` header when serving different CORS headers based on the request origin",
            "",
            "### Idempotency & Best Practices",
            "- POST requests: accept `Idempotency-Key` header to prevent duplicate creation on retry; store key+response for 24h",
            "- Use ETags for optimistic concurrency: `If-Match: \"etag_value\"` on PUT/PATCH returns 412 on conflict",
            "- Use `Prefer: return=representation` header to control whether responses include the full resource",
            "- Content negotiation: support `Accept: application/json` and version via content type when using header versioning",
            "- Keep request/response payloads lean: return only requested fields with sparse fieldsets (`?fields=id,name,email`)",
            "- Enforce request body size limits (e.g., 1MB) to prevent denial-of-service via oversized payloads",
            "",
            "### Commands",
            "```bash",
            "curl -X GET 'https://api.example.com/v1/users' -H 'Authorization: Bearer TOKEN'",
            "curl -X POST 'https://api.example.com/v1/users' -H 'Content-Type: application/json' -H 'Idempotency-Key: uuid-here' -d '{\"name\": \"Alice\"}'",
            "curl -X PUT 'https://api.example.com/v1/users/42' -H 'If-Match: \"etag123\"' -H 'Content-Type: application/json' -d '{\"name\": \"Alice Updated\"}'",
            "curl -X PATCH 'https://api.example.com/v1/users/42' -H 'Content-Type: application/json' -d '{\"email\": \"new@example.com\"}'",
            "curl -X DELETE 'https://api.example.com/v1/users/42'",
            "openapi-generator-cli generate -i openapi.yaml -g python-fastapi -o server/",
            "redoc-cli bundle openapi.yaml -o api-docs.html",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "http-methods",
            "status-codes",
            "authentication",
            "authorization",
            "rate-limiting",
            "openapi",
            "swagger",
            "api-versioning",
            "hateoas",
            "pagination",
            "error-handling",
            "cors",
            "idempotency",
            "best-practices",
        ]


module = CogApiRest()
