from cog.cog_module import CogModule

class CogFrameworkNextjs(CogModule):
    name = "cog-framework-nextjs"
    version = "1.0.0"
    description = "Next.js framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Next.js Framework Expertise",
            "",
            "### App Router Architecture",
            "- File-system based routing under app/ directory",
            "- layout.tsx defines shared UI that wraps nested routes",
            "- page.tsx defines the unique UI for a route",
            "- loading.tsx provides instant loading states (React Suspense)",
            "- error.tsx catches unexpected errors in route segments",
            "- not-found.tsx handles 404 cases for route segments",
            "- template.tsx re-renders on navigation (unlike layout)",
            "- default.tsx fallback UI for parallel routes",
            "- Route groups with (folder) parentheses for organization",
            "- Parallel routes with @folder interception",
            "- Intercepting routes with (..)folder syntax",
            "",
            "### Server Components vs Client Components",
            "- All components are Server Components by default (App Router)",
            "- Server Components render on the server, send HTML to client",
            "- Use 'use client' directive for client-side interactivity",
            "- Server Components: data fetching, backend access, large deps",
            "- Client Components: event handlers, useState/useEffect, browser APIs",
            "- Server Components cannot use hooks or event handlers",
            "- Client Components cannot directly call server-side functions",
            "- Pass Server Component as children props to Client Components",
            "- Minimize client component boundary for performance",
            "",
            "### Data Fetching Patterns",
            "- fetch() is extended with caching and revalidation in Next.js",
            "- cache: 'force-cache' — cache indefinitely (default for GET)",
            "- cache: 'no-store' — always fetch fresh data",
            "- next: { revalidate: 60 } — revalidate every 60 seconds (ISR)",
            "- next: { tags: ['products'] } — on-demand revalidation by tag",
            "- revalidatePath('/path') — purge cache for a path",
            "- revalidateTag('products') — purge cache for a tag",
            "- Parallel data fetching: await Promise.all([fetchA, fetchB])",
            "- Sequential data fetching when one depends on another",
            "- Server Actions for mutations (async functions with 'use server')",
            "- use() hook to suspend on promises in components",
            "",
            "### Rendering Strategies",
            "- Static Site Generation (SSG) — built at build time",
            "- Server-Side Rendering (SSR) — rendered per request",
            "- Incremental Static Regeneration (ISR) — static with periodic updates",
            "- Client-Side Rendering (CSR) — rendered in browser",
            "- Streaming SSR — progressive rendering with Suspense",
            "- Dynamic rendering based on cookies(), headers(), searchParams",
            "- generateStaticParams for static paths at build time",
            "- dynamic = 'force-dynamic' | 'force-static' | 'error'",
            "",
            "### API Routes and Route Handlers",
            "- Pages Router: pages/api/ files export handler functions",
            "- App Router: app/api/route.ts exports GET, POST, PUT, DELETE",
            "- Route Handlers accept Web Request/Response API",
            "- Edge Runtime support for API routes",
            "- Middleware can intercept and rewrite API requests",
            "",
            "### Middleware",
            "- Runs before a request completes (Edge runtime)",
            "- Defined in middleware.ts at project root",
            "- Chainable with matcher config for route filtering",
            "- Use for auth redirects, A/B testing, geolocation, i18n",
            "- Can modify response headers and rewrite destinations",
            "- Cannot access Node.js APIs (Edge runtime limitations)",
            "",
            "### Image Optimization",
            "- next/image component with automatic optimization",
            "- Automatic WebP/AVIF format selection",
            "- Responsive srcset generation",
            "- Lazy loading by default (above-fold with priority prop)",
            "- Blur placeholder for loading states",
            "- Remote images need domain allowlisting in next.config.js",
            "- Custom loader prop for third-party image CDNs",
            "",
            "### Layout System",
            "- Root layout (app/layout.tsx) is required, wraps all pages",
            "- Nested layouts persist across route navigations",
            "- Layouts receive children prop for nested content",
            "- State is preserved in layouts when navigating between pages",
            "- Multiple root layouts possible via route groups",
            "",
            "### Performance Best Practices",
            "- Use Server Components to reduce client JavaScript",
            "- Implement Suspense boundaries for streaming",
            "- Optimize images with next/image",
            "- Use dynamic imports for heavy client components",
            "- Leverage ISR instead of full SSR where possible",
            "- Minimize 'use client' boundaries",
            "- Use next/font for zero-layout-shift font loading",
            "- Use next/link for prefetching and client navigation",
            "- Configure route segment config for caching strategy",
            "",
            "### Common Operations",
            "Create Next.js app:",
            "```bash",
            "npx create-next-app@latest myapp --typescript --tailwind --app",
            "```",
            "",
            "Development server:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build and start:",
            "```bash",
            "npm run build",
            "npm run start",
            "```",
            "",
            "Example server action:",
            "```typescript",
            "'use server'",
            "import { revalidatePath } from 'next/cache';",
            "",
            "export async function createPost(formData: FormData) {",
            "  const title = formData.get('title') as string;",
            "  await db.post.create({ data: { title } });",
            "  revalidatePath('/posts');",
            "}",
            "```",
            "",
            "Example route handler:",
            "```typescript",
            "import { NextResponse } from 'next/server';",
            "",
            "export async function GET(request: Request) {",
            "  const data = await fetch('https://api.example.com/data');",
            "  const json = await data.json();",
            "  return NextResponse.json(json);",
            "}",
            "```",
            "",
            "Example middleware:",
            "```typescript",
            "import { NextResponse } from 'next/server';",
            "import type { NextRequest } from 'next/server';",
            "",
            "export function middleware(request: NextRequest) {",
            "  const token = request.cookies.get('token');",
            "  if (!token) {",
            "    return NextResponse.redirect(new URL('/login', request.url));",
            "  }",
            "  return NextResponse.next();",
            "}",
            "",
            "export const config = {",
            "  matcher: ['/dashboard/:path*', '/admin/:path*']",
            "};",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["nextjs", "app_router", "pages_router", "ssr", "ssg", "isr", "api_routes", "middleware", "server_components", "client_components", "image_optimization", "server_actions", "streaming"]

module = CogFrameworkNextjs()
