from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class GCloudTool(Tool):
    name = "gcp.gcloud"
    description = "Execute Google Cloud SDK commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"gcloud {command}", timeout=120)
        return result

class GCloudStorageTool(Tool):
    name = "gcp.storage"
    description = "Manage Google Cloud Storage"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"gsutil {action}")
        return result

class GCloudComputeTool(Tool):
    name = "gcp.compute"
    description = "Manage Google Cloud Compute Engine"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"gcloud compute {action}")
        return result

class CogCloudGcp(CogModule):
    name = "cog-cloud-gcp"
    version = "1.0.0"
    description = "Google Cloud Platform expertise"

    def register_tools(self) -> list[Tool]:
        return [GCloudTool(), GCloudStorageTool(), GCloudComputeTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Google Cloud Platform (GCP) Expertise",
            "",
            "### Core GCP Services",
            "",
            "Compute:",
            "- Compute Engine (VMs)",
            "- Google Kubernetes Engine (GKE)",
            "- Cloud Run (serverless containers)",
            "- App Engine (PaaS)",
            "- Cloud Functions (serverless functions)",
            "- Batch (batch jobs)",
            "",
            "Storage:",
            "- Cloud Storage",
            "- Persistent Disks",
            "- Local SSDs",
            "- Filestore",
            "- Cloud Storage for Firebase",
            "",
            "Databases:",
            "- Cloud SQL (MySQL, PostgreSQL)",
            "- Cloud Spanner (global DB)",
            "- Cloud Firestore (NoSQL)",
            "- Firebase Realtime Database",
            "- Bigtable (NoSQL)",
            "- Memorystore (Redis)",
            "",
            "Networking:",
            "- Virtual Private Cloud (VPC)",
            "- Cloud Load Balancing",
            "- Cloud CDN",
            "- Cloud Armor (DDoS protection)",
            "- Cloud DNS",
            "- Cloud NAT",
            "- Cloud Router",
            "- Interconnect",
            "- Partner Interconnect",
            "",
            "### GCP Commands",
            "",
            "Authentication:",
            "- gcloud auth login",
            "- gcloud auth list",
            "- gcloud config set project PROJECT_ID",
            "- gcloud config set compute/region REGION",
            "- gcloud config set compute/zone ZONE",
            "",
            "Projects:",
            "- gcloud projects list",
            "- gcloud projects create PROJECT_ID",
            "- gcloud projects describe PROJECT_ID",
            "",
            "Compute Engine:",
            "- gcloud compute instances create",
            "- gcloud compute instances list",
            "- gcloud compute instances stop",
            "- gcloud compute instances start",
            "- gcloud compute instances delete",
            "- gcloud compute ssh INSTANCE_NAME",
            "- gcloud compute instances describe",
            "",
            "GKE:",
            "- gcloud container clusters create",
            "- gcloud container clusters list",
            "- gcloud container clusters get-credentials",
            "- gcloud container clusters resize",
            "- gcloud container clusters upgrade",
            "",
            "Cloud Run:",
            "- gcloud run deploy",
            "- gcloud run services list",
            "- gcloud run describe SERVICE",
            "",
            "App Engine:",
            "- gcloud app deploy",
            "- gcloud app browse",
            "- gcloud app logs read",
            "",
            "Cloud Functions:",
            "- gcloud functions deploy",
            "- gcloud functions list",
            "- gcloud functions describe",
            "",
            "Cloud Storage:",
            "- gsutil mb gs://BUCKET_NAME",
            "- gsutil ls",
            "- gsutil cp",
            "- gsutil rsync",
            "- gsutil rm",
            "",
            "Cloud SQL:",
            "- gcloud sql instances create",
            "- gcloud sql instances list",
            "- gcloud sql instances describe",
            "- gcloud sql databases create",
            "- gcloud sql users create",
            "",
            "BigQuery:",
            "- bq query",
            "- bq mk",
            "- bq load",
            "- bq extract",
            "",
            "### GCP vs AWS vs Azure",
            "",
            "GCP advantages:",
            "- Kubernetes (created it)",
            "- Big data/analytics",
            "- AI/ML (TensorFlow)",
            "- Live migration",
            "- Custom machine types",
            "- Per-second billing",
            "- Sustained use discounts",
            "- Google network",
            "",
            "AWS advantages:",
            "- Largest market share",
            "- Most services",
            "- Mature ecosystem",
            "- More regions",
            "",
            "Azure advantages:",
            "- Windows integration",
            "- Enterprise agreements",
            "- Hybrid cloud",
            "- Office 365 integration",
            "",
            "When to use GCP:",
            "- Kubernetes workloads",
            "- Big data/analytics",
            "- ML/AI workloads",
            "- Google ecosystem",
            "- Need live migration",
            "- Custom machine types",
            "",
            "### Key GCP Concepts",
            "",
            "Resource hierarchy:",
            "- Organization",
            "- Folders",
            "- Projects",
            "- Resources",
            "",
            "Regions and zones:",
            "- Regions (geographic areas)",
            "- Zones (failure domains)",
            "- Regional resources",
            "- Zonal resources",
            "",
            "IAM:",
            "- Members (users, groups, service accounts)",
            "- Roles (permissions)",
            "- Policies (bindings)",
            "- Primitive roles (Owner, Editor, Viewer)",
            "- Predefined roles",
            "- Custom roles",
            "",
            "### Compute Engine",
            "",
            "VM types:",
            "- E2 (general purpose)",
            "- N2 (general purpose)",
            "- N2D (AMD)",
            "- T2A (ARM)",
            "- C2 (compute-optimized)",
            "- M1/M2 (memory-optimized)",
            "- A2 (accelerator-optimized)",
            "",
            "Machine types:",
            "- Standard",
            "- E2-custom (custom vCPU/memory)",
            "- Preemptible (spot)",
            "",
            "VM features:",
            "- Live migration",
            "- Scheduling (maintenance)",
            "- Block project-wide SSH keys",
            "- Shielded VM",
            "- Confidential VM",
            "",
            "Storage options:",
            "- Persistent disks (standard, balanced)",
            "- Local SSDs (NVMe)",
            "- Image storage",
            "- Snapshots",
            "",
            "### Google Kubernetes Engine",
            "",
            "GKE features:",
            "- Managed Kubernetes",
            "- Autopilot (serverless)",
            "- Auto-scaling (HPA, VPA)",
            "- Auto-provisioning",
            "- Node auto-repair",
            "- Node auto-upgrade",
            "- Binary authorization",
            "- Private clusters",
            "- Network policies",
            "",
            "GKE modes:",
            "- Standard (you manage nodes)",
            "- Autopilot (Google manages nodes)",
            "",
            "Node pools:",
            "- Default pool",
            "- Spot VMs",
            "- Preemptible VMs",
            "- Node auto-provisioning",
            "",
            "GKE commands:",
            "- gcloud container clusters create CLUSTER --num-nodes 3",
            "- gcloud container clusters get-credentials CLUSTER",
            "- kubectl get nodes",
            "",
            "### Cloud Run",
            "",
            "Cloud Run features:",
            "- Container-based serverless",
            "- Automatic scaling",
            "- Scale to zero",
            "- HTTP/2",
            "- Traffic splitting",
            "- Revision management",
            "- min/max instances",
            "- Concurrency",
            "",
            "Cloud Run services:",
            "- Fully managed (Google Cloud)",
            "- Cloud Run for Anthos (GKE/On-prem)",
            "",
            "Cloud Run vs Cloud Functions:",
            "- Cloud Run: containers, HTTP, stateless",
            "- Cloud Functions: functions, events, lightweight",
            "",
            "### App Engine",
            "",
            "App Engine environments:",
            "- Standard (run by Google)",
            "- Flexible (compute engine VMs)",
            "",
            "App Engine Standard:",
            "- Python 3.9+",
            "- Node.js 14+",
            "- Java 11+",
            "- Go 1.12+",
            "- PHP 7.4+",
            "- Ruby 2.7+",
            "- Scales automatically",
            "- Versions and services",
            "",
            "App Engine Flexible:",
            "- Runtime customization",
            "- Dockerfile support",
            "- Local SSD",
            "- Scalable VMs",
            "",
            "### Cloud Functions",
            "",
            "Cloud Functions triggers:",
            "- HTTP triggers",
            "- Cloud Storage triggers",
            "- Pub/Sub triggers",
            "- Cloud Firestore triggers",
            "- Firebase triggers",
            "- Audit log triggers",
            "",
            "Cloud Functions runtime:",
            "- Node.js 10/12/14/16",
            "- Python 3.8/3.9",
            "- Go 1.13+",
            "- Java 11+",
            "- .NET Core 3.1+",
            "- Ruby 2.7+",
            "",
            "Cloud Functions vs Cloud Run:",
            "- Cloud Functions: functions, events, lightweight",
            "- Cloud Run: containers, HTTP, stateless",
            "",
            "### Cloud Storage",
            "",
            "Storage classes:",
            "- Standard (frequent access)",
            "- Nearline (30-day minimum)",
            "- Coldline (90-day minimum)",
            "- Archive (180-day minimum)",
            "",
            "Storage types:",
            "- Multi-regional (high availability)",
            "- Regional (low cost)",
            "- Dual-region (business continuity)",
            "",
            "Bucket features:",
            "- Object versioning",
            "- Retention policies",
            "- Object lifecycle management",
            "- Bucket policies (IAM)",
            "- ACLs (legacy)",
            "- Public access prevention",
            "",
            "### Cloud SQL",
            "",
            "Cloud SQL databases:",
            "- MySQL 5.7, 8.0",
            "- PostgreSQL 12, 13, 14",
            "- SQL Server 2017, 2019",
            "",
            "Cloud SQL features:",
            "- Automated backups",
            "- Point-in-time recovery",
            "- High availability (regional)",
            "- Read replicas",
            "- Cross-region replication",
            "- Automated storage increases",
            "- Private IP",
            "- SQL Server (Windows)",
            "- Automatic failover",
            "",
            "Cloud SQL pricing:",
            "- Per-use pricing",
            "- License included (SQL Server)",
            "",
            "### Firestore",
            "",
            "Firestore features:",
            "- NoSQL document database",
            "- Real-time updates",
            "- Offline support",
            "- Automatic scaling",
            "- Strong consistency",
            "- Mobile and web SDKs",
            "- Client SDKs",
            "",
            "Firestore vs Realtime Database:",
            "- Firestore: richer queries, indexes",
            "- Realtime DB: real-time sync, lower latency",
            "",
            "### BigQuery",
            "",
            "BigQuery features:",
            "- Serverless data warehouse",
            "- Petabyte scale",
            "- SQL queries",
            "- Auto-scaling",
            "- Partitioning",
            "- Clustering",
            "- BI Engine",
            "- Machine learning (BigQuery ML)",
            "- Geospatial",
            "",
            "BigQuery tables:",
            "- Native tables (BigQuery storage)",
            "- External tables (Cloud Storage, Bigtable)",
            "- Views (virtual tables)",
            "- Partitioned tables",
            "- Clustered tables",
            "",
            "### Bigtable",
            "",
            "Bigtable use cases:",
            "- Time series",
            "- IoT",
            "- High-throughput",
            "- Low latency",
            "- Key-value store",
            "- Graph databases",
            "",
            "Bigtable features:",
            "- Wide-column NoSQL",
            "- High throughput",
            "- Low latency",
            "- HBase API",
            "- Replication",
            "- Managed instances",
            "",
            "### GCP Networking",
            "",
            "VPC:",
            "- Global VPC",
            "- Subnets (regional)",
            "- VPC peering",
            "- Shared VPC",
            "- Private Service Connect",
            "",
            "Load balancing:",
            "- Global load balancing",
            "- HTTP(S) load balancing (global)",
            "- SSL proxy load balancing",
            "- TCP proxy load balancing",
            "- Network load balancing (regional)",
            "- Internal load balancing",
            "- Cross-region load balancing",
            "- Content-based load balancing",
            "",
            "Cloud CDN:",
            "- Global edge locations",
            "- Cache static content",
            "- Custom origins",
            "- Edge security (Cloud Armor)",
            "",
            "Cloud DNS:",
            "- Managed DNS",
            "- DNSSEC",
            "- Private zones",
            "- Forwarding zones",
            "- Peering zones",
            "",
            "Cloud NAT:",
            "- Private instances",
            "- No public IP",
            "- Internet egress",
            "- Private Google access",
            "",
            "### Cloud Deployment Manager",
            "",
            "Deployment Manager:",
            "- Infrastructure as code",
            "- YAML or Jinja2 templates",
            "- Declarative",
            "- Preview and deploy",
            "- Updates",
            "- Imports",
            "",
            "Terraform vs Deployment Manager:",
            "- Terraform: multi-cloud, more providers",
            "- Deployment Manager: GCP native, simpler",
            "",
            "### Quick Reference",
            "",
            "Create VM:",
            "- gcloud compute instances create my-vm --zone=us-central1-a --machine-type=e2-medium",
            "",
            "SSH into VM:",
            "- gcloud compute ssh my-vm --zone=us-central1-a",
            "",
            "Create GKE cluster:",
            "- gcloud container clusters create my-cluster --num-nodes=3 --zone=us-central1-a",
            "",
            "Get GKE credentials:",
            "- gcloud container clusters get-credentials my-cluster --zone=us-central1-a",
            "",
            "Deploy to Cloud Run:",
            "- gcloud run deploy my-service --image=gcr.io/PROJECT_ID/my-service --platform=managed",
            "",
            "Create storage bucket:",
            "- gsutil mb gs://my-unique-bucket-name",
            "",
            "Upload to Cloud Storage:",
            "- gsutil cp myfile.txt gs://my-bucket/myfile.txt",
            "",
            "Create Cloud SQL instance:",
            "- gcloud sql instances create my-instance --tier=db-f1-micro --region=us-central1",
            "",
            "Create Cloud SQL database:",
            "- gcloud sql databases create mydb --instance=my-instance",
            "",
            "Create Cloud Function:",
            "- gcloud functions deploy my-function --runtime=nodejs14 --trigger-http --allow-unauthenticated",
            "",
            "Create App Engine app:",
            "- gcloud app deploy",
            "",
            "Create BigQuery dataset:",
            "- bq mk my_dataset",
            "",
            "Query BigQuery:",
            "- bq query \"SELECT * FROM dataset.table LIMIT 10\"",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "gcp",
            "google_cloud",
            "cloud_platform",
            "compute_engine",
            "gke",
            "kubernetes",
            "cloud_run",
            "app_engine",
            "cloud_functions",
            "cloud_storage",
            "cloud_sql",
            "bigquery",
            "firestore",
            "bigtable",
            "vpc",
            "load_balancing",
            "cdn",
            "serverless",
            "big_data",
            "machine_learning"
        ]

module = CogCloudGcp()
