from cog.cog_module import CogModule

class CogLangJava(CogModule):
    name = "cog-lang-java"
    version = "1.0.0"
    description = "Java language expertise including Spring Boot, streams, records, sealed classes, virtual threads, Maven/Gradle, JUnit 5, and concurrency"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Java Language Expertise",
            "",
            "### Modern Java Features (11–21+)",
            "- var for local variable type inference (Java 10+)",
            "- Text blocks with triple quotes: String sql = '''SELECT * FROM users'''",
            "- Switch expressions: String result = switch (day) { case MON, FRI -> 'work'; default -> 'off'; }",
            "- Pattern matching for instanceof: if (obj instanceof String s) { s.length(); }",
            "- Records for immutable data carriers: record Point(int x, int y) {}",
            "- Sealed classes: sealed interface Shape permits Circle, Rect {}",
            "- Virtual threads (Java 21): Thread.ofVirtual().start(() -> task())",
            "- Sequenced collections: SequencedCollection, SequencedMap, SequencedSet",
            "- String templates (preview): STR.'Hello \\{name}'",
            "",
            "### Records",
            "- Automatically generates: constructor, getters, equals(), hashCode(), toString()",
            "- Immutable by default — all fields are final",
            "- Can implement interfaces, define methods, define static members",
            "- Compact constructor for validation: public Point { if (x < 0) throw ... }",
            "- Use for DTOs, value objects, configuration objects",
            "- Cannot extend classes or be extended (implicitly final)",
            "- Local records inside methods for ad-hoc data groupings",
            "",
            "### Sealed Classes and Interfaces",
            "- sealed permits only specified subclasses",
            "- All permitted subclasses must be in the same package or module",
            "- Permitted subclasses: final, sealed, or non-sealed",
            "- Enables exhaustive pattern matching in switch",
            "- Combine with records for algebraic data types",
            "- Example: sealed interface JsonValue permits JsonString, JsonNumber, JsonObject, JsonArray",
            "",
            "### Pattern Matching (Java 21+)",
            "- Type patterns in switch: case String s -> s.length()",
            "- Record patterns: case Point(int x, int y) -> x + y",
            "- Guarded patterns: case String s when s.length() > 5 -> ...",
            "- Exhaustiveness checked by compiler for sealed hierarchies",
            "- Parenthesized patterns for grouping complex conditions",
            "",
            "### Streams API",
            "- Stream sources: collection.stream(), Arrays.stream(), Stream.of(), Stream.generate()",
            "- Intermediate ops: filter, map, flatMap, distinct, sorted, peek, limit, skip",
            "- Terminal ops: collect, forEach, reduce, count, min, max, findFirst, findAny, anyMatch",
            "- Collectors: toList(), toSet(), toMap(), groupingBy(), partitioningBy(), joining()",
            "- Primitive streams: IntStream, LongStream, DoubleStream for numeric operations",
            "- Parallel streams: .parallel() for fork-join parallelism",
            "- FlatMap for one-to-many transformations: stream.flatMap(List::stream)",
            "- Collectors.toUnmodifiableList() for immutable results",
            "",
            "### Optional",
            "- Optional<T> as a container for nullable values",
            "- Creation: Optional.of(value), Optional.ofNullable(maybeNull), Optional.empty()",
            "- Transformation: map, flatMap, filter",
            "- Consumption: ifPresent, ifPresentOrElse",
            "- Default: orElse, orElseGet, orElseThrow",
            "- Never use Optional as a field or method parameter — return type only",
            "- Optional.stream() for integration with Stream API",
            "",
            "### Spring Boot",
            "- @SpringBootApplication: @Configuration + @EnableAutoConfiguration + @ComponentScan",
            "- @RestController + @GetMapping/@PostMapping for REST endpoints",
            "- @Service, @Repository, @Component for stereotype components",
            "- @Autowired or constructor injection (prefer constructor injection)",
            "- application.yml / application.properties for configuration",
            "- Profile-specific config: application-{profile}.yml",
            "- @Value for property injection, @ConfigurationProperties for grouped properties",
            "- Spring Data JPA: extend JpaRepository<T, ID>",
            "- @Transactional for declarative transaction management",
            "- Spring Security for authentication and authorization",
            "- Actuator: /actuator/health, /actuator/metrics, /actuator/info",
            "- @ExceptionHandler + @ControllerAdvice for global error handling",
            "- WebClient for non-blocking HTTP client",
            "",
            "### Maven and Gradle",
            "- Maven: pom.xml with groupId, artifactId, version (GAV coordinates)",
            "- Maven lifecycle: validate, compile, test, package, verify, install, deploy",
            "- Maven profiles for environment-specific builds",
            "- Gradle: build.gradle with Groovy or Kotlin DSL",
            "- Gradle tasks: build, test, bootRun, bootJar",
            "- Dependency management: BOM for Spring Boot versions",
            "- Both support multi-module project structures",
            "",
            "### JUnit 5",
            "- @Test for test methods, @DisplayName for readable names",
            "- Assertions: assertEquals, assertTrue, assertThrows, assertAll",
            "- Lifecycle: @BeforeEach, @AfterEach, @BeforeAll, @AfterAll",
            "- @ParameterizedTest with @ValueSource, @CsvSource, @MethodSource",
            "- @Nested for grouped test classes within a test class",
            "- @Tag for filtering test suites",
            "- Assumptions: assumeTrue() for conditional test execution",
            "- Extensions model: @ExtendWith for custom behavior",
            "",
            "### Concurrency Utilities",
            "- java.util.concurrent: ExecutorService, Future, CompletableFuture",
            "- CompletableFuture: supplyAsync, thenApply, thenCompose, thenCombine, allOf",
            "- Virtual threads (Java 21): lightweight threads managed by JVM, not OS",
            "- Executors.newVirtualThreadPerTaskExecutor() for virtual thread pool",
            "- ReentrantLock, ReadWriteLock for fine-grained locking",
            "- CountDownLatch, CyclicBarrier, Semaphore for coordination",
            "- ConcurrentHashMap for thread-safe maps",
            "- Atomic types: AtomicInteger, AtomicReference for lock-free updates",
            "- VarHandle for low-level atomic operations",
            "",
            "### JVM Tuning and Garbage Collectors",
            "- Serial GC: -XX:+UseSerialGC (small heaps, simple apps)",
            "- Parallel GC: -XX:+UseParallelGC (throughput-oriented)",
            "- G1 GC: -XX:+UseG1GC (default since Java 9, balanced)",
            "- ZGC: -XX:+UseZGC (low latency, sub-millisecond pauses)",
            "- Shenandoah: -XX:+UseShenandoahGC (low latency alternative)",
            "- Heap sizing: -Xms (initial), -Xmx (maximum)",
            "- GC logging: -Xlog:gc* for diagnostics",
            "- JVM metadata: -XX:MaxMetaspaceSize for class metadata",
            "- JFR (Java Flight Recorder) for production profiling",
            "",
            "### Generics",
            "- Type parameters: <T>, <T extends Comparable<T>>",
            "- Bounded type parameters: <T extends Number>",
            "- Wildcards: <?>, <? extends Number> (covariant), <? super Integer> (contravariant)",
            "- PECS: Producer Extends, Consumer Super",
            "- Type erasure: generics are compile-time only",
            "- Bridge methods generated by compiler for covariant return types",
            "",
            "### JPMS (Java Platform Module System)",
            "- module-info.java: module com.app { requires java.sql; exports com.app.api; }",
            "- 'requires' for dependencies, 'exports' for public API packages",
            "- 'opens' for reflection access (needed by Spring, Hibernate)",
            "- Automatic modules: plain JARs on module path get auto module name",
            "- Unnamed module: classpath-based code behaves as single module",
            "",
            "### Code Examples",
            "Spring Boot REST controller:",
            "```java",
            "@RestController",
            "@RequestMapping('/api/users')",
            "public class UserController {",
            "",
            "    private final UserRepository repo;",
            "",
            "    public UserController(UserRepository repo) {",
            "        this.repo = repo;",
            "    }",
            "",
            "    @GetMapping",
            "    public List<User> list() {",
            "        return repo.findAll();",
            "    }",
            "",
            "    @GetMapping('/{id}')",
            "    public ResponseEntity<User> get(@PathVariable Long id) {",
            "        return repo.findById(id)",
            "            .map(ResponseEntity::ok)",
            "            .orElse(ResponseEntity.notFound().build());",
            "    }",
            "",
            "    @PostMapping",
            "    @ResponseStatus(HttpStatus.CREATED)",
            "    public User create(@Valid @RequestBody CreateUserRequest req) {",
            "        return repo.save(new User(req.name(), req.email()));",
            "    }",
            "}",
            "```",
            "",
            "Sealed hierarchy with pattern matching:",
            "```java",
            "sealed interface Shape permits Circle, Rectangle, Triangle {",
            "    double area();",
            "}",
            "",
            "record Circle(double radius) implements Shape {",
            "    public double area() { return Math.PI * radius * radius; }",
            "}",
            "",
            "record Rectangle(double width, double height) implements Shape {",
            "    public double area() { return width * height; }",
            "}",
            "",
            "record Triangle(double base, double height) implements Shape {",
            "    public double area() { return 0.5 * base * height; }",
            "}",
            "```",
            "",
            "Build and run commands:",
            "```bash",
            "mvn clean package -DskipTests",
            "mvn spring-boot:run",
            "gradle bootRun",
            "gradle build && java -jar build/libs/app.jar",
            "java -XX:+UseZGC -Xmx512m -jar app.jar",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["java", "spring_boot", "streams", "optional", "records", "sealed_classes", "pattern_matching", "virtual_threads", "maven", "gradle", "junit5", "jvm_tuning", "generics", "concurrency", "jpms"]

module = CogLangJava()
