from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class PhpTool(Tool):
    name = "php.execute"
    description = "Execute PHP scripts"
    required_permissions = ["shell.execute"]

    def execute(self, script: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"php {script}")
        return result

class ComposerTool(Tool):
    name = "php.composer"
    description = "Execute Composer commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"composer {command}", timeout=300)
        return result

class LaravelTool(Tool):
    name = "php.laravel"
    description = "Execute Laravel artisan commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"php artisan {command}")
        return result

class CogLangPhp(CogModule):
    name = "cog-lang-php"
    version = "1.0.0"
    description = "PHP programming language expertise"

    def register_tools(self) -> list[Tool]:
        return [PhpTool(), ComposerTool(), LaravelTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## PHP Programming Expertise",
            "",
            "### Core PHP",
            "",
            "Basic concepts:",
            "- Variables (starts with $)",
            "- Data types (int, float, string, bool, array, object, NULL)",
            "- Constants (define(), const)",
            "- Operators (arithmetic, comparison, logical)",
            "- Control structures (if/else, switch, for, foreach, while)",
            "- Functions",
            "- Classes and objects",
            "- Namespaces",
            "- Traits",
            "- Interfaces",
            "- Abstract classes",
            "",
            "PHP syntax:",
            "- <?php ?> tags",
            "- Statements end with semicolon (;)",
            "- Variables are case-sensitive",
            "- Functions are case-insensitive",
            "- Comments (//, /* */, #)",
            "- Heredoc (<<<)",
            "- Nowdoc (<<<')",
            "",
            "Modern PHP features (PHP 7-8):",
            "- Scalar type hints (int, float, string, bool)",
            "- Return type hints",
            "- Null coalescing operator (??)",
            "- Spaceship operator (<=>)",
            "- Constant arrays (const)",
            "- Anonymous classes",
            "- Nullable types (?int)",
            "- Void return type",
            "- Null coalescing assignment (??=)",
            "- Constructor property promotion",
            "- Named arguments",
            "- Attributes (#[Attribute])",
            "- Match expression",
            "- Union types (int|float)",
            "- Mixed type",
            "- Static return type",
            "- Readonly properties",
            "- First-class callables",
            "",
            "### Composer",
            "",
            "Composer commands:",
            "- composer init (create composer.json)",
            "- composer install (install dependencies)",
            "- composer update (update dependencies)",
            "- composer require (add package)",
            "- composer remove (remove package)",
            "- composer dump-autoload (regenerate autoloader)",
            "- composer show (show installed)",
            "- composer outdated (show outdated)",
            "- composer why (show why package is installed)",
            "- composer global (global packages)",
            "",
            "composer.json structure:",
            "- name (vendor/project)",
            "- description",
            "- type (project, library, etc.)",
            "- require (production dependencies)",
            "- require-dev (dev dependencies)",
            "- autoload (PSR-4)",
            "- autoload-dev",
            "- scripts",
            "",
            "Composer versions:",
            "- caret (^): 1.2.x (compatible)",
            "- tilde (~): 1.2.3 (same minor version)",
            "- exact (1.2.3): exact version",
            "- wildcard (*): any version",
            "- range (>=1.2, <2.0): version range",
            "",
            "### Laravel",
            "",
            "Laravel architecture:",
            "- MVC pattern",
            "- Service providers",
            "- Facades",
            "- Contracts",
            "- Middleware",
            "- Service container",
            "- Request lifecycle",
            "",
            "Laravel CLI (Artisan):",
            "- php artisan make:model",
            "- php artisan make:controller",
            "- php artisan make:migration",
            "- php artisan make:seeder",
            "- php artisan make:factory",
            "- php artisan migrate",
            "- php artisan migrate:rollback",
            "- php artisan migrate:fresh",
            "- php artisan db:seed",
            "- php artisan tinker (REPL)",
            "- php artisan serve (dev server)",
            "- php artisan route:list",
            "- php artisan cache:clear",
            "- php artisan config:clear",
            "- php artisan view:clear",
            "- php artisan queue:work",
            "- php artisan schedule:run",
            "",
            "Eloquent ORM:",
            "- Models (extends Model)",
            "- Mass assignment ($fillable, $guarded)",
            "- Relationships (hasOne, hasMany, belongsTo, belongsToMany)",
            "- Eager loading (with)",
            "- Lazy loading (N+1 problem)",
            "- Accessors and mutators",
            "- Attribute casting",
            "- Query scopes",
            "- Observers",
            "- Events (creating, created, updating, updated)",
            "- Soft deletes",
            "- Polymorphic relations",
            "",
            "Laravel features:",
            "- Routing (routes/web.php, routes/api.php)",
            "- Middleware (auth, csrf, throttle)",
            "- Controllers",
            "- Views (Blade templates)",
            "- Requests (validation)",
            "- Responses (JSON, views, redirects)",
            "- Sessions",
            "- Authentication (scaffolding)",
            "- Authorization (gates, policies)",
            "- Database (query builder, Eloquent)",
            "- Migrations",
            "- Seeders",
            "- Factories",
            "- Queues",
            "- Jobs",
            "- Events and listeners",
            "- Notifications",
            "- Storage (local, S3)",
            "- Logging",
            "- Error handling",
            "",
            "Blade templating:",
            "- {{ $var }} (escaped)",
            "- {!! $var !!} (unescaped)",
            "- @if/@else/@elseif/@endif",
            "- @foreach/@endforeach",
            "- @forelse/@empty/@endforelse",
            "- @while/@endwhile",
            "- @include",
            "- @extends/@section/@yield",
            "- @component/@slot/@endcomponent",
            "- @csrf",
            "- @method",
            "- @auth/@guest",
            "",
            "### Symfony",
            "",
            "Symfony components:",
            "- Console (CLI)",
            "- HttpFoundation (Request/Response)",
            "- Routing",
            "- Twig (templating)",
            "- Doctrine (ORM)",
            "- Validator",
            "- Form",
            "- Security",
            "- Event Dispatcher",
            "",
            "Symfony CLI:",
            "- symfony new (create project)",
            "- php bin/console cache:clear",
            "- php bin/console doctrine:migrations:migrate",
            "- php bin/console doctrine:fixtures:load",
            "- php bin/console make:controller",
            "- php bin/console make:entity",
            "- php bin/console debug:router",
            "- php bin/console debug:container",
            "",
            "### WordPress",
            "",
            "WordPress architecture:",
            "- Themes (presentation)",
            "- Plugins (functionality)",
            "- Hooks (actions, filters)",
            "- Custom post types",
            "- Taxonomies",
            "- Shortcodes",
            "- Widgets",
            "",
            "WordPress hooks:",
            "- Actions (add_action)",
            "- Filters (add_filter)",
            "- Priorities",
            "- Arguments",
            "",
            "WordPress development:",
            "- wp_enqueue_script",
            "- wp_enqueue_style",
            "- register_post_type",
            "- register_taxonomy",
            "- add_theme_support",
            "- add_menu_page",
            "",
            "### Testing",
            "",
            "PHPUnit:",
            "- Test classes extend PHPUnit\\Framework\\TestCase",
            "- @test annotation or test* prefix",
            "- setUp/tearDown",
            "- assertEquals, assertSame, assertTrue",
            "- Data providers (@dataProvider)",
            "- Mock objects (getMock, createMock)",
            "",
            "Laravel testing:",
            "- Tests extend Tests\\TestCase",
            "- RefreshDatabase trait",
            "- ActingAs (auth)",
            "- get/post/put/delete/patch",
            "- assertStatus",
            "- assertJson",
            "- assertSee",
            "- assertDatabaseHas",
            "- assertDatabaseMissing",
            "- Factory (factory())",
            "- Fake (Mail::fake(), Queue::fake())",
            "",
            "### PHP Best Practices",
            "",
            "Code style:",
            "- Follow PSR-12 (coding style)",
            "- Use meaningful names",
            "- Keep functions small",
            "- Single responsibility",
            "- DRY (Don't Repeat Yourself)",
            "- Use type hints",
            "- Use return types",
            "- Use namespaces",
            "",
            "Error handling:",
            "- Use try/catch for exceptions",
            "- Use custom exceptions",
            "- Use error_reporting()",
            "- Use set_error_handler()",
            "- Don't use @ operator (suppresses errors)",
            "",
            "Security:",
            "- Use prepared statements (PDO)",
            "- Use password_hash/password_verify",
            "- Use htmlspecialchars() (XSS)",
            "- Use input validation",
            "- Use CSRF tokens",
            "- Don't expose errors in production",
            "- Use HTTPS",
            "- Validate file uploads",
            "",
            "Performance:",
            "- Use OPcache (bytecode cache)",
            "- Use database indexes",
            "- Use caching (Redis, Memcached)",
            "- Optimize autoload (composer dump-autoload -o)",
            "- Use lazy loading",
            "- Use connection pooling",
            "",
            "### PHP vs Other Languages",
            "",
            "PHP advantages:",
            "- Easy deployment (copy files)",
            "- Low cost (shared hosting)",
            "- Large ecosystem",
            "- WordPress (CMS)",
            "- Laravel (framework)",
            "- Fast iteration",
            "- Great for freelancing",
            "- Large talent pool",
            "",
            "When to use PHP:",
            "- Web development (LAMP stack)",
            "- CMS (WordPress, Drupal)",
            "- E-commerce (WooCommerce)",
            "- Rapid prototyping",
            "- Freelance projects",
            "- Small business websites",
            "",
            "### Quick Reference",
            "",
            "Run PHP:",
            "- php script.php",
            "- php -r 'echo \"hello\";'",
            "",
            "Interactive shell:",
            "- php -a",
            "",
            "Composer:",
            "- composer init",
            "- composer install",
            "- composer update",
            "- composer require vendor/package",
            "- composer dump-autoload",
            "",
            "Create Laravel app:",
            "- composer create-project laravel/laravel myapp",
            "- laravel new myapp (global Laravel installer)",
            "",
            "Laravel dev server:",
            "- php artisan serve",
            "",
            "Laravel tinker (REPL):",
            "- php artisan tinker",
            "",
            "Generate code:",
            "- php artisan make:model User",
            "- php artisan make:controller UserController",
            "- php artisan make:migration create_users_table",
            "",
            "Run migrations:",
            "- php artisan migrate",
            "",
            "Seed database:",
            "- php artisan db:seed",
            "",
            "Clear cache:",
            "- php artisan cache:clear",
            "- php artisan config:clear",
            "- php artisan view:clear",
            "",
            "Run tests:",
            "- php artisan test",
            "- vendor/bin/phpunit",
            "",
            "PHP examples:",
            "",
            "Variables:",
            "$name = 'John';",
            "$age = 30;",
            "",
            "Arrays:",
            "$fruits = ['apple', 'banana', 'cherry'];",
            "$assoc = ['name' => 'John', 'age' => 30];",
            "",
            "Foreach loop:",
            "foreach ($fruits as $fruit) {",
            "  echo $fruit;",
            "}",
            "",
            "Function with type hints:",
            "function greet(string $name, int $age): string {",
            "  return \"Hello, $name! You are $age.\";",
            "}",
            "",
            "Null coalescing:",
            "$name = $_GET['name'] ?? 'Guest';",
            "",
            "Spaceship operator:",
            "$result = $a <=> $b; // -1, 0, 1",
            "",
            "Match expression (PHP 8):",
            "$message = match ($status) {",
            "  '200' => 'OK',",
            "  '404' => 'Not Found',",
            "  default => 'Unknown'",
            "};",
            "",
            "Constructor property promotion (PHP 8):",
            "class User {",
            "  public function __construct(",
            "    public string $name,",
            "    public int $age",
            "  ) {}",
            "}",
            "",
            "Named arguments (PHP 8):",
            "query(select: '*', from: 'users', where: 'active = 1');",
            "",
            "Attributes (PHP 8):",
            "#[Route('/api/users', methods: ['GET'])]",
            "public function index() {}",
            "",
            "Laravel model:",
            "class User extends Model {",
            "  protected $fillable = ['name', 'email'];",
            "",
            "  public function posts() {",
            "    return $this->hasMany(Post::class);",
            "  }",
            "}",
            "",
            "Laravel controller:",
            "class UserController extends Controller {",
            "  public function show($id) {",
            "    $user = User::find($id);",
            "    return view('users.show', compact('user'));",
            "  }",
            "}",
            "",
            "Laravel route:",
            "Route::get('/users/{id}', [UserController::class, 'show']);",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "php",
            "laravel",
            "symfony",
            "wordpress",
            "composer",
            "web_development",
            "mvc",
            "eloquent",
            "blade",
            "artisan",
            "testing",
            "phpunit",
            "orm",
            "database",
            "rest_api",
            "routing",
            "middleware",
            "oop",
            "namespaces",
            "traits",
            "modern_php",
            "type_hints"
        ]

module = CogLangPhp()
