from cog.cog_module import CogModule

class CogLangGo(CogModule):
    name = "cog-lang-go"
    version = "1.0.0"
    description = "Go language expertise including goroutines, channels, interfaces, error handling, modules, generics, and concurrency patterns"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Go Language Expertise",
            "",
            "### Language Fundamentals",
            "- Statically typed with type inference via := short variable declaration",
            "- Zero values: 0 for numbers, '' for strings, nil for pointers/slices/maps/chans/interfaces",
            "- Multiple return values: func div(a, b int) (int, error)",
            "- Named return values for documentation and naked returns in short functions",
            "- Blank identifier _ to discard values",
            "- Constants with iota for enumerated sequences",
            "- Short variable declarations only inside functions",
            "- Package-level variables use var keyword",
            "",
            "### Goroutines and Concurrency",
            "- go keyword launches a goroutine: go doWork()",
            "- Goroutines are multiplexed onto OS threads by the Go scheduler",
            "- GOMAXPROCS controls number of OS threads (default: number of CPUs)",
            "- Goroutines are cheap: ~2KB stack that grows/shrinks as needed",
            "- sync.WaitGroup for waiting on multiple goroutines",
            "- sync.Once for one-time initialization",
            "- sync.Pool for object reuse and GC pressure reduction",
            "- Prefer channels for communication; mutexes for shared state",
            "",
            "### Channels",
            "- Unbuffered: send blocks until receiver ready, receive blocks until sender ready",
            "- Buffered: make(chan int, 10) — sends block when buffer full",
            "- Directional types: chan<- int (send-only), <-chan int (receive-only)",
            "- Close a channel: close(ch) — receivers get zero value after drain",
            "- Check closed: val, ok := <-ch — ok is false when closed",
            "- Range over channel: for val := range ch { } — exits on close",
            "- Channel ownership pattern: owner creates, writes, closes; consumer reads",
            "",
            "### Select Statement",
            "- Select waits on multiple channel operations simultaneously",
            "- Random selection among ready cases (not FIFO)",
            "- Default case for non-blocking operations",
            "- Time.After for timeout: case <-time.After(5 * time.Second)",
            "- Done channel pattern for cancellation",
            "- Select {} blocks forever (useful in main goroutine)",
            "",
            "### Interfaces and Embedding",
            "- Interfaces are implicit: no 'implements' keyword needed",
            "- Define behavior: type Reader interface { Read(p []byte) (n int, err error) }",
            "- Empty interface interface{} or 'any' for dynamic types",
            "- Type assertion: val, ok := x.(string)",
            "- Type switch: switch v := x.(type) { case string: ... }",
            "- Embedding for composition (not inheritance)",
            "- Prefer small, single-method interfaces (io.Reader, io.Writer)",
            "- Interface satisfaction checked at compile time",
            "",
            "### Error Handling Patterns",
            "- Multiple return: func Do() (Result, error)",
            "- Always check errors: if err != nil { return err }",
            "- Custom error types: type MyError struct { Msg string } with Error() string",
            "- errors.Is for error chain matching, errors.As for type extraction",
            "- fmt.Errorf with %w for error wrapping: fmt.Errorf('context: %w', err)",
            "- Sentinel errors: var ErrNotFound = errors.New('not found')",
            "- panic/recover for truly unrecoverable situations only",
            "- defer for cleanup: file.Close(), mutex.Unlock()",
            "",
            "### Go Modules and Packages",
            "- go mod init github.com/user/project",
            "- go mod tidy to add missing and remove unused dependencies",
            "- go.sum contains cryptographic checksums of dependencies",
            "- Replace directive for local development: replace => ../localpkg",
            "- Internal packages: internal/ restricts visibility to parent tree",
            "- Package naming: lowercase, single word, no underscores",
            "- go get pkg@version to add or update a dependency",
            "- go mod vendor for vendored dependencies",
            "",
            "### Generics (Go 1.18+)",
            "- Type parameters: func Map[T any, R any](s []T, f func(T) R) []R",
            "- Constraints via interfaces: func Max[T constraints.Ordered](a, b T) T",
            "- Type sets in interfaces for operators: interface { int | float64 }",
            "- Generic types: type Stack[T any] struct { items []T }",
            "- Type inference often eliminates explicit type arguments",
            "- comparable constraint for types supporting == and !=",
            "- constraints package for common constraints (though now deprecated, use cmp package)",
            "",
            "### Slices and Maps",
            "- Slices: dynamic views over arrays, make([]T, 0, capacity)",
            "- append returns new slice: s = append(s, elem)",
            "- Slice tricks: s[len(s)-1], s[:len(s)-1] for stack operations",
            "- Copy slices: copy(dst, src)",
            "- Maps: make(map[string]int) or literal map[string]int{'a': 1}",
            "- Check existence: val, ok := m[key]",
            "- Delete: delete(m, key)",
            "- Maps are not concurrent-safe; use sync.Map for concurrent access",
            "",
            "### Testing and Benchmarking",
            "- Test files: xxx_test.go in same package",
            "- Test function signature: func TestXxx(t *testing.T)",
            "- Table-driven tests with subtests: t.Run('name', func(t *testing.T) { })",
            "- Benchmarks: func BenchmarkXxx(b *testing.B) { for i := 0; i < b.N; i++ { } }",
            "- go test ./... — run all tests recursively",
            "- go test -v for verbose output, -run for pattern matching",
            "- go test -bench=. -benchmem for memory allocation stats",
            "- testify/assert for fluent assertions (third-party)",
            "",
            "### Build and Cross-Compilation",
            "- go build -o bin/app ./cmd/app",
            "- Cross-compile: GOOS=linux GOARCH=arm64 go build",
            "- Build tags: //go:build linux or //go:build !windows",
            "- ldflags for version injection: -ldflags '-X main.version=1.0.0'",
            "- go vet for static analysis, staticcheck for deeper checks",
            "",
            "### Code Examples",
            "HTTP server with graceful shutdown:",
            "```go",
            "package main",
            "",
            "import (",
            "    'context'",
            "    'fmt'",
            "    'log'",
            "    'net/http'",
            "    'os'",
            "    'os/signal'",
            "    'syscall'",
            "    'time'",
            ")",
            "",
            "func main() {",
            "    mux := http.NewServeMux()",
            "    mux.HandleFunc('/health', func(w http.ResponseWriter, r *http.Request) {",
            "        w.WriteHeader(http.StatusOK)",
            "        fmt.Fprint(w, 'ok')",
            "    })",
            "",
            "    srv := &http.Server{",
            "        Addr:         ':8080',",
            "        Handler:      mux,",
            "        ReadTimeout:  5 * time.Second,",
            "        WriteTimeout: 10 * time.Second,",
            "    }",
            "",
            "    go func() {",
            "        if err := srv.ListenAndServe(); err != http.ErrServerClosed {",
            "            log.Fatal(err)",
            "        }",
            "    }()",
            "",
            "    quit := make(chan os.Signal, 1)",
            "    signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)",
            "    <-quit",
            "",
            "    ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)",
            "    defer cancel()",
            "    if err := srv.Shutdown(ctx); err != nil {",
            "        log.Fatal(err)",
            "    }",
            "}",
            "```",
            "",
            "Generic functions with constraints:",
            "```go",
            "func Filter[T any](s []T, pred func(T) bool) []T {",
            "    result := make([]T, 0)",
            "    for _, v := range s {",
            "        if pred(v) {",
            "            result = append(result, v)",
            "        }",
            "    }",
            "    return result",
            "}",
            "",
            "func Map[T any, R any](s []T, f func(T) R) []R {",
            "    result := make([]R, len(s))",
            "    for i, v := range s {",
            "        result[i] = f(v)",
            "    }",
            "    return result",
            "}",
            "```",
            "",
            "Worker pool with channels:",
            "```bash",
            "go test ./... -v -race",
            "go test -bench=. -benchmem -count=3",
            "go vet ./...",
            "staticcheck ./...",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["go", "goroutines", "channels", "interfaces", "error_handling", "go_modules", "generics", "testing", "benchmarks", "cross_compilation", "concurrency", "slices", "maps"]

module = CogLangGo()
