# Creating remaining 18 modules...

# Module 3: MongoDB
mkdir -p cog/modules/cog-db-mongodb
cat > cog/modules/cog-db-mongodb/manifest.json << 'EOF'
{
  "name": "cog-db-mongodb",
  "version": "1.0.0",
  "description": "MongoDB NoSQL database expertise including document modeling, aggregation, replication, and sharding",
  "capabilities": ["mongodb_query", "document_modeling", "aggregation_pipeline", "mongodb_backup", "mongodb_replication", "mongodb_indexing"],
  "requires": ["tool-core"],
  "permissions": ["shell.execute", "filesystem.read", "filesystem.write", "network.request"],
  "entrypoint": "module.py"
}
EOF

cat > cog/modules/cog-db-mongodb/module.py << 'MODULE'
from cog.cog_module import CogModule

class CogDbMongodb(CogModule):
    name = "cog-db-mongodb"
    version = "1.0.0"
    description = "MongoDB database expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## MongoDB NoSQL Database Expertise",
            "",
            "### Document Database Concepts",
            "- BSON format (Binary JSON)",
            "- Collections (similar to tables)",
            "- Documents (similar to rows)",
            "- _id field (unique identifier)",
            "- Flexible schema",
            "- Embedded documents vs references",
            "- Document size limit (16MB)",
            "- GridFS for large files",
            "",
            "### Data Modeling",
            "- Document structure design",
            "- Embedding vs referencing",
            "- One-to-one, one-to-many, many-to-many",
            "- Schema validation",
            "- Indexing strategies",
            "- Data types (String, Number, Boolean, Date, Array, Object, Null)",
            "- _id vs custom ids",
            "- Atomic operations",
            "",
            "### Query Language",
            "- find() for querying",
            "- Query operators ($eq, $ne, $gt, $lt, $in, $nin, $and, $or, $not)",
            "- Projection (limit returned fields)",
            "- sort() and limit()",
            "- count() and countDocuments()",
            "- distinct()",
            "- aggregation pipeline",
            "",
            "### Aggregation Pipeline",
            "- $match (filter documents)",
            "- $group (group by fields)",
            "- $project (reshape documents)",
            "- $sort (sort results)",
            "- $limit (limit results)",
            "- $lookup (join collections)",
            "- $unwind (array operations)",
            "- $facet (multiple aggregations)",
            "- $count (count documents)",
            "",
            "### Indexing",
            "- Single field indexes",
            "- Compound indexes",
            "Multikey indexes",
            "- Text indexes",
            "- Geospatial indexes",
            "- Hashed indexes",
            "- TTL indexes (time-to-live)",
            "- Index properties (unique, sparse)",
            "- Covered queries",
            "- Index build process",
            "",
            "### Replication",
            "- Replica sets",
            "- Primary and secondary nodes",
            "- Automatic failover",
            "- Write concerns",
            "- Read preferences",
            "- Oplog (operations log)",
            "- Arbiter (for automatic failover)",
            "",
            "### Sharding",
            "- Sharded clusters",
            "- Shard keys",
            "- Chunk splitting",
            "- Balancer",
            "- Config servers",
            "- Query routers",
            "- Shard key selection",
            "",
            "### GridFS",
            "- Large file storage",
            "- Chunks (255KB default)",
            "- Files collection metadata",
            "- Upload and retrieve files",
            "- Streaming",
            "",
            "### MongoDB vs Relational Databases",
            "- Schema flexibility vs strict schema",
            "- Document-oriented vs table-oriented",
            "- Horizontal scaling (sharding) vs vertical scaling",
            "- JSON documents vs rows/columns",
            "- ACID properties at document level vs transaction level",
            "- Better for unstructured/hierarchical data",
            "- Slower for complex joins",
            "- Better for rapid iteration",
            "",
            "### Common Operations",
            "Connect:",
            "```bash",
            "mongosh mongodb://localhost:27017",
            "mongo --host localhost --port 27017",
            "```",
            "",
            "Use database:",
            "```javascript",
            "use mydb",
            "```",
            "",
            "Insert document:",
            "```javascript",
            "db.users.insertOne({",
            "  name: 'John',",
            "  age: 30,",
            "  email: 'john@example.com'",
            "  created: new Date()",
            "  tags: ['developer', 'admin']",
            "})",
            "```",
            "",
            "Query documents:",
            "```javascript",
            "db.users.find({ age: { $gt: 25 } })",
            "db.users.find({ tags: 'mongodb' })",
            "db.users.find({ name: /^J/ })",
            "```",
            "",
            "Update document:",
            "```javascript",
            "db.users.updateOne({ _id: ObjectId('...') }, {",
            "  $set: { age: 31 }",
            "  $push: { tags: 'senior' }",
            "})",
            "```",
            "",
            "Delete document:",
            "```javascript",
            "db.users.deleteOne({ _id: ObjectId('...') })",
            "```",
            "",
            "Aggregation:",
            "```javascript",
            "db.orders.aggregate([",
            "  { $match: { status: 'completed' } },",
            "  { $group: { _id: '$product', total: { $sum: '$amount' } } } },",
            "  { $sort: { total: -1 } },",
            "  { $limit: 10 }",
            "])",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["mongodb", "nosql", "document_modeling", "aggregation", "replication", "sharding", "gridfs", "indexing"]

module = CogDbMongodb()
MODULE

# Module 4: Redis
mkdir -p cog/modules/cog-db-redis
cat > cog/modules/cog-db-redis/manifest.json << 'EOF'
{
  "name": "cog-db-redis",
  "version": "1.0.0",
  "description": "Redis in-memory data store expertise including caching, pub/sub, streams, and clustering",
  "capabilities": ["redis_cache", "redis_pub_sub", "redis_streams", "redis_clustering", "redis_persistence", "redis_transactions"],
  "requires": ["tool-core"],
  "permissions": ["shell.execute", "network.request"],
  "entrypoint": "module.py"
}
EOF

cat > cog/modules/cog-db-redis/module.py << 'MODULE'
from cog.cog_module import CogModule

class CogDbRedis(CogModule):
    name = "cog-db-redis"
    version = "1.0.0"
    description = "Redis expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Redis In-Memory Data Store Expertise",
            "",
            "### Core Concepts",
            "- Key-value store",
            "- In-memory data structure store",
            "- Single-threaded (mostly)",
            "- O(1) operations",
            "- Data persistence to disk (RDB/AOF)",
            "- Pub/Sub messaging",
            "- Transaction support (MULTI/EXEC/DISCARD)",
            "- Keyspace expiration (TTL)",
            "- Lua scripting",
            "- Modules (extensions)",
            "",
            "### Data Structures",
            "- Strings (binary safe)",
            "- Hashes (object fields)",
            "- Lists (ordered collections)",
            "- Sets (unique collections)",
            "- Sorted Sets (ranked sets with scores)",
            "- Bitmaps (binary operations)",
            "- HyperLogLogs (probabilistic data structures)",
            "- Geospatial (location data)",
            "- Streams (log processing)",
            "",
            "### Redis Operations",
            "- SET key value",
            "- GET key",
            "- MGET key1 key2",
            "- SETEX key seconds value",
            "- INCR key (atomic increment)",
            "- DECR key",
            "- EXISTS key",
            "- DELETE key",
            "- EXPIRE key seconds",
            "- TTL key",
            "- KEYS pattern",
            "",
            "### Hash Operations",
            "- HSET key field value",
            "- HGET key field",
            "HGETALL key",
            "HINCRBY key field increment",
            "HEXISTS key field",
            "",
            "### List Operations",
            "- LPUSH key value",
            "- LRANGE key start stop",
            "- LPOP key",
            "- LLEN key",
            "",
            "### Set Operations",
            "- SADD key member",
            "- SMEMBERS key",
            "- SISMEMBER key member",
            "- SUNION, SINTER, SDIFF",
            "",
            "### Sorted Set Operations",
            "- ZADD key score member",
            "ZRANGE key start stop",
            "ZRANK key member",
            "- ZRANGEBYSCORE min max",
            "",
            "### Pub/Sub",
            "- PUBLISH channel message",
            "- SUBSCRIBE channel",
            "- PSUBSCRIBE pattern",
            "- UNSUBSCRIBE channel",
            "",
            "### Persistence",
            "- RDB (snapshot)",
            "- AOF (append-only file)",
            "- RDB+AOF (both)",
            "- Save commands for manual snapshots",
            "",
            "### Clustering",
            "- Redis Cluster (distributed)",
            "- Sentinel (high availability)",
            "- Master-slave replication",
            "- Hash slots across nodes",
            "- Redis Enterprise",
            "",
            "### Common Use Cases",
            "",
            "Caching:",
            "- Session storage",
            "- Query results",
            "API responses",
            "- Page fragments",
            "- Database query cache",
            "",
            "Rate limiting:",
            "- Request counting",
            "- Sliding window",
            "- Token bucket",
            "",
            "Real-time features:",
            "- Leaderboards",
            "- Session management",
            "- Pub/Sub messaging",
            "- Real-time analytics",
            "",
            "Queues:",
            "- Job queues",
            "- Message queues",
            "- Task queues",
            "",
            "### Redis vs Memcached",
            "- Redis: Persistence, data structures, pub/sub",
            "- Memcached: Simple caching only",
            "- Redis: Slower for simple caching",
            "- Memcached: Faster for simple key-value",
            "",
            "### Quick Reference",
            "Connect:",
            "```bash",
            "redis-cli",
            "redis-cli -h localhost -p 6379",
            "```",
            "",
            "Basic operations:",
            "```redis",
            "SET user:1:name 'John'",
            "GET user:1:name",
            "SETEX user:1:session 3600 'abc123'",
            "INCR counter",
            "ZADD leaderboard 100 'player1'",
            "PUBLISH updates 'User updated'",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["redis", "caching", "pub_sub", "streams", "clustering", "persistence"]

module = CogDbRedis()
MODULE

echo "✅ Created MongoDB and Redis modules"

# Module 5 & 6: Docker & Kubernetes  
# These are large modules, I'll create their structures first
echo "📁 Created 4 complete modules so far..."
echo "🎯 Creating Docker and Kubernetes modules next..."
echo ""
