from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult
from cog.verification.base import Verifier, VerificationResult, VerificationStatus


class NpmInstallTool(Tool):
    name = "nodejs.npm.install"
    description = "Install npm packages"
    required_permissions = ["shell.execute"]

    def execute(self, packages: str, save: bool = True, dev: bool = False, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        flags = []
        if save:
            flags.append("--save")
        if dev:
            flags.append("--save-dev")
        
        command = f"npm install {' '.join(flags)} {packages}"
        result = shell.execute(command=command, timeout=300)
        return result


class NpmRunTool(Tool):
    name = "nodejs.npm.run"
    description = "Run npm scripts"
    required_permissions = ["shell.execute"]

    def execute(self, script: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"npm run {script}"
        result = shell.execute(command=command, timeout=300)
        return result


class NodeStartTool(Tool):
    name = "nodejs.start"
    description = "Start Node.js application"
    required_permissions = ["shell.execute"]

    def execute(self, file: str = "index.js", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"node {file}"
        result = shell.execute(command=command, timeout=60)
        return result


class NodeTestTool(Tool):
    name = "nodejs.test"
    description = "Run Node.js tests"
    required_permissions = ["shell.execute"]

    def execute(self, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = "npm test"
        result = shell.execute(command=command, timeout=180)
        return result


class NodeLintTool(Tool):
    name = "nodejs.lint"
    description = "Lint Node.js code"
    required_permissions = ["shell.execute"]

    def execute(self, path: str = ".", fix: bool = False, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        tool = "eslint" if not fix else "eslint --fix"
        command = f"{tool} {path}"
        result = shell.execute(command=command, timeout=60)
        return result


class NodeSyntaxVerifier(Verifier):
    name = "nodejs.syntax"
    description = "Verify Node.js syntax"

    def verify(self, target, **kwargs) -> VerificationResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        result = shell.execute(
            command=f"node --check {target}", timeout=30
        )
        if result.success:
            return VerificationResult(
                verifier=self.name,
                status=VerificationStatus.PASSED,
                message=f"Node.js syntax OK: {target}",
            )
        return VerificationResult(
            verifier=self.name,
            status=VerificationStatus.FAILED,
            message=f"Node.js syntax error in {target}",
            details={"error": result.error},
        )


class CogBackendNodejs(CogModule):
    name = "cog-backend-nodejs"
    version = "1.0.0"
    description = "Node.js backend development expertise"

    def register_tools(self) -> list[Tool]:
        return [
            NpmInstallTool(),
            NpmRunTool(),
            NodeStartTool(),
            NodeTestTool(),
            NodeLintTool(),
        ]

    def register_verifiers(self) -> list[Verifier]:
        return [NodeSyntaxVerifier()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Node.js Backend Development Expertise",
            "",
            "### Core Node.js Concepts",
            "",
            "Event Loop & Concurrency:",
            "- Event-driven, non-blocking I/O",
            "- Single-threaded with event loop",
            "- libuv thread pool for I/O",
            "- Async/await patterns",
            "- Promise handling",
            "- Callback patterns (avoid callback hell)",
            "- Event emitters and listeners",
            "- Stream API (readable, writable, transform)",
            "- Buffer handling",
            "- Child processes",
            "- Worker threads for CPU-intensive tasks",
            "- Cluster module for multi-core",
            "",
            "### Module System",
            "",
            "CommonJS (CJS):",
            "- require() for importing",
            "- module.exports for exporting",
            "- __dirname, __filename",
            "- module caching",
            "- Node.js module resolution algorithm",
            "",
            "ES Modules (ESM):",
            "- import/export statements",
            "- "type": "module" in package.json",
            "- Dynamic import()",
            "- import.meta.url",
            "- Top-level await support",
            "",
            "package.json:",
            "- Dependencies management",
            "- Scripts definition",
            "- Main entry point",
            "- Engine requirements",
            "- Configuration fields",
            "",
            "### Express.js Framework",
            "",
            "Application structure:",
            "- const app = express()",
            "- Middleware pattern",
            "- Routing: app.get(), app.post(), etc.",
            "- Request and response objects",
            "- req.params, req.query, req.body",
            "- res.send(), res.json(), res.render()",
            "- res.status(), res.set()",
            "",
            "Middleware:",
            "- Application-level middleware",
            "- Router-level middleware",
            "- Error handling middleware",
            "- Body parsing middleware",
            "- Static file serving",
            "- Session management",
            "- Passport.js for authentication",
            "",
            "Routing:",
            "- express.Router()",
            "- Route parameters: '/users/:id'",
            "- Query parameters: '?search=test'",
            "- Route handlers (req, res, next)",
            "- next() for error handling",
            "",
            "### Fastify Framework",
            "",
            "Why Fastify:",
            "- High performance",
            "- Schema validation",
            "- Serialization",
            "- Logging",
            "- TypeScript support",
            "",
            "Fastify patterns:",
            "- const fastify = require('fastify')({ logger: true })",
            "- fastify.get('/', async (request, reply) => {})",
            "- fastify.register() for plugins",
            "- fastify.addHook() for lifecycle hooks",
            "- Validation schemas",
            "- Reply APIs",
            "",
            "### NestJS Framework",
            "",
            "Architecture:",
            "- Modules and providers",
            "- Controllers and services",
            "- Dependency injection",
            "- Decorators (@Controller, @Get, @Post)",
            "- Pipes and guards",
            "- Interceptors",
            "- Middleware and filters",
            "",
            "Modules:",
            "- @Module() decorator",
            "- providers array",
            "- imports array",
            "- controllers array",
            "- exports array",
            "",
            "Providers:",
            "- @Injectable() decorator",
            "- Use class-based providers",
            "- Use value factories",
            "- Use async providers",
            "",
            "Controllers:",
            "- @Controller() decorator",
            "- @Get(), @Post(), @Put(), @Delete() decorators",
            "- Param decorators (@Param(), @Body(), @Query())",
            "- Request DTOs and validation",
            "",
            "### REST API Design",
            "",
            "REST principles:",
            "- Resource-based URLs (/api/users)",
            "- HTTP methods: GET, POST, PUT, PATCH, DELETE",
            "- Status codes: 200, 201, 204, 400, 401, 403, 404, 500",
            "- Statelessness",
            "- JSON request/response",
            "- HATEOAS (optional)",
            "",
            "API design patterns:",
            "- Versioning (/api/v1/users)",
            "- Pagination (page=1&limit=10)",
            "- Sorting (sort=created_at:desc)",
            "- Filtering (filter=status:active)",
            "- Search (q=search_term)",
            "- Fields projection (fields=id,name)",
            "- Include related resources (?include=posts)",
            "",
            "Error handling:",
            "- Consistent error response format",
            "- Proper HTTP status codes",
            "- Error middleware",
            "- Validation errors (400)",
            "- Not found errors (404)",
            "- Server errors (500)",
            "",
            "### Authentication & Authorization",
            "",
            "JWT (JSON Web Tokens):",
            "- Token generation and validation",
            "- Middleware for protected routes",
            "- Token refresh strategy",
            "- Payload signing",
            "- Expiration handling",
            "",
            "Passport.js:",
            "- Passport strategies (local, JWT, OAuth)",
            "- Serialize/deserialize user",
            "- Session management",
            "- Remember me functionality",
            "",
            "Role-based access control:",
            "- User roles and permissions",
            "- Route guards",
            "- Middleware for authorization",
            "- Resource ownership checks",
            "",
            "### Database Integration",
            "",
            "ORM/ODM choices:",
            "- Sequelize (SQL)",
            "- TypeORM (TypeScript)",
            "- Mongoose (MongoDB)",
            "- Prisma (TypeScript, modern)",
            "- Bookshelf (Google Cloud SQL)",
            "",
            "Connection patterns:",
            "- Connection pooling",
            "- Singleton pattern for connections",
            "- Environment-based configuration",
            "- Migration support",
            "- Seed data",
            "",
            "### Real-time Features",
            "",
            "WebSockets:",
            "- ws library",
            "- Socket.IO",
            "- Real-time event broadcasting",
            "- Room/channel support",
            "- Authentication with WebSockets",
            "- Connection management",
            "- Reconnection strategies",
            "",
            "Server-Sent Events (SSE):",
            "- Event streaming",
            "- One-way communication",
            "- Auto-reconnection",
            "- Keep-alive messages",
            "",
            "### File Uploads",
            "",
            "Handling uploads:",
            "- Multer middleware",
            "- Busboy",
            "- Formidable",
            "- File size limits",
            "- File type validation",
            "- Streaming uploads",
            "- S3 integration",
            "- Local storage",
            "- CDN integration",
            "",
            "### Security Best Practices",
            "",
            "Security measures:",
            "- Input validation and sanitization",
            "- SQL injection prevention",
            "- XSS prevention",
            "- CSRF protection (csrf tokens)",
            "- Rate limiting",
            "- Helmet.js security headers",
            "- CORS configuration",
            "- HTTP parameter pollution prevention",
            "- Brute force protection",
            "- Dependency security audits",
            "",
            "### Performance Optimization",
            "",
            "Caching strategies:",
            "- In-memory caching (Node-cache)",
            "- Redis caching",
            "- CDN caching",
            "- HTTP caching headers",
            "- Application-level caching",
            "",
            "Optimization techniques:",
            "- Cluster mode for multi-core",
            "- Worker threads for CPU-heavy tasks",
            "- Stream processing for large data",
            "- Async operations",
            "- Connection pooling",
            "- Database query optimization",
            "- Nginx reverse proxy",
            "- Load balancing",
            "- Gzip compression",
            "",
            "### Testing Strategies",
            "",
            "Testing frameworks:",
            "- Jest (unit, integration, e2e)",
            "- Mocha/Chai (TDD/BDD)",
            "- Supertest (HTTP testing)",
            "- Nock (HTTP mocking)",
            "- Sinon (spies, mocks, stubs)",
            "",
            "Testing patterns:",
            "- Unit tests for individual functions",
            "- Integration tests for endpoints",
            "- E2E tests with Cypress/Playwright",
            "- Test database setup and teardown",
            "- Mock external dependencies",
            "- Test factories and fixtures",
            "",
            "### Deployment & DevOps",
            "",
            "Deployment options:",
            "- PM2 process manager",
            "- Docker containers",
            "- Kubernetes (K8s)",
            "- Serverless (AWS Lambda, Vercel, Netlify)",
            "- PaaS (Heroku, Railway, Render)",
            "- VPS (DigitalOcean, Linode)",
            "",
            "Process management:",
            "- PM2 cluster mode",
            "- Graceful shutdown",
            "- Zero-downtime deployments",
            "- Health check endpoints",
            "- Logging and monitoring",
            "",
            "### Node.js Tooling Ecosystem",
            "",
            "Package managers:",
            "- npm (Node Package Manager)",
            "- yarn (Facebook, alternative to npm)",
            "- pnpm (fast, disk-space efficient)",
            "- npx (package runner)",
            "",
            "Build tools:",
            "- Webpack",
            "- Vite",
            "esbuild",
            "- Rollup",
            "",
            "Development tools:",
            "- Nodemon (auto-restart)",
            "- PM2 (production process manager)",
            "- ts-node (TypeScript execution)",
            "- tsc (TypeScript compiler)",
            "- ESLint (linting)",
            "- Prettier (code formatting)",
            "",
            "### Node.js Version Features",
            "",
            "Latest Node.js (18+, 20+):",
            "- Top-level await (ESM)",
            "- Fetch API (built-in)",
            "- Blob/File global",
            "- Navigator API (built-in)",
            "- Performance improvements",
            "- ES2022+ features",
            "- Import assertions",
            "- RegExp match indices",
            "- Array methods",
            "- Object.hasOwn()",
            "",
            "### Common Patterns",
            "",
            "Async/await patterns:",
            "```javascript",
            "async function getUser(id) {",
            "  const user = await User.findById(id)",
            "  return user;",
            "}",
            "",
            "// Error handling",
            "try {",
            "  const result = await api.call();",
            "} catch (error) {",
            "  logger.error('API call failed:', error);",
            "  throw error;",
            "}",
            "```",
            "",
            "Middleware pattern:",
            "```javascript",
            "function logger(req, res, next) {",
            "  console.log(`${req.method} ${req.url}`);",
            "  next();",
            "}",
            "```",
            "",
            "Singleton pattern:",
            "```javascript",
            "class Database {",
            "  static instance = null;",
            "  ",
            "  static getInstance() {",
            "    if (!Database.instance) {",
            "      Database.instance = new Database();",
            "    }",
            "    return Database.instance;",
            "  }",
            "}",
            "```",
            "",
            "### When Working with Node.js",
            "",
            "Creating APIs:",
            "- Use RESTful principles",
            "- Implement proper error handling",
            "- Validate input data",
            "- Use appropriate HTTP methods",
            "- Return consistent responses",
            "- Implement pagination",
            "- Add rate limiting",
            "- Include API documentation",
            "",
            "Working with databases:",
            "- Use connection pooling",
            "- Implement transactions",
            "- Handle connection errors",
            "- Use parameterized queries",
            "- Optimize database queries",
            "- Implement migrations",
            "- Seed development data",
            "",
            "Performance:",
            "- Use async/await properly",
            "- Avoid blocking operations",
            "- Implement caching",
            "- Use streams for large data",
            "- Optimize database queries",
            "- Use worker threads for CPU tasks",
            "",
            "Security:",
            "- Validate all input",
            "- Sanitize user input",
            "- Use HTTPS",
            "- Implement rate limiting",
            "- Use security headers",
            "- Keep dependencies updated",
            "- Don't expose sensitive data",
            "",
            "### Common Issues",
            "",
            "Callback hell → Use async/await or promises",
            "Memory leaks → Proper cleanup, avoid global variables",
            "Blocking operations → Use async patterns",
            "Security vulnerabilities → Input validation, security headers",
            "Performance issues → Caching, optimization, profiling",
            "Callback depth → Use async/await",
            "Error handling → Try/catch, error middleware",
            "",
            "### Best Practices",
            "",
            "Code organization:",
            "- MVC pattern (Model-View-Controller)",
            "- Layered architecture",
            "- Separation of concerns",
            "- Dependency injection",
            "- Use TypeScript for type safety",
            "- Follow style guides (ESLint, Prettier)",
            "",
            "Error handling:",
            "- Try-catch for async operations",
            "- Error middleware",
            "- Consistent error responses",
            "- Proper logging (Winston, Pino)",
            "- Error monitoring (Sentry)",
            "",
            "Performance:",
            "- Use async/await",
            "- Avoid blocking operations",
            "- Use streams",
            "- Implement caching",
            "- Use connection pooling",
            "- Optimize database queries",
            "- Use compression",
            "",
            "Security:",
            "- Validate input",
            "- Sanitize data",
            "- Use HTTPS",
            "- Security headers (Helmet.js)",
            "- Rate limiting",
            "- Authentication/authorization",
            "- Keep dependencies updated",
            "",
            "### Tools Integration",
            "",
            "Development:",
            "- Nodemon for auto-restart",
            "- ESLint for linting",
            "- Prettier for formatting",
            "- Jest for testing",
            "- Git for version control",
            "",
            "Production:",
            "- PM2 for process management",
            "- Winston for logging",
            "- Prometheus for metrics",
            "- Sentry for error tracking",
            "- Docker for containerization",
            "- Nginx for reverse proxy",
            "",
            "### Node.js vs Other Backend Technologies",
            "",
            "vs Python:",
            "- Faster I/O performance",
            "- Better for real-time apps",
            "- Smaller ecosystem than Python",
            "- Similar async/await patterns",
            "",
            "vs Java:",
            "- Lighter weight",
            "- Faster development cycle",
            "- Better for real-time features",
            "- Less verbose",
            "- Larger ecosystem",
            "",
            "vs Go:",
            "- Slower raw performance",
            "- Easier async programming",
            "- Larger ecosystem",
            "- More flexible",
            "- Better for rapid prototyping",
            "",
            "### Modern Node.js Trends",
            "",
            "Bun (Runtime alternative):",
            "- Faster than Node.js",
            "- Native TypeScript support",
            "- Compatible with npm packages",
            "- Drop-in replacement",
            "",
            "Deno (Runtime alternative):",
            "- Secure by default",
            "- Native TypeScript",
            "- Standard library included",
            "- Import maps (no node_modules)",
            "- ES modules only",
            "",
            "Edge computing:",
            "- Cloudflare Workers",
            "- Vercel Edge Functions",
            "- AWS Lambda@Edge",
            "- Deno Deploy",
            "",
            "### Quick Reference",
            "",
            "Create Express server:",
            "```javascript",
            "const express = require('express');",
            "const app = express();",
            "",
            "app.use(express.json());",
            "app.use(express.urlencoded({ extended: true }));",
            "",
            "app.get('/api/users', async (req, res) => {",
            "  const users = await User.find();",
            "  res.json(users);",
            "});",
            "",
            "app.listen(3000);",
            "```",
            "",
            "Run tests:",
            "```bash",
            "npm test",
            "```",
            "",
            "Lint code:",
            "```bash",
            "eslint . --fix",
            "```",
            "",
            "Start development:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build for production:",
            "```bash",
            "npm run build",
            "```",
            "",
            "Run in production:",
            "```bash",
            "NODE_ENV=production node server.js",
            "```",
            "",
            "or with PM2:",
            "```bash",
            "pm2 start server.js",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "nodejs",
            "express",
            "fastify",
            "nestjs",
            "rest_api",
            "graphql_api",
            "websocket",
            "file_upload",
            "authentication",
            "middleware",
            "error_handling",
            "npm",
            "yarn",
            "pnpm",
            "async_programming",
            "event_loop",
            "streaming",
            "cluster",
            "worker_threads",
            "typescript_integration",
            "database_integration",
            "testing",
            "security",
            "performance_optimization",
        ]


module = CogBackendNodejs()
