from cog.cog_module import CogModule

class CogInfraGithub(CogModule):
    name = "cog-infra-github"
    version = "1.0.0"
    description = "GitHub Actions CI/CD expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## GitHub Actions CI/CD Expertise",
            "",
            "### Core Concepts",
            "- Workflows (automated processes defined in YAML)",
            "- Events (triggers: push, pull_request, schedule, workflow_dispatch)",
            "- Jobs (groups of steps executed on the same runner)",
            "- Steps (individual tasks within a job: actions or shell commands)",
            "- Actions (reusable units of code from marketplace or custom)",
            "- Runners (servers that execute workflows: GitHub-hosted or self-hosted)",
            "- Artifacts (files produced by workflows, stored temporarily)",
            "- Environments (deployment targets with protection rules)",
            "- Secrets (encrypted environment variables)",
            "- Variables (non-secret configuration values)",
            "",
            "### Workflow Triggers",
            "- push (branches, tags, paths filters)",
            "- pull_request (types: opened, synchronize, closed, etc.)",
            "- schedule (cron expressions)",
            "- workflow_dispatch (manual trigger with inputs)",
            "- repository_dispatch (external event trigger)",
            "- release (types: published, created, etc.)",
            "- issues, issue_comment, discussion, etc.",
            "- paths and paths-ignore for selective triggers",
            "- branches and branches-ignore filters",
            "",
            "### Job Configuration",
            "- runs-on (runner OS: ubuntu-latest, windows-latest, macos-latest)",
            "- needs (job dependencies for DAG execution)",
            "- if (conditional execution using expressions)",
            "- timeout-minutes (prevent hung workflows)",
            "- continue-on-error (soft failures)",
            "- strategy.matrix (parallel job variants)",
            "- strategy.fail-fast (cancel siblings on failure)",
            "- concurrency (limit simultaneous runs, cancel in-progress)",
            "- outputs (pass data between jobs)",
            "- defaults.run (default shell and working-directory)",
            "- services (sidecar containers: databases, redis, etc.)",
            "",
            "### Matrix Builds",
            "- Define OS, language version, and custom dimension combinations",
            "- include to add specific combinations",
            "- exclude to remove specific combinations",
            "- Dynamic matrix generation from JSON",
            "- ${{ matrix.variable }} interpolation in steps",
            "- Examples: test on Node 18/20/22, Python 3.10/3.11/3.12",
            "",
            "### Reusable Workflows",
            "- workflow_call event type",
            "- with and secrets for passing inputs",
            "- outputs from reusable workflows",
            "- Organize common patterns (build, test, deploy)",
            "- Call from multiple repositories",
            "",
            "### Artifacts and Caching",
            "- actions/upload-artifact and actions/download-artifact",
            "- Build artifacts (binaries, test reports, coverage)",
            "- actions/cache for dependency caching (node_modules, pip, gradle)",
            "- Cache key patterns and restore-keys",
            "- Artifact retention periods",
            "- actions/cache with cache-hit for skip logic",
            "",
            "### Releases and Deployment",
            "- Automated release creation on tag push",
            "- softprops/action-gh-release for GitHub releases",
            "- Docker image build and push to registries",
            "- Environment protection rules (required reviewers, timers)",
            "- Deployment records in GitHub UI",
            "- OIDC authentication with cloud providers (AWS, Azure, GCP)",
            "",
            "### GitHub CLI (gh)",
            "- gh pr create --title --body",
            "- gh pr merge --squash/--merge",
            "- gh issue create --title --body",
            "- gh release create v1.0.0 ./dist/*",
            "- gh workflow run <workflow> --ref <branch>",
            "- gh run list / gh run view / gh run watch",
            "- gh api for direct API calls",
            "",
            "### Best Practices",
            "- Pin actions to commit SHA, not tags (security)",
            "- Use OIDC over long-lived secrets for cloud auth",
            "- Minimize secret exposure with GitHub-environments",
            "- Cache dependencies to speed up workflows",
            "- Use concurrency groups to prevent duplicate runs",
            "- Set timeout-minutes on all jobs",
            "- Use paths filters to avoid unnecessary runs",
            "- Use reusable workflows for DRY pipeline definitions",
            "- Scan for vulnerable actions with action security tools",
            "- Use dependabot for action version updates",
            "",
            "### Common Operations",
            "GitHub CLI:",
            "```bash",
            "gh auth login",
            "gh repo clone owner/repo",
            "gh pr create --title 'feat: add auth' --body 'description'",
            "gh pr checks",
            "gh pr merge 42 --squash --delete-branch",
            "gh issue create --title 'Bug: crash on login' --label bug",
            "gh release create v1.0.0 --title 'v1.0.0' --notes 'Release notes'",
            "gh workflow run deploy.yml -f environment=production",
            "gh run watch",
            "```",
            "",
            "### Example CI Workflow",
            "```yaml",
            "name: CI",
            "on:",
            "  push:",
            "    branches: [main]",
            "    paths-ignore: ['docs/**', '*.md']",
            "  pull_request:",
            "    branches: [main]",
            "",
            "concurrency:",
            "  group: ci-${{ github.ref }}",
            "  cancel-in-progress: true",
            "",
            "jobs:",
            "  test:",
            "    runs-on: ubuntu-latest",
            "    timeout-minutes: 15",
            "    strategy:",
            "      fail-fast: false",
            "      matrix:",
            "        node-version: [18, 20, 22]",
            "",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - name: Setup Node.js ${{ matrix.node-version }}",
            "        uses: actions/setup-node@v4",
            "        with:",
            "          node-version: ${{ matrix.node-version }}",
            "          cache: npm",
            "      - run: npm ci",
            "      - run: npm run lint",
            "      - run: npm test -- --coverage",
            "      - uses: actions/upload-artifact@v4",
            "        if: matrix.node-version == 22",
            "        with:",
            "          name: coverage-report",
            "          path: coverage/",
            "",
            "  build:",
            "    needs: test",
            "    runs-on: ubuntu-latest",
            "    outputs:",
            "      version: ${{ steps.meta.outputs.version }}",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-node@v4",
            "        with:",
            "          node-version: 22",
            "          cache: npm",
            "      - run: npm ci",
            "      - run: npm run build",
            "      - uses: actions/upload-artifact@v4",
            "        with:",
            "          name: build-output",
            "          path: dist/",
            "      - id: meta",
            "        run: echo \"version=$(node -p 'require(\"./package.json\").version')\" >> \"$GITHUB_OUTPUT\"",
            "",
            "  deploy:",
            "    needs: build",
            "    if: github.ref == 'refs/heads/main' && github.event_name == 'push'",
            "    runs-on: ubuntu-latest",
            "    environment: production",
            "    steps:",
            "      - uses: actions/download-artifact@v4",
            "        with:",
            "          name: build-output",
            "          path: dist/",
            "      - name: Deploy to production",
            "        run: echo \"Deploying v${{ needs.build.outputs.version }}\"",
            "```",
            "",
            "### Example Release Workflow",
            "```yaml",
            "name: Release",
            "on:",
            "  push:",
            "    tags: ['v*']",
            "",
            "jobs:",
            "  release:",
            "    runs-on: ubuntu-latest",
            "    permissions:",
            "      contents: write",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-node@v4",
            "        with:",
            "          node-version: 22",
            "      - run: npm ci",
            "      - run: npm run build",
            "      - name: Create release",
            "        uses: softprops/action-gh-release@v2",
            "        with:",
            "          files: dist/*.tar.gz",
            "          generate_release_notes: true",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["github_actions", "github", "cicd", "github_api", "pull_requests", "issues", "releases", "matrix_builds", "gh_cli"]

module = CogInfraGithub()
