from cog.cog_module import CogModule

class CogInfraDocker(CogModule):
    name = "cog-infra-docker"
    version = "1.0.0"
    description = "Docker containerization expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Docker Containerization Expertise",
            "",
            "### Core Concepts",
            "- Images (read-only templates for containers)",
            "- Containers (running instances of images)",
            "- Layers (union filesystem, copy-on-write)",
            "- Dockerfile (build instructions for images)",
            "- Docker Engine (runtime daemon)",
            "- Docker Hub / private registries",
            "- Volumes (persistent data storage)",
            "- Networks (container communication)",
            "- Build context (directory sent to daemon)",
            "- Build cache (layer caching for faster builds)",
            "",
            "### Dockerfile Best Practices",
            "- Use specific base image tags, avoid :latest",
            "- Minimize the number of layers",
            "- Order instructions from least to most frequently changing",
            "- Use .dockerignore to exclude unnecessary files",
            "- Prefer COPY over ADD",
            "- Use multi-stage builds to reduce final image size",
            "- Run as non-root user (USER directive)",
            "- Pin package versions in RUN commands",
            "- Combine RUN commands with && to reduce layers",
            "- Use --no-install-recommends with apt-get",
            "- Clean up package caches in the same layer",
            "- Set HEALTHCHECK for long-running services",
            "- Use ENTRYPOINT for executables, CMD for default arguments",
            "",
            "### Multi-Stage Builds",
            "- Separate build dependencies from runtime",
            "- Use AS keyword to name stages",
            "- COPY --from=<stage> to extract artifacts",
            "- Reduces final image size dramatically",
            "- Common pattern: builder stage + slim runtime stage",
            "- Can copy from external images (COPY --from=nginx:latest)",
            "",
            "### Docker Compose",
            "- Define multi-container applications in YAML",
            "- Service discovery via service names as hostnames",
            "- Volume mounts for development (bind mounts)",
            "- Network isolation with custom networks",
            "- Depends_on for startup ordering",
            "- Healthchecks in compose for readiness",
            "- Override files (docker-compose.override.yml)",
            "- Profile-based service selection",
            "- Environment variable interpolation and .env files",
            "- Resource limits (cpus, memory)",
            "",
            "### Networking",
            "- Bridge networks (default, user-defined)",
            "- Host network (share host networking stack)",
            "- Overlay networks (Swarm / multi-host)",
            "- Macvlan (container gets own MAC address)",
            "- None network (no networking)",
            "- Port mapping (-p host:container)",
            "- DNS resolution via service names",
            "- Network aliases for custom DNS",
            "- Internal networks (no external access)",
            "",
            "### Volumes and Storage",
            "- Named volumes (managed by Docker)",
            "- Bind mounts (host directory mapping)",
            "- tmpfs mounts (in-memory storage)",
            "- Volume drivers for external storage backends",
            "- Backup strategies: docker run --volumes-from",
            "- Volume labels for metadata",
            "- Anonymous volumes vs named volumes",
            "",
            "### Image Optimization",
            "- Use slim or alpine base images",
            "- Multi-stage builds to shed build tools",
            "- Remove unnecessary files in same RUN layer",
            "- Use .dockerignore aggressively",
            "- Squash layers with --squash (experimental)",
            "- Use dive to analyze image layers",
            "- Scan images with Trivy or Snyk for vulnerabilities",
            "- Distroless images for minimal attack surface",
            "",
            "### Common Operations",
            "Build image:",
            "```bash",
            "docker build -t myapp:1.0 .",
            "docker build --no-cache -t myapp:1.0 .",
            "docker build --build-arg VERSION=1.0 -t myapp .",
            "```",
            "",
            "Run container:",
            "```bash",
            "docker run -d --name myapp -p 8080:80 myapp:1.0",
            "docker run -d --name myapp --restart unless-stopped myapp:1.0",
            "docker run -it --rm ubuntu:22.04 bash",
            "```",
            "",
            "Compose commands:",
            "```bash",
            "docker compose up -d",
            "docker compose down -v",
            "docker compose logs -f app",
            "docker compose exec app bash",
            "docker compose build --no-cache",
            "docker compose ps",
            "```",
            "",
            "Debugging:",
            "```bash",
            "docker logs -f <container>",
            "docker exec -it <container> bash",
            "docker inspect <container>",
            "docker stats",
            "docker system df",
            "docker system prune -a --volumes",
            "```",
            "",
            "Registry operations:",
            "```bash",
            "docker tag myapp:1.0 registry.example.com/myapp:1.0",
            "docker push registry.example.com/myapp:1.0",
            "docker pull registry.example.com/myapp:1.0",
            "docker login registry.example.com",
            "```",
            "",
            "### Example Multi-Stage Dockerfile",
            "```dockerfile",
            "FROM node:20-alpine AS builder",
            "WORKDIR /app",
            "COPY package*.json ./",
            "RUN npm ci --only=production",
            "COPY . .",
            "RUN npm run build",
            "",
            "FROM node:20-alpine AS runtime",
            "RUN addgroup -g 1001 appgroup && adduser -u 1001 -G appgroup -s /bin/sh -D appuser",
            "WORKDIR /app",
            "COPY --from=builder --chown=appuser:appgroup /app/dist ./dist",
            "COPY --from=builder --chown=appuser:appgroup /app/node_modules ./node_modules",
            "USER appuser",
            "EXPOSE 3000",
            "HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/health || exit 1",
            "CMD [\"node\", \"dist/server.js\"]",
            "```",
            "",
            "### Example Docker Compose File",
            "```yaml",
            "version: '3.8'",
            "services:",
            "  app:",
            "    build:",
            "      context: .",
            "      target: runtime",
            "    ports:",
            "      - '3000:3000'",
            "    environment:",
            "      DATABASE_URL: postgres://user:pass@db:5432/mydb",
            "    depends_on:",
            "      db:",
            "        condition: service_healthy",
            "    volumes:",
            "      - ./src:/app/src",
            "    networks:",
            "      - frontend",
            "      - backend",
            "    deploy:",
            "      resources:",
            "        limits:",
            "          cpus: '0.5'",
            "          memory: 512M",
            "  db:",
            "    image: postgres:16-alpine",
            "    environment:",
            "      POSTGRES_USER: user",
            "      POSTGRES_PASSWORD: pass",
            "      POSTGRES_DB: mydb",
            "    volumes:",
            "      - pgdata:/var/lib/postgresql/data",
            "    healthcheck:",
            "      test: ['CMD-SHELL', 'pg_isready -U user']",
            "      interval: 5s",
            "      timeout: 5s",
            "      retries: 5",
            "    networks:",
            "      - backend",
            "volumes:",
            "  pgdata:",
            "networks:",
            "  frontend:",
            "  backend:",
            "    internal: true",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["docker", "dockerfile", "docker_compose", "containerization", "multi_stage_builds", "container_networking", "volumes", "image_optimization"]

module = CogInfraDocker()
