from cog.cog_module import CogModule


class CogDbElasticsearch(CogModule):
    name = "cog-db-elasticsearch"
    version = "1.0.0"
    description = "Elasticsearch module covering indexing, mappings, analyzers, search queries, aggregations, cluster management, shards, replicas, Elasticsearch DSL, Kibana, Logstash pipelines, and ingest pipelines"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Elasticsearch",
            "",
            "### Indexing & Document Operations",
            "- Create index with settings: `PUT /products { \"settings\": { \"number_of_shards\": 3, \"number_of_replicas\": 1 } }`",
            "- Index a document: `POST /products/_doc/1 { \"name\": \"Widget\", \"price\": 29.99, \"category\": \"electronics\" }`",
            "- Bulk indexing for throughput: use `_bulk` endpoint with NDJSON action+doc pairs",
            "- Bulk format: `{ \"index\": { \"_index\": \"products\", \"_id\": \"1\" } }\\n{ \"name\": \"Widget\" }\\n`",
            "- Update partial document: `POST /products/_update/1 { \"doc\": { \"price\": 24.99 } }`",
            "- Upsert: `POST /products/_update/1 { \"doc\": { \"price\": 24.99 }, \"doc_as_upsert\": true }`",
            "- Delete by query: `POST /products/_delete_by_query { \"query\": { \"range\": { \"price\": { \"lt\": 5 } } } }`",
            "- Use `_create` instead of `_doc` to fail if document already exists (prevent accidental overwrites)",
            "",
            "### Mappings & Field Types",
            "- Define explicit mappings before indexing: `PUT /products/_mapping { \"properties\": { \"name\": { \"type\": \"text\", \"analyzer\": \"english\" }, \"sku\": { \"type\": \"keyword\" } } }`",
            "- Use `keyword` for exact match, filtering, sorting, aggregations; `text` for full-text search",
            "- Nested type for arrays of objects: `{ \"type\": \"nested\" }` preserves object boundaries for querying",
            "- Use `flattened` type for dynamic objects with unknown keys to avoid mapping explosion",
            "- Date formats: `{ \"type\": \"date\", \"format\": \"yyyy-MM-dd||epoch_millis\" }`",
            "- Use `alias` field type to create alternate names for existing fields without reindexing",
            "- Runtime fields (7.12+): compute values at query time without changing schema: `{ \"type\": \"runtime\", \"script\": \"emit(doc['price'].value * params.tax_rate)\" }`",
            "- Reindex with mapping changes: `POST _reindex { \"source\": { \"index\": \"old\" }, \"dest\": { \"index\": \"new\" } }`",
            "",
            "### Analyzers & Tokenization",
            "- Built-in analyzers: `standard`, `simple`, `whitespace`, `stop`, `keyword`, `pattern`, `english`, `french`",
            "- Custom analyzer: define in index settings with char_filters, tokenizer, and token_filters",
            "- Example: `{ \"analyzer\": { \"my_analyzer\": { \"type\": \"custom\", \"tokenizer\": \"standard\", \"filter\": [\"lowercase\", \"stop\", \"snowball\"] } } }`",
            "- Use `_analyze` API to test: `POST /products/_analyze { \"analyzer\": \"standard\", \"text\": \"Hello World 123\" }`",
            "- Synonym filter: `{ \"filter\": { \"my_synonyms\": { \"type\": \"synonym\", \"synonyms\": [\"tv, television\"] } } }`",
            "- N-gram tokenizer for autocomplete: `{ \"tokenizer\": { \"my_ngram\": { \"type\": \"ngram\", \"min_gram\": 3, \"max_gram\": 4 } } }`",
            "- Use multi-fields to index same text with different analyzers: `{ \"type\": \"text\", \"fields\": { \"keyword\": { \"type\": \"keyword\" }, \"english\": { \"type\": \"text\", \"analyzer\": \"english\" } } }`",
            "",
            "### Search Queries (DSL)",
            "- Match query (full-text): `{ \"query\": { \"match\": { \"name\": { \"query\": \"wireless keyboard\", \"operator\": \"and\", \"fuzziness\": \"AUTO\" } } } }`",
            "- Term query (exact): `{ \"query\": { \"term\": { \"status\": { \"value\": \"published\" } } } }` — never use for text fields",
            "- Bool query (combine): `{ \"query\": { \"bool\": { \"must\": [...], \"should\": [...], \"filter\": [...], \"must_not\": [...] } } }`",
            "- Use `filter` clause in bool for caching — no scoring needed for yes/no conditions",
            "- Range query: `{ \"query\": { \"range\": { \"price\": { \"gte\": 10, \"lte\": 100 } } } }`",
            "- Multi-match: `{ \"query\": { \"multi_match\": { \"query\": \"laptop\", \"fields\": [\"name^3\", \"description\"] } } }` — boost with `^N`",
            "- Function score for custom ranking: boost by popularity, recency, or script score",
            "- Search after for deep pagination instead of `from/size`: `{ \"query\": { \"match_all\": {} }, \"sort\": [{ \"date\": \"desc\" }, { \"_id\": \"asc\" }], \"search_after\": [\"2025-01-01\", \"abc123\"] }`",
            "",
            "### Aggregations",
            "- Terms agg: `{ \"aggs\": { \"by_category\": { \"terms\": { \"field\": \"category.keyword\", \"size\": 20 } } } }`",
            "- Stats agg: `{ \"aggs\": { \"price_stats\": { \"stats\": { \"field\": \"price\" } } } }` returns min, max, avg, sum, count",
            "- Date histogram: `{ \"aggs\": { \"over_time\": { \"date_histogram\": { \"field\": \"created_at\", \"calendar_interval\": \"month\" } } } }`",
            "- Nested agg: `{ \"aggs\": { \"by_cat\": { \"terms\": { \"field\": \"category\" }, \"aggs\": { \"avg_price\": { \"avg\": { \"field\": \"price\" } } } } } }`",
            "- Filter agg: `{ \"aggs\": { \"expensive\": { \"filter\": { \"range\": { \"price\": { \"gte\": 100 } } }, \"aggs\": { \"avg_rating\": { \"avg\": { \"field\": \"rating\" } } } } } }`",
            "- Cardinality for unique count: `{ \"aggs\": { \"unique_authors\": { \"cardinality\": { \"field\": \"author_id\" } } } }`",
            "- Composite agg for pagination of agg results: use `after_key` for cursor-based iteration",
            "",
            "### Cluster Management, Shards & Replicas",
            "- Cluster health: `GET _cluster/health` — green/yellow/red status with shard counts",
            "- Node info: `GET _cat/nodes?v&h=name,heap.percent,ram.percent,cpu,load_1m,node.role,master`",
            "- Shard allocation awareness: set `cluster.routing.allocation.awareness.attributes: zone` for cross-zone resilience",
            "- Adjust replicas at runtime: `PUT /products/_settings { \"index.number_of_replicas\": 2 }`",
            "- Force merge read-only indices: `POST /products/_forcemerge?max_num_segments=1` (only on indices no longer receiving writes)",
            "- Use ILM (Index Lifecycle Management) to automate rollover, shrink, force-merge, delete",
            "- ILM policy: hot (rollover at 50GB or 30 days) → warm (force-merge, read-only) → cold (searchable snapshots) → delete",
            "- Split shards at index creation time only; use reindex or shrink to reduce shards later",
            "",
            "### Kibana, Logstash & Ingest Pipelines",
            "- Kibana Dev Tools console uses `GET`, `POST`, `PUT`, `DELETE` prefixes instead of curl",
            "- Kibana saved searches, visualizations, and dashboards are stored in `.kibana` index",
            "- Logstash pipeline: input → filter (grok, mutate, date) → output",
            "- Logstash grok: `grok { match => { \"message\" => \"%{IP:client_ip} %{WORD:method} %{URIPATH:path} %{NUMBER:bytes:int} %{NUMBER:response_time:float}\" } }`",
            "- Logstash conditional: `if [response_code] >= 500 { ... } else if [response_code] >= 400 { ... }`",
            "- Ingest pipeline (built into ES): `PUT _ingest/pipeline/my_pipeline { \"processors\": [{ \"set\": { \"field\": \"indexed_at\", \"value\": \"{{_ingest.timestamp}}\" } }, { \"remove\": { \"field\": \"debug_info\" } }] }`",
            "- Attach pipeline to index: `PUT /logs/_settings { \"index.default_pipeline\": \"my_pipeline\" }`",
            "- Simulate pipeline before applying: `POST _ingest/pipeline/my_pipeline/_simulate { \"docs\": [{ \"_source\": { \"message\": \"test\" } }] }`",
            "",
            "### Elasticsearch DSL (Python Client)",
            "- Use `elasticsearch-dsl` Python library for type-safe query construction",
            "- Search object: `s = Search(using=client, index='products').query('match', name='laptop').filter('range', price={'gte': 500})`",
            "- Chain queries: `s = s.query('bool', must=[Q('match', title='phone')], filter=[Q('term', brand='apple')])`",
            "- Aggregation: `s.aggs.bucket('categories', 'terms', field='category.keyword').metric('avg_price', 'avg', field='price')`",
            "- Execute: `response = s.execute()` then iterate `response.hits` and `response.aggregations.categories.buckets`",
            "- Bulk helpers: `from elasticsearch.helpers import bulk; bulk(client, actions)` where actions are dicts",
            "",
            "### Commands",
            "```bash",
            "curl -X PUT 'localhost:9200/products' -H 'Content-Type: application/json' -d '{\"settings\": {\"number_of_shards\": 3}}'",
            "curl -X POST 'localhost:9200/products/_doc' -H 'Content-Type: application/json' -d '{\"name\": \"Widget\"}'",
            "curl -X POST 'localhost:9200/_bulk' -H 'Content-Type: application/json' --data-binary @bulk.json",
            "curl -X GET 'localhost:9200/products/_search' -H 'Content-Type: application/json' -d '{\"query\": {\"match\": {\"name\": \"laptop\"}}}'",
            "curl -X GET 'localhost:9200/_cluster/health?pretty'",
            "curl -X GET 'localhost:9200/_cat/indices?v&h=index,docs.count,store.size,pri,rep'",
            "curl -X GET 'localhost:9200/_cat/shards?v&h=index,shard,prirep,state,docs,store,node'",
            "curl -X PUT 'localhost:9200/_ingest/pipeline/my_pipeline' -H 'Content-Type: application/json' -d @pipeline.json",
            "curl -X POST 'localhost:9200/products/_forcemerge?max_num_segments=1'",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "indexing",
            "mappings",
            "analyzers",
            "search-queries",
            "aggregations",
            "cluster-management",
            "shards",
            "replicas",
            "elasticsearch-dsl",
            "kibana",
            "logstash",
            "ingest-pipelines",
        ]


module = CogDbElasticsearch()
