from cog.cog_module import CogModule

class CogInfraJenkins(CogModule):
    name = "cog-infra-jenkins"
    version = "1.0.0"
    description = "Jenkins CI/CD expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Jenkins CI/CD Expertise",
            "",
            "### Core Concepts",
            "- Jenkinsfile (pipeline-as-code in SCM)",
            "- Declarative Pipeline (structured, opinionated syntax)",
            "- Scripted Pipeline (Groovy-based, flexible)",
            "- Agents (execution environments: any, label, docker, kubernetes)",
            "- Nodes (machines running Jenkins agents)",
            "- Stages (logical grouping of work)",
            "- Steps (individual operations: sh, bat, echo, git, etc.)",
            "- Shared Libraries (reusable Groovy code across pipelines)",
            "- Credentials (stored secrets: username/password, SSH keys, tokens)",
            "- Plugins (extensible functionality ecosystem)",
            "- Builds (individual executions of a job/pipeline)",
            "- Workspaces (per-build directory on agent)",
            "",
            "### Declarative Pipeline",
            "- pipeline {} top-level block",
            "- agent (any, none, label, docker, kubernetes)",
            "- stages {} containing stage blocks",
            "- environment {} for environment variables",
            "- parameters {} for build parameterization",
            "- triggers {} for automatic build triggers",
            "- options {} for pipeline-level settings",
            "- post {} for post-build actions (always, success, failure, unstable)",
            "- tools {} for auto-installing tools",
            "- when {} directive for conditional stage execution",
            "- input {} for manual approval steps",
            "- Parallel stages with parallel {} block",
            "- Matrix builds with matrix { axes { axis } }",
            "",
            "### Scripted Pipeline",
            "- Groovy-based, full programming flexibility",
            "- node {} block for agent allocation",
            "- stage('name') {} for logical grouping",
            "- Standard Groovy control flow: if/else, try/catch, for loops",
            "- Binding variables: env, params, currentBuild, scm",
            "- catchError for non-fatal error handling",
            "- Lockable resources with lock()",
            "- Timed operations with timeout()",
            "- Retry with retry(N)",
            "- Milestone for build ordering",
            "",
            "### Shared Libraries",
            "- Global shared libraries (configured in Manage Jenkins)",
            "- Folder-level shared libraries",
            "- Standard structure: vars/*.groovy, src/**/*.groovy",
            "- @Library('name') annotation for importing",
            "- @Library('name@branch') for branch selection",
            "- Custom steps in vars/globalVar.groovy",
            "- Object-oriented code in src/ using Groovy classes",
            "- Access Jenkins internals via Jenkins.getInstance()",
            "- Library versioning and changelog",
            "",
            "### Agents and Distribution",
            "- Built-in agent (controller node, not recommended for production)",
            "- SSH agents (connect via SSH to remote machines)",
            "- JNLP agents (connect outbound from agent to controller)",
            "- Docker agents (ephemeral build containers)",
            "- Kubernetes agents (dynamic pod provisioning)",
            "- Agent labels for capability matching",
            "- Agent offline handling and retention",
            "- Agent root directory and tool locations",
            "",
            "### Credentials Management",
            "- Jenkins credentials store (system-level)",
            "- Credential types: Username/password, SSH key, Secret text, Secret file",
            "- Certificate credentials (PKCS#12, PEM)",
            "- Credentials binding in pipelines with withCredentials()",
            "- Credential scopes: System, Global",
            "- Credentials plugin for masking secrets in logs",
            "- HashiCorp Vault integration for external secrets",
            "- AWS Secrets Manager plugin",
            "- Credential rotation and expiration",
            "",
            "### Key Plugins",
            "- Pipeline (workflow-aggregator)",
            "- Git plugin and Git Client plugin",
            "- Docker Pipeline plugin",
            "- Kubernetes plugin",
            "- Credentials Binding plugin",
            "- Blue Ocean (modern UI)",
            "- Pipeline Utility Steps (readJSON, writeJSON, etc.)",
            "- Artifactory plugin",
            "- SonarQube plugin",
            "- Slack/Teams notification plugins",
            "- Email Extension plugin",
            "- Parameterized Trigger plugin",
            "- Build User Vars plugin",
            "",
            "### Build Triggers",
            "- SCM polling (Poll SCM: H/5 * * * *)",
            "- Webhook triggers (GitHub webhook, GitLab webhook)",
            "- Periodic builds (Build periodically: H H(0-2) * * *)",
            "- Upstream/downstream job triggers",
            "- Parameterized triggers from other jobs",
            "- Generic Webhook Trigger plugin",
            "- Cron syntax with H (hash) for load distribution",
            "",
            "### Best Practices",
            "- Always use pipelines-as-code (Jenkinsfile in SCM)",
            "- Use declarative pipeline over scripted when possible",
            "- Don't run builds on the controller node",
            "- Use ephemeral agents (Docker/Kubernetes) for reproducibility",
            "- Use withCredentials for all secret access",
            "- Archive artifacts for downstream consumption",
            "- Use shared libraries to reduce code duplication",
            "- Set build discarder to limit build history",
            "- Use timeouts to prevent hung builds",
            "- Implement proper error handling with post blocks",
            "- Use multibranch pipelines for branch-based CI/CD",
            "- Parameterize pipelines for flexibility",
            "- Use when directives to skip unnecessary stages",
            "",
            "### Common Operations",
            "Jenkins CLI:",
            "```bash",
            "java -jar jenkins-cli.jar -s http://localhost:8080/ build my-job",
            "java -jar jenkins-cli.jar -s http://localhost:8080/ console my-job 42",
            "java -jar jenkins-cli.jar -s http://localhost:8080/ list-jobs",
            "java -jar jenkins-cli.jar -s http://localhost:8080/ reload-configuration",
            "```",
            "",
            "Script console (Manage Jenkins > Script Console):",
            "```groovy",
            "Jenkins.instance.getItemByFullName('my-job').builds.each { build ->",
            "  println \"\\${build.number}: \\${build.result}\"",
            "}",
            "",
            "Jenkins.instance.nodes.each { node ->",
            "  println \"\\${node.name}: \\${node.toComputer().offline ? 'offline' : 'online'}\"",
            "}",
            "```",
            "",
            "### Example Declarative Pipeline",
            "```groovy",
            "@Library('shared-lib') _",
            "",
            "pipeline {",
            "    agent none",
            "",
            "    options {",
            "        buildDiscarder(logRotator(numToKeepStr: '20'))",
            "        timeout(time: 30, unit: 'MINUTES')",
            "        timestamps()",
            "        ansiColor('xterm')",
            "        disableConcurrentBuilds()",
            "    }",
            "",
            "    environment {",
            "        DOCKER_REGISTRY = credentials('docker-registry-url')",
            "        REGISTRY_CREDS = credentials('docker-registry-creds')",
            "        APP_NAME = 'myapp'",
            "        VERSION = \"${env.BUILD_NUMBER}\"",
            "    }",
            "",
            "    stages {",
            "        stage('Build') {",
            "            agent {",
            "                docker {",
            "                    image 'node:20-alpine'",
            "                    args '-p 3000:3000'",
            "                }",
            "            }",
            "            steps {",
            "                sh 'npm ci'",
            "                sh 'npm run build'",
            "            }",
            "        }",
            "",
            "        stage('Test') {",
            "            agent {",
            "                docker {",
            "                    image 'node:20-alpine'",
            "                }",
            "            }",
            "            steps {",
            "                sh 'npm ci'",
            "                sh 'npm test'",
            "            }",
            "            post {",
            "                always {",
            "                    junit 'reports/junit.xml'",
            "                }",
            "            }",
            "        }",
            "",
            "        stage('Docker Build & Push') {",
            "            agent any",
            "            when {",
            "                anyOf {",
            "                    branch 'main'",
            "                    branch 'develop'",
            "                    tag 'v*'",
            "                }",
            "            }",
            "            steps {",
            "                sh \"docker build -t ${DOCKER_REGISTRY}/${APP_NAME}:${VERSION} .\"",
            "                sh \"docker push ${DOCKER_REGISTRY}/${APP_NAME}:${VERSION}\"",
            "            }",
            "        }",
            "",
            "        stage('Deploy') {",
            "            agent any",
            "            when {",
            "                branch 'main'",
            "            }",
            "            input {",
            "                message 'Deploy to production?'",
            "                ok 'Deploy'",
            "            }",
            "            steps {",
            "                sh \"kubectl set image deployment/${APP_NAME} ${APP_NAME}=${DOCKER_REGISTRY}/${APP_NAME}:${VERSION}\"",
            "                sh \"kubectl rollout status deployment/${APP_NAME} --timeout=300s\"",
            "            }",
            "        }",
            "    }",
            "",
            "    post {",
            "        failure {",
            "            slackSend(",
            "                color: 'danger',",
            "                message: \"Build ${env.JOB_NAME} #${env.BUILD_NUMBER} failed: ${env.BUILD_URL}\"",
            "            )",
            "        }",
            "        success {",
            "            slackSend(",
            "                color: 'good',",
            "                message: \"Build ${env.JOB_NAME} #${env.BUILD_NUMBER} succeeded\"",
            "            )",
            "        }",
            "        always {",
            "            cleanWs()",
            "        }",
            "    }",
            "}",
            "```",
            "",
            "### Example Shared Library (vars/deploy.groovy)",
            "```groovy",
            "def call(String environment, String image) {",
            "    stage(\"Deploy to ${environment}\") {",
            "        def namespace = environment == 'production' ? 'prod' : 'staging'",
            "        sh \"\"\"kubectl set image deployment/myapp -n ${namespace} \\",
            "            myapp=${image} --record\"\"\"",
            "        sh \"\"\"kubectl rollout status deployment/myapp -n ${namespace} --timeout=300s\"\"\"",
            "    }",
            "}",
            "```",
            "",
            "### Troubleshooting",
            "- Check build console output for error details",
            "- Use replay to modify and re-run pipeline script",
            "- Check agent connectivity in Manage Jenkins > Nodes",
            "- Review pipeline steps with Pipeline Steps view",
            "- Use BRANCH_NAME and CHANGE_ID for multibranch pipelines",
            "- Resolve script approval issues in In-process Script Approval",
            "- Restart Jenkins safely: safeRestart from CLI or /safeRestart URL",
        ]

    def get_capabilities(self) -> list[str]:
        return ["jenkins", "cicd", "jenkinsfile", "declarative_pipeline", "scripted_pipeline", "shared_libraries", "jenkins_plugins", "continuous_integration"]

module = CogInfraJenkins()
