from cog.cog_module import CogModule

class CogFrameworkNuxtjs(CogModule):
    name = "cog-framework-nuxtjs"
    version = "1.0.0"
    description = "Nuxt.js framework expertise"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Nuxt.js Framework Expertise",
            "",
            "### Core Architecture",
            "- Built on Vue 3 with automatic configuration",
            "- File-based routing under pages/ directory",
            "- Auto-imports for components, composables, and utilities",
            "- Nuxt 3 uses Nitro as its server engine",
            "- Hybrid rendering with route rules per-page",
            "- Supports SSR, SSG, SPA, and hybrid modes",
            "- Built-in TypeScript support with auto-generated types",
            "- Module system for extending core functionality",
            "",
            "### Auto-Imports",
            "- Components in components/ are auto-imported",
            "- Composables in composables/ are auto-imported (useXxx pattern)",
            "- Utilities in utils/ are auto-imported",
            "- No manual import statements needed for these directories",
            ".nuxt/imports.d.ts provides TypeScript declarations",
            "- Configure additional auto-import paths in nuxt.config.ts",
            "",
            "### Routing System",
            "- File-based routing: pages/index.vue maps to /",
            "- Dynamic routes: pages/blog/[slug].vue maps to /blog/:slug",
            "- Nested routes with NuxtPage component",
            "- Route middleware: definePageMeta({ middleware: ['auth'] })",
            "- Navigation with navigateTo() utility",
            "- useRoute() for current route info, useRouter() for navigation",
            "- Route rules for per-route rendering mode (ssr, swr, prerender)",
            "",
            "### Composables",
            "- useFetch(url) — data fetching with SSR support",
            "- useAsyncData(key, fn) — async data with caching and deduplication",
            "- useState(key, fn) — cross-component shared state (SSR-safe)",
            "- useHead() — manage head tags (title, meta, links)",
            "- useRoute() / useRouter() — routing information",
            "- useCookie(name) — SSR-safe cookie access",
            "- useRequestHeaders() — access server request headers",
            "- useAppConfig() — access runtime app configuration",
            "- useRuntimeConfig() — access environment variables and config",
            "- Custom composables in composables/ directory",
            "",
            "### Nitro Server Engine",
            "- Server routes in server/api/ directory",
            "- Event handlers: defineEventHandler()",
            "- Supports GET, POST, PUT, DELETE via file naming",
            "- server/api/users.get.ts — GET handler for /api/users",
            "- server/api/users/[id].get.ts — dynamic route parameter",
            "- Server middleware in server/middleware/",
            "- Cross-platform deployment targets (Node, Deno, Cloudflare, Vercel)",
            "- Built-in caching with cachedEventHandler()",
            "- Storage layer with useStorage() for key-value operations",
            "- Nitro presets for deployment targets",
            "",
            "### Layers",
            "- Extend Nuxt applications with reusable layers",
            "- Layers provide components, composables, pages, server routes",
            "- Configured in nuxt.config.ts extends array",
            "- Local path or git repository as layer source",
            "- Layer priority: local app > last layer > first layer",
            "- Useful for shared design systems and utility libraries",
            "",
            "### Data Fetching with useFetch",
            "- Automatic SSR data fetching on server, hydration on client",
            "- useFetch deduplicates requests during SSR",
            "- Options: method, body, query, headers, immediate, watch",
            "- Returns { data, pending, error, refresh, status }",
            "- useLazyFetch for non-blocking client-side fetching",
            "- $fetch for raw API calls without composables",
            "- Transform and pick options for response shaping",
            "",
            "### SSR and SSG Modes",
            "- SSR mode: server renders pages on each request",
            "- SSG mode: pre-render all pages at build time (nuxt generate)",
            "- Hybrid: route rules specify mode per route",
            "- routeRules: { '/blog/**': { swr: 3600 }, '/admin/**': { ssr: false } }",
            "- prerenderRoutes for build-time static generation",
            "- CSR fallback with ssr: false for SPA-like pages",
            "",
            "### State Management",
            "- useState() for SSR-safe cross-component state",
            "- Pinia integration via @pinia/nuxt module",
            "- usePinia() composable auto-imported with module",
            "- Store patterns: defineStore with setup or options API",
            "- App config with useAppConfig() for shared reactive config",
            "- Avoid shared mutable state outside of useState/Pinia",
            "",
            "### Middleware",
            "- Route middleware in middleware/ directory",
            "- Named middleware: export default defineNuxtRouteMiddleware()",
            "- Global middleware: named with .global suffix",
            "- Set per-page with definePageMeta in <script setup>",
            "- abortNavigation() to block navigation",
            "- navigateTo() to redirect",
            "- Server middleware in server/middleware/ for API routes",
            "",
            "### Performance Best Practices",
            "- Use useFetch with deduplication for data loading",
            "- Lazy-load components with Lazy prefix (LazyMyComponent)",
            "- Configure route rules for optimal rendering per page",
            "- Use Nuxt Image module for optimized images (@nuxt/image)",
            "- Enable payload extraction for SSG with experimental.payloadExtraction",
            "- Minimize client bundle with tree-shaking auto-imports",
            "- Use Nitro caching for server API responses",
            "",
            "### Common Operations",
            "Create Nuxt app:",
            "```bash",
            "npx nuxi@latest init myapp",
            "```",
            "",
            "Development server:",
            "```bash",
            "npm run dev",
            "```",
            "",
            "Build and generate:",
            "```bash",
            "npx nuxi build",
            "npx nuxi generate",
            "npx nuxi preview",
            "```",
            "",
            "Example server API route:",
            "```typescript",
            "export default defineEventHandler(async (event) => {",
            "  const query = getQuery(event);",
            "  const body = await readBody(event);",
            "  const users = await db.user.findMany({ where: query });",
            "  return users;",
            "});",
            "```",
            "",
            "Example composable:",
            "```typescript",
            "export const useCounter = (initial = 0) => {",
            "  const count = useState<number>('counter', () => initial);",
            "  const increment = () => count.value++;",
            "  const decrement = () => count.value--;",
            "  return { count, increment, decrement };",
            "};",
            "```",
            "",
            "Example page with data fetching:",
            "```vue",
            "<script setup lang=\"ts\">",
            "const route = useRoute();",
            "const { data: post, pending } = await useFetch(`/api/posts/${route.params.slug}`);",
            "useHead({ title: () => post.value?.title });",
            "</script>",
            "",
            "<template>",
            "  <div v-if=\"pending\">Loading...</div>",
            "  <article v-else>",
            "    <h1>{{ post.title }}</h1>",
            "    <div v-html=\"post.content\"></div>",
            "  </article>",
            "</template>",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return ["nuxtjs", "auto_imports", "nitro", "ssr", "ssg", "composables", "layers", "server_routes", "middleware", "vue_ecosystem", "use_fetch", "state_management"]

module = CogFrameworkNuxtjs()
