from cog.cog_module import CogModule


class CogBackendNodejs(CogModule):
    name = "cog-backend-nodejs"
    version = "1.0.0"
    description = "Node.js backend module covering Express/Fastify, middleware patterns, async/await, error handling, streams, clustering, Worker threads, npm scripts, PM2, environment config, logging, and health checks"

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Node.js Backend Development",
            "",
            "### Express.js Fundamentals",
            "- Minimal Express app: `const app = express(); app.use(express.json()); app.listen(3000)`",
            "- Route handlers: `app.get('/users/:id', async (req, res, next) => { const user = await User.findById(req.params.id); res.json(user); })`",
            "- Use `express.Router()` for modular route organization: `const router = Router(); router.get('/', ...); module.exports = router`",
            "- Built-in middleware: `express.json()` for JSON body parsing, `express.static('public')` for file serving",
            "- Enable trust proxy in production behind reverse proxy: `app.set('trust proxy', 1)` for correct `req.ip`",
            "- Use `helmet` middleware for security headers: `app.use(helmet())` — sets HSTS, CSP, X-Frame-Options, etc.",
            "- Use `cors` middleware: `app.use(cors({ origin: 'https://app.example.com', credentials: true }))`",
            "- Route-level middleware for auth: `app.get('/admin', authenticate, authorize('admin'), handler)`",
            "",
            "### Fastify (High-Performance Alternative)",
            "- Create server: `const app = fastify({ logger: true }); app.listen({ port: 3000, host: '0.0.0.0' })`",
            "- Schema-based validation built-in: `app.post('/users', { schema: { body: { type: 'object', required: ['name', 'email'], properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' } } } } }, handler)`",
            "- Fastify hooks: `onRequest`, `preHandler`, `preSerialization`, `onResponse`, `onError` for lifecycle control",
            "- Plugins: `app.register(require('@fastify/cors'), { origin: true }); app.register(require('@fastify/jwt'), { secret: process.env.JWT_SECRET })`",
            "- Use `app.decorate('auth', authFunction)` to add custom decorators accessible in all handlers",
            "- Fastify is 2-3x faster than Express due to JSON schema validation and efficient routing via find-my-way",
            "- Decorators pattern: `app.decorateRequest('user', null)` then set in preHandler hook",
            "",
            "### Middleware Patterns",
            "- Error middleware must be last with 4 params: `app.use((err, req, res, next) => { logger.error(err); res.status(err.status || 500).json({ error: { message: err.message, code: err.code } }); })`",
            "- Request logging middleware: `app.use((req, res, next) => { const start = Date.now(); res.on('finish', () => { logger.info({ method: req.method, path: req.path, status: res.statusCode, duration: Date.now() - start }); }); next(); })`",
            "- Rate limiting: use `express-rate-limit` — `app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 100, standardHeaders: true, legacyHeaders: false }))`",
            "- Request ID middleware: `app.use((req, res, next) => { req.id = uuidv4(); res.set('X-Request-Id', req.id); next(); })`",
            "- Compose middleware: `const chain = (middleware) => (req, res, next) => middleware.reduceRight((n, fn) => () => fn(req, res, n), next)()`",
            "",
            "### Async/Await & Error Handling",
            "- Always wrap async route handlers: `const asyncHandler = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next); app.get('/data', asyncHandler(async (req, res) => { ... }))`",
            "- Express 5 has built-in async error propagation; Express 4 requires wrapper or try/catch in every handler",
            "- Custom error classes: `class AppError extends Error { constructor(message, status, code) { super(message); this.status = status; this.code = code; } }`",
            "- Use `http-errors` or custom error factory: `throw createError(404, 'User not found', { code: 'USER_NOT_FOUND' })`",
            "- Promise.allSettled for concurrent operations: `const [users, orders] = await Promise.allSettled([getUsers(), getOrders()])` — handle each result's status",
            "- Avoid unhandled promise rejections: `process.on('unhandledRejection', (reason, promise) => { logger.fatal({ reason }, 'Unhandled rejection'); process.exit(1); })`",
            "- Catch sync errors with `process.on('uncaughtException', ...)` — log and exit, don't continue in undefined state",
            "",
            "### Streams & Buffers",
            "- Readable stream: `const stream = fs.createReadStream('large.json'); stream.pipe(res)` — pipe directly to response",
            "- Transform stream: `const { Transform } = require('stream'); const upper = new Transform({ transform(chunk, enc, cb) { cb(null, chunk.toString().toUpperCase()); } })`",
            "- Pipeline for error handling (prefer over `.pipe()`): `await pipeline(readable, transform, writable)` from `stream/promises`",
            "- Pass-through for monitoring: `const pass = new PassThrough(); pass.on('data', (chunk) => bytes += chunk.length); readable.pipe(pass).pipe(writable)`",
            "- Stream CSV processing: `fs.createReadStream('data.csv').pipe(csv.parse({ headers: true })).on('data', (row) => processRow(row))`",
            "- Backpressure: Node handles automatically with `pipe()` and `pipeline()`; manual streams must check `write()` return value",
            "- Use `stream.Readable.from(array)` to convert arrays or generators into readable streams",
            "",
            "### Clustering & Worker Threads",
            "- Cluster module for multi-core utilization: `const cluster = require('cluster'); if (cluster.isPrimary) { const cpus = require('os').cpus().length; for (let i = 0; i < cpus; i++) cluster.fork(); } else { app.listen(3000); }`",
            "- PM2 manages clustering automatically: `pm2 start app.js -i max` spawns one worker per CPU core",
            "- Worker threads for CPU-intensive tasks (not I/O): `const { Worker } = require('worker_threads'); const w = new Worker('./heavy-task.js', { workerData: { input } }); w.on('message', (result) => ...)`",
            "- Pass data to workers: `workerData` for init, `parentPort.postMessage()` for ongoing communication",
            "- SharedArrayBuffer for zero-copy data sharing between workers (requires specific CORS headers)",
            "- Use `worker_threads` for image processing, compression, cryptography; use cluster for HTTP throughput",
            "",
            "### npm Scripts & Process Management",
            "- Define scripts in package.json: `\"scripts\": { \"dev\": \"nodemon src/index.js\", \"start\": \"node src/index.js\", \"test\": \"jest --coverage\", \"lint\": \"eslint src/ --fix\" }`",
            "- Cross-platform env vars: use `cross-env` — `\"start\": \"cross-env NODE_ENV=production node src/index.js\"`",
            "- PM2 ecosystem file: `module.exports = { apps: [{ name: 'api', script: 'src/index.js', instances: 'max', exec_mode: 'cluster', env: { NODE_ENV: 'production', PORT: 3000 }, max_memory_restart: '1G' }] }`",
            "- PM2 commands: `pm2 start ecosystem.config.js && pm2 logs && pm2 monit && pm2 reload api` (zero-downtime restart)",
            "- Use `npm-run-all` for parallel/serial script composition: `\"test:all\": \"run-p test:unit test:integration\"`",
            "",
            "### Environment Config & Logging",
            "- Use `dotenv` for local dev: `require('dotenv').config()` — loads `.env` into `process.env`",
            "- Validate env at startup: `const env = z.object({ PORT: z.coerce.number().default(3000), DATABASE_URL: z.string().url(), JWT_SECRET: z.string().min(32) }).parse(process.env)`",
            "- Never commit `.env` files; use `.env.example` with placeholder values for documentation",
            "- Structured logging with `pino`: `const logger = pino({ level: process.env.LOG_LEVEL || 'info', transport: process.env.NODE_ENV !== 'production' ? { target: 'pino-pretty' } : undefined })`",
            "- Log JSON in production: `{ level: 'info', time: 1234567890, msg: 'Request completed', method: 'GET', path: '/api/users', status: 200, duration: 45, requestId: 'abc123' }`",
            "- Use correlation IDs: attach `req.id` to all log entries within a request context for distributed tracing",
            "- Log levels: `logger.trace` → `debug` → `info` → `warn` → `error` → `fatal`; set `LOG_LEVEL=warn` in production",
            "",
            "### Health Checks & Graceful Shutdown",
            "- Health endpoint: `app.get('/health', (req, res) => res.json({ status: 'ok', uptime: process.uptime(), timestamp: new Date().toISOString() }))`",
            "- Readiness check with dependency probing: `app.get('/ready', async (req, res) => { try { await db.raw('SELECT 1'); await redis.ping(); res.json({ status: 'ready' }); } catch (err) { res.status(503).json({ status: 'not ready', error: err.message }); } })`",
            "- Graceful shutdown: `process.on('SIGTERM', async () => { logger.info('Shutting down...'); server.close(); await db.destroy(); await redis.quit(); process.exit(0); })`",
            "- Set `server.keepAliveTimeout = 65000` and `server.headersTimeout = 66000` when behind ALB (65s idle timeout)",
            "- Start metrics server on separate port for Prometheus scraping: separate Express app on 9090",
            "",
            "### Commands",
            "```bash",
            "npm init -y",
            "npm install express helmet cors pino pino-pretty dotenv zod",
            "npm install -D nodemon eslint jest",
            "node src/index.js",
            "pm2 start ecosystem.config.js",
            "pm2 reload api --update-env",
            "pm2 logs api --lines 100",
            "pm2 monit",
            "node -e \"const { Worker } = require('worker_threads'); new Worker('./worker.js', { workerData: { n: 42 } })\"",
            "```",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "express",
            "fastify",
            "middleware",
            "async-await",
            "error-handling",
            "streams",
            "clustering",
            "worker-threads",
            "npm-scripts",
            "pm2",
            "environment-config",
            "logging",
            "health-checks",
        ]


module = CogBackendNodejs()
