from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult
from cog.verification.base import Verifier, VerificationResult, VerificationStatus

class DockerBuildTool(Tool):
    name = "docker.build"
    description = "Build Docker image"
    required_permissions = ["shell.execute"]

    def execute(self, path: str = ".", tag: str = "latest", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"cd {path} && docker build -t {tag} ."
        result = shell.execute(command=command, timeout=600)
        return result

class DockerRunTool(Tool):
    name = "docker.run"
    description = "Run Docker container"
    required_permissions = ["shell.execute"]

    def execute(self, image: str, command: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        cmd = f"docker run --rm {image}"
        if command:
            cmd += f" {command}"
        result = shell.execute(command=cmd, timeout=300)
        return result

class DockerComposeTool(Tool):
    name = "docker.compose"
    description = "Run Docker Compose commands"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool

        shell = ShellTool()
        command = f"docker-compose {action}"
        result = shell.execute(command=command, timeout=300)
        return result

class CogInfraDocker(CogModule):
    name = "cog-infra-docker"
    version = "1.0.0"
    description = "Docker containerization expertise"

    def register_tools(self) -> list[Tool]:
        return [DockerBuildTool(), DockerRunTool(), DockerComposeTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## Docker Containerization Expertise",
            "",
            "### Docker Fundamentals",
            "- Containers vs VMs",
            "- Images and containers",
            "- Docker daemon",
            "- Docker CLI commands",
            "- Docker registry",
            "- Docker Hub",
            "",
            "### Dockerfile",
            "- FROM (base image)",
            "- RUN (execute commands)",
            "- COPY/ADD (copy files)",
            "- ENV (environment variables)",
            "- EXPOSE (expose ports)",
            "- WORKDIR (working directory)",
            "- CMD (default command)",
            "- ENTRYPOINT",
            "- VOLUME (mount points)",
            "- USER (run as user)",
            "- ARG (build-time variables)",
            "- LABEL (metadata)",
            "- HEALTHCHECK (container health)",
            "- STOPSIGNAL",
            "- SHELL",
            "",
            "### Docker Compose",
            "- Services definition",
            "- Networks (bridge, overlay, host)",
            "- Volumes and volume drivers",
            "- Environment variables",
            "- Dependencies between services",
            "- docker-compose.yml syntax",
            "- Override compose files",
            "- Multiple compose files",
            "",
            "### Docker Images",
            "- Official images",
            "- Community images",
            "- Multi-stage builds",
            "- Base images (alpine, slim)",
            "- Image optimization",
            "- Layer caching",
            "- Minimization",
            "- Security scanning",
            "",
            "### Docker Networks",
            "- Bridge network (default)",
            "- Host network",
            "- Overlay network (Swarm)",
            "- Macvlan network",
            "- Network drivers",
            "- Container communication",
            "- Service discovery",
            "",
            "### Docker Volumes",
            "- Bind mounts",
            "- Named volumes",
            "- Volume drivers",
            "- Volume plugins",
            "- Backup and restore",
            "- Data persistence",
            "- Container data sharing",
            "",
            "### Docker Security",
            "- Container isolation",
            "- Non-root user",
            "- Readonly filesystems",
            "- Resource limits",
            "- Security scanning",
            "- Vulnerability databases",
            "- Image signing",
            "- Content trust",
            "- Secrets management",
            "",
            "### Docker Orchestration",
            "- Docker Swarm",
            "- Services and tasks",
            "- Raft consensus",
            "- Load balancing",
            "- Service discovery",
            "- Rolling updates",
            "- Rollbacks",
            "- Secrets management",
            "- Config updates",
            "",
            "### Docker vs VMs",
            "- Containers: Lightweight, fast startup, resource-efficient",
            "- VMs: Complete OS, slower startup, more resources",
            "- Containers share host kernel",
            "- VMs have separate kernel",
            "- Better isolation with VMs",
            "- Better density with containers",
            "",
            "### Docker Best Practices",
            "",
            "Dockerfile patterns:",
            "- Use official base images",
            "- Use alpine for smaller images",
            "- Multi-stage builds",
            "- Layer caching",
            "- Combine RUN commands",
            "- Order layers by change frequency",
            "- Minimize layers",
            "- Remove build dependencies",
            "- Don't run as root",
            "- Scan for vulnerabilities",
            "",
            "Image optimization:",
            "- Use .dockerignore",
            "- Multi-stage builds",
            "- Copy only needed files",
            "- Use specific versions",
            "- Remove unnecessary tools",
            "- Compress layers",
            "- Use build cache",
            "- Scan images",
            "",
            "Container orchestration:",
            "- Orchestrate with compose",
            "- Use networks for communication",
            "- Use volumes for persistence",
            "- Use environment variables",
            "- Configure resource limits",
            "- Health checks",
            "- Restart policies",
            "",
            "### Common Docker Patterns",
            "",
            "Development environment:",
            "```yaml",
            "version: '3.8'",
            "services:",
            "  app:",
            "    build: .",
            "    volumes:",
            "      - .:/app",
            "    ports:",
            "      - '3000:3000'",
            "    environment:",
            "      - NODE_ENV=development",
            "  db:",
            "    image: postgres:15",
            "    environment:",
            "      - POSTGRES_PASSWORD=pass",
            "    volumes:",
            "      - dbdata:/var/lib/postgresql/data",
            "volumes:",
            "  dbdata:",
            "",
            "Production deployment:",
            "```yaml",
            "services:",
            "  web:",
            "    image: myapp:latest",
            "    deploy:",
            "      replicas: 3",
            "      update_config:",
            "        parallelism: 1",
            "        order: start-first",
            "      rollback_config:",
            "        parallelism: 1",
            "        order: start-first",
            "    environment:",
            "      - NODE_ENV=production",
            "",
            "### Docker Troubleshooting",
            "",
            "Container won't start:",
            "- Check logs: docker logs <container>",
            "- Check if image exists: docker images",
            "- Check if port conflicts: docker ps",
            "- Check resource usage: docker stats",
            "",
            "Can't connect to container:",
            "- Check network mode",
            "- Check exposed ports",
            "- Check firewall rules",
            "- Verify container is running",
            "",
            "Image build failures:",
            "- Check Dockerfile syntax",
            "- Check base image availability",
            "- Check network connectivity",
            "- Check build logs",
            "- Verify file permissions",
            "",
            "### Docker Tools",
            "",
            "Command-line tools:",
            "- docker (main CLI)",
            "- docker-compose (multi-container apps)",
            "- docker-machine (local VMs)",
            "- docker swarm (orchestration)",
            "",
            "GUI tools:",
            "- Docker Desktop",
            "- Portainer",
            "Kitematic",
            "- Shipyard",
            "",
            "Monitoring:",
            "- Docker stats",
            "- docker events",
            "- container logs",
            "- cgroups metrics",
            "- Resource usage",
            "",
            "### Docker Registry",
            "",
            "- Docker Hub (public registry)",
            "- Private registries (AWS ECR, GCR, ACR)",
            "- Registry authentication",
            "- Image tagging and versioning",
            "- Image scanning",
            "- Webhooks",
            "",
            "### Advanced Docker",
            "",
            "Docker APIs:",
            "- Docker Engine API",
            "- Docker Hub API",
            "- Registry HTTP API V2",
            "- Remote API access",
            "",
            "Custom networks:",
            "- Bridge network",
            "- Overlay networks",
            "- MACVLAN networks",
            "- Network plugins",
            "",
            "Storage drivers:",
            "- Local driver",
            "- Overlay2 driver",
            "AUFS driver",
            "Btrfs driver",
            "- ZFS driver",
            "",
            "### Docker vs Kubernetes",
            "",
            "Docker:",
            "- Single host deployment",
            "- Manual scaling",
            "- Docker Swarm for multi-host",
            "- Simpler setup",
            "- Faster to learn",
            "- Good for small-medium apps",
            "",
            "Kubernetes:",
            "- Multi-cluster management",
            "- Auto-scaling",
            "- Self-healing",
            "- More complex",
            "- Better for large scale",
            "- Industry standard",
            "",
            "### When Working with Docker",
            "",
            "Creating Dockerfile:",
            "- Choose minimal base image",
            "- Use multi-stage builds",
            "- Optimize layer caching",
            "- Copy only needed files",
            "- Run as non-root user",
            "- Expose necessary ports",
            "- Add health checks",
            "- Set environment variables",
            "",
            "Building images:",
            "- docker build -t myapp:v1 .",
            "- docker build -t myapp:latest .",
            "- docker build --no-cache .",
            "- docker build --build-arg ARG=1 .",
            "",
            "Running containers:",
            "- docker run -d -p 8080:80 myapp",
            "- docker run -it myapp sh",
            "- docker run --rm myapp",
            "- docker run -v hostpath:containerpath myapp",
            "",
            "Managing containers:",
            "- docker ps (list running)",
            "- docker ps -a (all containers)",
            "- docker logs (view logs)",
            "- docker exec (run command)",
            "- docker stop (stop container)",
            "- docker rm (remove container)",
            "- docker rmi (remove image)",
            "",
            "Security:",
            "- Scan images for vulnerabilities",
            "- Run as non-root user",
            "- Use specific image versions",
            "- Don't run as root",
            "- Limit container capabilities",
            "- Use read-only filesystems",
            "- Scan regularly",
            "",
            "Performance:",
            "- Use specific versions",
            "- Cache dependencies",
            "- Minimize layers",
            "- Use .dockerignore",
            "- Multi-stage builds",
            "- Optimize images",
            "- Clean up unused resources",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "docker",
            "containers",
            "images",
            "docker_compose",
            "dockerfile",
            "docker_swarm",
            "container_orchestration",
            "microservices",
            "container_security",
            "docker_optimization",
            "multi_stage_builds",
            "docker_registry",
            "container_networking",
            "docker_volumes",
            "container_monitoring",
        ]

module = CogInfraDocker()
