from cog.cog_module import CogModule
from cog.tools.base import Tool, ToolResult

class DotnetTool(Tool):
    name = "csharp.dotnet"
    description = "Execute .NET CLI commands"
    required_permissions = ["shell.execute"]

    def execute(self, command: str, **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"dotnet {command}", timeout=300)
        return result

class CSharpCompileTool(Tool):
    name = "csharp.compile"
    description = "Compile C# source files"
    required_permissions = ["shell.execute"]

    def execute(self, project: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        if project:
            result = shell.execute(command=f"dotnet build {project}")
        else:
            result = shell.execute(command="dotnet build")
        return result

class NuGetTool(Tool):
    name = "csharp.nuget"
    description = "Manage NuGet packages"
    required_permissions = ["shell.execute"]

    def execute(self, action: str, package: str = "", **kwargs) -> ToolResult:
        from cog.tools.shell import ShellTool
        shell = ShellTool()
        result = shell.execute(command=f"dotnet {action} {package}")
        return result

class CogLangCsharp(CogModule):
    name = "cog-lang-csharp"
    version = "1.0.0"
    description = "C# and .NET expertise"

    def register_tools(self) -> list[Tool]:
        return [DotnetTool(), CSharpCompileTool(), NuGetTool()]

    def get_prompt_extensions(self) -> list[str]:
        return [
            "## C# and .NET Expertise",
            "",
            "### Core C#",
            "",
            "Basic concepts:",
            "- Classes and objects",
            "- Interfaces",
            "- Abstract classes",
            "- Inheritance",
            "- Polymorphism",
            "- Encapsulation",
            "- Namespaces",
            "- Access modifiers (public, private, protected, internal, protected internal)",
            "- Static vs instance",
            "- Properties (get, set, init)",
            "- this keyword",
            "- base keyword",
            "",
            "C# types:",
            "- Value types (struct, enum, int, double, bool, etc.)",
            "- Reference types (class, interface, delegate, array, string)",
            "- Nullable value types (T?)",
            "- Nullable reference types (string?, T?)",
            "- Anonymous types",
            "- Tuples",
            "- Records",
            "- Pattern matching",
            "",
            "Modern C# features (C# 8-12):",
            "- Nullable reference types",
            "- Async streams",
            "- Indices and ranges",
            "- Null-coalescing assignment (??=)",
            "- Default interface methods",
            "- Record types",
            "- Pattern matching enhancements",
            "- Top-level statements",
            "- Init-only properties",
            "- With expressions",
            "- Enhanced using",
            "- File-scoped namespaces",
            "- Global using directives",
            "- List patterns",
            "- Required members",
            "",
            "### LINQ",
            "",
            "LINQ operators:",
            "- Filtering (Where, OfType)",
            "- Projection (Select, SelectMany)",
            "- Partitioning (Skip, Take, SkipWhile, TakeWhile)",
            "- Ordering (OrderBy, ThenBy, OrderByDescending, ThenByDescending)",
            "- Grouping (GroupBy)",
            "- Joining (Join, GroupJoin)",
            "- Concatenation (Concat)",
            "- Aggregation (Count, Sum, Min, Max, Average, Aggregate)",
            "- Quantifiers (Any, All, Contains)",
            "- Projection (Single, SingleOrDefault, First, FirstOrDefault, Last, LastOrDefault)",
            "- Set operations (Distinct, Union, Intersect, Except)",
            "- Generation (Range, Repeat, Empty)",
            "- Equality (SequenceEqual)",
            "- Element (ElementAt, ElementAtOrDefault)",
            "- Conversion (ToArray, ToList, ToDictionary, ToLookup, Cast, AsEnumerable)",
            "",
            "LINQ query syntax:",
            "- from clause",
            "- where clause",
            "- select clause",
            "- join clause",
            "- orderby clause",
            "- group clause",
            "- into clause",
            "- let clause",
            "",
            "LINQ method syntax:",
            "- Method chaining",
            "- Lambda expressions",
            "- Func delegates",
            "- Expression trees",
            "",
            "### .NET CLI",
            "",
            ".NET commands:",
            "- dotnet new (create project)",
            "- dotnet build",
            "- dotnet run",
            "- dotnet test",
            "- dotnet publish",
            "- dotnet pack",
            "- dotnet add package",
            "- dotnet remove package",
            "- dotnet list package",
            "- dotnet sln",
            "- dotnet ef (Entity Framework Core)",
            "",
            ".NET SDKs:",
            "- .NET 8 (LTS)",
            "- .NET 6 (LTS)",
            "- .NET 7 (STS)",
            "",
            "### ASP.NET Core",
            "",
            "ASP.NET Core fundamentals:",
            "- Startup vs Program.cs",
            "- Middleware pipeline",
            "- Dependency injection",
            "- Configuration (appsettings.json)",
            "- Hosting model",
            "- Kestrel web server",
            "- IIS integration",
            "- HTTPS",
            "- CORS",
            "- Routing",
            "- Logging",
            "",
            "Controllers:",
            "- Controller base class",
            "- ApiController attribute",
            "- Routing (attributes, conventional)",
            "- Action results (Ok, NotFound, BadRequest, etc.)",
            "- Model binding",
            "- Model validation",
            "- Action filters",
            "- From services",
            "",
            "Minimal APIs:",
            "- WebApplication builder",
            "- MapGet, MapPost, MapPut, MapDelete",
            "- Route handlers",
            "- Endpoint filters",
            "- OpenAPI/Swagger",
            "- Minimal API vs Controllers",
            "",
            "Entity Framework Core:",
            "- DbContext",
            "- DbSet",
            "- Models (entities)",
            "- LINQ queries",
            "- Tracking vs no-tracking",
            "- Eager loading (Include)",
            "- Lazy loading",
            "- Explicit loading",
            "- Migrations (add, remove, update)",
            "- Query filters",
            "- Global query filters",
            "- Transactions",
            "- Concurrency",
            "- Indexes",
            "- Shadow properties",
            "- Owned types",
            "- Value conversions",
            "- Raw SQL queries",
            "",
            "### Dependency Injection",
            "",
            "DI lifetimes:",
            "- Transient (new each time)",
            "- Scoped (once per request)",
            "- Singleton (once per app lifetime)",
            "",
            "DI registration:",
            "- AddTransient",
            "- AddScoped",
            "- AddSingleton",
            "- TryAdd* (don't override)",
            "- AddHttpClient (typed clients)",
            "",
            "DI best practices:",
            "- Avoid service locator pattern",
            "- Use constructor injection",
            "- Avoid injecting scoped services into singletons",
            "- Use factory pattern for complex creation",
            "",
            "### Middleware",
            "",
            "Middleware pipeline:",
            "- Order matters",
            "- Use, Map, UseWhen, MapWhen",
            "- Custom middleware",
            "- Branching",
            "",
            "Built-in middleware:",
            "- Exception handler",
            "- HTTPS redirection",
            "- Static files",
            "- Routing",
            "- Authentication",
            "- Authorization",
            "- CORS",
            "- Endpoint routing",
            "",
            "### Configuration",
            "",
            "Configuration providers:",
            "- appsettings.json",
            "- appsettings.{Environment}.json",
            "- Environment variables",
            "- Command line args",
            "- User secrets",
            "- Key per file",
            "- Azure Key Vault",
            "",
            "Options pattern:",
            "- IOptions",
            "- IOptionsSnapshot",
            "- IOptionsMonitor",
            "- Configure method",
            "- Options validation",
            "- Named options",
            "",
            "### Logging",
            "",
            "Logging levels:",
            "- Trace",
            "- Debug",
            "- Information",
            "- Warning",
            "- Error",
            "- Critical",
            "- None",
            "",
            "Logging providers:",
            "- Console",
            "- Debug",
            "- EventSource",
            "- EventLog",
            "- Application Insights",
            "- Serilog",
            "- NLog",
            "",
            "Structured logging:",
            "- Log scopes",
            "- Structured logs",
            "- Serilog sinks",
            "- log levels",
            "",
            "### Authentication & Authorization",
            "",
            "Authentication:",
            "- ASP.NET Core Identity",
            "- JWT Bearer",
            "- OAuth2",
            "- OpenID Connect",
            "- Cookie authentication",
            "- Windows authentication",
            "- Custom authentication",
            "",
            "Authorization:",
            "- Authorization policies",
            "- Requirements",
            "- Handlers",
            "- Role-based authorization",
            "- Claims-based authorization",
            "- Resource-based authorization",
            "",
            "### Testing",
            "",
            "Unit testing frameworks:",
            "- xUnit",
            "- NUnit",
            "- MSTest",
            "",
            "Testing attributes:",
            "- [Fact]",
            "- [Theory]",
            "- [InlineData]",
            "- [MemberData]",
            "- [ClassData]",
            "- [Trait]",
            "",
            "Testing best practices:",
            "- Arrange-Act-Assert",
            "- Test behavior, not implementation",
            "- Use mocks (Moq)",
            "- Test one thing per test",
            "- Descriptive test names",
            "",
            "Integration testing:",
            "- WebApplicationFactory",
            "- TestServer",
            "- HttpClient",
            "- Database testing (InMemory, SQLite)",
            "",
            "### C# Best Practices",
            "",
            "Code style:",
            "- Follow C# conventions",
            "- Use meaningful names",
            "- Keep methods small",
            "- Single responsibility",
            "- DRY (Don't Repeat Yourself)",
            "- Use using statements",
            "- Use var when type is obvious",
            "- Use expression-bodied members",
            "- Use pattern matching",
            "",
            "Error handling:",
            "- Use exceptions, not error codes",
            "- Use specific exception types",
            "- Don't catch Exception (unless rethrowing)",
            "- Use await using (async disposable)",
            "- Use throw expressions",
            "- Use null-coalescing operators",
            "",
            "Async/await:",
            "- ConfigureAwait(false) for libraries",
            "- Don't use .Result or .Wait() (deadlock risk)",
            "- Use CancellationToken",
            "- Avoid async void (use async Task)",
            "- Return Task instead of void",
            "- Use ValueTask for hot paths",
            "",
            "### Performance Optimization",
            "",
            "Memory optimization:",
            "- Use structs for small types",
            "- Use Span and Memory",
            "- Use ArrayPool",
            "- Use stackalloc",
            "- Use ref struct",
            "- Avoid boxing",
            "- Use pooled objects",
            "",
            "LINQ optimization:",
            "- Use Where before Select",
            "- Avoid multiple enumerations (ToList)",
            "- Use foreach instead of ForEach",
            "- Use AsEnumerable to switch to LINQ to Objects",
            "",
            "Async optimization:",
            "- Use ConfigureAwait(false)",
            "- Use ValueTask",
            "- Use CancellationToken",
            "- Use async streams (IAsyncEnumerable)",
            "",
            "### .NET vs Java",
            "",
            ".NET advantages:",
            "- C# is more modern than Java",
            "- Better async/await support",
            "- LINQ",
            "- Records (before Java)",
            "- Pattern matching (more advanced)",
            "- Properties (no getters/setters)",
            "- Extension methods",
            "- Better IDE support (Visual Studio)",
            "",
            "Java advantages:",
            "- Platform independent (JVM)",
            "- More mature ecosystem",
            "- Larger market share",
            "- Open source (JDK)",
            "",
            "### Quick Reference",
            "",
            "Create project:",
            "- dotnet new webapi",
            "- dotnet new mvc",
            "- dotnet new console",
            "",
            "Build project:",
            "- dotnet build",
            "",
            "Run project:",
            "- dotnet run",
            "",
            "Add package:",
            "- dotnet add package Microsoft.EntityFrameworkCore.SqlServer",
            "- dotnet add package Serilog.AspNetCore",
            "",
            "Run tests:",
            "- dotnet test",
            "",
            "Publish:",
            "- dotnet publish -c Release",
            "",
            "LINQ example:",
            "var result = users",
            "  .Where(u => u.Age > 18)",
            "  .OrderBy(u => u.Name)",
            "  .Select(u => u.Name)",
            "  .ToList();",
            "",
            "LINQ query syntax:",
            "var result = from u in users",
            "              where u.Age > 18",
            "              orderby u.Name",
            "              select u.Name;",
            "",
            "Async/await:",
            "public async Task<User> GetUserAsync(int id)",
            "{",
            "  return await _context.Users.FindAsync(id);",
            "}",
            "",
            "Dependency injection:",
            "builder.Services.AddScoped<IUserService, UserService>();",
            "",
            "Minimal API:",
            "app.MapGet(\"/users/{id}\", async (int id, IUserService service) =>",
            "{",
            "  return await service.GetUserAsync(id);",
            "});",
            "",
            "Controller:",
            "[HttpGet(\"{id}\")]",
            "public async Task<ActionResult<User>> GetUser(int id)",
            "{",
            "  var user = await _service.GetUserAsync(id);",
            "  if (user == null) return NotFound();",
            "  return Ok(user);",
            "}",
            "",
            "Record class:",
            "public record User(int Id, string Name, int Age);",
            "",
            "Pattern matching:",
            "if (user is User { Age: > 18 })",
            "{",
            "  // user is an adult",
            "}",
            "",
            "Nullable reference types:",
            "string? name = null; // nullable",
            "string name = \"John\"; // non-nullable",
            "",
            "Using declarations:",
            "using var scope = _scopeFactory.CreateScope();",
            "// automatically disposed at end of scope",
            "",
        ]

    def get_capabilities(self) -> list[str]:
        return [
            "csharp",
            "dotnet",
            "aspnet_core",
            "entity_framework",
            "linq",
            "mvc",
            "web_api",
            "minimal_api",
            "dependency_injection",
            "middleware",
            "authentication",
            "authorization",
            "testing",
            "xunit",
            "nunit",
            "async_await",
            "patterns",
            "best_practices",
            "performance",
            "memory_optimization",
            "modern_csharp",
            "records",
            "pattern_matching"
        ]

module = CogLangCsharp()
